### ISSUE TITLE
No highlighting for ambiguous instance argument

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1003]
In the following example, there is an unsolved instance argument, but no part of the code is highlighted.
```agda
module InstanceTest where

typeof : ∀ {{T : Set}} → T → Set
typeof {{T}} x = T

test : {A : Set} {B : Set} (y : A) → typeof y
test y = y
```

Original issue reported on code.google.com by `jesper.c...@gmail.com` on 20 Dec 2013 at 11:27

**Comment by jespercockx** [comment]
I don't think this fix is very satisfactory because it breaks an important guarantee of instance arguments: that any solution is indeed one of the marked 'instance's. Maybe a more principled solution would be instead to refuse to solve any instance metas through conversion, instead **requiring** that they are solved by instance search.

**Comment by jespercockx** [comment]
Fixed.
