### ISSUE TITLE
Allow multiple layout keywords on the same line

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1145]
We are trying to make the following code (in the lexer):
```agda
private abstract
  A = Set

private module _ where
  A = Set
  B = Set

private module _
  (C : let X = Set in X)
    where
  A = Set
  B = Set
```
But we are not sure how the following code should be parsed (or rejected) by 
the lexer.  Any thought?
```agda
private A : Set
        B : Set

private A : Set
  B : Set

private module _ where
         A = Set
         B = Set
        C = Set
        D = Set

```

Original issue reported on code.google.com by `favonia` on 23 May 2014 at 10:19

**Comment by andreasabel** [comment]
The proposed change would be:

  The token following the last layout keyword on a line determines the indentation level of the block.

For the three examples, I would say:
1. Accept.
2. Reject.
3. Reject.

**Comment by guillaumebrunerie** [comment]
Would that work for the third example of the OP?

``` agda
private module _
  (C : let X = Set in X)
    where
  A = Set
  B = Set
```

Note that the layout keywords here are `private` and `where` (not `module`).

**Comment by guillaumebrunerie** [comment]
Maybe the string `private module` should be treated differently (i.e. in that case `private` should not be treated as a layout keyword).

**Comment by UlfNorell** [comment]
> The token following the last layout keyword on a line determines the indentation level of the block.

There might be some gnarly cases with let. For instance:

``` agda
foo : Nat → Nat → Nat
foo n = let n' = suc n in λ where
  zero    → zero
  (suc _) → suc n'
```

**Comment by UlfNorell** [comment]
> Maybe the string private module should be treated differently (i.e. in that case private should not be treated as a layout keyword).

This might work. There could be anti-layout keywords which cancels a preceding layout keyword.

**Comment by andreasabel** [comment]
> There might be some gnarly cases with let. For instance:
> 
> foo : Nat → Nat → Nat
> foo n = let n' = suc n in λ where
>   zero    → zero
>   (suc _) → suc n'

What is the problem here?  The last layout keyword on the line is `where`.  Thus, `let` is not treated as layout keyword in this case.

My preferred rule would be that a layout keyword is only treated as such if it is followed by a line break (modulo whitespace of course).  This is very much non backwards compatible but implements the Pfenning principle: Renaming of identifiers should not affect the parsing.

But the thing with anti-layout tokens might work.  Besides `module`, I guess it would be `in`.  Anything else?

**Comment by UlfNorell** [comment]
> What is the problem here? The last layout keyword on the line is where. Thus, let is not treated as layout keyword in this case.

Some fiddling might be needed to make let parse in this case is what I meant, but I guess that goes for all the blocks.

`in` wouldn't be an anti-layout keyword I think since they should only cancel an immediately preceding layout keyword. All the normal layout keywords would also be anti-layout keywords I believe, to let you write

``` agda
private postulate
   A : Set
```

**Comment by guillaumebrunerie** [comment]
I like Andreas’ suggestion:

> My preferred rule would be that a layout keyword is only treated as such if it is followed by a line break (modulo whitespace of course).

That means that the following code would not be allowed anymore, but do people write code like that?

``` agda
private A : Set
        B : Set
```

It seems a bit ugly to me, I would rather write either

``` agda
private A : Set
private B : Set
```

or

``` agda
private
  A : Set
  B : Set
```

**Comment by andreasabel** [comment]
People write maybe more often

``` agda
  where x = a
        y = b
```

The problem is how we could possibly launch such a drastic syntax change.

**Comment by UlfNorell** [comment]
Or

``` agda
  let x = u
      y = v in bla
```

**Comment by andreasabel** [comment]
I think with `let`, it would be awkward to forbid

``` haskell
let x = u
    y = v
in bla
```

In general, I think `let-in` is ill-designed language construct in all of ML, Haskell, Agda.  I would prefer 

``` haskell
let x = u
let y = v
bla
```

similar to what Haskell's `do` notation allows, or even

```
x = u
y = v
bla
```

or, on a single line

``` haskell
let x = u; let y = v; bla
x = u; y = v; bla
```

**Comment by UlfNorell** [comment]
I think this looks awkward:

``` agda
  let f : A
  let f = e
  bla
```

Introducing mandatory `;`s would be a step backwards, and I'm not sure how you would make the first two suggestions parse without a layout block.

**Comment by UlfNorell** [comment]
A cheap alternative might be to merge empty blocks with the following block, letting you write
```agda
private
abstract
  A = Set

private
module _ where
  A = Set
  B = Set

private
module _
  (C : let X = Set in X)
    where
  A = Set
  B = Set
```
without the awkward one space indentation of the inner keyword.

**Comment by andreasabel** [comment]
Nice idea.  But in my opinion, that does not look good.  
Also, it can lead to confusion when a preceding block became empty by commenting out the last definition (which was not already commented out).

**Comment by nad** [comment]
> Also, it can lead to confusion when a preceding block became empty by commenting our the last definition (which was not already commented out).

I agree.

**Comment by jespercockx** [comment]
@gallais why did you add the `status: blocking-issue` tag?

**Comment by gallais** [comment]
Because it is blocking #2293?

**Comment by andreasabel** [comment]
Maybe we can settle for the following amendment of the current parser:
> If there are several layout keywords on the same line, only the last one introduces layout.

Proposal how to implement this:
- When encountering a layout keyword and thus pushing a new column onto the layout stack, mark this new column as _tentative_ (unless the next token is on a new line).
- When encountering a line break, mark the last tentative layout column as _definitive_.
- When popping a column from the layout stack, pop all surfacing tentative columns as well.

This would enable (Example `pp1`)
```agda
private postulate
  A : Set
  B : Set
```
and
```
abstract f = do
  foo
  bar
```
But it would disable (Example `pp2`)
```agda
private postulate A : Set
        postulate B : Set
```
and
```agda
f = do let x = a
           y = b
       foo
```

**Comment by andreasabel** [comment]
There could be a simple fix.  Currently, this is a parse error:
```agda
private postulate
  A : Set
  B : Set
```
The reason is that `private` introduced layout column 8, and `postulate` wants to introduce layout column 2, but decreasing indentation is not allowed.
How about we allow `postulate` to proceed with column 2, but when the `postulate` block ends, we also end all blocks with greater or equal layout column.  
This would pass all examples of the previous comment.

**Comment by andreasabel** [comment]
In my last comment, I simplified a bit too much.  For example,
```agda
private data Unit : Set where
unit : Unit
```
`private` introduces column 8, `where` wants to allow column `0`.  This should _not_ open a new block.

We need some concept of _confirmed_ indentation level, which is `0` in the beginning.  New blocks must still be strictly above the confirmed level.
A new confirmed level on the top of the stack should also confirm unconfirmed levels directly below it in the stack that are strictly below the new level.

So working with a stack of positions `(line,column)` that are either confirmed or unconfirmed. The column is the indentation level.
- Encounter layout keyword: unconfirm all positions that have the `line` of the layout keyword.
- Encounter token after layout keyword: 
  * Case `column` strictly above the last confirmed column: Open new block. Confirm all positions (since the last confirmed one) that are can be confirmed.  The confirmed columns need to form a strictly increasing sequence.
  * Otherwise: We are encountering an empty block. Close all blocks with a strictly greater column.  Check whether we then are on the column of the top block of the remaining stack.  If yes, produce a semicolon and proceed.  Otherwise, parse error.

In the stack, write `?` for unconfirmed and `!` for confirmed entries.  A final `?` says we just encountered a layout keyword.

Example `pp1`: 
| stack | input | output |
|---|---|---|
| 0! | private | private 
| 0!,? | postulate | private { postulate 
| 0!,(1,8)?,? | A : Set | private { postulate { A : Set 
| 0!,(1,8)?,(2,2)! | B : Set | private { postulate { A : Set ; B : Set 
| 0!,(1,8)?,(2,2)! | EOF | private { postulate { A : Set ; B : Set } } 
| 0!

Example `pp2`: 
| stack | input | output |
|---|---|---|
| 0! | private | private 
| 0!,? | postulate | private { postulate 
| 0!,(1,8)?,? | A : Set | private { postulate { A : Set 
| 0!,(1,8)?,(1,18)? | postulate | private { postulate { A : Set } ; postulate
| 0!,(1,8)!,? | B : Set | private { postulate { A : Set } ; postulate { B : Set 
| 0!,(1,8)!,(2,18)? | EOF | private { postulate { A : Set } ; postulate { B : Set } } 
| 0!

Example:
```
private postulate
mutual
```
| stack | input | output |
|---|---|---|
| 0! | private | private 
| 0!,? | postulate | private { postulate 
| 0!,(1,8)?,? | mutual | private { postulate { } } ; mutual
| 0!,? | EOF | private { postulate { } } ; mutual {}
| 0!

**Comment by andreasabel** [comment]
This is now implemented in the layout processor generated by BNFC (dev version 2.9.2), see https://bnfc.readthedocs.io/en/latest/lbnf.html#stacking-layout-keywords.
The layout processor works on a stream of non-whitespace tokens with line/column information.  When a layout token is encountered, we look ahead to the next token.  From the line information, we can see whether we are on a new line, and this need to confirm layout columns.

A BNFC-generated layout processor has a bit more flexibility than the one of Agda.  Agda's is tied into the lexer and has to follow the discipline of e.g. only producing one token at a time.  Thus, we cannot directly port the one of BNFC but need to convert it into an automaton first.

**Comment by andreasabel** [comment]
I noticed that there a semantics change included in the new feature "stacking layout keywords":
- #6686
