### ISSUE TITLE
Feature suggestion: Add an --exec-compiler option

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1163]
```
Currently, Agda (in MAlonzo mode) calls GHC concurrently with itself, which 
means that Agda and GHC compete for memory.
(I am passing RTS options to both Agda and GHC,
 and it is currently quite tight on my 16GB machine.
 Without -M for GHC, it grows too far.
 I admit that this is stuff that about a year ago
 didn't even typecheck in 16GB :-)
)

It would be nice to have an option that lets Agda use exec() to invoke GHC, so 
that Agda's memory is returned to the OS before GHC starts.

Wolfram
```

Original issue reported on code.google.com by `k...@cas.mcmaster.ca` on 1 Jun 2014 at 4:35

**Comment by phile314** [comment]
I implemented a --ghc-dont-call-ghc flag, which suppresses the call to GHC but still prints the GHC command:
https://github.com/agda/agda/commit/a927b974a5ed79b9adb3dba1ab767f1b9619abf3

@WolframKahl FYI

**Comment by WolframKahl** [comment]
@phile314 : Thank you!

Happy new year everybody!

**Comment by asr** [comment]
@phile314 Please take ownership of this issue (sometimes I need to search in the bug tracker using anything I can remember).

**Comment by phile314** [comment]
Maybe it would make sense to call `perform(Major)GC` before calling GHC? GHC should release unused memory back to the OS on major GC according to this ticket:
https://ghc.haskell.org/trac/ghc/ticket/698

One problem might be that currently, the calls to GHC are done inside TCM, so the whole TCM environment is still live. Not sure if that's a problem. Profiling Agda would probably be a sensible next move, but I'm not going to invest any time in this for now.

**Comment by WolframKahl** [comment]
Also, according to my observations when I still let Agda execute GHC, the Agda process is actually active while GHC is running, IIRC because GHC's IO channels pass through the Agda process.

I think that `--ghc-dont-call-ghc` is a good solution for those for whom this is a problem, so this should just be documented together with its motivation everywhere where compilation is documented.

A solution based on `exec(3)` would have the disadvantage that Agda would be releasing complete control to the GHC process ─ except if you were to write a low-profile wrapper process that replaces Agda while GHC is running, controlling GHC's IO channels and waiting for GHC's exit status, and that then reacts for Agda at the end, in the extreme case by calling a new Agda process...

As Ulf said, this has the danger of being non-portable, and I currently don't see any reason that would justify the effort.
