### ISSUE TITLE
Auto crashes on variable arity function

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1397]
Source:
```agda
module Test where

open import Data.Vec
open import Data.List using (List)
open import Data.Bin renaming (fromℕ to fromℕtoBin)

hello : {!!}
hello = fromList (toBits (fromℕtoBin 3))
```
On C-c C-a:
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/Auto/Typecheck.hs:365
```

Original issue reported on code.google.com by `ak3ntev` on 4 Jan 2015 at 8:48

**Comment by identicalsnowflake** [comment]
I think I just hit this. Here is a case with no dependencies:

```agda
open import Agda.Builtin.Equality
open import Agda.Builtin.Nat renaming (Nat to ℕ)
open import Agda.Builtin.Bool

data ⊥ : Set where

¬_ : Set → Set
¬ P = P → ⊥

record Σ (A : Set) (B : A → Set) : Set where
  constructor _,_
  field
    proj₁ : A
    proj₂ : B proj₁


stepDown : ∀ {a b} → ℕ.suc a ≡ ℕ.suc b → a ≡ b
stepDown {a} {.a} refl = refl

¬==→¬≡ : ∀ {a b} → (a == b) ≡ false → ¬ (a ≡ b)
¬==→¬≡ {ℕ.zero} {ℕ.zero} ()
¬==→¬≡ {ℕ.zero} {ℕ.suc b} refl = λ ()
¬==→¬≡ {ℕ.suc a} {ℕ.zero} refl = λ ()
¬==→¬≡ {ℕ.suc a} {ℕ.suc b} p k = ¬==→¬≡ p (stepDown k)

proof : ∀ {t₁ : Set} {t₂ : Set} (f : t₁ → t₂) (x : t₁) → Σ _ λ y → f x ≡ y
proof f x = f x , refl

_ : {a b : ℕ} → a ≡ (a + b) - b
_ = { -m }
```

Proof search in the hole with `-m` yields `An internal error has occurred. Please report this as a bug. Location of the error: src/full/Agda/Auto/Typecheck.hs:362`.

Interestingly, if you postulate those 3 theorems instead of proving them, this will not happen and proof search will simply time out.

**Comment by andreasabel** [comment]
In absence of a maintainer for Auto, it is rotting away...

**Comment by identicalsnowflake** [comment]
I wish I could help, but I simply have no idea what is even going on, much less know how to fix it.

But I think the cause of this bug is because [this match](https://github.com/agda/agda/blob/master/src/full/Agda/Auto/Typecheck.hs#L353) assumes these two lists are going to be the same size. You can see in the proof `¬==→¬≡` above that this is a bad assumption. It doesn't crash if we rewrite `¬==→¬≡` so all the clauses have the same number of patterns:

```agda
-- no crash
¬==→¬≡ : ∀ {a b} → (a == b) ≡ false → ¬ (a ≡ b)
¬==→¬≡ {ℕ.zero} {ℕ.zero} () _ -- remove this `_` to induce crash
¬==→¬≡ {ℕ.zero} {ℕ.suc b} refl () -- replace `()` with `= λ ()` to induce crash
¬==→¬≡ {ℕ.suc a} {ℕ.zero} refl ()
¬==→¬≡ {ℕ.suc a} {ℕ.suc b} p k = ¬==→¬≡ p (stepDown k)
```

Anyway, I'm sure that was the easy part, but at least it should clarify the issue.

**Comment by andreasabel** [comment]
The MWE by @identicalsnowflake now just times out.  The example from the OP isn't easily salvaged due to changes in the standard library.
