### ISSUE TITLE
The unifier fails to infer dot pattern. It does not respect eta.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1608]
``` agda
postulate
  C : Set
  anything : C

record I : Set where
  constructor c
  field
    {f} : C

data Wrap : (i : I) → Set where
  wrap : ∀ {i} → Wrap i

works : ∀ {j} → Wrap j → C
works {c {._}} (wrap {c {x}}) = anything

fails : ∀ {j} → Wrap j → C
fails {c {._}} (wrap {c}) = anything

-- Failed to infer the value of dotted pattern
-- when checking that the pattern ._ has type C
```

See also issue #473.

Original issue reported on code.google.com by `andreas....@gmail.com` on 7 Jul 2015 at 7:38

**Comment by jespercockx** [comment]
I'm currently working on fixing this issue for my new unifier. The unifier has two eta-expansion rules:
- A flexible variable of record type can be eta-expanded into one variable for each record field.
- An equation of record type can be eta-expanded into equations between the projections, e.g. an equation `x == y` of type `A x B` can be eta-expanded into two equations `proj1 x == proj1 y` and `proj2 x == proj2 y`.

Both these rules are doing what they should do, but I'm having some trouble on finding the right strategy when to apply them. The problem is that sometimes the unifier has to make a choice between either solving a variable, eta-expanding it, or postponing the equation to come back to later. Sometimes the choice is clear: a DotFlex should be solved, and a RecordFlex should be expanded. But most of the time we're dealing with ImplicitFlex variables and there it's not clear to me what we should do. Consider an equation `x == t` where `x` is an ImplicitFlex variable of record type.
- Solving the equation by assigning `t` to `x` is not always the right choice because `t` could contain DotFlex variables, and these should take priority over ImplicitFlex. This leads to the `Failed to infer the value of dotted pattern` error.
- Eagerly eta-expanding the variable leads to the same performance problem we have now with deeply nested records.
- Always postponing such equations could also lead to performance problems, and when coming back to the equation it may still be unclear which of the two above options should be chosen.

I'd be really grateful if someone can suggest a sensible strategy to deal with this problem.

One alternative would be to always instantiate variables when possible, and afterwards try to match the generated patterns with the user patterns by shuffling around the dots:
- `c x .x` should be equivalent to `c .x x`.
- `.(c p q)` should be equivalent to `c .p .q` if c is a record constructor.
  This would make the unifier simpler, but requires more work afterwards. 

Do you think this would be a better solution?

**Comment by jespercockx** [comment]
I've tried to implement my second suggestion (shuffling around the dots, or rather checking that the user pattern and computed pattern are shuffle-equivalent). The first rule (moving a dot on a variable to another position) is working, but implementing the second one seems to require eta-expanding all pattern variables recursively, which brings us back to square one. So I'm not sure what to do anymore at the moment.

**Comment by jespercockx** [comment]
I've managed to implement the second rule as well, see function checkLeftoverDotPatterns at https://github.com/agda/agda/blob/master/src/full/Agda/TypeChecking/Rules/LHS.hs#L332-L425. This makes https://github.com/agda/agda/blob/master/test/Succeed/Issue1608.agda work with the new unifier, however there's still something going wrong when combined with 'with' as you can see by the tests I had to disable in https://github.com/agda/agda/blob/master/test/Succeed/Issue473-1606.agda.

**Comment by UlfNorell** [comment]
I'm not sure I would consider any of the tests you disabled problematic. A bunch of them are using `._` which is deprecated in favour of `_` (and work if you replace `._` by `_`). The others all seem to be variants of dotting something in a with-clause that wasn't dotted in the parent:

``` agda
bad : (x y : I) → x ≡ y → C
bad _ .c refl with anything
bad .c _ refl | z = z   --- failed to infer dot pattern
```

I don't think it's unreasonable that this doesn't work. You might have expected the error

```
Inaccessible (dotted) patterns from the parent clause must also be
inaccessible in the with clause
```

but I don't think `failed to infer` is really a worse error. At least that one points to the offending pattern.

Actually fixing this seems very difficult since the dot patterns are not present in the generated with-function (see also #142). A proper fix would have to check the with-clauses as they stand rather than checking the generated with-function.

**Comment by jespercockx** [comment]
After my work on #1605, I think I finally understand what's going on here. The problem is that the dot patterns in the *internal* patterns are not necessarily in the position where the user wrote them, but the `stripWithClausePatterns` function in TypeChecking/With.hs assumes that they are. Here are a few possible ways to fix this issue:
1. Instead of checking whether the dots in the internal pattern can in principle be shuffled around to conform to the user-written dot patterns (as the `checkLeftoverDotPatterns` function in TypeChecking/LHS currently does), we could actually do the shuffling. This gets rid of the mismatch between abstract and internal patterns.
2. We could use the abstract parent pattern instead of the internal one as the input to `stripWithClausePatterns`. It seems that this used to be the case but it was changed to the internal patterns for some reason, so I'm not sure if it's a good idea to change it back.
3. We could leave everything the way it is now and just tell the users that you shouldn't repeat dot patterns from the parent clause in the child clause, only the *new* dot patterns should be mentioned. This would only require to change the behaviour of the interactive case splitter (which also expands ellipsis) to replace all dot patterns of the parent clause by underscores.

I think I'm currently in favor of 3. as it should be easy to implement. Any objections?

**Comment by andreasabel** [comment]
Choice 3. would "fix" #142 by decree, but I think this is a bit too restrictive.  See the snippet from the std-lib at #142; I repeat it here:
```agda
group : ∀ {a} {A : Set a} n k (xs : Vec A (n * k)) →
        ∃ λ (xss : Vec (Vec A k) n) → xs ≡ concat xss
group zero    k [] = ([] , refl)
group (suc n) k xs                  with splitAt k xs
group (suc n) k .(ys ++ zs)         | (ys , zs , refl) with group n k zs
group (suc n) k .(ys ++ concat zss) | (ys , .(concat zss) , refl) | (zss , refl) =
  ((ys ∷ zss) , refl)
```
The second with refines a dot pattern, which is a good documentation for what it going on here.

**Comment by jespercockx** [comment]
Right. What about option 2, do you know the reason why stripWithClausePatterns uses the internal patterns of the parent clause instead of the abstract ones?

**Comment by UlfNorell** [comment]
We need the actual values of dot patterns from the parent clause to set up appropriate let bindings. Also the user might write more implicit arguments in the child clauses, so we need the parent patterns after implicit insertion.

**Comment by jespercockx** [comment]
This was fixed by the new unifier.
