### ISSUE TITLE
Badly aligned let type declarations / bindings

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1618]
```
In the LaTeX backend, the let binding coming after a let type declaration is 
not aligned properly.

Cf. the attached lagda, Makefile and sample output.
```

Original issue reported on code.google.com by `g.x.all...@gmail.com` on 30 Jul 2015 at 1:48

Attachments:
- [letAlign.lagda](https://storage.googleapis.com/google-code-attachments/agda/issue-1618/comment-0/letAlign.lagda)
- [Makefile](https://storage.googleapis.com/google-code-attachments/agda/issue-1618/comment-0/Makefile)
- [letAlign.pdf](https://storage.googleapis.com/google-code-attachments/agda/issue-1618/comment-0/letAlign.pdf)

**Comment by andreasabel** [comment]
The HTML backend seems to have a problem with properly aligning stuff like

``` agda
  where x = 1
        y = 2
```

because it assumes monospaced font, but least this should work

``` agda
id : (A : Set) → A → A
id A =
  let
    id' : B → B
    id' = λ a → a
  in id'
```

(Does not require monospaced font for relatively correct amount of leading whitespace.)

**Comment by andreasabel** [comment]
The problem seems to be that ConcreteToAbstract throws away the second binding of id' (because id' is already bound by the type signature for id').  Abstract syntax currently only stores one binding for a let binding.  Consequently, the highlighter does not produce any info for the second binding of id' (in the clause), and the latex backend produces garbage.

This can be confirmed by setting the  `Agda2 Highlight Bound Variable Face`  to anything but default in emacs: The second biding of id' is not recognized as such.
