### ISSUE TITLE
Latex backend omits certain subscripts

### ISSUE THREAD

**Issue by phile314** [agda/agda#1642]
The pdf generated from literate Agda code is missing certain subscripts. It seems to depend on the
letter inside the subscript whether it goes missing or not.

Example (l)agda code:

<pre>
\documentclass{article}
\usepackage{agda}
\begin{document}

\begin{code}
module LatexTest where

data ⊤ : Set where

kₐ = ⊤

kₗ = ⊤

\end{code}

\end{document}
</pre>

The produced pdf (using xelatex or lualatex) is missing the "l" subscript, but the "a" subscript is there:
http://files.314.ch/LatexTest.pdf

Produced tex file:

<pre>
\documentclass{article}
\usepackage{agda}
\begin{document}

\begin{code}%
\>\AgdaKeyword{module} \AgdaModule{LatexTest} \AgdaKeyword{where}\<%
\\
%
\\
\>\AgdaKeyword{data} \AgdaDatatype{⊤} \AgdaSymbol{:} \AgdaPrimitiveType{Set} \AgdaKeyword{where}\<%
\\
%
\\
\>\AgdaFunction{kₐ} \AgdaSymbol{=} \AgdaDatatype{⊤}\<%
\\
%
\\
\>\AgdaFunction{kₗ} \AgdaSymbol{=} \AgdaDatatype{⊤}\<%
\\
\>\<%
\end{code}

\end{document}
</pre>

**Comment by gallais** [comment]
The problem is that ₗ is not supported by XITS Math. I don't really know how
defaulting rules work with xelatex / lualatex. What @stevana and I typically
do is postprocess the tex file with a sed script.

You could target this subscript in particular or have a more generic approach:
we use \undertie for subscripts and ^ for superscripts together with something
like this:
https://github.com/gallais/potpourri/blob/master/papers/models/rules.sed

**Comment by andreasabel** [comment]
I am closing this issue.  If there is a request to change the LaTeX-backend in some way, please reopen and detail how to change it.

**Comment by phile314** [comment]
Reported this upstream to XITS Math:
https://github.com/khaledhosny/xits-math/issues/42

**Comment by phile314** [comment]
This has been fixed upstream in the unicode-math package:
https://github.com/wspr/unicode-math/pull/325
