### ISSUE TITLE
The new library management system should be easier to discover

### ISSUE THREAD

**Issue by nad** [agda/agda#1693]
I suggest that if `agda2-include-dirs` is set (with a non-default value?), then we should give some informative message to the user (including information about how to turn off the message).

**Comment by andreasabel** [comment]
+1.

**Comment by banacorn** [comment]
Could you please elaborate this a little bit more? 
I've built a [agda-mode for Atom editor](https://atom.io/packages/agda-mode) and I'm currently working on library management things. Thanks.

**Comment by nad** [comment]
On 2015-12-01 16:36, Ting-Yan Lai wrote:

> Could you please elaborate this a little bit more?
> I've built a agda-mode for Atom editor https://atom.io/packages/agda-mode and I'm currently working on library management things. Thanks.

This issue refers to the Emacs variable agda2-include-dirs, which is no
longer used. For more information about the new library management
system, see
http://agda.readthedocs.org/en/latest/tools/package-system.html.

## 

/NAD

**Comment by andreasabel** [comment]
For backwards-compatibility, I'd prefer that agda2-include-dirs is transformed into -i... upon calls to agda (rather than removing this customization option).

**Comment by banacorn** [comment]
+1

**Comment by andreasabel** [comment]
Also, the current solution does not really work well if one alternates between agda-2.5.1 and agda-2.4.x and has a binding for agda2-include-dirs in the .emacs file.

**Comment by WolframKahl** [comment]
As long as I routinely work with multiple Agda installations, anything that uses a single global configuration file with hard-coded paths does not work for me.

In each of my Agda installations (`/usr/local/packages/Agda-2.X.Y.Z`) I generate a `bin/agdalib` that just `echo`s the path to the standard library, so that at least on the command-line, the complete Agda configuration is covered by the current `PATH` setting.:

```
time agda -v profile:7 +RTS -S -K256M -H11G -M11G -A1G -RTS -i . -i $(agdalib) AContext2.lagda
```

When I open an Emacs with a different `PATH`, I always still have to edit the `-i ....X.Y.Z/lib/std-lib/src` in the customisation variables, and I see this only getting worse with the new library system.

Probably there is a way to set program-args depending on the output of `agda-lib`, similar to what `agda-mode locate` does, but I have not yet tried to invest time to do that kind of thing in ELisp (which I am not familiar with)...

**Comment by UlfNorell** [comment]
Ignoring agda-2.4.*, one idea might be to allow version suffixes on the libraries file. So if you have `~/.agda/libraries-2.5.1` it's preferred over `~/.agda/libraries` by Agda-2.5.1 and ignored by other versions.

**Comment by UlfNorell** [comment]
I guess for this to work with different versions of the development version we'd need an easy way to add a version suffix when building.

**Comment by WolframKahl** [comment]
On Fri, Apr 08, 2016 at 08:19:00AM -0700, Ulf Norell wrote:

> I guess for this to work with different versions of the development version we'd need an easy way to add a version suffix when building.

I am changing 2.5.0 to, e.g., 2.4.3.34 in two places in Agda.cabal and in one place in agda/src/data/emacs-mode/agda2-mode.el .

**Comment by UlfNorell** [comment]
Now `.agda/libraries-VERSION` is picked over `.agda/libraries`. Hopefully this will let you get rid of your `agda-lib` script @WolframKahl.

**Comment by UlfNorell** [comment]
I'm not sure that transforming `include-dirs` to `-i` options is a good idea. There's enough difference between `2.5.1` and `2.4.*` that old libraries (which are what you would have in your include dirs) likely won't work with `2.5.1`.

As far as I can see, the only thing this will do is not give people an incentive to switch to the library system. What is your use case?

**Comment by UlfNorell** [comment]
Seems to me there's nothing more to be done here. Reopen if you disagree.
