### ISSUE TITLE
Feature request: ML-style forall-generalization

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#1706]
Often in papers that use Agda, you see authors using an idealized version of Agda that omits implicit arguments, e.g.

```
data _∈_ : A → List A → Set where
  hd : x ∈ x :: xs
  tl : x ∈ xs → x ∈ (y :: xs)
```

I think it would be very nice if this was actually valid Agda code, and Agda inserted the required `∀ {...} →` automatically.

The obvious problem here is that if you make a typo, Agda doesn't warn you but happily quantifies over the new variable. But maybe then there should just be an option to turn off this behaviour for people who make a lot of typo's :)

Are there any other considerations besides this? Maybe efficiency would be a problem, I cannot really tell. If there's nothing else, then I'll try to implement this when I have some time.

**Comment by UlfNorell** [comment]
I remember discussing this with Andres Löh (@kosmikus) a while ago and concluding that it's tricky. What I vaguely remember is that it's not obvious how to figure out dependencies between the implicit arguments. We didn't look at what they do in Idris though.

I believe Idris solves the typo problem by making you declare the names that are available for implicit bindings. Something like

```
%using x y xs
```

before your data type definition.

One thing you might also want to do is quantify over unsolved (and unconstrained) metas. For instance, if you want to bind a Vec A n implicitly, you will also need to bind the n even though its not mentioned anywhere.

**Comment by WolframKahl** [comment]
On Wed, Oct 28, 2015 at 09:47:09AM -0700, Jesper Cockx wrote:

> Often in papers that use Agda, you see authors using an idealized version of Agda that omits implicit arguments, e.g.
> 
> ```
> data _∈_ : A → List A → Set where
>   hd : x ∈ x :: xs
>   tl : x ∈ xs → x ∈ (y :: xs)
> ```
> 
> I think it would be very nice if this was actually valid Agda code, and Agda inserted the required `∀ {...} →` automatically.

It is valid Agda code, at least if inside

  module _ {A : Set} where

...

Wolfram

**Comment by jespercockx** [comment]
@UlfNorell : Good points. I was thinking of just naively generating the forall's in concreteToAbstract and letting the typechecker do the hard work, but that doesn't really work if the implicit variables depend on each other. I'll try to take a look at what they do in Idris.

@WolframKahl : How so? The variables x, y and xs are also not bound anywhere.

**Comment by WolframKahl** [comment]
On Wed, Oct 28, 2015 at 02:45:50PM -0700, Jesper Cockx wrote:

> @WolframKahl : How so? The variables x, y and xs are also not bound anywhere.

Indeed.

Thinking about that, the proposed feature looks like a rather dubious idea to me ---
Agda is already prone to pick up inadvertently imported constructors
instead of seeing the intended pattern variables --- how do you decide
whether an `x` that happens to be in scope needs to be shadowed by local bindings?

Wolfram

**Comment by UlfNorell** [comment]
> How do you decide whether an `x` that happens to be in scope needs to be shadowed by local bindings?

The sensible thing would be to never do that. Requiring a declaration of the variables you want to be available for implicit binding solves the problem of inadvertently imported things: declaring something that's already in scope for implicit binding would be an error.

**Comment by andreasabel** [comment]
Yes, such a feature would be very welcome.  But please, DON'T JUST HACK 
SOMETHING that works in simple cases, and will be an eternal maintenance 
burden.

The feature is called "generalization" and has been present in 
implementations of LF for 20 years.  A detailed description of the 
associated unification algorithm is here:

   Brigitte Pientka.
   An insider's look at LF type reconstruction:
   Everything you (n)ever wanted to know,
   Journal of Functional Programming, Jan 2013
   http://www.cs.mcgill.ca/~bpientka/papers/recon-jfp.pdf

The tricky thing is where to place the quantification over the free 
variables x, xs, etc. so that their types can depend on each other (and 
the completely omitted variables) in the right way.

As already noted, we should not just generalize over every free variable 
without some assurance from the user.  In Twelf, only capitalized 
identifiers are quantified over.  We do not have this option, but I'd 
favor a similar simple criterion, like only identifiers consisting of 
1-3 letters followed by digits are quantified over, or there is a

   generalize <pattern>

statement in which the user can declare which identifiers are 
generalizable, selected by a suitable pattern (regexp, or some simpler 
pattern format like for filenames).

On 29.10.2015 07:02, Ulf Norell wrote:

> ```
> How do you decide whether an |x| that happens to be in scope needs
> to be shadowed by local bindings?
> ```
> 
> The sensible thing would be to never do that. Requiring a declaration of
> the variables you want to be available for implicit binding solves the
> problem of inadvertently imported things: declaring something that's
> already in scope for implicit binding would be an error.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/agda/agda/issues/1706#issuecomment-152085725.

## 

Andreas Abel  <><      Du bist der geliebte Mensch.

Department of Computer Science and Engineering
Chalmers and Gothenburg University, Sweden

andreas.abel@gu.se
http://www2.tcs.ifi.lmu.de/~abel/

**Comment by jespercockx** [comment]
Ok, I take your point. Maybe it's better to wait with this feature until we can discuss it some more at one of the Agda meetings then. I was just wondering if it had ever come up before.

**Comment by andreasabel** [comment]
I did not mean to discourage your initiative, only this should be done properly using the existing theoretical work.

**Comment by nad** [comment]
A discussion from 2009 about this issue: [Why aren't free vars in types automatically generalized](http://thread.gmane.org/gmane.comp.lang.agda/772).

**Comment by UlfNorell** [comment]
About to happen! See #3071.

**Comment by UlfNorell** [comment]
Now merged and reasonably stable. See the `generalize` label for open issues.
