### ISSUE TITLE
Type in type and universe polymorphism

### ISSUE THREAD

**Issue by asr** [agda/agda#1764]
Nils wrote in the [user mailing list](https://lists.chalmers.se/pipermail/agda/2015/008346.html):

> I don't know why universe polymorphism and --type-in-type cannot be used together

and Escardo [wrote](https://lists.chalmers.se/pipermail/agda/2015/008349.html):

> I would be lovely if they could be used together.

I'll create a branch allowing type in type and universe polymorphism for experimental purposes.

**Comment by asr** [comment]
I created the [issue-1764-maint](https://github.com/agda/agda/tree/issue-1764-maint) branch.

**Comment by andreasabel** [comment]
I think it makes sense to allow both together, and be it just to temporarily disable universe checking in a universe polymorphic development.

**Comment by andreasabel** [comment]
A combination of --type-in-type and --universe-polymorphism would still need to try to solve for level metas, but not report an error if there is an inconsistency.  Not so easy to implement.

**Comment by asr** [comment]
I created the [issue-1764-master](https://github.com/agda/agda/tree/issue-1764-master) branch and I removed the issue-1764-maint branch.

**Comment by andreasabel** [comment]
One way to implement this is that whenever we conversion-check `Set l ?= Set l'` and we have `--type-in-type`, we set a flag in the type-checking environment that we want to ignore all errors coming from the comparison of the levels `l ?= l'`.

**Comment by asr** [comment]
Great! I removed the issue-1764-master branch and I'll write to the mailing list.

**Comment by effectfully** [comment]
D.agda:

```
{-# OPTIONS --type-in-type --universe-polymorphism #-}

open import Level
open import Function
open import Data.Unit.Base
open import Data.Product
open import Data.List.Base

Sets : ∀ αs -> Set (foldr (_⊔_ ∘ suc) zero αs)
Sets  []      = ⊤
Sets (α ∷ αs) = Set α × Sets αs

data D {αs} (As : Sets αs) : Set where
```

Fail.agda:

```
open import Level
open import Data.List.Base
open import D

postulate
  fail : ∀ {αs} {As : Sets αs} -> D As
```

Agda reports

```
(Set (foldr (λ x → _⊔_ (suc x)) zero αs)) != Set
```

**Comment by andreasabel** [comment]
Currently, using --type-in-type with universe polymorphism implies that some inferred levels are garbage.  You see this garbage when you use a --type-in-type module in a non-type-in-type module.

I can try to refine the implementation to produce less garbage, but ultimately, I would need a specification of how the expected behavior of mixing universe polymorphism and type-in-type should look like.

**Comment by gallais** [comment]
Ok here is a practical use case. Currently `IO` is quite unusable because:

- all of the types used in an IO action need to live at the same level
- the bindings to Haskell all live at `Set 0`

This means that in practice you have to either only have `IO` actions delivering values of type in `Set 0` or not use any of the bindings. Here is an alternative definition that would be nice to have:

```agda
data    IO′ {a} (i : Size) (ℓ : Level) (A : Set a) : Set (ℓ ⊔ a)
record ∞IO′ {a} (i : Size) (ℓ : Level) (A : Set a) : Set (ℓ ⊔ a)

data IO′ {a} i ℓ A where
  lift   : Prim.IO {a} A → IO′ i ℓ A
  return : A → IO′ i ℓ A
  bind   : ∀ {b} {B : Set b} → ∞IO′ i ℓ B → (B → ∞IO′ i ℓ A) → IO′ i ℓ A

record ∞IO′ i ℓ A where
  coinductive
  constructor delay
  field force : {j : Size< i} → IO′ j ℓ A
```
Effectively if you have a program of type `IO ℓ Unit : Set ℓ`, this is a way of saying "I'm not going to use anything at level higher than `ℓ`" without being stuck to `Set 0` only  or having to wrap `Unit` (and all other small values) in `Lift` all the time. This needs `--type-in-type` to be accepted (otherwise it'd live in `Set w` because of `bind`).

We can write (possibly in the `--type-in-type` module) fairly nice combinators such as:

```agda
 _>>=_ : ∀ {ℓ a b} {A : Set a} {B : Set b} {i} → IO′ i ℓ A → (A → IO′ i ℓ B) → IO′ i ℓ B
```

Now, we'd like to bind primitives (`Prim.getArgs` has type `Prim.IO (List String)`):

```agda
getArgs : ∀ {ℓ} → IO ℓ (List String)
getArgs = lift Prim.getArgs
```
but we get the error: `Set != Set ℓ
when checking that the expression lift Prim.getArgs has type
IO ℓ (List String)`

However if we were to postulate `lift` instead of using the constructor, the typechecker would not complain!

```agda
postulate lift : ∀ {ℓ a} {A : Set a} → Prim.IO A → IO ℓ A
```

I would expect the type-annotated definitions typechecked using `--type-in-type` to not cause more type errors than if they were simply postulated.

Cf. [this branch](https://github.com/gallais/agda-sizedIO/tree/typeintype) for more details:
* [Sized.IO](https://github.com/gallais/agda-sizedIO/blob/typeintype/src/Sized/IO.agda) (unsafe)
* [System.Environment](https://github.com/gallais/agda-sizedIO/blob/typeintype/src/System/Environment.agda) (hoped to be safe)
* [cat](https://github.com/gallais/agda-sizedIO/blob/typeintype/examples/cat.agda) (unsolved level metas all over the place... when they're all solvable!)

**Comment by UlfNorell** [comment]
@jespercockx would `--setω-in-setω` solve this issue?

**Comment by jespercockx** [comment]
... maybe? I'll have to try it out.

**Comment by jespercockx** [comment]
`--omega-in-omega` is now implemented but unfortunately it doesn't immediately fix the problem here. With the new flag, the definition of `IO′` is not accepted unless you put it in `Setω`, which means there are a lot of things such as `sequence` that cannot be defined (since `Setω` is not part of the universe hierarchy).

What's needed to get the example of @gallais to work is a way to define an impredicative datatype without turning off universe checking entirely. Maybe we could add a pragma `{-# NO_UNIVERSE_CHECK #-}` (similar to `{-# NO_POSITIVITY_CHECK #-}`) that turns off the universe check for one datatype but otherwise leaves universe levels intact?

**Comment by effectfully** [comment]
> Effectively if you have a program of type `IO ℓ Unit : Set ℓ`, this is a way of saying "I'm not going to use anything at level higher than `ℓ`" without being stuck to `Set 0` only or having to wrap `Unit` (and all other small values) in `Lift` all the time.

I needed to solve the same problem a couple of years ago and I had found a solution: [Emulating cumulativity in Agda](http://effectfully.blogspot.com/2016/07/cumu.html). It's [battle-tested](https://github.com/effectfully/Generic/blob/master/Core.agda#L14). Though, it's non-trivial boilerplate for the library author.

**Comment by jespercockx** [comment]
@gallais could you try if the new `{-# NO_UNIVERSE_CHECK #-}` pragma helps for your use-case? If yes, I think we can close this issue.

**Comment by gallais** [comment]
It's perfect! Thanks @jespercockx!
