### ISSUE TITLE
Insufficient indentation in LaTeX-rendered Agda code

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#1832]
``` latex
\documentclass{article}
\usepackage{latex/agda}

\begin{document}
\begin{code}
record R : Set₁ where
  field VeryLongFieldNameForSomethingAsTrivialAsFunctor :
          Set → Set
\end{code}
\end{document}
```

This generates the attached PDF.
[IndentingLatex.pdf](https://github.com/agda/agda/files/126312/IndentingLatex.pdf)

If someone typed that into Agda, he'd get a parse error, since `field` is a layout keyword and the type of the field is not sufficiently indented.

I guess `polytable` is to be blamed for this.  The generated LaTeX is fine:

``` latex
\begin{code}%
\>\AgdaKeyword{record} \AgdaRecord{R} \AgdaSymbol{:} \AgdaPrimitiveType{Set₁} \AgdaKeyword{where}\<%
\\
\>[0]\AgdaIndent{2}{}\<[2]%
\>[2]\AgdaKeyword{field} \AgdaField{VeryLongFieldNameForSomethingAsTrivialAsFunctor} \AgdaSymbol{:}\<%
\\
\>[2]\AgdaIndent{10}{}\<[10]%
\>[10]\AgdaPrimitiveType{Set} \AgdaSymbol{→} \AgdaPrimitiveType{Set}\<%
\end{code}
```

**Comment by andreasabel** [comment]
In fact, polytable is not to blame. `\AgdaIndent` is currently emitting a fixed amount of whitespace, independent from its parameter, which might not be enough.  
I tried to make `\AgdaIndent{#1}` emit `\hspace*{#1ex}` but this did not look good (too much indentation).  I think we might need a smarter mechanism to get a correct and aesthetically pleasing indentation for situations like the example I posted.

**Comment by kosmikus** [comment]
@andreasabel I've added an example to the polytable bug on how you could perhaps use polytable in such a way that the desired layout would be generated more or less independently of the definition of `\AgdaIndent`.

**Comment by nad** [comment]
A relatively easy way to solve this problem might be to ensure that relative indentation is preserved in the output, even for things preceded by only a single space character. However, I think this would lead to too much alignment in the output.

**Comment by andreasabel** [comment]
We might also want to fix the Agda parser to accept something like
```agda
  field f : 
    A
```

**Comment by nad** [comment]
I suspect that the current implementation could also yield code of the following form:
```
    field f :
  A
```

**Comment by nad** [comment]
Here is a smaller example:
```
\begin{code}
postulate
 A : Set
\end{code}
```
The generated document puts the `A` right under the `p` in `postulate`.

**Comment by nad** [comment]
A compromise might be to preserve the relative indentation when at least two space characters are used. I think this is what lhs2TeX does. This is not perfect, because the user is left with the responsibility to check that the output makes sense, but perhaps it is easier to implement than a perfect solution.

**Comment by andreasabel** [comment]
Why is it easier?  Cannot you say it is a new indentation level if it is strictly bigger than the previous one?

**Comment by nad** [comment]
I don't want to align everything that just happens to start in the same column. Figuring out when it is essential to preserve the relative indentation of two things seems non-trivial to me.

My idea of a perfect solution:
* The output is valid Agda that is equivalent to what is written in the code block. (As long as the defaults set up in `agda.sty` are not changed.)
* If the user explicitly asks for two things to be aligned, then they should be aligned.
* If the user explicitly asks for one thing to be more indented than another one, then we should respect this.
* In other cases we should do something which is pleasing to the eye.

The last requirement rules out solutions where we use one column per code point (or something like that).

**Comment by nad** [comment]
I just realised that my recent change to the LaTeX backend (4b0f79cf9a19ebe58b1d27f6d626ba6b8366bbe0), in which extended grapheme clusters are counted instead of code points, makes the problem discussed above worse.

Consider the following code:
```
  f : ℕ → ℕ → ℕ
  f +̲  zero     = +̲
  f g  (suc n)  = f g n
```
Previously `zero` was not aligned with `(suc n)`, because `+̲` contains two code points. Now, because `+̲` contains a single extended grapheme cluster, the alignment works as one might expect.

However, Agda's layout machinery does not count grapheme clusters. Consider the following code:
```
record +̲ : Set₁ where  field A : Set
                        field B : Set
```
The layout machinery accepts this code, because the two instances of `field` are preceded by the same number of code points. However, the LaTeX backend will not produce proper alignment.

Should I revert my commit? An alternative would be to count extended grapheme clusters in the layout machinery, but that would make Agda's lexical syntax even more complicated, and I think the meaning of "extended grapheme cluster" could change when a new version of the Unicode standard is released. (I think it is somewhat unfortunate that "layout columns" can be initiated by a token which is preceded by something other than whitespace.)

For some information about my commit, see the [CHANGELOG](https://github.com/agda/agda/blob/569cf49bc54e5b527f946da7821e85e619cac235/CHANGELOG.md#latex-backend).

**Comment by nad** [comment]
> (I think it is somewhat unfortunate that "layout columns" can be initiated by a token which is preceded by something other than whitespace.)

@andreasabel pointed out that Agda does not satisfy a property that he attributed to Frank Pfenning (I am not sure if my statement matches Pfenning's): If you take a valid program and α-rename an identifier, then you should get an equivalent, valid program. In the case of Agda you may get a program which is no longer valid. We could perhaps change Agda so that Pfenning's property holds by not allowing "layout columns" to start to the right of tokens other than keywords and special characters like `(`. This would rule out the problematic record declaration above.

I checked some of my code, and found a large number of examples of code that would no longer work with the rule suggested above, all involving `let`. However, most of them were of a form in which the layout column isn't actually used. Perhaps such code could be allowed. Here are some examples of what I have in mind:
```
  (r : R) → let open R r in  -- All on one line.
  λ x → let y = x in         -- All on one line.
```

**Comment by andreasabel** [comment]
`in` on the same line cancels the layout started by `let`, thus, these are also fine.
See also #1145 for some more discussion.

**Comment by UlfNorell** [comment]
I suspect you'll find quite a lot of code like

```agda
foo =
  let x = a
      y = b
  in c
```

Note that allowing this code does not invalidate the alpha-renaming principle, though.

**Comment by andreasabel** [comment]
Yes, this should be continued to be allowed.  We can allow some exceptions to the general rule
> a block begins after a layout keyword on a new line with strictly increased indentation.
Exception:
> If no identifier (i.e. only keywords) occurs before the layout keyword, a block may start with the first token after the layout keyword on the same line.  The column of this token then determines the indentation of this block.
This exception covers your case and also cases like
```agda
  field f : A
        g : B
              
  where x = 1
        y = 2
```
If the layout keyword is not last on the line or not preceded only by keywords, then the whole block needs to be given until the end of the line, e.g.
```agda
  bla where x = 1; Y : Set; Y = Nat

  foo = let x = a; y = b in c
```
But this discussion should really happen at #1145.

**Comment by UlfNorell** [comment]
> But this discussion should really happen at #1145.

I knew we had discussed this before...

**Comment by nad** [comment]
> If no identifier (i.e. only keywords) occurs before the layout keyword, a block may start with the first token after the layout keyword on the same line.

I think we should also allow certain reserved characters, like parentheses (consider `(let ...`).

**Comment by andreasabel** [comment]
> I think we should also allow certain reserved characters, like parentheses (consider (let ...).

Ah yes, this falls under "no identifier".

**Comment by nad** [comment]
But not under "only keywords".

**Comment by andreasabel** [comment]
Ah, in some sense, reserved symbols are in one league with keywords.  They are both for the grammatical structure, the identifiers are the semantics...

**Comment by nad** [comment]
I've implemented a partial fix, see the [CHANGELOG](https://github.com/agda/agda/blob/5e34943f792c2a62b743330d07f071394abf5171/CHANGELOG.md#latex-backend). Are you content with this design? I make no attempt to ensure that the output is always valid Agda code.

> Should I revert my commit [related to counting extended grapheme clusters]?

I'm leaning towards keeping it. I've documented a potential problem in the CHANGELOG, and I hope that people write code in the fragment of Agda that does not exhibit this problem. I would rather change the layout rules to disallow this fragment than to revert the commit.

**Comment by nad** [comment]
I created a separate issue for discussion of "Pfenning-safety": #2465.

**Comment by nad** [comment]
@UlfNorell suggested a better way to handle indentation, and I've implemented something along these lines, see the [CHANGELOG](https://github.com/agda/agda/blob/bff1211973571c4293b1ddda124939b7b6c2cbea/CHANGELOG.md#latex-backend).

@andreasabel, can we close this issue now?

**Comment by nad** [comment]
Perhaps I should mention that some documents (for instance `Issue1062.lagda`) compile more slowly now. The reason seems to be that many more polytable columns are generated. Many of these columns are not actually used, so it should be possible to generate more efficient LaTeX code.

**Comment by nad** [comment]
> Many of these columns are not actually used, so it should be possible to generate more efficient LaTeX code.

Done.

**Comment by nad** [comment]
I think this issue can be closed now.
