### ISSUE TITLE
Internal error in new pattern match unifier

### ISSUE THREAD

**Issue by nad** [agda/agda#1863]
```agda
{-# OPTIONS --allow-unsolved-metas #-}

record ⊤ : Set where
  constructor tt

data I : Set where
  i : ⊤ → I

data D : I → Set where
  d : D (i tt)

postulate
  P : (x : I) → D x → Set

foo : (y : _) → P _ y
foo d = ?
```

The code above triggers the following internal error (for d72b3cf90d12511bf830c4a2c6412fb7ae8a6423):

```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Rules/LHS/Unify.hs:665
```

This is a regression. The problem seems to have been introduced with the new unifier (1b0a2d6a27fd1dc2f89b3c4a18100335ee037a31). However, for that commit Agda gives the following error message:

```
Failed to solve the following constraints:
  [12] i tt = _10 : I
when checking that the pattern d has type D _10
```

The internal error seems to occur starting with fe8fac46045493abd311764875ca2815c25194d2 (but with a different line number). @jespercockx, due you want to take a look?

**Comment by jespercockx** [comment]
Hm, the meta gets instantiated with `i (λ y → tt)`. That certainly shouldn't happen :) I'll look into it.

**Comment by jespercockx** [comment]
Fixed by https://github.com/agda/agda/commit/6990ced90dd4ddfcd23b4882da72c6eefa93a318

The problem turned out to be that metas that result from pruning depend on only a subset of the variables of the context they are defined in, yet calling `withMetaInfo` brings you in a context containing all of them. I fixed this by permuting the telescope according to the mvPermutation that I got from the meta. Another problem was that these mvPermutations were not preserved when creating new metas, so I had to add an additional argument to the various newMetaCtx functions.
