### ISSUE TITLE
Positivity checker does not treat datatypes and record types in the same way

### ISSUE THREAD

**Issue by nad** [agda/agda#1899]
I found the following line in one of the `Datatype` clauses in `Agda.TypeChecking.Positivity.computeOccurrences`:

```
TelV tel t <- telView' <$> normalise a -- normalization needed e.g. for test/succeed/Bush.agda
```

Do we really need to perform full normalisation, rather than on-demand reduction? And why is there a special case for datatypes? We accept the following definition:

```
data Bush (A : Set) : Set where
  leaf : Bush A
  node : A -> (Bush ^ 3) A -> Bush A
```

But not the following one:

```
record B (A : Set) : Set where
  field
    b : (B ^ 3) A
```

(With `_^_` defined as in `Bush.agda`.)

**Comment by andreasabel** [comment]
The collection of occurrences runs in the `OccM` monad which does not reduce/normalize.  I guess there is a special case for data types since this example came up in practice.  I agree that the version with records should be accepted as well, and the use of normalization/reduction should be more principled.

Here is an example that exploits that the positivity analysis does not normalize function bodies:

``` agda
data Unit : Set where 
  unit : Unit

postulate u : Unit

-- Composition from std-lib.Function

_∘_ : ∀ {a b c}
        {A : Set a} {B : A → Set b} {C : {x : A} → B x → Set c} →
        (∀ {x} (y : B x) → C y) → (g : (x : A) → B x) →
        ((x : A) → C (g x))
f ∘ g = λ x → f (g x)

Id : Set → Set
Id X = X

Id1 : Unit → Set → Set
Id1 unit X = Id X

Id2 : Unit → Set → Set
Id2 unit X = (Id ∘ Id) X

-- accepted:

data D1 : Set where
  c : Id1 u D1 → D1

-- rejected:

data D2 : Set where
  c : Id2 u D2 → D2
```

**Comment by andreasabel** [comment]
If we reduce to whnf during positivity checking, we will loop as soon we define a looping term, rather than when we eliminated the looping term.  For instance `test/Succeed/Hurkens` (with `--type-in-type`) will loop.  Anything which produces a big whnf will quasi-loop, see `test/Succeed/Issue1351`.  Therefore, I am hesitant to perform reduction in function definitions for positivity checking.
However, we should treat records like data types, i.e., normalize the field types.

**Comment by nad** [comment]
@andreasabel, your commit broke some of my code. Here is a cut-down example:
```agda
open import Agda.Builtin.Size

mutual

  D : Size → Set
  D i = D′ i

  record D′ (i : Size) : Set where
    coinductive
    field
      force : {j : Size< i} → D j

rejected : D′ ω
D′.force rejected = rejected
```
This code is accepted by Agda 2.5.2, but rejected by Agda e3c2ce469:
```
Termination checking failed for the following functions:
  rejected
```

Note that the following code is accepted:
```agda
open import Agda.Builtin.Size

record D (i : Size) : Set where
  coinductive
  field
    force : {j : Size< i} → D j

accepted : D ω
D.force accepted = accepted
```

**Comment by andreasabel** [comment]
I can see how this regression arose:  Since the positivity checker now normalizes record field types, it does not consider `D` to be mutually recursive with `D'`.  But the termination checker, to see whether a projection is coinductive, looked for occurrences of mutually recursive symbols in the non-normalized type.  This is fixed by normalizing in the termination checker as well.

Anyway, the untyped copattern termination checker is very brittle, you should really write
```agda
f : {i : Size} -> D i
```
instead of
```agda
f : D ω
```
