### ISSUE TITLE
Instance candidate pruning should perhaps be improved

### ISSUE THREAD

**Issue by nad** [agda/agda#1915]
Consider the following code:

```
record Pointed (A : Set) : Set where
  field
    point : A

point : {A : Set} ⦃ p : Pointed A ⦄ → A
point ⦃ p = p ⦄ = Pointed.point p

record R : Set₁ where
  field
    A : Set

    instance
      is-pointed : Pointed A

postulate
  r : R

open R r

x : A
x = point
```

Instance resolution fails in the right-hand side of `x`. Candidates:

```
Resolve instance argument _p_8 : Pointed A.
  Candidates:
    [ is-pointed : Pointed A
    , λ r₁ → R.is-pointed r₁ : (r₁ : R) → Pointed (R.A r₁) ]
```

Why is `λ r₁ → R.is-pointed r₁ : (r₁ : R) → Pointed (R.A r₁)` a candidate? There are no instances of type `R`.

(I used the 2.5.1 milestone because instance fields are new in 2.5.1.)

**Comment by UlfNorell** [comment]
~~The problem is that `R.is-pointed` is a projection, which seems to confuse the instance machinery. Any other instance of type `(r : R) → Pointed (R.A r)` will get pruned as expected.~~

Edit: no that's not true. The problem seems to be that instance search never gets to try solving `_X : R` since it gives up on the type constraint `R.A _X == R.A r`.
