### ISSUE TITLE
Declared syntax should be handled as importable name

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#1930]
Why do not we treat `syntax`-declared names like other names?  
Then we could use the syntax facility e.g. to define

``` agda
syntax zipWith _,_ = zip
```

and get Agda to fold back `zipWith _,_` to `zip` during printing, if `zip` is in scope.

**Comment by UlfNorell** [comment]
Short answer: because syntax declarations do not declare any names.

I'm confused about what you're asking for here. Certainly using the syntax declarations when printing is something we should fix (can't find an issue for it though). That wouldn't require syntax declarations to introduce new names though.

I suppose we could make

``` agda
syntax f x y z = y foo z bla x
```

introduce a new name `_foo_bla_` (although there might be some tricky corners with binding syntax) and expose that to the normal scope management machinery. I'm not sure we would gain by this though.

It seems you also want to be able to do some kind of pattern matching in syntax declarations which is a whole different can of worms.

**Comment by andreasabel** [comment]
Maybe I am on the wrong track here.  Maybe we get what I want with display forms.  For each declaration without pattern matching which is just a specialist call to another function, 

``` agda
  f x y z = g args
```

we introduce a displayform

``` agda
  g args --> f x y z
```

(and make sure we do not loop! :D).
