### ISSUE TITLE
Regression related to rewriting

### ISSUE THREAD

**Issue by nad** [agda/agda#1957]
The following code is accepted by Agda 2.5.1, but not by 0b06e89ce446194f70871d5481b2e2c3318464d8:

```
{-# OPTIONS --rewriting #-}

postulate
  A     : Set
  Eq    : A → A → Set
  subst : (P : A → Set) (x y : A) → Eq x y → P x → P y
  f g   : A → A
  e     : (x : A) → Eq (g (f x)) x
  R     : A → A → Set
  r     : (x : A) → R x x

{-# BUILTIN REWRITE Eq #-}
{-# REWRITE e          #-}

foo : (x y : A) → Eq (f x) (f y) → R (f x) (f y)
foo x y eq = subst (λ z → R _ z) (f x) (f y) eq (r (f x))
```

The code is accepted if the rewrite rule is removed.

The regression seems to have been introduced by "[ rewriting ] Remember which symbols rewrite rules match against to prevent overly eager pruning" (bc9b88f447ee2fc850758d543590d69238b3c831). I don't know if it is the new or the old behaviour that is buggy (or neither).

**Comment by jespercockx** [comment]
I'm afraid this is an example of something that used to work "by accident" but now no longer works with the correct pruning. The meta _20 in question should satisfy the two constraints

```
  _20 x y eq (f x) := f x
  _20 x y eq (f y) := f x
```

Previously, applications of `f` were considered non-matchable since it is a postulate, so _20 could not depend on its final argument. However, the rewrite rule `e` enables the recovery of the argument `x` from an application `f x`, so it's possible that there are other interesting solutions for _20 besides `\x y eq z -> f x`. 

I don't see what we can do here without violating the uniqueness of metavariable solutions in the presence of rewrite rules that match on `f`, so I'm closing the issue.
