### ISSUE TITLE
src/full/Agda/TypeChecking/Rewriting/NonLinMatch.hs

### ISSUE THREAD

**Issue by amp12** [agda/agda#1994]
Agda 2.5.1 when run on the attached file reports:

An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Rewriting/NonLinMatch.hs:287
[NonLinMatch-bug.agda.zip](https://github.com/agda/agda/files/278133/NonLinMatch-bug.agda.zip)

**Comment by jespercockx** [comment]
The problem seems to be that the argument `(r : Path A x y)` of the `seq` is not bound by the pattern, but it's used in the LHS. This causes an internal error when trying to match. We should do a check that all free variables in the LHS are bound somewhere, as we already do for the RHS.

However, fixing the bug in this way would mean your rewrite rule would be rejected with the error "... is not a valid rewrite rule, since the variable r is not bound in the left-hand side." I'm not sure if that's what you want. The problem is that there is no way to find a value o type `Path A x y` just from its first field, so Agda cannot know when using the rewrite rule is valid. Can you explain what the intention of this rewrite rule is?

**Comment by jespercockx** [comment]
See also #1980 for another instance where we should check that certain variables are bound but we currently don't.

**Comment by amp12** [comment]
On 24 May 2016 at 22:06, Jesper Cockx notifications@github.com wrote:

> The problem seems to be that the argument (r : Path A x y) of the seq is not
> bound by the pattern, but it's used in the LHS. This causes an internal
> error when trying to match. We should do a check that all free variables in
> the LHS are bound somewhere, as we already do for the RHS.
> 
> However, fixing the bug in this way would mean your rewrite rule would be
> rejected with the error "... is not a valid rewrite rule, since the variable
> r is not bound in the left-hand side." I'm not sure if that's what you want.
> The problem is that there is no way to find a value o type Path A x y just
> from its first field, so Agda cannot know when using the rewrite rule is
> valid. Can you explain what the intention of this rewrite rule is?

I could explain what I had in mind, but since I was just experimenting
I don't think it's worth doing so --  I'm happy for Agda to report
that an attempted rewrite rule is illegal and try to work around that
(which I can do in this case in fact by just dropping the offending
rewrite rule): better that than causing an internal error!

Thanks,

Andy
