### ISSUE TITLE
Enable more warnings? Support MonadFail proposal

### ISSUE THREAD

**Issue by nad** [agda/agda#2009]
GHC 8.0.1 introduces `-Wcompat`, which "Turns on warnings that will be enabled by default in the future". I tried this out, and got the following error message:

```
src/full/Agda/Utils/PartialOrd.hs:131:10: warning: [-Wsemigroup]
    ‘PartialOrdering’ is an instance of Monoid but not Semigroup.
    This will become an error in a future release.
```

If this will become an error in a future release, then it might be a good idea to address this warning right away.

**Comment by Blaisorblade** [comment]
Yes, this might break as early as 8.2. I'm testing a fix that should still be compatible with older releases without using CPP. On earlier GHCs, using the `semigroups` package will provide the same API.

For further info:
https://ghc.haskell.org/trac/ghc/wiki/Migration/8.0#Librarychanges
https://prime.haskell.org/wiki/Libraries/Proposals/SemigroupMonoid

**Comment by asr** [comment]
The above commit doesn't work because the new warnings were enabled _before_ the `-w` option, so those warnings are disabled by this option. I'll revert this commit.

**Comment by asr** [comment]
> ~~I'll revert this commit.~~

I only removed the wrong part of the commit.

**Comment by asr** [comment]
@Blaisorblade in d819d93 you didn't need to add `-Wnoncanonical-monad-instances` and `-Wnoncanonical-monadfail-instances` because you added `-Wcompat`.

In fact, please explicitly use the warnings enable why `-Wcompat` rather that this flag.

Also note that  `-Wnoncanonical-monad-instances` was duplicated.

**Comment by Blaisorblade** [comment]
Whoops sorry. That makes more sense.

> @Blaisorblade in d819d93 you didn't need to add -Wnoncanonical-monad-instances and -Wnoncanonical-monadfail-instances because you add -Wcompat.

Agreed — I did it following recommended practices in https://ghc.haskell.org/trac/ghc/wiki/Migration/8.0#Librarychanges.

I'll do this more properly.

**Comment by asr** [comment]
> Agreed — I did it following recommended practices in https://ghc.haskell.org/trac/ghc/wiki/Migration/8.0#Librarychanges.

Please report the issue.

**Comment by Blaisorblade** [comment]
> Please report the issue.

What issue? The docs are correct. Maybe I see the misunderstanding — `-Wcompat` doesn't imply those other warnings ([docs](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/using-warnings.html#ghc-flag--Wcompat)), it only implies `-Wmissing-monadfail-instances` `-Wsemigroup` `-Wnoncanonical-monoid-instances`.

Using only `-Wcompat` would be possible, but I think it is preferable to enable all of these warnings.

And since the choice of warnings in `-Wcompat` seems confusing to me, I agree with spelling them out.

**Comment by asr** [comment]
> What issue?

I was wrong, sorry.

**Comment by Blaisorblade** [comment]
No problem :-) (And BTW sorry for all the breakage with Travis.)

**Comment by asr** [comment]
It is difficult debugging Travis and its behaviour sometimes is "weird". My rules for modifying it are:
1. Keep as simple as possible
2. Full test the commits in my personal repository before pushing on the main repository
3. Push only one commit at a time

**Comment by Blaisorblade** [comment]
@nad: While refactoring this, there's a question on how to refactor derived instances of `Monoid`.
For instance:

``` diff
-instance Monoid c => Monoid (WithArity c) where
-  mempty = WithArity __IMPOSSIBLE__ mempty
-  mappend (WithArity n1 c1) (WithArity n2 c2)
+instance Monoid c => Semigroup (WithArity c) where
+  WithArity n1 c1 <> WithArity n2 c2
     | n1 == n2  = WithArity n1 $ mappend c1 c2
     | otherwise = __IMPOSSIBLE__   -- arity must match!
```

One could also generalize to `instance Semigroup c => Semigroup (WithArity c) where` (and replace `mappend` with `(<>)`), but IIUC since `Semigroup` isn't a superclass of `Monoid`, the new constraint might exclude some `Monoid`s that weren't converted to `Semigroup`s yet. So for now I'm leaning toward not generalizing things. Should I later go the full way?

**Comment by Blaisorblade** [comment]
The next issue is `MonadFail`. This is going to be harder, because this can find actual issues — some monads can't implement `fail` well. Luckily, this will also take a longer time: https://prime.haskell.org/wiki/Libraries/Proposals/MonadFail

For instance, the first warning I got looked a `MonadFail Identity` instance (which doesn't exist), required because of a non-exhaustive pattern match in the identity monad. Assuming all cases are correct and not oversight, maybe they should be converted to using **IMPOSSIBLE** — similarly to adaption approach n. 3 in docs ("desugaring pattern matching by hand"):
https://prime.haskell.org/wiki/Libraries/Proposals/MonadFail#Adaptingoldcode

**Comment by UlfNorell** [comment]
> For instance, the first warning I got looked a MonadFail Identity instance (which doesn't exist), required because of a non-exhaustive pattern match in the identity monad.

I guess there are two choices:
- Turn into `__IMPOSSIBLE__` as you suggest, or
- use a lazy match (`~pat`)

I guess it would depend on how sure we are that the case is impossible.

**Comment by nad** [comment]
> So for now I'm leaning toward not generalizing things. Should I later go the full way?

I don't know.

I don't think we should use lazy patterns.

**Comment by Blaisorblade** [comment]
Indeed: lazy patterns would make for bad bug reports. But that's already possible in principle for such matches — do you recall it happening?

**Comment by nad** [comment]
We typically try to use `__IMPOSSIBLE__` when there is a risk that the code might crash. Maybe you can prove that the code won't crash, but are you sure that later changes to the code base won't invalidate your proof?

**Comment by Blaisorblade** [comment]
Now that #2036 is merged and the `-Wmonoid` part is closed, I'm tempted to separate `monadfail` separately—maybe a separate issue? I'd maybe unassign myself for now, and I'm not sure this should be planned for the 2.5.2 milestone.

Unless one can convert all instances to `__IMPOSSIBLE__` blindly — then at least I have the competence to take care of this.

One thing I forgot is that one can _already_ convert code to declare `MonadFail` instances, and forward `Monad.fail` to `MonadFail.fail`, and then enable `-XMonadFailDesugaring` (for GHC >=8.0) and get the new desugaring (and compile errors for matches that can fail in monads without `MonadFail` instances).

**Comment by UlfNorell** [comment]
> lazy patterns would make for bad bug reports

Not really. It'll just say `Pattern match failure at File:Line` instead of `Internal error at File:Line`. But I was only suggesting lazy matching in cases where you can see locally that it will match.

**Comment by Blaisorblade** [comment]
> But I was only suggesting lazy matching in cases where you can see locally that it will match.

Sure — we're just unsure how reliable that is and whether that stays true in evolution — of course you can be careful enough.
But if you always get `File:Line`, the issue becomes only cosmetic, and about perceived quality... I instinctively distrust programs with "Pattern match failure", even though I see it's a bit irrational. (`__IMPOSSIBLE__` does not inspire confidence either but for some reason it feels different).

**Comment by nad** [comment]
> It'll just say `Pattern match failure at File:Line` instead of `Internal error at File:Line`.

With `__IMPOSSIBLE__` you get "Please report this as a bug". I guess it would be possible to include this message also for pattern match failures, but I don't think it's done at the moment.

**Comment by Blaisorblade** [comment]
Unassigned from #2009 as I had proposed earlier. This seems now needed for GHC 8.8 IIUC, but it can only be fixed correctly by people who understand the actual code. If it hasn't been fixed.

https://github.com/agda/agda/issues/2009#issuecomment-225750622
https://github.com/agda/agda/issues/2009#issuecomment-225890969.

**Comment by jespercockx** [comment]
I'm confused, is this actually required for 8.8? #3725 seems to suggest otherwise. If we don't need this to support 8.8, then I think it's fine to bump.

**Comment by Blaisorblade** [comment]
I then expect Agda supports MonadFail already?

I haven’t tested, only googled, but it seems [GHC 8.8 implements the MonadFail proposal](https://gitlab.haskell.org/ghc/ghc/wikis/migration/8.8#base-41300).

There’s no other clear actionable item here, so I’m tentatively closing. (For any other needed migrations, use separate issues I guess).

I should have unassigned myself earlier; sorry about that.

**Comment by asr** [comment]
> I then expect Agda supports MonadFail already?

Right.
