### ISSUE TITLE
Rewriting broken in the presence of sized types

### ISSUE THREAD

**Issue by nad** [agda/agda#2021]
The following code is rejected by Agda:

```
{-# OPTIONS --rewriting #-}

open import Agda.Builtin.Size

data _≡_ {A : Set} (x : A) : A → Set where
  refl : x ≡ x

{-# BUILTIN REWRITE _≡_ #-}

postulate

  Q      : Set → Set
  [_]    : {A : Set} → A → Q A
  map    : {A B : Set} → (A → B) → Q A → Q B
  map-[] : {A B : Set} {f : A → B} → ∀ x → map f [ x ] ≡ [ f x ]

{-# REWRITE map-[] #-}

data D (i : Size) : Set where

mutual

  g : ∀ {i} → D i → D i
  g ()

  h : ∀ {i} → Q (D i) → Q (D i)
  h = map g

rejected : ∀ {i} (x : D i) → h [ x ] ≡ [ g x ]
rejected x = refl
```

Error message:

```
map g [ x ] != [ g x ] of type Q (D .i)
when checking that the expression refl has type h [ x ] ≡ [ g x ]
```

The code is accepted if `g` and `h` are defined separately rather than in a mutual block, and also if the `Size` type is replaced with a postulated type `S : Set`.

**Comment by jespercockx** [comment]
With --show-implicit, the error message is:

```
map {D ω} {D ω} (g {ω}) ([_] {D .i} x) != [_] {D .i} (g {.i} x) of
type Q (D .i)
when checking that the expression refl has type
_≡_ {Q (D .i)} (h {.i} ([_] {D .i} x)) ([_] {D .i} (g {.i} x))
```

The rewrite rule doesn't fire since it assumes that the `{A : Set}` argument of map is the same as the `{A : Set}` argument of `[_]`, but in this case they're `D ω` and `D .i` respectively. The code works if you change the definition of `h` to the following:

```
h : ∀ {i} → Q (D i) → Q (D i)
h {i} = map (g {i})
```

It also works if you change the type of `rejected` to `∀ {i} (x : D i) → h ([_] {A = D ω} x) ≡ [ g x ]`. So I'm not sure if this is a bug or just a weird interaction between implicit arguments, sized types, and rewriting.
