### ISSUE TITLE
Parameter refinement causes Panic: unbound variable

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2053]
``` agda
data N : Set where
  suc : ∀ (a : N) → N

data Val : ∀ (t : N) → Set where
  valSuc  : ∀ (dom : N) → Val (suc dom)

record R : Set where
  field f : N

data W (ft : R) : Set where
  immed : (v : Val (R.f ft)) → W ft

postulate
  Evaluate : ∀ (ft : R) (P : (w : W ft) → Set) → Set

test : ∀ (fa : R) → Set
test fa = Evaluate fa testw
  where
  testw : W fa → Set
  testw (immed (valSuc a)) = fa
```

This is the third time I am shrinking the same file, see #2047 and #2049.

**Comment by UlfNorell** [comment]
Simplified:

``` agda
data N : Set where
  suc : N → N

data Val : N → Set where
  valSuc : ∀ n → Val (suc n)

record R : Set where
  constructor wrap
  field unwrap : N

data W (ft : R) : Set where
  immed : (v : Val (R.unwrap ft)) → W ft

test : (fa : R) → W fa → R
test fa (immed (valSuc a)) = fa
```

The record pattern matching seems to confuse the type checker. Instead of binding `fa = wrap (suc a)` it binds `unwrap = suc a`. Investigating.

**Comment by UlfNorell** [comment]
I fixed this by changing how the unifier handles eta expansion of variables.

Previously eta-expansion of a variable `fa` would introduce a constructor pattern `wrap unwrap` (with variable `unwrap`). This meant that `unwrap` would be treated as the refined variable (and thus get the let-binding) instead of `fa`.

Now eta-expanding `fa` introduces a dot pattern `.(wrap _)` instead.

@jespercockx: would you care to have a look at the commit to make sure I didn't cause any obvious breakage in the unifier (the test suite goes through though).

**Comment by jespercockx** [comment]
LGTM, this seems like the correct thing to do now that we can refine parameters.
