### ISSUE TITLE
pattern lambdas get printed with incorrect bodies

### ISSUE THREAD

**Issue by Saizan** [agda/agda#2076]
With 8fae46cdf22758d7c1996323c687cc0c813fbb40 we are closer to printing pattern lambdas (aka extended lambdas) the right way, but the bodies/RHS are not quire right yet.

Example:

``` agda
postulate
  A : Set
  _,_ : A -> A -> A

data Unit : Set where
  true : Unit

foo : (p : A) (q : A) → Unit → A
foo p q = \ { true -> p , q}

test : (a : A) (b : A) → Unit → A
test a b = {foo a b }0
```

by C-c C-n in the goal we get  `λ { true → p , q }` which is ill-scoped.
We should be getting `λ { true → a , b }` instead.

The problem is that while we drop the correct amount of arguments both from the LHS of the lambda and the application, we do not use those dropped arguments to update the RHS of the lambda.

I tried to fix this myself but I do not really understand what's going on with reify for NamedClause, there seems to be some hackery when bringing the RHS into the right context.

Also, there's a probably unintended interaction with module parameters:

``` agda
module M (X : Set) where
  bar : (p : A) (q : A) → Unit → A
  bar p q = \ { true -> p , q}

test : (x : A) (q : A) → Unit → A
test a b = {M.bar Unit a b }1
```

By C-c C-n in that goal we get `(λ { q true → p , q }) b`, i.e. the arguments and the lambda are in sync, but it would have made more sense to drop one more. 

I can see that X is not free in scope anymore, so in principle there is actually one fewer variable to drop, but it ends up keeping 'q' instead.

Printing `(λ { X true → a , b }) Unit` seems wrong too, since the well-typedness of the lambda might depend on `X` being `Unit`, so I'd go for `(λ { true → a , b })`.

**Comment by andreasabel** [comment]
I think the key to solving this issue is to not simply drop the parameters, but to use `apply` to substitute them into the body.  I'll push a fix that does this.  However, this does not work soundly with parameter refinement, where the first patterns of an extended lambda generated function may be different from variable patterns.  In this case, I just fall back to printing the internal name.  This is not satisfactory, but at least sound.  To get nice printing for parameter-refined extended lambdas, we have to actually do some pattern matching to compute the correct substitution.  But this might also fail, as the patterns might not match.  Loose ends in the parameter-refinement feature...

**Comment by UlfNorell** [comment]
This still doesn't work:

``` agda
module M (X : Set) where
  bar : (p : A) (q : A) → Unit → A
  bar p q = \ { true -> p , q}

test : (x : A) (q : A) → Unit → A
test a b = {!M.bar Unit a b!} -- prints: (λ { q true → a , q }) b
```

The problem, as far as I can see, is that the `ExtLamInfo` numbers don't include the module parameters so while it works inside the module (where module parameters are dropped) it doesn't work outside.
