### ISSUE TITLE
Regression in parsing literate files

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2077]
This does no longer parse:

``` latex
\documentclass{article}
\usepackage{agda}

\begin{document}

\AgdaHide{
\begin{code}
postulate A : Set
\end{code}}

\end{document}
```

Error:

```
Missing body for lambda
}<ERROR>

\end{document}
```

Works fine with agda-2.4.2.5 and agda-2.5.0.

**Comment by andreasabel** [comment]
@vlopezj Since you changed something in parsing of literate files, I assign you to this issue.

**Comment by vlopezj** [comment]
In the current state of things, both `\begin{code}` and `\end{code}` must be on a line of their own (modulo whitespace) in order to be recognized as code delimiters, like so:

``` latex
\documentclass{article}
\usepackage{agda}

\begin{document}

\AgdaHide{
\begin{code}
postulate A : Set
\end{code}
}

\end{document}
```

I will fix the implementation so that it recognizes `\end{code}` even if it is followed by more characters in the same line. I would rather still require that `\begin{code}` be in a line of its own. Otherwise one needs to specify a few corner cases about how `\begin{code}` interacts with indentation and other syntax.

**Comment by andreasabel** [comment]
Ok.  It think folks usually put `\begin{code}` on its own line.  Something preceding it is thinkable though.  For now, it is sufficient to address the `\end{code}` issue.
