### ISSUE TITLE
Unexpected type error with induction-recursion

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#212]
While playing around with an old embedded type theory formulation by Conor McBride, I ran into the following weirdness with inductive-recursive definitions:
```agda
module InductionRecursion where

data ℕ : Set where
  zero : ℕ
  suc  : ℕ → ℕ

data Type : ℕ → Set where
  ty : (n : ℕ) → Type (suc n)

mutual
  data U : Set where
    level : U
    type  : El level → U
    Π     : (s : U) → (El s -> U) → U

  El : U → Set
  El level = ℕ
  El (type i) = Type i -- error here
  El (Π s t)  = (S : El s) → El (t S)
```

When making use of the emacs mode, I can complete the `type i` case, as `Type ?` leaves a hole of type ℕ, which is what `type i` is judged to have.
However, upon reloading, I receive a type error saying:
```
  (El level) !=< ℕ of type Set
```
This occurs in Agda 2.2.5 pulled from the darcs repository as of a week or two ago.

Original issue reported on code.google.com by `dan.d...@gmail.com` on 28 Oct 2009 at 1:06
- Merged into: #118

**Comment by andreasabel** [comment]
As of today (2023-05-22), the OP is fixed (type checks).  This is because we now (since a while already) can reduce with the first clause of `El` to type-check the second clause.  (This behavior was introduced along with copatterns.)

(I put label copatterns here even though this is not about copatterns but about type-checking machinery needed for copatterns.)
