### ISSUE TITLE
Ill-typed definition seemingly accepted, provokes internal error

### ISSUE THREAD

**Issue by gallais** [agda/agda#2120]
When I load the following file, it gets typechecked, syntax-highlighted and after that I get an internal error:

> An internal error has occurred. Please report this as a bug.
> Location of the error: src/full/Agda/TypeChecking/Reduce/Monad.hs:122

```
module Minimal where

open import Data.Nat
open import Data.Product
open import Relation.Binary.PropositionalEquality

postulate _<∣_ : ∀ {X Y : Set} → (X → Y) → X → Y

argh : ℕ
argh = (λ { (0 , refl) → 0 }) <∣ (0 , 0)
```

**Comment by andreasabel** [comment]
Again (see #2028) a bug in the fix for #1811, offending patch is https://github.com/agda/agda/commit/b6b3f7a257e8fe03396ec1cd5a73878941c1bf56.

What is happening here is that we catch an error and then try to see whether a type delivered by this error is blocked by a meta.  However, this type is only well-formed in the state which is also delivered by the error. The issue is fixed if we reset to this state before doing the test.
