### ISSUE TITLE
--allow-unsolved-metas and --safe can be used together

### ISSUE THREAD

**Issue by nad** [agda/agda#2152]
```
$ cat Bad.agda 
module Bad where

bad : (A : Set) → A
bad = ?
$ agda --allow-unsolved-metas --safe Bad.agda
Checking Bad (/tmp/Bad.agda).
Finished Bad.
```

This is a regression:

```
$ agda-2.3.2 --allow-unsolved-metas --safe Bad.agda
Checking Bad (/tmp/Bad.agda).
Finished Bad.
$ agda-2.3.0.1 --allow-unsolved-metas --safe Bad.agda
Checking Bad (/tmp/Bad.agda).
/tmp/Bad.agda:3,1-20
Cannot postulate bad with safe flag
when scope checking the declaration
  bad : (A : Set) → A
```

**Comment by nad** [comment]
Bisection suggests that the problem was introduced by @andreasabel in the following patch (694d31929e18960505293b286718b1a6059f9485):

> Fixed a problem about --safe flag complaining about type signatures.
> It thought they were postulates.

**Comment by andreasabel** [comment]
Every features that is not secured by a test case is doomed to rot away... ;)

**Comment by andreasabel** [comment]
Looking at the cited patch, it seems that it fixed a severe problem: type signatures are not allowed in safe more (see #586).  After the cited patch, your `Bad` case passes, but there seems no connection to `--allow-unsolved-metas`, but it is simply the presence of a type signature.  The blame needs to be put on some other patch...
However, the problem seems easy to fix, by just forbidding the two options to coexist.
