### ISSUE TITLE
Two equal irrelevant definitions: one is type checked, the other is not

### ISSUE THREAD

**Issue by effectfully** [agda/agda#2170]
```agda
module _ {A : Set} .(x : A) where
  .irrelevant₁ : A
  irrelevant₁ = x

.irrelevant₂ : {A : Set} -> .(x : A) -> A
irrelevant₂ x = x
-- Variable x is declared irrelevant, so it cannot be used here
-- when checking that the expression x has type .A
```

Moreover, if I turn `.(x : A)` into `(x : . A)` Agda loops in both the cases (perhaps solved in #2167?). (What is the difference between `.(x : A)` and `(x : .A)`?)

**Comment by andreasabel** [comment]
Ah, yes, this seems inconsistent.

**Comment by effectfully** [comment]
@andreasabel, should both the definitions be rejected or accepted?

**Comment by andreasabel** [comment]
There is no real semantics for irrelevant definitions.  They were originally introduced to have irrelevant projections.  It might be reasonable to restrict them to empty contexts, thus, both would be rejected.

See also #610.

**Comment by tomjack** [comment]
Here is a possibly related proof of false, using just irrelevant projections:

```agda
-- checked in:
-- 2.5.2-eafc936
-- 2.6.0-adacc5b
-- 2.6.0-07804b2

module IrrFalse where

open import Agda.Builtin.Equality
open import Agda.Builtin.Bool

infixr 42 _,_
record Σ (A : Set) (B : A → Set) : Set where
  constructor _,_
  field
    fst : A
    snd : B fst
open Σ

data ⊥ : Set where

¬_ : Set → Set
¬ A = (A → ⊥)

true≠false : ¬ (true ≡ false)
true≠false ()

infixr 30 _∙_
_∙_ : {A : Set} {x y z : A} → x ≡ y → y ≡ z → x ≡ z
refl ∙ q = q

infix 42 !_
!_ : {A : Set} {x y : A} → x ≡ y → y ≡ x
! refl = refl



record Irr (A : Set) : Set where
  constructor irr
  field
    .unirr : A
open Irr

map-irr : {A B : Set} → (A → B) → Irr A → Irr B
map-irr f (irr x) = irr (f x)

factivity : ¬ (Irr ⊥)
factivity (irr ())


bizarre : Irr (Σ (Bool → Irr Bool) (λ i → Σ (Irr Bool → Bool) (λ u → (a : Bool) → u (i a) ≡ a)))
bizarre = irr (irr , unirr , (λ a → refl {x = a}))

bad : Irr (true ≡ false)
bad = map-irr (λ { (i , u , s) → ! (s true) ∙ s false }) bizarre

boom : ⊥
boom = factivity (map-irr true≠false bad)


-- the hole here is is .(a) ≡ a
-- bizarre' : Irr (Σ (Irr Bool → Bool) (λ u → (a : Bool) → u (irr a) ≡ a))
-- bizarre' = irr (unirr , (λ a → {!!}))

-- also fails, unirr (irr a) = .(a)
-- bizarre' : Irr (Σ (Bool → Irr Bool) (λ i → Σ (Irr Bool → Bool) (λ u → (a : Bool) → u (i a) ≡ a)))
-- bizarre' = irr (irr , unirr , (λ a → refl {x = unirr (irr a)}))
```

**Comment by andreasabel** [comment]
This is some older problem:
```agda
module Issue2170-unify where

data _≡_ {A : Set} (x : A) : A → Set where
  refl : x ≡ x

record Squash (A : Set) : Set where
  constructor squash
  field .unsquash : A
open Squash

record UnSquash (A : Set) (s : A → Squash A) : Set where
  constructor inverse
  field
    inv : Squash A → A
    prf : {a : A} → inv (s a) ≡ a

test : {A : Set} → Squash (UnSquash A squash)
test = squash (inverse _ refl)
```
Agda happily solves the meta with `unsquash` since at least Agda-2.3.2.

Update 2018-06-12: It seems that subtyping `.A -> Squash A` <= `A -> Squash A` essentially contributes to this problem.  Changing to `s : .A -> Squash A` yields the `Cannot instantiate` error.  However, this problem might be fixable in the constraint solver that "uncurries" the meta `?0 : Squash A -> A` into `?1 : .A -> A`.

**Comment by andreasabel** [comment]
@Saizan: maybe we can apply the techniques of agda-parametric to this problem!?

**Comment by Saizan** [comment]
@andreasabel modal projections like that do not really fit into the purely left-inverse framework of agda-parametric

Here it seems we need to keep track of the relevance of the position (i.e. envRelevance when typechecking) in the unifier.

**Comment by jespercockx** [comment]
In order to fix this problem, I think we need either some facility to allow irrelevant return types (in order to give a proper type to irrelevant projections and the `irrelevant₁` functions from the OP) or disallow irrelevant definitions in parametrized modules entirely, and hence also disallow irrelevant record fields. 

It seems that most (even all?) use cases  of irrelevant fields could be covered by having a Prop with definitional proof-irrelevance, like the `sProp` sort currently being worked on for Coq. I'm currently working on adding such a feature to Agda too, so maybe if it works well irrelevant fields could be deprecated.

**Comment by Saizan** [comment]
Better version of "Issue2170-unify"

```agda
data _≡_ {A : Set} (x : A) : A → Set where
  refl : x ≡ x

record Squash (A : Set) : Set where
  constructor squash
  field .unsquash : A
open Squash

record UnSquash (A : Set) (s : A → Squash A) : Set where
  constructor inverse
  field
    inv : Squash A → A
    prf : {a : A} → inv (s a) ≡ a

test : {A : Set} → (UnSquash A squash)
test = inverse _ refl
```

**Comment by jespercockx** [comment]
This seems to be a separate problem from the one given by @tomjack, since it relies on the constraint solver instantiating a relevant meta with an irrelevant solution somehow.

**Comment by andreasabel** [comment]
On AIM XXVII we agreed to fix this issue by turning off `--irrelevant-projections` off by default, since they are unsound, at least currently.  The new `Prop` can be used when irrelevant projections are needed.

**Comment by jespercockx** [comment]
Note that the definition of `bizarre` by @tomjack doesn't work anymore when you eta-expand `irr`:
```agda
bizarre : Irr (Σ (Bool → Irr Bool) (λ i → Σ (Irr Bool → Bool) (λ u → (a : Bool) → u (i a) ≡ a)))
bizarre = irr ((λ x → irr x) , unirr , (λ a → refl {x = a}))
```
gives
```
a != .(a) of type Bool
when checking that the expression refl {x = a} has type .(a) ≡ a
```
Internally, the difference is that Agda interprets `irr` as `\x → record { unirr = x }` but interprets `\ x → irr x` as `\x -> record { unirr = DontCare x }` instead. Maybe if we manage to insert `DontCare` consistently, we could make `--irrelevant-projections` (more) sound. 

On the long term, it would be nice if we could fully explain irrelevant projections from the propositional squash type, and translate between them automatically.

**Comment by jespercockx** [comment]
A similar thing seems to happen in the example by @Saizan: the second argument to `Unsquash` in the type of test is `squash`, but if you eta-expand it Agda rejects the definition. So it seems worth investigating whether we can insert the appropriate `DontCare`'s when encountering an application of a record constructor with irrelevant fields.

**Comment by jespercockx** [comment]
After some more investigation, it seems that Agda considers `.(x : A) -> B` to be a supertype of `(x : A) -> B`, but this is invalid without the appropriate coercion: if `f : (x : A) -> B` then it doesn't follow that `f : .(x : A) -> B`, but only that `\x -> f (dontCare x) : (x : A) -> B`. So either we have to do something here to actually perform the coercion, or we have to disable this subtyping rule altogether.

**Comment by jespercockx** [comment]
Failing test cases when I disable this subtyping rule:

- [test/Succeed/Issue2429-subtyping.agda](https://github.com/agda/agda/blob/37d38f5a3cdd830d00a65c16da277f1916168c69/test/Succeed/Issue2429-subtyping.agda)
- [test/Succeed/RelevanceSubtyping.agda](https://github.com/agda/agda/blob/37d38f5a3cdd830d00a65c16da277f1916168c69/test/Succeed/RelevanceSubtyping.agda)

See also #2428 and #2429. All in all not much breakage. @andreasabel what's your opinion? Would it be feasible to implement this rule as a coercion instead of the pure subtyping we have now?

**Comment by andreasabel** [comment]
Well, a coercion would be cleaner since we could aggressively remove irrelevant arguments in the compiler early on.  Currently, it seems the compiler has safeguards to deal with the subtyping and seems to subsume irrelevant arguments under its own dead code analysis.
```agda
open import Common.Bool
open import Common.IO
open import Common.String

ignored : .String → Bool → IO _
ignored _ true  = putStrLn "Hello, world!"
ignored _ false = putStrLn "Hello, cat!"

run : ∀{A : Set} → (String → Bool → IO A) → Bool → IO A
run f true  = f "Agda is too good to be" true
run f false = f "Agda is good!" true

main : IO _
main = run ignored true
```
This compiles fine, since Agda creates two versions of `ignored`, one with and one without erasure of the first argument, and takes care to use the second version in `main`.

In general, coercive subtyping is the better thing here, but I am not sure how strong the implementation is currently.  Also, the breakage should be evaluated on a bigger development.

**Comment by andreasabel** [comment]
In `bizarre`, I do not know why `refl` type checks here, since `unirr (irr a)` should reduce to `DontCare a`, printed as `.(a)`.  See the use of `argToDontCare`:
https://github.com/agda/agda/blob/da5afc593a25d1ccc2e6ee20d3b69cd20a557263/src/full/Agda/TypeChecking/Substitute.hs#L90-L102
https://github.com/agda/agda/blob/da5afc593a25d1ccc2e6ee20d3b69cd20a557263/src/full/Agda/TypeChecking/Substitute.hs#L132-L139

Update: As @jespercockx points out, the presence of subtyping causes the `Relevance` in the `ArgInfo` to not always be accurate.  In this case, the unsoundness could probably be fixed by adding `Arg` also to the field enumeration in the constructor and use this as accurate information:
https://github.com/agda/agda/blob/da5afc593a25d1ccc2e6ee20d3b69cd20a557263/src/full/Agda/Syntax/Internal.hs#L62-L69
However, it is a bit worrying that the `ArgInfo` might not be accurate always. Coercive subtyping seems safer.

Update 2: I now implemented this fix (adding `ArgInfo` to `conFields`).  Fast reduce does not seem a problem for this example, but in general I do not know.  In case, I added an option `--no-fast-reduce` to turn off fast reduction (untested).

**Comment by andreasabel** [comment]
@UlfNorell : How does the fast reduce handle irrelevant projections?  Shouldn't this case do something equivalent to `argToDontCare` rather than just `unArg`?
https://github.com/agda/agda/blob/da5afc593a25d1ccc2e6ee20d3b69cd20a557263/src/full/Agda/TypeChecking/Reduce/Fast.hs#L847-L854

**Comment by andreasabel** [comment]
Concerning the original issue, the rejection of:
```agda
{-# OPTIONS --irrelevant-projections #-}

.irrelevant₂ : {A : Set} → .(x : A) → A
irrelevant₂ x = x
```
We could resurrect the context after checking the lhs, and protect the body by a `DontCare`.  Then this could be accepted, within the caveat of `--irrelevant-projections`.

**Comment by UlfNorell** [comment]
> How does the fast reduce handle irrelevant projections?

It doesn't. I didn't think about irrelevant projections in the implementation.

> Shouldn't this case do something equivalent to `argToDontCare` rather than just `unArg`?

Most likely. Can you break it?

**Comment by jespercockx** [comment]
Both the original issue and the issue reported by @tomjack seem to be fixed now. What remains is the issue reported by @Saizan (copied below):

```agda


data _≡_ {A : Set} (x : A) : A → Set where
  refl : x ≡ x

record Squash (A : Set) : Set where
  constructor squash
  field .unsquash : A
open Squash

record UnSquash (A : Set) (s : A → Squash A) : Set where
  constructor inverse
  field
    inv : Squash A → A
    prf : {a : A} → inv (s a) ≡ a

test : {A : Set} → (UnSquash A squash)
test = inverse _ refl
```
This typechecks, but there is no way to fill in the `_` by hand (except by enabling `--irrelevant-projections`).
