### ISSUE TITLE
Agda loops on unguarded inductive record

### ISSUE THREAD

**Issue by m0davis** [agda/agda#2197]
Typechecking the following code uses all available memory.

``` agda
record R : Set where
  inductive

  field
    foo : R

  bar : R
  bar = {!!}
```

**Comment by UlfNorell** [comment]
Yeah, don't do that. You're only allowed to mark a recursive record as `inductive` if you are Thorsten Altenkirch. @nad or @andreasabel might be able to give some examples of safe uses of `inductive`.

Maybe there should be a flag you have to turn on to be allowed to do this?

**Comment by andreasabel** [comment]
Agda detects this as unguarded recursive record type, but does not raise an error.  It just turns eta off for `R`.  I do not know why Agda loops here.
I think the correct thing here is to raise an error.

**Comment by andreasabel** [comment]
The problem here is that the positivity check comes too late.  It would flag `R` as record type not suitable for eta-expansion, but eta-expansion already is happening while checking the record type declaration. 
We need to postpone eta-expansion until after the positivity check.  However, I don't know how to do this.

**Comment by andreasabel** [comment]
Just disabling eta by default and turning it on after the positivity check still passes the test suite (except for one failing case, where one has to add `eta-equality` to the record).  This seems a feasible solution to avoid Agda to loop.
