### ISSUE TITLE
Private anonymous modules?

### ISSUE THREAD

**Issue by favonia** [agda/agda#2199]
Currently, an anonymous module under the keyword `private` will be opened publicly, effectively ignoring the `private` keyword. I am wondering if it is actually more desirable to make anonymous modules under `private` stay private, or even change the semantics of or disallow `open M public` under `private` so that everything under `private` will always remain private.

**Comment by andreasabel** [comment]
Like you expect the following to fail:

``` agda
module _ where

module _ where
  private
    module _ where
      postulate
        A : Set

test = A
```

At least, I think you should get a `UselessPrivate` error here!

**Comment by andreasabel** [comment]
For now, I implemented a `UselessPrivate` error for the above example.  

Whether the semantics of `open public` under `private` should be changed, should be discussed in a larger forum (@UlfNorell, @nad). 
Reopen if necessary.

**Comment by UlfNorell** [comment]
It would certainly be useful to have `private` negate the `public` in the `open public` of anonymous modules. Currently you have to forgo anonymous modules if you want to do something like this:

``` agda
module _ where

module M where
  private
    module _ (A : Set) where
      Id : Set
      Id = A

  foo : Set → Set
  foo A = Id A

open M

bar : Set → Set
bar A = Id A -- Id should not be in scope
```

**Comment by andreasabel** [comment]
You can do it with a private named module.

``` agda
module _ where

module M where
  private
    module N (A : Set) where
      Id : Set
      Id = A
  open N

  foo : Set → Set
  foo A = Id A

open M

bar : Set → Set
bar A = Id A -- Id should not be in scope
```

**Comment by andreasabel** [comment]
The more extreme suggestion was that it should also work this way:

``` agda
module _ where

module M where
  private
    module N (A : Set) where
      Id : Set
      Id = A
    open N public

  foo : Set → Set
  foo A = Id A

open M

bar : Set → Set
bar A = Id A -- Id should not be in scope
```

where the `public` is neutralized by the surrounding `private`.
That is what it would take to not define a special semantics for `module _`.

**Comment by favonia** [comment]
Just want to clarify that, once anonymous modules earn special treatments to stay private under `private`, personally I am in favor of banning public opening under `private` altogether. It seems confusing and probably not that useful.

**Comment by favonia** [comment]
FYI: I made a post to the Agda mailing list.

**Comment by UlfNorell** [comment]
Since anonymous modules desugar in `ConcreteToAbstract` and the useless private error is triggered in `Concrete.Definitions` it should be very easy to keep the error for `private open public` but allow it for anonymous modules. There wouldn't even be any special treatment of `open public` under `private`, just a change to the desugaring of anonymous modules:

``` agda
private
  module _ Γ where
    Decls
==>
private
  module .Fresh Γ where
    Decls
open .Fresh
```

Non-private anonymous modules would desugar as before.

**Comment by andreasabel** [comment]
To clarify:
You mean, just remove the useless-private error I just added and instead give `private module _` a modified semantics (open private instead of open public).
The useless-private error is currently not triggered for an `open` statement if there is a module definition in the same block (my example with `N` does not trigger this error).

**Comment by UlfNorell** [comment]
Yeah, I think that's the most sensible thing to do. That way we'd treat `open public` the same as other things that aren't affected by `private`. I.e. give an error if there's nothing else the `private` applies to and ignore it otherwise.
