### ISSUE TITLE
Broken `putStrLn` on the JS backend? 

### ISSUE THREAD

**Issue by asr** [agda/agda#2222]
``` agda
open import Common.IO

header = putStrLn "foo"

main : IO _
main = putStrLn "42"
```

```
$ agda --js --ignore-interfaces Test.agda
$ node jAgda.Test.js 
foo
42
```

You are seeing well, `foo` was printed.

**Comment by phile314** [comment]
Generated JS code:

```
var agdaRTS = require("agda-rts");
var jAgda_Common_IO = require("jAgda.Common.IO");

exports["header"] = jAgda_Common_IO["putStrLn"]("foo");
exports["main"] = jAgda_Common_IO["putStrLn"]("42");
```

The problem is that the IO monad just gets erased by the JS compiler. If an IO function is fully applied, the JS runtime will execute the side effect no matter if we are in the top-level main IO action or not.

I suggest to wrap all IO values in a lambda to block evaluation. Pseudo-js-code:

```
bind = \x y _ -> let y' = y unit in (x y') unit
return = \x _ -> x
putStrLn = \x _ -> js-putStrLn x
```

I will give that a go tomorrow or so.

**Comment by UlfNorell** [comment]
Does this mean that the test case for #2218 can be enabled for the JS backend?

**Comment by np** [comment]
@phile314 I'm wondering if a continuation monad would be better suited to integrate with JS libraries. Since a large fraction of JS libraries are async it would be easier to integrate them.

See for instance the monad I used in crypto-agda: https://github.com/crypto-agda/agda-libjs/blob/master/lib/FFI/JS.agda#L267-L310

And one example of an async function `readFile`: https://github.com/crypto-agda/agda-libjs/blob/master/lib/FFI/JS/FS.agda#L14-L16

**Comment by phile314** [comment]
Haven't given it much thought, just used the first idea that came to mind. I don't have any strong opinion on this, but yes, I see how cps style could integrate better with existing JS libraries.

PR would be greatly appreciated, else I might give it a go next week :-)
