### ISSUE TITLE
Absence or presence of top-level module header affects scope

### ISSUE THREAD

**Issue by nad** [agda/agda#2229]
Consider the following modules. `M.agda`:

```agda
postulate
  A : Set
```

`Reexport1.agda`:

```agda
open import M public
```

`Reexport2.agda`:

```agda
module Reexport2 where

open import M public
```

`Fails.agda`:

```agda
open import Reexport1

B : Set
B = A
```

`Works.agda`:

```agda
open import Reexport2

B : Set
B = A
```

Agda accepts `Works.agda`, but rejects `Fails.agda` (because `A` is claimed to not be in scope). The problem exists already in Agda 2.4.0.2.

**Comment by UlfNorell** [comment]
I guess the fix would be to disallow `open public` before the module header. That would cause `Reexport1` to desugar to the same code as `Reexport2` instead of what you get now:

``` agda
open import M public
module Reexport1 where
```

**Comment by nad** [comment]
> I guess the fix would be to disallow `open public` before the module header.

Sounds reasonable to me.

**Comment by andreasabel** [comment]
What is the intended semantics of

``` agda
open import M public
module Reexport1 where
```

Is `public` just ignored at the moment?  Maybe it should be an error.
Relevant code is function `spanAllowedBeforeModule` in `Syntax.Concrete`.

**Comment by UlfNorell** [comment]
From the original report it looks like it's ignored, which is not surprising I suppose. Making it an error is better.

**Comment by andreasabel** [comment]
The reason to allow import statements before the module header is to use the imported things in the module parameters.  Unparametrized modules do not need this feature, and if one drops the module header then there are no parameters.  Thus it would make sense to (virtually) insert the

```agda
module _ where
```

before the first import declaration.  This would fix this issue.

The error message for open public before the module header is a separate issue then.  One could also change the semantics of

```agda
open import N public
module M pars where
```

to reexport the symbols of `N` from `M`.  (This would only make sense in the semantics of `open public` which I oppose, so that is a silly suggestion.)

**Comment by andreasabel** [comment]
I am opening a new issue for the useless `public` import.
