### ISSUE TITLE
Module applications do not eagerly introduce hidden arguments

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#2232]
``` agda
open import Level
open import Relation.Binary.PropositionalEquality

record Eq {ℓ} (t : Set) : Set (suc ℓ) where
  field
    eq : t → t → Set ℓ

module MyModule {ℓ} (t : Set) {{requires : Eq {ℓ} t}} where
  -- blah blah

instance
  myClass⊤ : Eq ⊤
  myClass⊤ = record { eq = _≡_ }

-- doesn't work
open MyModule ⊤

-- does work
open MyModule ⊤ {{_}}
```

This is strange behavior -- why is `{{_}}` somehow providing more information than simply leaving it off?

**Comment by andreasabel** [comment]
Does not feel strange to me.  The first `open` leaves level `l` completely unconstrained, hence, the yellow. The second `open` asks to find an instance for `Eq {l} Top` which is found as `myClassT`, solving the level variable `l` to `lzero`.

Maybe what your are suprised about is that `open` does not eagerly introduce hidden and instance parameters, but lazily. But then, you should also be surprised that simply writing

``` agda
open MyModule
```

succeeds (instead of producing an unconstrained level meta).

Does this answer your question or do you see some action needed on this issue?

**Comment by identicalsnowflake** [comment]
Well it is unintuitive to me that `open MyModule` doesn't complain about unsolved parameters but `open MyModule X` does. I had written down `open MyModule X` first when I was working, and it didn't occur to me to resolve the compiler complaints about lack of constraint information by removing even more information!

But anyway, yeah, removing the type parameter works and I was able to get the API I wanted working nicely, so there's no issue beyond the confusion it might cause people like me.

**Comment by andreasabel** [comment]
Agda does not generalize over unconstrained metas; it seems that you intuitively expect it, though. One you force Agda to instantiate a hidden argument by a meta, it becomes a meta that needs to be solved (case `open MyModule X`).  It you don't force Agda so (case `open MyModule`), the imported symbols will be generalized over the hidden parameter (e.g. `P : forall {l} (t : Set) -> ...`).
