### ISSUE TITLE
Performance issue with deeply-nested lambdas

### ISSUE THREAD

**Issue by m0davis** [agda/agda#2255]
In the code below, `foo` should normalise linearly in the size of its argument, yet Agda's actual normalisation behavior is non-linear.

``` agda
open import Agda.Builtin.Nat

foo : Nat → (Nat → Nat) → Nat
foo zero f = f zero
foo (suc n) f = foo n λ n → f (suc n)

test-1 : Nat
test-1 = {!foo 2000 (λ n → n)!} -- C-c C-n is fast

test-2 : Nat
test-2 = {!foo 10000 (λ n → n)!} -- C-c C-n generates a space leak
```

**Comment by UlfNorell** [comment]
This is due (in part) to the fact that the internal syntax of Agda cannot represent beta redexes, so instead of building up a (linearly sized) thunk `λ n → (λ n → (... λ n → (λ n → n) (suc n) ...) (suc n)) (suc n)` you'll end up having to push the argument through each time the substitution is forced.

I don't understand why it's quite so bad though, but as a work-around you can name the lambda:

``` agda
fsuc : (Nat → Nat) → Nat → Nat
fsuc f n = f (suc n)

foo : Nat → (Nat → Nat) → Nat
foo zero    f = f zero
foo (suc n) f = foo n (fsuc f)
```

**Comment by UlfNorell** [comment]
Changing the lambda to a pattern lambda also fixes the problem:

``` agda
foo : Nat → (Nat → Nat) → Nat
foo zero    f = f zero
foo (suc n) f = foo n λ { n → f (suc n) }
```

**Comment by UlfNorell** [comment]
The reason it's slower than it has to be is that we can't be strict enough in the substitution under lambdas without destroying performance in other cases (for instance #2215).
