### ISSUE TITLE
Wrong coloring of OPTIONS pragma

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#2268]
The syntax coloring of

``` agda
{-# OPTIONS --foo #-}
```

is (mildly) broken. It displays the inital `{-#` in black, the word `OPTIONS` in yellow, and the rest of the line in red, including the final `#-}`.
The reason is that font-lock is used for automatically highlighting `--`-comments and that Agda’s smart highlighting cannot override that (and the two dashes before `foo` are detected as the beginning of a comment).

One way to fix it is to disable automatic highlighting of comments altogether, the main drawback being that `--`-comments won’t be colored before loading the file (they will be colored as before after loading, of course). Note that automatic highlighting of `{- -}`-comments is already disabled because of issue #1559. 

Do people care about having `--`-comments already colored before the file is loaded?

**Comment by guillaumebrunerie** [comment]
Actually I just noticed another drawback of disabling automatic highlighting of `--`-comments.
Currently, adding `--` in the middle (or at the beginning) of a line in a file which is already loaded will color the rest of line in red instantly, but with what I am proposing it will have to wait until the file is loaded again.

So I can answer to myself, I do care about it :)
The issue about the wrong coloring of `{-# OPTIONS --foo #-}` remains, though.

**Comment by gallais** [comment]
Looking into it because I'm not happy either about the way pragmas are highlighted / the lack of highlighting for multi-line comments my previous fix entails. One solution could be to use 3-characters long tokens to detect comments. It's not possible using emacs' syntax table but it looks like it [could be done programmatically](http://emacs.stackexchange.com/a/13300/11893).
