### ISSUE TITLE
Printer does not use sections.

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2270]
In goals I see `\ section -> x + section` and `_+_ x` but never `x +_`.
If we parse sections, we should also print them!

**Comment by nad** [comment]
Should everything that could be written as a section be printed as one? Now we consistently choose to use lambdas. Are you suggesting to consistently use sections instead?

**Comment by andreasabel** [comment]
I want Agda to consistently print me back what I wrote.  So, if I wrote a section, Agda should print a section. If I wrote a lambda, I want Agda to print a lambda.  For system-generated things, we can choose a default (e.g. leave at it is, print lambdas).

The information is there in the beginning and can be preserved to be used in printing.  We do this now also for hidden arguments and style of projections (prefix/postfix).  See, e.g., `Origin` and `ProjOrigin` types.

**Comment by WolframKahl** [comment]
On Sat, Oct 22, 2016 at 03:21:48AM -0700, Andreas Abel wrote:

> I want Agda to consistently print me back what I wrote.

Something to consider in this context:

Where do you draw the line between concrete syntax and abstract syntax?

And where do you draw the line between syntactic essence and syntactic sugar?

Wolfram

**Comment by andreasabel** [comment]
I do not exactly what you are hinting at, but the more faithful Agda printing is to the user's choice of expression, the more efficient the interaction between Agda and the user will be (for the user ;-)).

SML-NJ is the enfant terrible: it desugars and prints to the user the desugared syntax for error messages.  Haskell tries to do a better job, but is not perfect either.

**Comment by WolframKahl** [comment]
I think there is a tricky design space here.

If a user chooses to write `f : A → (A → A)`, are you opposed to displaying the type of `f` as `A → A → A`?

If yes, then I consider that as moving the usual boundary between abstract and concrete syntax:
The usual abstract syntax grammar for function types has only one recursive production:

```
  ty ::= ty → ty
```

while the concrete syntax grammar also has

```
    ty ::= (ty)
```

(simplifying the situation quite a bit...).

Correspondingly, the abstract syntax tree has no constructor for parenthesisation.

The concrete syntax tree is rarely constructed explicitly, but it would have such a constructor.

A related issue that crops up in syntax tree libraries intended for code generation is whether the syntax tree provided there should include comments, since comments are typically not part of the abstract syntax of a language, but while generating some low-level code (C, Go, SQL :wink:), I may still want to insert automatically-generated “comments”, even though I definitely do not want to bother about where parentheses need to be inserted.

Hope this clarifies a bit what I trtied to hint at...

**Comment by andreasabel** [comment]
About comments, just discussed this with Ulf today.  If we want to offer refactoring tools, we need to parse comments properly (and store them in the tree).

Wrt. to parentheses, Agda is not optimally pruning them.  However, I think more or less parentheses in error messages are not that crucial than the other issues like sections, unsolicited unfolding of definitions etc.

**Comment by nad** [comment]
Are you suggesting that we should have sections in abstract as well as internal syntax, or only in abstract syntax?

I agree that it's nice not to desugar too much before checking types, but on the other hand the type checker becomes more complicated if we add sections to the abstract syntax.

I certainly don't want to have sections in the internal syntax.

**Comment by andreasabel** [comment]
``` haskell
Abstract.Expr = ...
  | App   ExprInfo Expr (NamedArg Expr) -- ^ Ordinary (binary) application.
```

The `ExprInfo` could be exchanged for a type `AppInfo` which also says how this application should be printed (prefix, mixfix w w/o sections).
The internal syntax could be extended with similar information.  Note that the internal syntax already carries information about what the user has written or what comes from the system, see `argInfoOrigin`.
This could also allow us to make some progress on #632.

**Comment by andreasabel** [comment]
The severity of this issue shows with the `refine` command:
```agda
open import Common.List
open import Common.Equality

map-append : ∀{A B : Set}(f : A → B) (xs {ys} : List A) →
  map f (xs ++ ys) ≡ map f xs ++ map f ys

map-append f [] = refl
map-append f (x ∷ xs) = {!cong (f x ∷_)!}  -- C-c C-r
```
produces
```
map-append f (x ∷ xs) = cong (λ section → f x ∷ section) {!!} 
```

**Comment by nad** [comment]
The refine command also removes "unnecessary" module qualifiers that I put in on purpose to make the code more readable.

**Comment by UlfNorell** [comment]
The fix makes any system-inserted lambda term print as a section when possible.

**Comment by nad** [comment]
> The refine command also removes "unnecessary" module qualifiers that I put in on purpose to make the code more readable.

I did not include a test case, and when I tried some simple examples now they worked fine. If I encounter this problem again I might open a new issue.

**Comment by andreasabel** [comment]
There is a bug with sections for qualified operators: #3072.
