### ISSUE TITLE
Simplification should apply rewrite rules

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#2277]
Simplification (`C-c C-t`) should apply rewrite rules. Indeed, one of the uses of rewriting is to simulate higher inductive types with definitional reduction rules for the point-constructors, and the idea of simplification is that an eliminator applied to a constructor should reduce. So the rewrite rules used should be considered by simplification (are there other uses of rewrite rules which should not be simplified?)

I’m not sure if it is easy to do, though, given the interlacing between normal reduction and rewrite rules.

**Comment by jespercockx** [comment]
I agree this is a real problem, I often find myself normalizing terms when using rewrite rules because the simplification didn't trigger them. To fix this, I think the best approach would be to change when rewrite rules are applied: right now they are applied in `reduce`, but maybe a better position would be in `unfoldDefinition` or one of its variants. Since `unfoldDefinition` is called by both `reduce` and `simplify`, that should fix this issue. I'll see if I can get this to work...

**Comment by jespercockx** [comment]
I improved the integration of rewriting with the rest of the reduction machinery, see https://github.com/agda/agda/commit/e8f61164cb515263d400df4a2bdfa18ab16e876d. This means rewrite rules are now also considered as simplifications, so this issue is fixed. 

I also took the opportunity to integrate rewrite rules into @UlfNorell 's fastReduce (I hope he doesn't mind). This should improve the performance of long-running computations involving rewrite rules.
