### ISSUE TITLE
Agda allows to define data types that lie in Setω.

### ISSUE THREAD

**Issue by effectfully** [agda/agda#2285]
```agda
data Big : _ where
  big : (∀ {α} -> Set α) -> Big
```

No unsolved metas or constraints. `C-c C-d Big` gives `Setω`. Agda version 2.6.0.

[Found](https://www.reddit.com/r/agda/comments/59nn8b/preserving_in_free_containers/) by [dnkndnts](https://www.reddit.com/user/dnkndnts)

**Comment by nad** [comment]
The problem seems to go back to Agda 2.3.0.

**Comment by identicalsnowflake** [comment]
> bug

Come on, it's an _incomplete feature_ with a [compelling use case](https://identicalsnowflake.github.io/Voldemort.html) 🙂

**Comment by andreasabel** [comment]
``` agda
{-# OPTIONS -v tc.meta.assign:50 #-}
{-# OPTIONS -v tc.meta.new:50 #-}

data Big : {!!} where
  big : (∀ {α} -> Set α) -> Big

-- new sort meta _0 : .Agda.Primitive.Level
-- new meta (?0) _1 : Set _0
-- new sort meta _2 : .Agda.Primitive.Level
-- solving _0 := .Agda.Primitive.lsuc _2
-- solving _1 := Set _2
-- solving _2 := Setω
```

We end up with

```
Set _2 : Set (lsuc _2)
```

which is fine, but then the sort meta `_2` is solved by `Inf`.  This is also considered fine, and there are no further checks whether some type contains a subexpression `lsuc _2`.

**Comment by andreasabel** [comment]
Unfortunately, this bug cannot be exploited to get Hurken's paradox through. :(

**Comment by andreasabel** [comment]
Maybe the occurs check for

```
_0 := .Agda.Primitive.lsuc _2
```

could mark `_2` as not instantiable by `Setw`.

**Comment by identicalsnowflake** [comment]
So I'm obviously asking for a very ignorant friend here, but why exactly is this bad?

**Comment by andreasabel** [comment]
One could think about extending Agda by a new predicative universe `Setw`, but certainly we do not want `Setw : Setw`, which we partially have now.

**Comment by identicalsnowflake** [comment]
> certainly we do not want Setw : Setw

Sure, but isn't this just an artefact of the current definition of level? As I understand (and I don't know much about this), all we really need in universe levels is a decidable total order with a zero, right?

Exactly what that should be is a matter beyond anything I care about, but getting something more flexible than SetW and N should be doable: I mean even `N x N` has an order, and (1,a) can be greater than (0,b), etc.

In any case, I feel like my example case is pretty compelling -- everyone already knows about combining initial states and making free monads out of them, then reifying later; the problem is that you lose the distinction between <*> and >>=, meaning you suffer a potential performance penalty (everything executing unnecessarily sequentially). Being able to forall over the process of reification allows you to preserve this distinction end-to-end, meaning you get the same "user experience" writing code, but don't have to pay that annoying performance penalty for it.

That's what I was trying to demonstrate in my example.

**Comment by andreasabel** [comment]
You cannot have both `((i : Level) -> Set i) : Set l` and `l : Level` at the same time without running into inconsistencies.  Thus, we need a second type of levels you cannot quantify over if we want to go to `Setw` and beyond.  At the moment, this second level type has a single inhabitant, `w`, and the rules are (meant to be) designed to implement this.

**Comment by identicalsnowflake** [comment]
> we need a second type of levels you cannot quantify over

And then this bumps the issue back one more step, right? Is it not possible to decide how many times this needs to be done by looking at the AST, and then say "wow, what luck! One more forall and you'd have broken the rules!" -- drawing the target around the arrow, so to speak? 

To me this sounds very similar to `Rank2Types` and `RankNTypes`.

**Comment by andreasabel** [comment]
Indeed, and this is called "predicativity".  You cannot quantify over a totality (Levels) to define a member of that totality (a level).

**Comment by WolframKahl** [comment]
On Tue, Nov 01, 2016 at 12:17:05AM -0700, Andreas Abel wrote:

> One could think about extending Agda by a new predicative universe `Setw`, but certainly we do not want `Setw : Setw`, which we partially have now.

Would it be perhaps less effort and more gain to have new impredicative universes `Set (Level.suc w)` etc., with `Setw : Set (Level.suc w)`?

Just speculating wildly...

**Comment by WolframKahl** [comment]
On Tue, Nov 01, 2016 at 02:22:09AM -0700, Andreas Abel wrote:

> You cannot have both `((i : Level) -> Set i) : Set l` and `l : Level` at the same time without running into inconsistencies.  Thus, we need a second type of levels you cannot quantify over if we want to go to `Setw` and beyond.  At the moment, this second level type has a single inhabitant, `w`, and the rules are (meant to be) designed to implement this. 

Would bounded Level quantification be an option?

E.g., `((i : Levels l) -> Set i) : Set l` with `l : Level`?

**Comment by andreasabel** [comment]
Having an empty type of levels `Levels lzero` can easily get us into paradoxes as well, so we might try

``` agda
((i : Level<= l) -> Set i) : Set (suc l)
```

@identicalsnowflake Would that be sufficient for the Voldemort example?

**Comment by WolframKahl** [comment]
On Tue, Nov 01, 2016 at 10:47:42AM -0700, Andreas Abel wrote:

> Having an empty type of levels `Levels lzero` can easily get us into paradoxes as well, so we might try
> 
> ``` agda
> ((i : Level<= l) -> Set i) : Set (suc l)
> ```

In comparison with `Levels<`, this `Level<=` also looses the ability to quantify over all levels that are less than a limit ordinal (e.g., ω).

**Comment by andreasabel** [comment]
Adapting a paradox of @Saizan from sized types to strictly bounded levels, here you go:

``` agda
module _ (lpred : (i : Level) → Level< i) where

  data D i : Set i where
    c : (∀ (j : Level< i) (A : Set j) → A → A) → D i

  f : ∀ i → D i → ⊥
  f i (c g) = f j (g j (D j) (c λ _ _ x → x))
    where 
    j = lpred i

  agdaLoops : ∀ (o : ⊥) → o ≡ f lzero (c λ _ _ x → x)
  agdaLoops o = refl
```

**Comment by guillaumebrunerie** [comment]
The problem is the fact that Agda would loop or is there an actual paradox (being able to prove false)? Because of course there can’t be such an `lpred` function given that `lpred lzero` would be a level smaller than zero.

**Comment by identicalsnowflake** [comment]
> @andreasabel Would that be sufficient for the Voldemort example?

Mm I don't think that's strong enough. Even if you could adjust the type classes to use `<=`, the `Interpreter` data type appears at first glance more flexible than it actually is: the combinators are where you start to notice how little wiggle room you have.

Look at the definition of `_>>-_`, in particular the expression `i r`. If the interpreter `r` only worked on types in levels <= `l` for some `l`, what happens when the first parameter provides an `i` which is more demanding? There would be no way to "run" the first part to get the `t₁` result, since the interpreter `r` we're given isn't strong enough, so we're stuck.

**Comment by andreasabel** [comment]
@guillaumebrunerie Agda looping is bad enough.  Since we normalize open terms, we need to terminate also for those that are built from lies such as `lpred`.

**Comment by guillaumebrunerie** [comment]
Thanks, interesting example.
