### ISSUE TITLE
Instance arguments are not available as instances in record modules

### ISSUE THREAD

**Issue by nad** [agda/agda#2320]
The following code is rejected:
```agda
record R₁ : Set₁ where
  field
    A : Set

open R₁ ⦃ … ⦄

record R₂ : Set₁ where
  field
    ⦃ r₁ ⦄ : R₁

  B : Set
  B = A
```
Error message:
```
No instance of type R₁ was found in scope.
when checking that the expression A has type Set
```
I discussed this with @UlfNorell, and he thought that `r₁` should be available as an instance in `R₂`'s record module. Note that this instance is available in fields:
```agda
  field
    x : let B = A in B
```
However, a simple transformation breaks the code:
```agda
  B : Set
  B = A

  field
    x : B
```

**Comment by UlfNorell** [comment]
The problem is that we haven't yet decided that it's safe to turn on eta equality for the record type when checking the record module, so there's no eta expansion available to reveal the `r₁` field. It checks if you add `eta-equality` explicitly:

```agda
record R₂ : Set₁ where
  eta-equality
  field
    ⦃ r₁ ⦄ : R₁

  B : Set
  B = A  -- works
```

The `let` version works because the types of fields are checked with previous fields explicitly in the context (rather than an element of the record type). When you make it a declaration interleaved with the fields it's checked twice: once as part of the field telescope, which checks ok, and once as part of the record module, where it fails.

Implementing the proposal in https://github.com/agda/agda/issues/434#issuecomment-235684127 might make this easier to handle, but I'm not sure.

**Comment by UlfNorell** [comment]
This is kind of a special case though. It does make sense to eta expand `self` (once) when inside the record module, regardless of whether the record type supports eta or not.
