### ISSUE TITLE
Literate Agda parser does not recognize TeX comments

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2355]
In a `.lagda` file, this commented-out block
```tex
% \begin{code}
% postulate A : Set
% \end{code}
```
gives a parse error. 

@vlopezj Can you take this issue?

**Comment by andreasabel** [comment]
Used to work e.g. in Agda-2.4.2.5.

**Comment by vlopezj** [comment]
I'll take a look.

**Comment by asr** [comment]
@vlopezj, please add the 2.5.3 milestone to this issue.

**Comment by asr** [comment]
The LaTeX-backend was not tested in some test cases (see #2392) including  `test/LaTeXAndHTML/succeed/Issue2355.lagda`. Since this test case failed, I removed it from the latex-html test suite.

The error is:

```latex
\documentclass{article}

\usepackage{agda}

\begin{document}

% \begin{code}
% postulate A : Set
% \end{code}

\end{document}
```

```
$ agda --latex Issue2355.lagda
$ cd latex
$ pdflatex Issue2355.tex
! Missing $ inserted.
<inserted text> 
                $
l.8 \>
      \AgdaComment{\<\\
```

Note that for testing the LaTeX-backend on `Issue2355.lagda` must exist a file called `Issue2355.compile`. If this file is empty, `Issue2355.lagda` is tested using all the LaTeX compilers (pdflatex, xelatex and lualatex).

**Comment by vlopezj** [comment]
@asr After some digging I see that the problem you report is not with the literate parser, but with the LaTeX back-end. In this case it starts a new code-block from commented-out `\begin{code}`, which is wrong.

However, I think the real problem is having two different implementations for finding `\begin{code}` and `\end{code}` macros: one in `Agda.Syntax.Parser.Literate.literateTeX` and one in `Agda.Interaction.Highlighting.LaTeX.nextToken'`. I believe the LaTeX back-end should reuse the literate parser implementation.

**Comment by asr** [comment]
I'll file a new issue reporting the LaTeX backend problem and adding your comment.

**Comment by asr** [comment]
I filed #2400 and I added the original Issue2355.lagda into the suite of successfull tests.

**Comment by WolframKahl** [comment]
Is 2.5.3 coming very soon? Otherwise this might deserve a bugfix release --- this is issue pretty bad for trying to get large literate code bases into Agda-2.5.2.
