### ISSUE TITLE
Type-checking-order-dependent choice between relevant and irrelevant function type

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#2428]
Consider the following example:
````agda
open import Agda.Builtin.Equality

postulate A : Set

test : {F F' : .A → Set}
     → _≡_ {A = {!!}} (λ a → F a) (λ a → F' a) → Set₁
test e = Set
````
Calling the constraint solver in the hole (C-c C-s) produces the solution `{A = (a : A) → Set}`, but this solution is not unique: another valid (and distinct!) solution is `{A = .(a : A) → Set}`.

I encountered my issue when trying out my fix of #2407 on `test/Succeed/EtaContractIrrelevant.agda`.

**Comment by jespercockx** [comment]
In my fix to #2407 (https://github.com/agda/agda/commit/0dae57c75ca5f6fd22ca2a0a1844e01ca85ac6bb#diff-3ecf99d3033eaf761b2a27c3b1f4c4a8R28) this issue forced me to make the type of the equality explicit because otherwise it would be resolved to a non-irrelevant function type and subsequently cause the case splitting to fail.

**Comment by andreasabel** [comment]
After pulling your fix, behavior has slightly changed, but Agda allows a split here and later complains:
```agda
test : (F : A → Set) (F' : .A → Set)
     → F ≡ F' → Set₁
test F F' e = {!e!}

-- Splitting on e gives
--   test .F' F' refl = ?
-- Error
-- (A → Set) !=< (.A → Set) because one is a relevant function type
-- and the other is an irrelevant function type
-- when checking that the expression F has type .A → Set
```

**Comment by andreasabel** [comment]
> Calling the constraint solver in the hole (C-c C-s) produces the solution `{A = (a : A) → Set}`, but this solution is not unique: another valid (and distinct!) solution is `{A = .(a : A) → Set}`.

I'd say the only valid solution is `.A -> Set`, which is also unique.  Note that `A -> Set <= .A -> Set` but not the other way round, thus, the only common type of `F` and `F'` is `.A -> Set`.

**Comment by jespercockx** [comment]
If you eta-contract `λ a → F a` and `λ a → F' a` manually to `F` and `F'` then the constraint solver correctly finds the solution `.(a : A) → Set`. However, the eta-expanded form is inherently ambiguous: either you're lambda-binding a relevant variable and then only using it irrelevantly, or you're lambda binding an irrelevant variable from the beginning. 

@anuyts suggested that we maybe should have a different syntax for binding a variable irrelevantly, for example `λ .a → F a`. Then we could reserve the `λ a → ...` syntax for *only* the relevant function space.

**Comment by andreasabel** [comment]
Sorry, I got it wrong, the subtyping is `.A -> Set <= A -> Set`, thus, my previous comment is bogus.  The only common type is `A -> Set` which is found by Agda.  Where was the problem again?

**Comment by jespercockx** [comment]
The problem is that the constraint solver is filling the implicit argument with solution `A -> Set`, but the solution I actually wanted is `.A -> Set` and that's not found by the unifier.

**Comment by andreasabel** [comment]
Because it is not a solution.

**Comment by jespercockx** [comment]
So then why is it accepted when I fill it in manually? Are you saying this is a bug and I shouldn't be able to?

**Comment by jespercockx** [comment]
Oh sorry, I think we're talking about different examples. If one `F` is relevant and the other is irrelevant, then I agree that the only solution should be the relevant function space `A -> Set`. However, we *also* get this solution if both `F`'s are irrelevant, even though `.A -> Set` is in that case also a valid solution.

**Comment by andreasabel** [comment]
OK, sorry about that.

For my example:
If I try to fill it in manually with give, I get
```agda
.A → Set != (a : A) → Set because one is a relevant function type
and the other is an irrelevant function type
when checking that the expression .A → Set has type Set₁
```
If I write it before loading, 
```agda
test-o : (F : A → Set) (F' : .A → Set)
     → _≡_ {A = .A → Set} (λ a → F a) (λ a → F' a) → Set₁
test-o F F' e = Set
```
Agda complains about `F a`:
```
Variable a is declared irrelevant, so it cannot be used here
when checking that the expression a has type A
```
LGTM.

By why is the split result
> test .F' F' refl = ?

not accepted?

**Comment by jespercockx** [comment]
I don't know, it is accepted on my system.

**Comment by andreasabel** [comment]
Regarding your example:
If I put a `.` on the first lambda, Agda takes the solution `.A -> Set`.
```agda
test : {F F' : .A → Set} → _≡_ {A = {!!}} (λ .a → F a) (λ a → F' a) → Set₁
```
If I put a `.` on the second lambda, I get an error:
```agda
test : {F F' : .A → Set} → _≡_ {A = {!!}} (λ a → F a) (λ .a → F' a) → Set₁
```
```
Found an irrelevant lambda where a relevant lambda was expected
when checking that the expression (λ .a → F' a) has type
((a : A) → Set)
```
Agda already decided that the solution should be `A -> Set`.
But this error is not justified, the eta-expansion does not change anything...

**Comment by andreasabel** [comment]
> I don't know, it is accepted on my system.

You are right, your fix for #2407 must have repaired this.

**Comment by andreasabel** [comment]
After fixing #2429, putting the dot on the second lambda has no effect, the inferred type stays `A -> Set`.
Lambdas are somewhat ghastly, the heuristics associated with them make type-checking non-confluent, i.e., the order in which Agda considers the subterms of an expression matters.  And the order is dependent on the constraint solver, which metas have already been solved and which are waiting.  See #1079 and friends.

Agda's behavior for your original example is consistent: First, it gets to `\ a -> F a` for which it has no type.  It decides that this should be a relevant function space with no leading hidden arguments. Consequently, the solution is `A -> Set`.  If make it `\ .a -> F a`, it decides it should be an irrelevant function space.

We could of course not make such decisions.  Then, you'd just get yellow here.  You would always have to supply the type of the equality explicitly, because the arguments would not give away the type.  There could always be extra hidden lambdas, leading to the type of the equality being of hidden function space. 

Less radically, we could have relevance metas which are solved just as other metas.  Then, we would rely less on heuristics.

Or, we could follow Andreas N's suggestion to require to always mark irrelevant lambdas as such, if they are in inference position.  But then "in inference position" should not depend on whether the type of a lambda is already known or not, but on the syntax.  I had fruitless discussions with @UlfNorell about this two years ago.  Originally, typed lambdas would be inferred, and untyped lambdas would be checked.  Thus, there was a difference between `\ x -> e` (checked, waits for type, can be complemented by hidden lambdas) and `\ (x : _) -> e` (inferred, has type `(x : _) -> _`, no extra hidden pis).  This is hard to communicate, thus the distinction was removed, and we are in this muddy situation now.   But introducing a new notation for an inferred lambda, while clean, is very unconventional and would alienate Haskellers etc.

**Comment by jespercockx** [comment]
Well, I guess the original example can be fixed by putting dots before the lambda-bound variables (which I didn't know was already possible) so I guess the problem is not very urgent. In a sense we are already in a situation where a regular lambda `\ x -> ...` is always assumed to be relevant, *unless* the user gives the lambda explicitly annotates the lambda with an irrelevant function type somehow. So I can live with the current situation, I guess.

**Comment by andreasabel** [comment]
I also have no plans to return to fixing the lambdas, so I close...
