### ISSUE TITLE
The LaTeX and HTML backends do not highlight (all) unsolved metas

### ISSUE THREAD

**Issue by nad** [agda/agda#2474]
Consider the following literate Agda code:
```latex
\documentclass{article}
\usepackage{agda}
\begin{document}

\begin{code}
{-# OPTIONS --allow-unsolved-metas #-}

postulate
  F : {_ : Set} → Set

A : Set
A = F
\end{code}
\end{document}
```
The LaTeX backend generates the following LaTeX code:
```latex
\documentclass{article}
\usepackage{agda}
\begin{document}

\begin{code}%
\>[0]\AgdaSymbol{\{{-}\#}\AgdaSpace{}%
\AgdaKeyword{OPTIONS}\AgdaSpace{}%
\AgdaOption{{-}{-}allow{-}unsolved{-}metas}\AgdaSpace{}%
\AgdaSymbol{\#{-}\}}\<%
\\
%
\\
\>[0]\AgdaKeyword{postulate}\<%
\\
\>[0][@{}l@{\AgdaIndent{0}}]%
\>[2]\AgdaPostulate{F}\AgdaSpace{}%
\AgdaSymbol{:}\AgdaSpace{}%
\AgdaSymbol{\{}\AgdaBound{\_}\AgdaSpace{}%
\AgdaSymbol{:}\AgdaSpace{}%
\AgdaPrimitiveType{Set}\AgdaSymbol{\}}\AgdaSpace{}%
\AgdaSymbol{→}\AgdaSpace{}%
\AgdaPrimitiveType{Set}\<%
\\
%
\\
\>[0]\AgdaFunction{A}\AgdaSpace{}%
\AgdaSymbol{:}\AgdaSpace{}%
\AgdaPrimitiveType{Set}\<%
\\
\>[0]\AgdaFunction{A}\AgdaSpace{}%
\AgdaSymbol{=}\AgdaSpace{}%
\AgdaPostulate{F}\<%
\end{code}
\end{document}
```
Note that there is no call to `\AgdaUnsolvedMeta` in the code above.

**Comment by gallais** [comment]
You'd think it'd be a simple matter of [also looking at `otherAspects`](https://github.com/agda/agda/blob/master/src/full/Agda/Interaction/Highlighting/LaTeX.hs#L462) and this is what
[I have attempted to do](https://github.com/agda/agda/commit/bc74b3e420fa41ea2df545f89ae43b045ebcf8af) but it turns out that `otherAspects` seems to be empty for `F`.
Which is pretty puzzling given it is properly highlighted in emacs.

Edit: do we need to explicitly call [`errorHighlighting`](https://github.com/agda/agda/blob/master/src/full/Agda/Interaction/InteractionTop.hs#L307) or [`computeUnsolvedMetaWarnings`](https://github.com/agda/agda/blob/master/src/full/Agda/Interaction/InteractionTop.hs#L305)
and fuse the resulting `CompressedFile`s for the appropriate `otherAspects` to be set?

Edit²: looks like calling `computeUnsolvedMetaWarnings` and `computeUnsolvedConstraints` does
indeed do the trick.

**Comment by nad** [comment]
Now Agda generates code like `\AgdaUnsolvedMeta{\AgdaPostulate{F}}` instead of code like `\AgdaPostulate{\AgdaUnsolvedMeta{F}}`. I implemented this change because the `\AgdaFormat` command is (by default) applied to the argument of (for instance) `\AgdaPostulate`, not to the argument of `\AgdaUnsolvedMeta`.
