### ISSUE TITLE
Extensible syntax for function space annotations

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#2513]
Currently the only ways we have to annotate a function space is with braces `( ) / {} / {{ }}` or with varying numbers of dots (for irrelevant and non-strict). The problem is that there are lots of things people want to add annotations for: linearity, polarity, parametricity, strictness, custom meta solvers, etc.

It would be nice if we could come up with an extensible syntax that would let us experiment with various annotations without coming up with an ad hoc syntax and fighting the Happy parser every time.

My initial offer is using a bar: `(annotations | x : A) → B`. Multiple annotations could be separated by `;` as in `(pos; linear 4 | x : A) → B`. We would then add annotations corresponding to all the current ways to annotate function spaces:

- `{x : A} → B` = `(implicit | x : A) → B`
- `{{x : A}} → B` = `(instance | x : A) → B`
- `.(x : A) → B` = `(irrelevant | x : A) → B`
- `..(x : A) → B` = `(what-ever-this-actually-means |  x : A) → B`

**Comment by Saizan** [comment]
Recently I implemented the alternative syntax ```(x :{ annotation } A) -> B``` for the Agda/parametric branch.
Actually not only for function types but for definitions too, e.g.
```
postulate
  foo :{ # } Set
```
declares ```foo``` as parametric. I guess it might be better to focus on Pi types for now though.

Here's the commit:

https://github.com/agda/agda/commit/38d06ec0f4108102e3035bf76bb785242df3fbde

There the annotation is parsed as an identifier, and then converted to a Relevance in the parser itself by string comparison. It should be more flexible to resolve the modality during scope checking instead.

**Comment by andreasabel** [comment]
Right, we need a story also for declarations and record fields.

@Saizan's syntax goes back to Jean-Philippe and Guilhem's colors.

`implicit` --> `hidden`

**Comment by UlfNorell** [comment]
Generalising from the `field {x} : A` syntax, I suppose my syntax would be `(annotation | x) : A`. It's tempting to drop the parens, but not sure that would fly in the parser.

I feel that having the annotations between the `x` and the `A` makes the type a bit hard to read if all you care about is the unannotated type (which you often do).

**Comment by andreasabel** [comment]
I think it should be consistent with the function space.  Either dropping the parentheses, or doing them in the same way as in the Pi-type:  `(annotation | x : A)`.  But we also need to support the `(annotation | x)` notation, for the `forall`.  Thus, maybe all variants should be accepted.

Note we also want `(x (hidden | y z) : A) -> B` matching the current `(x {y z} : A) -> B`.

The question is how we handle the non-dependent function space.  @Saizan's syntax would generalize to 
```
  {annotation} A -> B
```
How do you handle that?

**Comment by UlfNorell** [comment]
It's not obvious that we need to handle the non-dependent function space, since we currently don't support it for most annotations. I'd be ok with `(annotation | _ : A) → B`.

How would you deal with `forall` in @Saizan's syntax?

**Comment by andreasabel** [comment]
There is no good story for `forall` in @Saizan's syntax.

Non-dependent function space could be
```
(annotation | A) -> B
```

**Comment by UlfNorell** [comment]
Unfortunately that conflicts with the (not yet implemented) `with` application syntax.

**Comment by andreasabel** [comment]
Maybe it is time to implement it then before it is too late.  Or wait another 8 years...

**Comment by andreasabel** [comment]
Forall can be handled as `forall :{p} x -> A` or maybe, for a single modality `forall :p x -> A`.

**Comment by UlfNorell** [comment]
The latter is already valid syntax binding two variables `:p` and `x`. The former isn't but only because `:` is a reserved character.

I would like any syntax we device to scale up to more complex modalities like use-this-tactic-to-solve-this-argument.

**Comment by anuyts** [comment]
Whatever syntax you come up with, should work for:

* Function type formation (including the declaration of constructor arguments):
    * `(x :{p} A) -> B`
    * `{p} A -> B`
* Module parameters
* Postulates: `postulate a :{p} A`
* Declarations
```Agda
a :{p} A
a = a'
```
* Perhaps lambda-terms, with or without type annotation:
    * `\ (x :{p} A) -> b`
    * `\ x :{p} -> b`
* Record field declarations
```Agda
record A : Set where
    field
        b :{p} B
```
* Perhaps (neither the use nor the uselessness of this is clear to me) constructor declaration:
```Agda
data A : Set where
    a :{p} A
```
* Inductive type parameters
* Inductive type indices
* Type declarations? `data A :{p} Set where`
* ...?

A development in the research that should perhaps also be anticipated on, is the existence of different modes. Currently, all modalities are endomorphisms of the type theory and hence form a pomonoid (partially ordered monoid). I think we are moving to a situation where we consider modalities that are morphisms _between_ type theories (modes), so that the modalities form a category enriched over posets (where objects are type theories/modes and the Hom-sets are posets of modalities between the given modes; if there is only one mode, we are back in a pomonoid). Examples of modes could be: categories, 2-categories, groupoids, sets, propositions, sets with non-trivial relational structure, ...
Each mode would likely be more or less a model of Agda, it's just that types will have a mode and you will need modalities to move from one mode to the other.
See:

* [Licata](http://dlicata.web.wesleyan.edu/pubs.html), Shulman, 2016: Adjoint logic with a 2-category of modes
* Licata, Shulman, Riley, 2017: A fibrational framework for substructural and modal logics
(here modalities even form a multicategory enriched over posets)

I think this is a powerful idea that may increase, rather than decrease, the practical usability of modalities. At least it is worthwhile to think about how to (keep) open the possibility of supporting it.

**Comment by andreasabel** [comment]
Syntax alternatives summary.  The modality annotation should work in:
- telescopes (typed bindings and untyped bindings)
- declarations (type signatures, e.g. on the top level and in records)
- non-dependent function space

@UlfNorell 's proposal:
- telescope `(m | x y : A) (m | z v)`
- declaration `(m | x) : A`
- non-dependent function space: `(m | _ : A) -> B`  (no syntax)

@Saizan 's syntax
- telescope `(x y :{m} A) (z v :{m} _)`, no syntax for untyped bindings 
- declaration `x :{m} A`
- non-dependent function space `(_ :{m} A) -> B` (no syntax)
My suggestion: `{m} A -> B`

Post-@ proposal (new):
- telescope `(x y : A @ m) (z v @ m)`
- declaration `x : A @ m`
- non-dependent function space `A @ m -> B`

Pre-@ proposal (new):
- telescope `(m @ x y : A) (m @ z v)`
- declaration `m @ x : A`
- non-dependent function space `m @ A -> B`
 
Attribute proposal (new):
- telescope `(@(m n) x y : A) (@(m n) z v)` or `(@m @n x y : A)` or (single attribute) `(@m x y : A)(@m z v)`
- declaration `@(m n) x : A` or `@m @n x : A` or `@m x : A`
- non-dependent function space `@(m n) A -> B` or `@m @n A -> B` or `@m A -> B`

**Comment by UlfNorell** [comment]
I can get behind the pre-@ proposal.

**Comment by gallais** [comment]
Do the `@` proposals mean we would get a new primitive `_@_ : Mode -> forall {l} -> Set l -> Set l`?
With this we could state generic distributions laws such as `m @ All id As -> All (m @_) As`
(for the `m`s for which it makes sense, obviously) where `As` is a list of Sets.

**Comment by UlfNorell** [comment]
No.. I'm pretty sure it doesn't mean that.

**Comment by UlfNorell** [comment]
I can also get behind the attribute proposal.

**Comment by andreasabel** [comment]
I'll try to make the parse understand the attribute proposal.

**Comment by anuyts** [comment]
In order to come up with a good syntax for a toy type checker for multimode dependent type theory, I've been writing some example code in different syntaxes. I found the pre-`@` and pre-`|` (Ulf's) proposals significanlty more readable than the attribute proposal. I think the reason is that the attribute proposal does not give you an obvious visual boundary between the annotations and the annotated names.

Compare:
```
IsMph : (@irr @~ lA lB : Nat)
	-> (@~ A : Set lA)
	-> (@~ B : Set lB)
	-> (@str mkA : IsAlg A)
	-> (@str mkB : IsAlg B)
	-> (@str f : A -> B)
	-> Set (max lA lB)

@str mkMu : (@~ @irr l : Nat) -> IsAlg (Mu l)
```
and
```
IsMph : (~ irr | lA lB : Nat)
	-> (~| A : Set lA)
	-> (~| B : Set lB)
	-> (str | mkA : IsAlg A)
	-> (str | mkB : IsAlg B)
	-> (str | f : A -> B)
	-> Set (max lA lB)

str | mkMu : (~ irr | l : Nat) -> IsAlg (Mu l)
```
In the above code, `~` stands for 'implicit', `irr` for 'irrelevant' and `str` for the structural modality.

**Comment by andreasabel** [comment]
Some more visual aid would come from coloring.
The problem with `(p | A) -> B` is that the domain can be confused for a with-application.  This cannot be parsed.

**Comment by anuyts** [comment]
That does not refute pre-@ proposal `(p @ A) -> B`.
But indeed, when syntax coloring is available, they are probably equally readable.

**Comment by nad** [comment]
Syntax highlighting is perhaps not always available (consider papers printed on black-and-white printers), and might not be suitable for people with certain kinds of impaired eyesight.

**Comment by jespercockx** [comment]
Maybe we should offer an alternative color scheme which makes use of different contrast/fonts/bold/italics to distinguish different syntax, I'll create a new issue for that.
