### ISSUE TITLE
Duplicate warning printing

### ISSUE THREAD

**Issue by favonia** [agda/agda#2584]
Git-bisecting told me that, since commit 9f315a6fff45da373b357dc01b0ba0b97fc499f6, the `OldBuiltin` warning (and probably other warnings too) will be printed again when imported into other files. Such warnings were printed only once, which I feel is better. Check the following file `B.agda` and you will see the same warning twice.

`A.agda`:
```agda
data ℕ : Set where
  O : ℕ
  S : ℕ → ℕ

{-# BUILTIN NATURAL ℕ #-}
{-# BUILTIN ZERO O #-}
```

`B.agda`:
```agda
open import A
```

**Comment by andreasabel** [comment]
Right, there should be maybe two classes of warnings.  Inessential ones like the one above, and more essential ones (like overlapping clauses).
Over to @fredrikNordvallForsberg and @gallais.

**Comment by fredrikNordvallForsberg** [comment]
The warning is printed once when encountering it in `A.agda` (before `Finished A` in the output), and again at the end after finishing typechecking `B.agda`. In general, I think this is the right thing to do, because the first time it is printed could be deep inside the trace and overlooked by the user. However I am implementing an option to ignore warnings from imported modules, would that satisfy you @favonia? (Note also that in the emacs mode, the warning is only seen once. This is a commandline issue only.)

```
/tmp/A.agda:6,1-23
Builtin ZERO does no longer exist. It is now bound by BUILTIN
NATURAL
when checking the pragma BUILTIN ZERO O
 Finished A.
/tmp/A.agda:6,1-23
Builtin ZERO does no longer exist. It is now bound by BUILTIN
NATURAL
when checking the pragma BUILTIN ZERO O
Finished B.
```

**Comment by gallais** [comment]
I can see use cases for both of these warnings:

* the in-trace ones allow you to cancel the build as soon as there's a warning to fix it
* the end ones allow you to actually see the list of all warnings if the trace flashes by really quickly

I guess we could have options controlling the behaviour and allowing the user to pick one, the other or even both.

**Comment by favonia** [comment]
@gallais Indeed. @fredrikNordvallForsberg I would then concur @gallais and suggest the following as the default behavior (possibly with options to change it): one at the end of checking `A.agda` and another one *at the very end* of Agda type-checking if `A.agda` is not the "root" of type-checking. So Agda accumulates those warnings along the way and prints them at the very end, with a clear message indicating that they come from other modules and are collected from the trace. Currently, if `B.agda` is again imported in another `C.agda` and so on, you can see the same warnings many times.

(EDIT: clarify the UI in my head.)

**Comment by fredrikNordvallForsberg** [comment]
Yes, that seems very sensible. Let's see what we can do. Maybe it would be clearer to consistently report warnings in the trace, even if they arise from the root module, and then collect them all in the end?

For `A.agda` containing `{-# BUILTIN ZERO O #-}` and `B.agda` importing A, and having unreachable clauses, I propose the following output:
```
Checking B (/tmp/B.agda).
 Checking A (/tmp/A.agda).
/tmp/A.agda:6,1-23
Builtin ZERO does no longer exist. It is now bound by BUILTIN
NATURAL
when checking the pragma BUILTIN ZERO O
 Finished A.
/tmp/B.agda:5,1-8
Unreachable clause
when checking the definition of f
Finished B.

———— Warnings encountered ————————————————————————————————————
/tmp/A.agda:6,1-23
Builtin ZERO does no longer exist. It is now bound by BUILTIN
NATURAL
when checking the pragma BUILTIN ZERO O

/tmp/B.agda:5,1-8
Unreachable clause
when checking the definition of f

```

**Comment by favonia** [comment]
I am fine with this, and would like to leave the detailed UI design to others.

**Comment by favonia** [comment]
@fredrikNordvallForsberg @gallais I would like to reopen this thread because it seems when there is an error, the error will be printed directly (without empty lines in between) _after_ the list of warnings. I think either the error should go before the list, or it should have its own separator, or something reasonable.

**Comment by gallais** [comment]
Do you have a minimal working example?

It has to be noted that "errors" which are not fatal (termination or positivity errors, unsolved constraints, etc.) are just warnings under the hood and IIRC we print the lot in one go. So in your situation it may appear after the warnings because it was generated after them, not because of a deliberate attempt to give benign warning first and non fatal errors second.

**Comment by favonia** [comment]
@gallais Change the `B.agda` in my original post to
```agda
open import A

x : Set
x = Set 
```
and you will see this:
```
Checking B (/tmp/B.agda).
 Loading  A (/tmp/A.agdai).

———— Warnings encountered ——————————————————————————————————

/tmp/A.agda:6,1-23
Builtin ZERO does no longer exist. It is now bound by BUILTIN
NATURAL
/tmp/B.agda:4,5-8
Set₁ != Set
when checking that the expression Set has type Set
```
Maybe we have to deliberately delay the printing of the list, then?

**Comment by gallais** [comment]
We already have [a function](https://github.com/agda/agda/blob/master/src/full/Agda/TypeChecking/Monad/Base.hs#L2443) to partition the warnings between "benign warnings" and "non-fatal errors" so it's just a matter of calling it and displaying the two in separate lists.

So far we were printing them in the order they were raised in but I think you may be right that it would be more convenient to change the UI and print errors in their own list.

**Comment by favonia** [comment]
@gallais Not sure if I understand your solution. AFAIK the errors and the warnings in the MWE do not come from the new functions implemented by @fredrikNordvallForsberg. If they were, there would be a blank line in between. I think the real issue is that we print the warning list too early. That said, I like the idea of splitting the list.

**Comment by fredrikNordvallForsberg** [comment]
@gallais the non-fatal errors and splitting the list is a red herring: we already error out if we encounter a non-fatal error, so the list we display at the end will always consist of benign warnings only. I tried to make this a little bit clearer by changing the title to "All done; warnings encountered" in the pushed patch.

@favonia thanks for reporting! The problem was that we printed the list in the finalizer even if an error was thrown. I've moved the printing to just before returning in the main computation, which I think solves the problem. Please re-open if there are further issues.
