### ISSUE TITLE
"λ where" with single absurd clause not parsed

### ISSUE THREAD

**Issue by nad** [agda/agda#2586]
The following code does not parse:
```
data ⊥ : Set where

⊥-elim : {A : Set} → ⊥ → A
⊥-elim = λ where
  ()
```

**Comment by andreasabel** [comment]
There is evidence in the code that someone originally tried to get this to work (for extended lambdas), but gave up due to conflicts.
```haskell

-- Parses all extended lambda clauses except for a single absurd clause, which is taken care of
-- in AbsurdLambda
LamClauses :: { [(LHS,RHS,WhereClause,Bool)] }
LamClauses
   : LamClauses semi LamClause { $3 : $1 }
   | AbsurdLamClause semi LamClause { [$3, $1] }
   | NonAbsurdLamClause { [$1] }
--   | {- empty -} { [] }
```
Note that the last (conflicting) clause is commented out.

I think we could just document this special case.  The workaround `\()` is actually shorter than the `\ where ()`.

**Comment by nad** [comment]
> I think we could just document this special case.  The workaround `\()` is actually shorter than the `\ where ()`.

Just an aside: Your workaround does not work for more complicated absurd patterns.

**Comment by nad** [comment]
@UlfNorell, I suspect (but have not verified) that your commit broke the following code, which Agda 2.5.2 parses:
```agda
data ⊥ : Set where

data D : Set where
  c₁ : ⊥ → D
  c₂ : D

Parses : D → Set₁
Parses = λ where
  c₂      → Set
  (c₁ ())

Does-not-parse : D → Set₁
Does-not-parse = λ where
  (c₁ ())
  c₂      → Set
```
