### ISSUE TITLE
Preserve the ellipsis (dots) when case splitting "with" arguments

### ISSUE THREAD

**Issue by xekoukou** [agda/agda#2589]
It seems to me that it would make the code cleaner and more readable if case splitting of a "with" argument maintained the 3 dots "... | r".

What do you think?

**Comment by jespercockx** [comment]
This should now actually be possible since we have parameter refinement (previously it wasn't because of the mandatory dot patterns). Maybe then we should also add a new command to expand the `...`?

**Comment by xekoukou** [comment]
Yes it would be nice to have this command, instead of having to copy paste the remaining arguments from above.

**Comment by andreasabel** [comment]
I guess we could add "Ellipsis" to the origin of patterns and use this information during printing.

**Comment by andreasabel** [comment]
This is actually an old feature request: #573.

**Comment by xekoukou** [comment]
Feel free to close this issue. I didn't know that it was called ellipsis. I thought you meant [ellipse](https://en.wikipedia.org/wiki/Ellipse)

Ellipsis (έλλειψη) means the shortage/absence of something which actually makes sense in this case.

**Comment by andreasabel** [comment]
"Ellipsis" is used to describe the omission of syntactically necessary but semantically redundant words in literature.  I know this word from high school when we analysed poems.
The Japanese language makes excessive use of ellipsis (from a German perspective).

**Comment by andreasabel** [comment]
I wonder how to implement this feature.  We could record in the pattern origin that they come from an ellipsis.  We could fold back the patterns to an ellipsis in the printer if none of the ellipsis patterns has been split. This requires us to record some more history, like "was originally coming from an ellipsis but now has to be regarded as written by the user".  Because otherwise we cannot check whether all ellipsis patterns are still untouched, in the case that the last pattern coming from an ellipsis was split (for not-last patterns we can check if a later pattern is labelled as coming from an ellipsis).

**Comment by andreasabel** [comment]
Expanding an ellipsis could be bound to `C-c C-c . RET`.

**Comment by jespercockx** [comment]
I will take a look at this before the release.

Edit: I took a look and changed my mind.

**Comment by jespercockx** [comment]
I finally managed to find the right angle to tackle this problem! Phew. I did some basic tests, but if someone would like to give it some more extended testing that would be very welcome.

**Comment by andreasabel** [comment]
Could be cause of #4704.
