### ISSUE TITLE
Valid partial cover rejected: "Cannot split on argument of non-datatype"

### ISSUE THREAD

**Issue by gallais** [agda/agda#2594]
During interactive development, it is sometimes nice to write partial covers. In the presence of a telescope `(b : Bool) (_ : dispatch b) → _`, it can lead to the following error:

```
Cannot split on argument of non-datatype dispatch b
when checking the definition of argh
```
Although adding a catchall case makes the error go away, it goes against the usability of the interactive mode (we don't get any warning listing the missing cases anymore). MWE:

```agda
open import Agda.Builtin.Bool

dispatch : Bool → Set
dispatch true  = Bool
dispatch false = Bool

argh : (b : Bool) → dispatch b → Bool
argh false false = {!!}
argh false true  = {!!}
-- argh _ _ = ? -- this catchall makes the error go away
```

**Comment by jespercockx** [comment]
The problem is that the coverage checker doesn't distinguish between errors and warnings: it simply tries all possible splits until one succeeds, or returns the last error/warning in case none of them do (this is the effect of the `altM1` on line 252 of Coverage.hs). We could instead collect all the errors/warnings and pick out a warning if there is any.

An alternative solution is to not throw an error when there are constructors missing from a case split and instead postpone the detection of missing clauses until after the case tree has been built. But this doesn't work currently because sometimes there are multiple possible case trees and only one of them leads to a successful coverage check (see for example the test case for #408).

**Comment by gallais** [comment]
Reading the code around line 252 of Coverage.hs, this is my current understanding of what is happening:

* Agda tries to case on `b` which is clearly pattern-matched on
* Failing to find a full cover, it guesses that arguments depending upon `b` are forcing its value
* Agda tries to split the second argument first and then fails because it's not a datatype

So the collection of warnings should start a bit earlier than the `altM1`, precisely when we are generating partial covers and rejecting them.

**Comment by andreasabel** [comment]
I have a fix.  If splitting fails, we retry it, this time not failing hard on a partial cover.  This fixes the issue for the test case above.
