### ISSUE TITLE
Option to switch off warnings

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2596]
I'd like a option I can put in my file to squelch the warnings, like
```agda
{-# OPTIONS --no-warnings #-}
```
Maybe this  would go a bit to far, but at least I want to squelch the deprecation warnings and other unimportant warnings.

![warnings](https://cloud.githubusercontent.com/assets/1155218/26752505/ffe80f80-4851-11e7-80d4-fe7ac9dad235.png)

Note that also somehow the warnings are separated by a single space on a line. That should go in favor of just an empty line.
@fredrikNordvallForsberg @gallais

**Comment by fredrikNordvallForsberg** [comment]
I've implemented the basic functionality, but the experience is suboptimal because of #2487; i.e. if A.agda contains `{-# OPTIONS -W ignore #-}` but imports B.agda which raises some warnings, then they will still be reported. However if Agda is called by `agda -W ignore A.agda` on the command-line, then the imported warnings will also be ignored as was probably intended.

Feel free to re-open then issue if you feel that this is still too annoying.

**Comment by nad** [comment]
I think there should be some documentation for the new option.

**Comment by fredrikNordvallForsberg** [comment]
You are absolutely right, don't know why I forgot about it to start with...

**Comment by nad** [comment]
The `--help` flag states that one can `set warning mode to MODE`, but does not list any modes.
