### ISSUE TITLE
Internal error in MetaVars.hs

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#2603]
Discovered by @rfindler.

I haven't done any bisection, but the `__IMPOSSIBLE__` in question was introduced by @andreasabel in e62fd730.

Shrunk test case:
```agda
open import Agda.Builtin.Equality

data List (A : Set) : Set where
  [] : List A

postulate
  Signal : Set

data Any (xs : List Signal) : Set where
  no : Any xs

any : ∀ xs → Any xs
any [] = no

record Env : Set where
  field sig : List Signal
open Env public

Can : (θ : Env) → Any (sig θ) → Set
Can θ no = Signal

postulate
  elephant : ∀ θ → Can θ (any (sig θ)) ≡ Signal

lemma2 : Set
lemma2 rewrite elephant _ = Signal
```

**Comment by andreasabel** [comment]
Well the story goes like this: The `rewrite` tactic tests whether the rewrite equation is a reflexive one and calls the conversion checker but `dontAssignMetas`!  The conversion checker eta-expands a meta which does not respect `dontAssignMetas` and reaches the crash site.

Since `dontAssignMetas` should be respected, the way to fix this is to disable eta-expansion of metas when `dontAssignMetas`.

**Comment by rfindler** [comment]
Thank you! And thanks so very much for agda. It is wonderful.
