### ISSUE TITLE
Internal error in auto.

### ISSUE THREAD

**Issue by xekoukou** [agda/agda#2620]
Pressing C-c C-a (auto) into the hole, results into an internal error:

https://github.com/xekoukou/sparrow/blob/872efb80a4cc6d30136b2075976989235e6b3de3/agda/LinFunContructw.agda#L26

```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/Auto/NarrowingSearch.hs:216
```
https://github.com/agda/agda/blob/master/src/full/Agda/Auto/NarrowingSearch.hs#L216

My agda version is this [one](https://github.com/agda/agda/tree/47bba7d4a4f3fd34b3ea45d8d823cf66a99b80fa) with cubical and cache enabled.

**Comment by gallais** [comment]
It goes back to at least to 2.5.2. I'm going to investigate some more.

**Comment by gallais** [comment]
The first commit reveals that the error arises from [CaseSplit.hs at line 479](https://github.com/agda/agda/blob/4c4e89ff2f5b3e414337b773be0e5644f40a5216/src/full/Agda/Auto/CaseSplit.hs#L479).

I think the issue shows up because there is an unsolved metavariable in the type (specifically in `t ←∧`) of the thing the pattern `hitsAtLeastOnce←∧←∧ x` splits upon. I'd be nice to have a minimal, reproducible example.

The latest commit prevents the issue from blowing up in your face. I think but I'm not sure it's the right thing to do.

**Comment by xekoukou** [comment]
If you explicitly set the type of (t ←∧) , then the error goes away.

**Comment by gallais** [comment]
Shrunk test case:

```agda
open import Agda.Builtin.Nat

data B {A : Set} : A → Set where
  b : (a : A) → B a

data C {A : Set} : ∀ {a} → B {A} a → Set where
  c : {a : A} → C (b a)

id : ∀ {b} → C b → B 0
id c = {!!}
```

I'll push it together with the fix for Haddock which I have seem to have broken (no idea how though!).
