### ISSUE TITLE
Required instance of FromNat when compiling imported files

### ISSUE THREAD

**Issue by wenkokke** [agda/agda#2641]
When using `FromNat`, Agda requires an instance of `FromNat` to be in scope when compiling imported files which don't use `FromNat`. When compiling the imported files, they compile as expected (since they don't use `FromNat`).

I am using Agda version 2.6.0-dc58db0.

# How to reproduce

Create a file called `File1.agda` with the following content. Make sure the file is *not* compiled.

```agda
module File1 where

open import Agda.Builtin.Nat

data Bar : Nat -> Set where
  bar : {n : Nat} -> Bar n

foo : Bar (1 + 1)
foo = bar
```

Create a second file with the following content. Compile the second file.

```agda
open import Agda.Builtin.Nat
open import Agda.Builtin.FromNat using (Number)

data Unit : Set where tt : Unit

instance
  NumberNat : Number Nat
  NumberNat = record
    { Constraint = λ{x → Unit}
    ; fromNat    = λ{x → x}
    }

open import File1
```

# Expected result

Everything compiles.

# Actual result

You now get the following error:

```
No instance of type .Agda.Builtin.FromNat.Number Nat was found in scope.
when checking that 1 is a valid argument to a function of type
({a : .Agda.Primitive.Level} {A : Set a}
 {{r : .Agda.Builtin.FromNat.Number A}} (n : Nat)
 {{_ : .Agda.Builtin.FromNat.Number.Constraint r n}} → A)
```

**Comment by andreasabel** [comment]
One solution could be to put to put the `Number` class into `Agda.Builtin.Nat` and define an instance for `Nat` right there.  But I did not design the `FromNat` feature, so I do not really know how it is supposed to work.

**Comment by UlfNorell** [comment]
That wouldn't completely fix the problem unless you also make sure to reexport the instance when you repackage `Agda.Builtin.Nat`.

The issue is that built-in bindings are global, but instance resolution relies on instances being (more or less) in scope. The way literal overloading works at the moment is that it looks at the built-in binding for `fromNat` (and `fromString`) to see if overloading is enabled. A better way would be to do the same scope check on `fromNat` as we do for instances and only enable overloading when it's in scope.
