### ISSUE TITLE
eq proof rejected by Agda 2.6.0-c9e11c1

### ISSUE THREAD

**Issue by mechvel** [agda/agda#2696]
Please download the code from
ftp://ftp.botik.ru/pub/local/Mechveliani/agdaNotes/bugRep-aug16-2017.zip
(17 Kb).
See   Readme.txt   there.
It rejects a certain equality proof, whis was accepted by Agda 
 2.6.0-207bde6 (April 13, 2017).
I wonder: which Agda is more correct?
Is this a bug in Agda 2.6.0-c9e11c1 ?

**Comment by gallais** [comment]
After a few changes for compatibility with stdlib-0.13 (cf. [compat-2.5.2.patch.txt](https://github.com/agda/agda/files/1228049/compat-2.5.2.patch.txt)), it does indeed typecheck with 2.5.2.

**Comment by mechvel** [comment]
1) Which type checker is more correct at this example: 
2.5.2patched or Agda 6.0-c9e11c1 ?

2) I cannot use 2.5.2 for DoCon-A-2.00, due to certain bugs in 2.5.2.
I hope for the line of  2.6.0-207bde, 2.6.0-c9e11c1.

**Comment by fredrikNordvallForsberg** [comment]
The proof `cong-fromJustIf {mp-digs-e'} {mp-bs+1} (uReflexive mp-digs-e'=mp-bs+1) isJust-mp-digs-e'` proves
```
   fromJustIf mp-digs-e' {isJust-mp-digs-e'} ≈ fromJustIf mp-bs+1 {p}
```
where `p = cong-isJustC (uReflexive mp-digs-e'=mp-bs+1) isJust-mp-digs-e'`, while we need a proof of 
```
   fromJustIf mp-digs-e' {isJust-mp-digs-e'} ≈ fromJustIf mp-bs+1 {isJust-mp-bs+1}
```
So somehow Agda 2.5.2 concludes that `p = isJust-mp-bs+1` for the purposes of that equation. Since `p` is of the form `cong-isJust ...` and `isJust-mp-bs+1` is of the form `subst ...`, this cannot hold definitionally. My guess would be that Agda 2.5.2 considered `fromJustIf` to be irrelevant in the `isJust-m` argument (@andreasabel ?) and hence accept the proof, whereas current Agda (probably rightfully) does not.

Note that if you generalise `cong-fromJustIf` to
```
  cong-fromJustIf : {m : Maybe C} → {m' : Maybe C} → (m=m' : m =u m') →
                    (isJust-m : isJust m) →
                    (isJust-m' : isJust m') →
                    (fromJustIf m {isJust-m}) ≈ (fromJustIf m' {isJust-m'})
  cong-fromJustIf {nothing} {_}       _                () _
  cong-fromJustIf {just _}  {just _}  (Mb.Eq.just x=y) _  _  = x=y
  cong-fromJustIf {just _}  {nothing} _                _  ()
```
then
```
eq0 = cong-fromJustIf {mp-digs-e'} {mp-bs+1} (uReflexive mp-digs-e'=mp-bs+1) isJust-mp-digs-e' _
```
works.

**Comment by mechvel** [comment]
DoCon-A-0.04.1 is of January 2016, and it works under 2.5.2. 
I do not recall what was the first reason for leaving  2.5.2.
Anyway  DoCon-A-2.00 uses Agda Prelude in such a way that it would not be type-checked in
2.5.2. 
This misfeature for relation to Agda Prelude is fixed in  2.6.0-c9e11c1 (as Ulf and you  wrote recently).
(And the reduced example reported here does not use Agda Prelude).

So that I think, that, probably, I need to deal with the line of 2.6.0-c9e11c1.
(?)

**Comment by andreasabel** [comment]
@fredrikNordvallForsberg : Indeed, with the fix of #2480 Agda will consider less arguments to be irrelevant (and be more sound).

**Comment by mechvel** [comment]
It looks like my library has several places that rely on the above irrelevance incorrectly, and so that Agda of April 13 allows this. 
I need to somehow rewise  the program.
Thanks to you, people, for fast response and explanation !

**Comment by andreasabel** [comment]
I guess we can close this then.
