### ISSUE TITLE
Interactive 'give' doesn't insert enough parenthesis

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#2718]
In the following program, you can 'give' the contents of the hole, but after reloading the solution is rejected.
```
postulate
  T : Set
  pre : (T → T) → T
  _post : T → Set

tester : Set
tester = {!pre λ x → x!} post
```
This is in some way the dual problem to #737.

**Comment by nad** [comment]
I seem to recall that Agda keeps track of fixities and uses that information in some way to figure out whether parantheses should be inserted. The following variant of your example is handled correctly:
```agda
postulate
  T     : Set
  pre_  : (T → T) → T
  _post : T → Set

infix 1 pre_
infix 2 _post

tester : Set
tester = {!pre λ x → x!} post
```
I guess that the parenthesis-insertion machinery has not been programmed with lambdas in mind.

**Comment by UlfNorell** [comment]
The problem here is that we decide whether to insert parenthesis based on what the pretty printer (`AbstractToConcrete`) does, but we're not actually using the output from the pretty printer since we want to preserve the user input.

In this case the pretty printer wants to print the term as `pre (λ x → x)` and thus (correctly) determines that no parentheses are needed. A possible solution might be to keep track of parenless lambdas in abstract syntax.

**Comment by UlfNorell** [comment]
> A possible solution might be to keep track of parenless lambdas in abstract syntax.

Fixed by doing exactly that.
