### ISSUE TITLE
`Give` command doesn't seem to be working

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda#2741]
Just updated to f5e0f4137cf391d4930209ff9c031b1b5bce39a0 and the interactive `give` command no longer seems to be working for me.

```agda
open import Data.Nat

module Test where

  test : ℕ
  test = {!zero!}
```
Pressing C-space in the hole results in: 

> error in process filter: Problem encountered. The \*agda2* buffer can perhaps explain why. 

Looking at the \*agda2* buffer I see

> IOTCM "/auto/homes/mld46/Test.agda" Interactive Indirect ( Cmd_give 0 (intervalsToRange (Just (mkAbsolute "/auto/homes/mld46/Test.agda")) [Interval (Pn () 562 27 12) (Pn () 566 27 16)]) "zero" )
Agda2> cannot read: IOTCM "/auto/homes/mld46/Test.agda" Interactive Indirect ( Cmd_give 0 (intervalsToRange (Just (mkAbsolute "/auto/homes/mld46/Test.agda")) [Interval (Pn () 562 27 12) (Pn () 566 27 16)]) "zero" )

Other commands including `Auto` seem to be working fine.

**Comment by UlfNorell** [comment]
It looks like you are still running an old version of the Emacs mode. Since 021e6d2 `Cmd_give` takes an additional argument `WithoutForce | WithForce`. Here's what the command looks like for me:

`IOTCM "..." NonInteractive Indirect ( Cmd_give WithoutForce 0 (intervalsToRange (Just (mkAbsolute "...")) [Interval (Pn () 62 7 12) (Pn () 66 7 16)]) "..." )`

**Comment by MatthewDaggitt** [comment]
Ah thanks! Apologies, not sure why I've been failing to update `agda-mode` along with `agda` itself.
