### ISSUE TITLE
Agda-2.5.3 has a Haddock build failure (on Stackage build)

### ISSUE THREAD

**Issue by decentral1se** [agda/agda#2748]
```
haddock: internal error: dist/doc/html/Agda/../Agda-2.5.3/Agda-Version.html: 
openFile: does not exist (No such file or directory)
```

**Comment by asr** [comment]
I couldn't reproduce the issue using `cabal-install`:

```
$ cabal get Agda
$ cd Agda-2.5.3
$ cabal haddock
...
Preprocessing executable 'agda' for Agda-2.5.3..
```

How do you get the issue using `stack`?

**Comment by decentral1se** [comment]
I saw this failure as part of the stackage-curator driven LTS build. I was in a rush and wasn't able to grab any more logs. I'm not really sure how you might debug this. If you really cannot reproduce this, then re-enable haddocks (revert https://github.com/fpco/stackage/commit/8fff76ac405078f0a4b63d7d56e65fb988c507ce) and perhaps it works (it may also have been some build server issue) or at least, you get more logs :)

**Comment by asr** [comment]
@Blaisorblade, can you reproduce the problem?

**Comment by asr** [comment]
I neither could reproduce the issue using `stack`:

```
$ stack-8.0.2.yaml
resolver: lts-9.4

# Local packages, usually specified by relative directory name
packages:
- '.'
```

```
$ cabal get Agda
$ cd Agda-2.5.3
$ export ARGS="--stack-yaml stack-8.0.2.yaml --system-ghc"
$ stack $ARGS haddock
...
Updating Haddock index for snapshot packages in
/<PATH>/.stack/snapshots/x86_64-linux/lts-9.4/8.0.2/doc/index.html
```

@lwm, from which version of GHC did you get the error?

**Comment by decentral1se** [comment]
It was GHC-8.0.2 alright.

**Comment by Blaisorblade** [comment]
Trying this out with Stack.

But we just learned from Michael Snoyman that Stackage does not use Stack (ahem).

And `Agda.Version` includes file `Paths_Agda`, which is generated (IIUC) while configuring Agda.

So hypothesis: if haddock is called before configuring the build, trouble should be expected, maybe even the above error. Not sure how to invoke `haddock` to verify that—does somebody know the right invocation? My attempt gets handled reasonably with recent haddock, maybe the server uses a different version though?

@lwm are the Stackage logs in question public? Where's the build script? Is there a chance to reproduce it locally?

With haddock 2.18.1:
```
$ haddock --version
Haddock version 2.18.1, (c) Simon Marlow 2006
Ported to use the GHC API by David Waern 2006-2008

$ haddock src/full/Agda/Version.hs
Haddock coverage:

src/full/Agda/Version.hs:6:1: error:
    Could not find module ‘Paths_Agda’
    Use -v to see a list of the files searched for.
  |
6 | import qualified Paths_Agda as PA
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

(EDITED) With haddock 2.17.3:
```
$ stack exec -- haddock --version
Haddock version 2.17.3, (c) Simon Marlow 2006
Ported to use the GHC API by David Waern 2006-2008

$ stack exec haddock src/full/Agda/Version.hs
Haddock coverage:

src/full/Agda/Version.hs:6:1: error:
    Failed to load interface for ‘Paths_Agda’
    Use -v to see a list of the files searched for.
````

**Comment by Blaisorblade** [comment]
So, `stack haddock` completed successfully.

I suspect the problem is with stackage and would likely be solved by having stackage using stack (as mentioned — Snoyman explains [here](https://github.com/fpco/stackage/issues/2852#issuecomment-328583840) this isn't the case yet). I'd suggest @asr close this on our side, but I'll leave him the choice.

Somehow, https://www.stackage.org/haddock/lts-9.4/Agda-2.5.3/Agda-Version.html and https://www.stackage.org/lts-9.4/package/Agda-2.5.3 look fine.

@lwm I can't commit on stackage and I'm not familiar with its internals. Could you try reverting https://github.com/fpco/stackage/commit/8fff76ac405078f0a4b63d7d56e65fb988c507ce as you suggested and saving any logs?

Even if that breaks and we end up with no haddocks on Stackage, that might be acceptable: Agda is not a library after all. Worst-case, people who hack on Agda would have to look at docs on hackage or build their own.

**Comment by decentral1se** [comment]
@Blaisorblade - reverted 👍
