### ISSUE TITLE
Unsolved constraint, related to instance arguments and sized types

### ISSUE THREAD

**Issue by nad** [agda/agda#2753]
The following code is not accepted:
```agda
open import Agda.Builtin.Size

mutual

  data D (i : Size) : Set where
    c : D′ i → D i

  data D′ (i : Size) : Set where
    [_] : ({j} : Size< i) → D j → D′ i

record R (A B : Set) : Set where
  field
    f : A → B

open R ⦃ … ⦄ public

mutual

  instance

    r : ∀ {i} → R (D i) (D i)
    R.f r (c y) = c (f y)

    r′ : ∀ {i} → R (D′ i) (D′ i)
    R.f r′ [ e ] = [ f e ]
```
Error message:
```
Failed to solve the following constraints:
  [47] _r_24 e = r : R (D .j) (D .j)
```
I suspect that this is a bug.

**Comment by UlfNorell** [comment]
The problem is that the meta occurs check refuses `_r_24 := r`, since it forms a recursive solution. Somewhat related to #2710 and #589.

Perhaps the recursion check should be disabled for instance metas?

**Comment by nad** [comment]
If I remove the sized types, then the code is accepted:
```agda
mutual

  data D : Set where
    c : D′ → D

  data D′ : Set where
    [_] : D → D′

record R (A B : Set) : Set where
  field
    f : A → B

open R ⦃ … ⦄ public

mutual

  instance

    r : R D D
    R.f r (c y) = c (f y)

    r′ : R D′ D′
    R.f r′ [ e ] = [ f e ]
```

**Comment by andreasabel** [comment]
If one replaces sized types by their dead shell and resolves the hidden size variable `j`,
```agda
postulate
  Size : Set

Size<_ : Size → Set
Size< i = Size

mutual

  data D (i : Size) : Set where
    c : D′ i → D i

  data D′ (i : Size) : Set where
    box : (j : Size< i) → D j → D′ i

record Fun (A B : Set) : Set where
  field
    applyTo : A → B

open Fun ⦃ … ⦄ public

mutual

  instance

    r : ∀ {i} → Fun (D i) (D i)
    Fun.applyTo r (c y) = c (applyTo y)

    r′ : ∀ {i} → Fun (D′ i) (D′ i)
    Fun.applyTo r′ (box j e) = box j (applyTo e)

```
then the code is accepted.

With actual sized types, the constraint you describe is left over in the last expression `applyTo e`.

**Comment by andreasabel** [comment]
@UlfNorell is correct: the `metaOccurs` check prevents the solution.  However, why does it work without the sized types then?  The meta-occurs check does not go into solutions of metas.  Thus, in the case without sized types, where instance search succeeds immediately (solving the hidden argument `i` by the conversion check), we are lucky enough to slip through the meta-occurs check.  However, in the case with sized types, instance search does not succeed immediately because the constraint on size `i` does not give a solution for `i` directly.  After size solving, instance search is retried, but then (when we solve the second instance variable), `instantiateFull` already has put in the solution for the first instance variable.  Thus, the loop becomes apparent, and `metaOccurs` protests.

Probably turning off the meta-occurs check for instance variables is the right thing to do, since termination of instance search is in the responsibility of the user anyway.

**Comment by UlfNorell** [comment]
> ... termination of instance search is in the responsibility of the user anyway.

Instance search always terminates (or did until the fix?), since it has a limited search depth.

**Comment by andreasabel** [comment]
But what if instance resolution introduces a non-terminating function, which is subsequently evaluated in further instance search?  (Do this in a mutual block, before the termination checker kicks in.)

**Comment by UlfNorell** [comment]
Isn't that what the occurs check is supposed to prevent?

**Comment by andreasabel** [comment]
Well, but it does not go into meta solutions, thus, is sensitive whether `instantiateFull` has been called or not.  Maybe it should go into meta solutions...
