### ISSUE TITLE
Relevant meta is instantiated with irrelevant solution

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#2758]
```agda
{-# OPTIONS --experimental-irrelevance #-}

open import Agda.Builtin.Bool

data Box (A : Set) : ..(x : A) → Set where
  c : (x : A) → Box A x

unbox : {A : Set} → .(x : A) → Box A x → A
unbox a (c b) = b

.b : Bool
b = true

b' : Bool
b' = unbox b (c _)
```

In the above code, the meta is filled in with solution `b`, but manually filling in this solution results in an error.

We need to double-check the solutions of metas that they don't use irrelevant top-level definitions in a relevant position. We could integrate this check with the occurs check, so we don't have to traverse the solution twice.

**Comment by jespercockx** [comment]
See also #875

**Comment by Saizan** [comment]
I agree that the occurs check should be made to verify that the solution for a meta is respecting the relevance rules.

However, I would think that in this case we should have that the following typechecks:
```
b' : Bool
b' = unbox b (c b)
```

because the following should typecheck and it would be nice if "." didn't break referential transparency, (though I see how DontCare is supposed to be a sort of sealing operation):

```
b' : Bool
b' = unbox true (c true)
```

Since we are not erasing irrelevant stuff anyway at typechecking, we could consider definitions like ".b" as just living in a different context, e.g.

```
module M Gamma where
  .foo : T
```

would be the same as 

```
module M (Irrelevant `inverseCompose` Gamma) where
  foo : T
```

and then when using foo the typing rules only have to verify that the parameters are available at the appropriate modality. That's the principle I used when I fixed #2450 in the parametric branch.


(We would also need to discuss envRelevance then, also make sure things like #610 don't surface back up)

**Comment by jespercockx** [comment]
But isn't declaring a top-level definition as irrelevant **supposed** to break referential transparency? If I mark a definition as irrelevant, then I'd expect the actual definition of the thing to be, y'know, *not relevant*. So I think there's a pretty strong case that we shouldn't accept the definition of b'.

**Comment by Saizan** [comment]
I can see the reasoning behind that expectation. 

But referential transparency makes sense if you think of ¨.b : Bool" as instead saying "I will only use b in an irrelevant context", so that what it does is making more things available from the context.

However now I'm wondering how much this makes sense with irrelevant projections.

**Comment by jespercockx** [comment]
But in the definition `b' = unbox b (c b)`, aren't you using `b` in a relevant context (as an argument to `c`)?

**Comment by Saizan** [comment]
Hah, that's true.

But the special thing about "b" is that it's defined in a closed context, so actually there's no information flow to track. it's more of a relativized notion. I'm wondering if it scales to more in-the-wild uses of irrelevance.
