### ISSUE TITLE
Using pragmas related to rewriting without --rewriting

### ISSUE THREAD

**Issue by nad** [agda/agda#2778]
Neither of the following two pieces of code are accepted:
```agda
{-# OPTIONS --safe --rewriting #-}

open import Agda.Builtin.Equality public

{-# BUILTIN REWRITE _≡_ #-}
```
```agda
{-# OPTIONS --safe #-}

open import Agda.Builtin.Equality public

{-# BUILTIN REWRITE _≡_ #-}
```
I suggest that the second piece of code should be accepted. I'd like to mark a definition for later use with the rewriting facility, without making that piece of code unsafe.

In fact, I suppose all pragmas related to rewriting should be safe, as long as `--rewriting` is not active.

**Comment by andreasabel** [comment]
I somewhat agree, but if option `--rewriting` just switches on the use of rewrite rules, it could be very confusing to be able to declare rewrite rules and see no effect because of forgotten option `--rewriting`.  

It seems more natural that `--rewriting` is automatically on if you import a file that declares rewrite rules.  We could have an option `--no-rewriting` to switch rewriting off in this case.

**Comment by nad** [comment]
Rewriting is very experimental, so I want to keep careful track of where it is used. Hence I don't think `--rewriting` should be switched on automatically.

**Comment by nad** [comment]
Given the recent work on option consistency checking (#2487) I suggest that we close this issue.
