### ISSUE TITLE
Using \texttt{-} destroys code coloring in literate file

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#2794]
Minimal example: a file `test.lagda` with the following contents:
```latex
\texttt{-}

\begin{code}
postulate A : Set
\end{code}
```
The postulate doesn't get any code coloring, but it does when I remove the `texttt{-}`.

**Comment by nad** [comment]
A workaround is to insert `{}` before `-`.

Perhaps we should stop using the font-lock mechanism for highlighting comments. I see that @monnier switched to using font-lock back in 2009 (6c70946d363e54cb43ae770eedf5467f223d32d9). @monnier, do you have any opinion on this?

**Comment by monnier** [comment]
As an Emacs user, I expect highlighting to be updated on-the-fly immediately (that's how it works in every other major mode).  That's why I changed agda-mode to use font-lock for comments (I'd use it for even more things if it were me).  Obviously, this requires duplicating part of the syntactic rules into the Elisp code, and in this present case, I think the problem is that this part of the Elisp code wasn't taught about literate Agda.

**Comment by nad** [comment]
> Obviously, this requires duplicating part of the syntactic rules into the Elisp code, and in this present case, I think the problem is that this part of the Elisp code wasn't taught about literate Agda.

This is not the first bug of this kind. Here are some others: #601, #873, #1104, #1144. I don't think it is feasible for us to implement and maintain two Agda lexers, and I've [previously suggested](https://github.com/agda/agda/issues/1144#issuecomment-129029032) that we should let Emacs use the Haskell lexer.

**Comment by monnier** [comment]
There is no doubt that "duplicating" here implies extra work, bugs and inconsistencies.  Whether that's more important than the immediate feedback you get from on-the-fly highlighting is a question of personal judgment.

**Comment by gallais** [comment]
Cf. #2268 for a quick fix: turn the regular expression `{-[^#]` into `{-[^#}]` [here](https://github.com/agda/agda/blob/master/src/data/emacs-mode/agda2-mode.el#L1017). Or maybe we want to to have `{-[[:space:]\n]` instead?

**Comment by monnier** [comment]
I believe `{-} blabla {-}` is a valid Agda comment, which your quick fix would break.  If you decide to fix the font-lock rule rather than to get rid of it, I can try to provide a real fix (which will involve using `syntax-propertize-function`).

**Comment by andreasabel** [comment]
I think it is rather useful that commenting out Agda code immediately shows in the syntax highlighting (without reload).

**Comment by nad** [comment]
One option would perhaps be to invoke the Haskell lexer every time the buffer is modified.

**Comment by gallais** [comment]
Ok, here's a new suggestion (unless the target is the very beginning of the
file in which case we use the old behaviour): jump to the character *before*
the one the comment may start at and check that it is either a space or a
newline like so:

```emacs
(defun agda2-font-syntactic-face (state)
  (cond ((nth 4 state)
         ( save-excursion
	   (let* ((char (max 0 (1- (nth 8 state))))
	          (sglc (if (= 0 char) "--[[:space:]\n]" "[[:space:]\n]--[[:space:]\n]"))
		  (mltc (if (= 0 char) "{-[^#]" "[[:space:]\n]{-[^#]"))
		 )
	         (progn
	          (goto-char char)
                  (cond ((looking-at sglc) 'font-lock-comment-face)
                        ((looking-at mltc) 'font-lock-comment-face)
          )))))))
```

This means that things like:

```agda
horrendous : Set{- comment -}
horrendous = ?
```

won't get highlighted but then again the *same* comment with a single-line marker
instead of a multiline one would lead to a parse error.

**Comment by nad** [comment]
Instead of another hack I suggest that we do something principled. I repeat my previous comment: "One option would perhaps be to invoke the Haskell lexer every time the buffer is modified." (This is assuming that the Haskell lexer is sufficiently fast.) We could for instance let Emacs ask for highlighting information from the backend every time the buffer is saved manually by the user.

**Comment by gallais** [comment]
If no one is planning to fix this in a principled manner any time soon (this report is
already 3+ months old), I'd argue that a partial solution is better than no solution.
Then again I don't have to suffer this \texttt{-} issue so if you'd rather leave it like
this, it won't bug me.

**Comment by nad** [comment]
A very simple solution would be to only use the backend for highlighting, and only when other highlighting takes place. My suggestion was to do backend-based lexical highlighting more often, but perhaps that can wait (possibly indefinitely).

**Comment by nad** [comment]
> A very simple solution would be to only use the backend for highlighting, and only when other highlighting takes place.

I'll try this locally.

**Comment by nad** [comment]
I've implemented the very simple solution. I do think it is somewhat annoying that, say, a commented-out line of code is not immediately highlighted as a comment.

**Comment by andreasabel** [comment]
Everyone, we need to make a decision on this change (whether it is what we want) before the release.  The problem now is that commenting out code does not highlight it as comment until the next reload.  Maybe this change effects more common working situations for the worse than the original bug did.

**Comment by nad** [comment]
I have implemented (but not pushed) the following preliminary enhancement:
* I added a command which allows a frontend to ask the backend to compute highlighting information based on the token stream for a file, and send it to the frontend along with a command that asks the frontend to remove the current token-based highlighting.
* I wired the Emacs mode so that this command is sent whenever `comment-region` or `uncomment-region` is used. (These commands now save the file.)

I tried to run this command after every use of `self-insert-command`, but I can type two characters faster than this command completes (for a buffer with a couple of hundred lines), and then I get "Another command is currently in progress" warnings. I suppose it would be possible to suppress such warnings for this command, but perhaps it would be better to run it when the buffer has been inactive for a certain period of time (less than a second) and no other command is in progress. I would also prefer if the buffer wasn't saved all the time. This could perhaps be handled by writing the buffer to a temporary file.

Another option would be to do scope-based highlighting. However, for long files with lots of mixfix operators parsing can take considerably longer than lexing, and if an import statement is changed, then Agda may start type-checking dependencies.

Any comments on the design?

**Comment by jespercockx** [comment]
Seems like a good solution to me in order to avoid re-implementing the lexer (and possibly more) in elisp. I'd be a bit wary of running the lexer after every keypress, since any delay in typing is *really* annoying. By default, I would only run the lexer when saving the file, with an optional setting of running it automatically after not typing anything for x (milli)seconds.

**Comment by nad** [comment]
I've pushed an implementation. Highlighting is updated automatically (given certain conditions) 0.2 s after the last change to the file, and when the file is saved.

If you think this works sufficiently well, then we can close this ticket.

**Comment by nad** [comment]
I'm closing this now. Feel free to give further feedback.
