### ISSUE TITLE
`where` should remain a declaration keyword

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2816]
Using `where` both as a declaration and expression keyword leads to the following funny parse error:
```agda
data D λ:Level : Set λ where
  c : D λ
```
The error location is the `:` after the `c`.  Beginner's trap.

Keeping declaration keywords separate from expression keywords allows better parse error reporting.

**Comment by UlfNorell** [comment]
Did you actually have a beginner getting confused over this? In Agda 2.5.1 you get the parse error on the `where` instead, which I'm not sure is that much more helpful.

In any case I don't think it's worth adding another keyword just to get better parse errors in weird corner cases like this.

Also, since `where` hasn't been a "declaration keyword" for the last two releases I think the title is a bit misleading.

**Comment by andreasabel** [comment]
No, this is a constructed example.  I was thinking about separating declaration parsing from expression parsing.  If this were possible, parse errors would be more local.
