### ISSUE TITLE
Compiling from command line: missing modules

### ISSUE THREAD

**Issue by ivanperez-keera** [agda/agda#2857]
Compiling [Hello.agda](https://github.com/pigworker/MetaprogAgda/blob/master/Hello.agda) with Agda version 2.5.3 gives the following errors:
```
Checking Hello (/home/dash/tmp/agda/Hello.agda).
Finished Hello.
Compiling Hello in /home/dash/tmp/agda/Hello.agdai to /home/dash/tmp/agda/MAlonzo/Code/Hello.hs
Calling: ghc -O -Werror -i/home/dash/tmp/agda /home/dash/tmp/agda/MAlonzo/Code/Hello.hs --make -fwarn-incomplete-patterns -fno-warn-overlapping-patterns
Compilation error:

MAlonzo/RTE.hs:5:8:
    Could not find module ‘Numeric.IEEE’
    Use -v to see a list of the files searched for.

/home/dash/tmp/agda/MAlonzo/Code/Hello.hs:9:18:
    Could not find module ‘Data.Text’
    Perhaps you meant
      Data.Set (from containers-0.5.6.2@conta_2C3ZI8RgPO2LBMidXKTvIU)
    Use -v to see a list of the files searched for.
```

**Comment by ivanperez-keera** [comment]
Just a problem with sandboxes. Can be solved with cabal flags. Closing.

**Comment by andreasabel** [comment]
Ah, ok.  What is the solution?  (To inform the posterity.)

**Comment by ajrouvoet** [comment]
I have the same issue (Agda 2.6.0); also curious how you solved it.

**Comment by ivanperez-keera** [comment]
I don't remember exactly what I did, but I think all I needed was `cabal exec -- agda <args>`.

Does that work for you?

**Comment by Zalastax** [comment]
For me, this happened when setting up Agda on a completely fresh machine.
For some reason, running `stack exec agda` does not install the two modules that Agda needs to run correctly, causing a crash.
Solving this problem is easy, just tell stack to install these packages: `stack exec --package ieee754 --package text agda`.  Executions after this can be made using just `stack exec agda`.
I would assume these instructions transfer to cabal sandboxes as well.

**Comment by greatBigDot** [comment]
I still have this problem; `--package ieee754` doesn't help:

    Loading  Base (/home/me/Agda/minimal/src/Base.agdai).
    Agda.Primitive : no compilation is needed.
    Base : no compilation is needed.
    Calling: ghc -O -Werror -idist dist/MAlonzo/Code/Base.hs --make -fwarn-incomplete-patterns -fno-warn-overlapping-patterns
    [1 of 3] Compiling MAlonzo.RTE      ( dist/MAlonzo/RTE.hs, dist/MAlonzo/RTE.o )
    Compilation error:
    
    dist/MAlonzo/RTE.hs:11:1: error:
        Could not find module ‘Numeric.IEEE’
        Use -v to see a list of the files searched for.
       |
    11 | import Numeric.IEEE ( IEEE(identicalIEEE) )
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Note that I don't have the problem with the `text` package that others seem to. I dunno why.

I've tried two different ways to install agda with stack, and they've both yielded the above message whenever I try to compile anything (no problems occur when I just typecheck). `stack build`-ing Agda builds agda into the global stack package database; that doesn't work. `git clone`-ing the source, switching to the most recent release (v2.5.4.2), and `stack build`-ing locally also doesn't work. Neither method changes output when I include `--package ieee754` to `stack exec`. And again, everything works fine if you just typecheck (that is, if you don't use `agda -c`).

I do have a truly awful, terrible workaround if you clone the source. After liberally sprinkling a few `--verbose`'s and whatnot, I tracked the issue as far as the module `Agda.Compiler.MAlonzo.Compiler` in the source code. (I'm a terrible programmer and have been unable to trace it back further, if the bug's origin does indeed extend further.) At the very bottom, in the definition of `callGHC`, a local variable `args :: [String]` is set that contains the options fed to GHC. So I just replaced:

    args     = overridableArgs ++ ghcopts ++ otherArgs

with:

    args     = overridableArgs ++ ghcopts ++ otherArgs ++ ["-i" ++ "/usr/local/share/agda-fix/ieee754"]

I set things up so that `/usr/local/share/agda-fix/ieee754` is a symlink to `/usr/local/share/agda-fix/ieee754-0.8.0`, which is a directory containing the full source code of the [ieee754](https://www.stackage.org/lts-12.26/package/ieee754-0.8.0) package (version `0.8.0`, which is from `lts-12.26` and within the bounds for the package specified in `Agda.cabal`). This barely qualifies as a solution, but it works—I now have no trouble compiling programs.

Setup:
* `stack` 1.9.3 (I don't use `cabal` at all anymore)
* `lts-12.26`
    * `ghc-8.4.4`
    * `ieee754-0.8.0`
* Arch Linux 4.20.7
* Agda 2.5.4.2 (though I remember the same problem occurring with earlier versions)
    * EDIT: the behavior persists on the current `master` branch too; I just tried it on [`2.6.0-2a03519`](https://github.com/agda/agda/commit/2a0351914f5aa4b147484df09aecb524d8ad1180), which at the time of this writing is the most recent `master` commit that has passed all travis tests. It gives the same error message until the same terrible workaround is applied.

**Comment by greatBigDot** [comment]
Hold on, I just figured out what my problem was. I was using `--no-ghc-package-path` with `stack exec`. I was doing this because, in the past, `stack exec` would sometimes error out, with `cabal` telling me that `GHC_PACKAGE_PATH` is decprecated or something. Some googling (see [here](https://github.com/hdevtools/hdevtools/issues/6) and [here](https://github.com/haskell/cabal/issues/1944)) revealed that the solution is to feed `--no-ghc-package-path` to `stack exec`. So I set up a shell function that shadows `stack`, looks for whether the first non-option argument is `exec`, and if so, squeeze in `--no-ghc-package-path` right after it and before the rest of the arguments before calling the *real* `stack`.

And with that bug out of the way, I promptly forgot about it, until now. Long story short, not using `--no-ghc-package-path` completely alleviates all problems for me. ~~It looks like I don't even have to use `--package ieee754` or anything.~~ EDIT: Actually, upon further investigation, `--package ieee754` is necessary to use the first time. I think you could instead just download the package manually beforehand (that is, run `stack build -- ieee754`). It seems to me that this shouldn't have to be done explicitly—shouldn't the dependency solver work it out?—but at least I've got it working!

I dunno what the deal is with `GHC_PACKAGE_PATH` and why it's incompatible with `cabal-install`, so I don't know whether or not there's more to be done here with respect to compatibility.

**Comment by asr** [comment]
Thank you for sharing your solution. Please reopen if necessary.

**Comment by berndlosert** [comment]
I installed agda 2.6.0.1 using homebrew on macOS Mojave and I also have this problem. I have neither cabal nor stack installed.

**Comment by L-TChen** [comment]
Sorry, what’s the problem? @berndlosert, can you post the error message if it is not identical to op’s?

**Comment by berndlosert** [comment]
It's the same:

```
$ agda --compile HelloWorld.agda      
Calling: ghc -O -o /private/tmp/HelloWorld -Werror -i/private/tmp -main-is MAlonzo.Code.HelloWorld /private/tmp/MAlonzo/Code/HelloWorld.hs --make -fwarn-incomplete-patterns -fno-warn-overlapping-patterns
[1 of 5] Compiling MAlonzo.RTE      ( MAlonzo/RTE.hs, MAlonzo/RTE.o )
Compilation error:

MAlonzo/RTE.hs:13:1: error:
    Could not find module ‘Numeric.IEEE’
    Use -v to see a list of the files searched for.
   |
13 | import Numeric.IEEE ( IEEE(identicalIEEE) )
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by L-TChen** [comment]
It appears that you don't have the required package `ieee754` installed in your system, since you don't have cabal or stack.

Run `brew install cabal-install` and `cabal install ieee754`. Then it should work afterwards.

**Comment by berndlosert** [comment]
Thanks @L-TChen. Here's what I actually did to get it to work:

```
brew install cabal-install
cabal update
cabal install --lib ieee754
```

**Comment by andreasabel** [comment]
See also #3619

**Comment by AaronNGray** [comment]
I have done :-
 `cabal install --lib ieee754`

and have 
```
module hello-world where

open import IO

main = run (putStrLn "Hello, World!")
```

but get :- 
```
C:\Users\aaron\Projects\Agda>agda --compile hello-world.agda
Calling: ghc -O -o C:\Users\aaron\Projects\Agda\hello-world -Werror -iC:\Users\aaron\Projects\Agda -main-is MAlonzo.Code.QhelloZ45Zworld C:\Users\aaron\Projects\Agda\MAlonzo\Code\QhelloZ45Zworld.hs --make -fwarn-incomplete-patterns -fno-warn-overlapping-patterns
[  1 of 123] Compiling MAlonzo.RTE      ( MAlonzo\RTE.hs, MAlonzo\RTE.o )
Compilation error:

MAlonzo\RTE.hs:9:1: error:
    Could not find module `Numeric.IEEE'
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
9 | import Numeric.IEEE ( IEEE(identicalIEEE, nan) )
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
