### ISSUE TITLE
make up-to-date-std-lib fails

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2863]
I currently cannot run the library-test suite, because:
```
make up-to-date-std-lib 
```
returns
```
git submodule update --init std-lib
fatal: reference is not a tree: aaa04c9a6b7ab787eb30ccc0cd5e1604470a6eb6
Unable to checkout 'aaa04c9a6b7ab787eb30ccc0cd5e1604470a6eb6' in submodule path 'std-lib'
Makefile:242: recipe for target 'up-to-date-std-lib' failed
```
For me, this is both on `stable-2.5` and on `master`.

@UlfNorell : any clue what to do about it?

**Comment by UlfNorell** [comment]
Try `git fetch`? If that doesn't work nuke your std-lib directory and retry. The commit certainly exists: https://github.com/agda/agda-stdlib/commit/aaa04c9a6b7ab787eb30ccc0cd5e1604470a6eb6.

**Comment by asr** [comment]
Note that this commit hasn't associated any branch.

**Comment by UlfNorell** [comment]
The reason is that @MatthewDaggitt rebased/cherry-picked the commit instead of merging when accepting the PR, so it's https://github.com/agda/agda-stdlib/commit/be4f3bf6aaed0ba2f4b0a3193084a41e02476e36 on the master branch. If all else fails you could changed the submodule pointer to that commit instead.

**Comment by andreasabel** [comment]
> Try git fetch? If that doesn't work nuke your std-lib directory and retry. 

Neither of these changes the error.

I am moving the `std-lib` submodule to https://github.com/agda/agda-stdlib/commit/be4f3bf6aaed0ba2f4b0a3193084a41e02476e36 .
If this is wrong, please move to the correct commit, but not back to https://github.com/agda/agda-stdlib/commit/aaa04c9a6b7ab787eb30ccc0cd5e1604470a6eb6 .

**Comment by MatthewDaggitt** [comment]
@UlfNorell my deepest apologies that it was my fault. What did I do wrong so I know how to avoid it in future? I assume it happened while merging https://github.com/agda/agda-stdlib/pull/182, but all I did was hit "Squash and merge" as usual...

**Comment by UlfNorell** [comment]
You didn't do anything wrong. The problem was that we were pointing the stdlib submodule in the Agda repo to the commit in the PR, and this became a dangling commit when you merged and the PR branch got deleted. People, like Andreas, who hadn't fetched the standard library before the merge, couldn't then get to that particular commit.

The right move is to do what @andreasabel did and change the pointer in the Agda repo to the new commit.

**Comment by andreasabel** [comment]
Thanks for the explanation, now I understand what the problem was.
