### ISSUE TITLE
Internal error in BasicOps

### ISSUE THREAD

**Issue by nad** [agda/agda#2881]
If you load the following code and then try to show the constraints, then an internal error is reported:
```agda
open import Agda.Builtin.Size

postulate
  X : Set
  P : X → Set
  Q : (x : X) → P x → Set

data D (i : Size) : Set where
  c : D i

f : (i : Size) → D i → X
f i c = {!!}

g : (x : X) (y : P x) → Q x y → Q x y
g _ _ q = q

h : (i : Size) (n : D i) → P (f i n)
h _ c = {!!}

k : (n : D ω) → Q (f ω n) (h ω n)
k _ = g _ (h _ {!!}) _
```
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/Interaction/BasicOps.hs:444
```
The following script can be used to trigger the error:
```shell
#!/bin/sh

AGDA=$1

$AGDA --interaction --ignore-interfaces <<EOF
IOTCM "Bug.agda" None Indirect (Cmd_load "Bug.agda" [])
IOTCM "Bug.agda" None Indirect Cmd_constraints
EOF
```
This is a regression. The error is not present in Agda 2.5.2, but it is present in Agda 2.5.3.

**Comment by andreasabel** [comment]
Sounds very much like #2637.
Apparently the size solver violates some invariants of the constraint / meta store.

**Comment by nad** [comment]
Bisection suggests that the bug was introduced by @UlfNorell in a45f5ce064b97a590a090a4921d92906ab34a461, a fix of #2384 (which was later reopened): "[ constraints ] anti-unification when getting stuck checking argument spines".

**Comment by gallais** [comment]
Andreas is right. The problem comes from a call to `reify` in [`getConstraints`](https://github.com/agda/agda/blob/master/src/full/Agda/Interaction/BasicOps.hs#L538)
which does not expect an `UnBlock (InstV ...)`.

Looking around a bit, this seems relevant ([link](https://github.com/agda/agda/blob/master/src/full/Agda/TypeChecking/Constraints.hs#L223)):

```haskell
solveConstraint_ (UnBlock m)                =
    (...)
    inst <- mvInstantiation <$> lookupMeta m
    (...)
    case inst of
      (...)
       -- Andreas, 2009-02-09, the following were IMPOSSIBLE cases
      -- somehow they pop up in the context of sized types
      --
      -- already solved metavariables: should only happen for size
      -- metas (not sure why it does, Andreas?)
      -- Andreas, 2017-07-11:
      -- I think this is because the size solver instantiates
      -- some metas with infinity but does not clean up the UnBlock constraints.
      -- See also issue #2637.
      InstV{} -> return ()
```

We could either adopt the same fix or try to find where the size solver fails to clean up after
itself in which case we have to remember revert this back to `__IMPOSSIBLE__` too.

**Comment by andreasabel** [comment]
Thanks, Ulf!
