### ISSUE TITLE
Internal error caused by new forcing translation

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#2888]
I minimized the example as far as I could:
```agda
record ⊤ {a} : Set a where constructor tt

data F : Set → Set where
  c : F ⊤

data G : (A : Set) → F A → ⊤ → Set where
  d : (x : ⊤) → G ⊤ c x

test : (f : F ⊤) → G ⊤ f tt → ⊤
test f (d x) = tt
```
Location of the error: src/full/Agda/TypeChecking/Forcing.hs:208

@UlfNorell could you take a look?

**Comment by jespercockx** [comment]
This bug is triggered in the code by @nad I was testing with my refactoring, e.g. in http://www.cse.chalmers.se/~nad/repos/codata/:
```
Checking README (/home/jesper/agda-libraries/codata/README.agda).
 Checking Stream.Equality (/home/jesper/agda-libraries/codata/Stream/Equality.agda).
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Forcing.hs:207
```

**Comment by andreasabel** [comment]
@UlfNorell : And while you are at it, please document the `unforce` function (expected inputs, expected outputs), possibly with a representative example.  Thanks.

**Comment by UlfNorell** [comment]
The problem is that the unifier solves the equation `x = tt` by eta expansion instead of by turning `x` into `.tt` (due an unsolved level meta). This should be fine, except `x` is in a forced position so the forcing translation tries (and fails) to move the binding of `x`.

As far as I can see, this is only a problem for (possibly nested) singleton records, so a possible solution would be to do a prepass before forcing translation to explicitly eta expand any singleton-record pattern variables.

**Comment by nad** [comment]
I did not find a regression test for this bug.

**Comment by UlfNorell** [comment]
Forgot to add it. Thanks for spotting.
