### ISSUE TITLE
Inference change

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#2926]
I don't know if this is important or not, but I updated Agda master and checked my project, and there are a couple places where inference no longer works as before. Here's a minimal example:

```agda
data Maybe (t : Set) : Set where
  just : t → Maybe t
  nothing : Maybe t

data ⊥ : Set where

data Dec (t : Set) : Set where
  yes : t → Dec t
  no : (t → ⊥) → Dec t

test : ∀ {t : Set} → t → Maybe t
test x = go (yes x)
  where
    go : _ → _
    go (yes x) = just x
    go _ = nothing
```

Agda currently complains `Cannot split on argument of non-datatype _14 x`, but previously it solved this. Fwiw, it works when I write `go : Dec _ -> _`, so it's just the `Dec` part it's stuck on, which is odd, since `yes` cannot be anything else besides `Dec`.

**Comment by jespercockx** [comment]
Yes, this is an intentional change to the semantics of Agda. It turns out
that we cannot solve metas in the type of a function based on the pattern,
lest we get non-unique solutions (see
https://github.com/agda/agda/issues/2834). So in the new implementation of
the LHS checker I tried to be more principled and only have the information
flow from the type to the patterns, not the other way. Unfortunately this
means that you sometimes have to write a more detailed type for the
function than before.

At least in your example (and I guess also in others) we could improve the
situation by postponing the LHS problem and trying again later instead of
failing hard. However we need to add some new infrastructure to the Agda
internals before this is possible, so I'm not sure how long this will take.
But we'll at least discuss the problem at the Agda meeting this week.

I should really add this to the patch notes before we release the next
version of Agda, so thanks for the reminder!

-- Jesper

**Comment by gallais** [comment]
Food for thoughts (together with @fredrikNordvallForsberg) :

```agda
test' : ∀ {t : Set} → t → Maybe t
test' x = (λ { (yes p) → just p ; _ → nothing }) (yes x)

test'' : ∀ {t : Set} → t → Maybe t
test'' x = ((_ → _) ∋ λ { (yes p) → just p ; _ → nothing }) (yes x)
```

* The first one stops with unsolved metas & constraints
* The second one is accepted

Aren't both of these elaborated to something like:

```agda
test' : ∀ {t : Set} → t → Maybe t
test' x = go (yes x)
  where
    go : _
    go (yes x) = just x
    go _ = nothing

test'' : ∀ {t : Set} → t → Maybe t
test'' x = go (yes x)
  where
    go : _ → _
    go (yes x) = just x
    go _ = nothing
```

?

**Comment by jespercockx** [comment]
For pattern matching lambdas there's some postponing already implemented, so that explains why the pattern-lambda version of test'' is accepted but the local definition is not. For test', Agda doesn't know yet that the type of the pattern lambda/helper function should be a function type so it fails immediately, postponing would help here as well.

**Comment by jespercockx** [comment]
Since we already have #2056 I'm closing this issue.
