### ISSUE TITLE
Syntax highlighting fails

### ISSUE THREAD

**Issue by fredefox** [agda/agda#2962]
In emacs, when I load my file everything is syntax-highlighted. But when I change a character somewhere the syntax highlighting of the entire file disappears. Also I get this in `*Messages*`:

```
error in process filter: let*: Wrong type argument: sequencep, font-lock-comment-face
error in process filter: Wrong type argument: sequencep, font-lock-comment-face
```

I excpect this to be related somehow to #2960 and 99522f4ba98c2d62e28e6f820c2742e12246a910 since this was not an issue earlier today when I was running `Agda version 2.6.0-6f3203e`. Now I'm on `Agda version 2.6.0-4654bfb`.

**Comment by nad** [comment]
I have not managed to reproduce this problem. Can you provide a step-by-step recipe for reproducing it, starting from a clean installation? Note that if you had previously compiled the Emacs mode's files (for instance by running `agda-mode compile`), but you did not do this when reinstalling Agda, then Emacs was perhaps using the old, compiled files rather than the new ones.

**Comment by fredefox** [comment]
I'm on the most recent version now - though nothing seems to have changed that should touch this behavior. I haven't been affected by the problem for some time now - so it's likely I forget to call `agda-mode compile`. I'll close and reopen if it happens again and then I'll try to give more details. The problem was even causing agda-mode to get stuck (so that I had to issue `M-x agda-restart`).
