### ISSUE TITLE
Copatterns break canonicity

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#2974]
```agda
open import Agda.Builtin.Nat
open import Agda.Builtin.Equality

record _×_ (A B : Set) : Set where
  constructor _,_
  field
    fst : A
    snd : B

open _×_

-- Nested pattern prevents record pattern translation.
f : Nat × Nat → Nat
f (zero  , b) = b
f (suc a , b) = a + b

-- Definition by copatterns.
p : Nat × Nat
p .fst = 2
p .snd = 2

-- Matching p against _,_ is stuck.
non-canonical : f p ≡ 3
non-canonical = refl

-- f p != 3 of type Nat
-- when checking that the expression refl has type f p ≡ 3
```

**Comment by UlfNorell** [comment]
I think the best way to solve this is to get rid of the record pattern translation completely, and deal with record patterns during reduction.

**Comment by andreasabel** [comment]
This is one problem I left unaddressed when adding copatterns.  To be complete, `p` should reduce to `record { fst = 2; snd = 2}`, since the projection pattern matches here are not proper matches: they are not coinductive projections, and there are no proper matches following them.  (In analogy, if `q x = bla`, then `q` alone reduces to `\ x -> bla`.)
However, it seems that many rely on this missing reduction as _feature_ for efficiency.  (Otherwise, what could you gain in terms of efficiency when turning a record expression into a definition by copattern matching.)

What is your proposition?

[Not sure this bug is critical, when it has been around for 4 years.]

**Comment by UlfNorell** [comment]
> What is your proposition?

My proposition is that `p` still does not reduce by itself, but that matching against a record constructor does not block evaluation.

> [Not sure this bug is critical, when it has been around for 4 years.]

Indeed, but I guess it's gone unnoticed since people aren't using copatterns heavily, and nested matches inside record patterns are not that common.

I would still argue that it's critical, since changing a single definition to use copatterns can cause difficult-to-debug serious breakage.

**Comment by nad** [comment]
Should this ticket be closed?

**Comment by UlfNorell** [comment]
> Should this ticket be closed?

Those commits were on my fork. It closed once they made it onto master.
