### ISSUE TITLE
Mixing libraries and -i leads to unexpected result

### ISSUE THREAD

**Issue by nad** [agda/agda#2987]
Using the library facilities together with `-i` in a certain way does not work:
```
$ mkdir -p lib/src
$ echo "$PWD/lib/lib.agda-lib" > libraries
$ echo "include: src" > lib/lib.agda-lib
$ echo "import M" > lib/README.agda
$ touch lib/src/M.agda
$ agda --ignore-interfaces --no-libraries -ilib -ilib/src lib/README.agda
Checking README ([...]/lib/README.agda).
 Checking M ([...]/lib/src/M.agda).
$ (cd lib && agda --ignore-interfaces --no-default-libraries --library-file=../libraries -i. README.agda)
[...]
Checking README ([...]/lib/README.agda).
 Checking M ([...]/lib/src/M.agda).
$ agda --ignore-interfaces --no-default-libraries --library-file=libraries -ilib lib/README.agda
Checking README ([...]/lib/README.agda).
[...]/lib/README.agda:1,8-9
Failed to find source of module M in any of the following
locations:
  [...]/lib/M.agda
  [...]/lib/M.lagda
  [...]/Agda-2.6.0/lib/prim/M.agda
  [...]/Agda-2.6.0/lib/prim/M.lagda
when scope checking the declaration
  import M
```
Given that the first two calls to Agda above succeed I had expected that the last one would also succeed.

**Comment by andreasabel** [comment]
Some how the `libraries` file gets ignored.

Note that your second command even succeeds without the `--library-file` option, since it finds the `.agda-lib` file in the current directory.

I think this test case is not pointing to the problem yet.

**Comment by andreasabel** [comment]
Since your library does not have a name, it cannot be referenced by the `--library` option.
Thus, it does not matter whether, by providing a `--libraries-file`, you give the possibility to locate it.

The `lib.agda-lib` file is located by searching from the project root upward.  It should be found in both cases.  The include pathes retrieved from the `lib.agda-lib` file will be relative, thus, in the working case,
```
./src
```
and in the none-working case,
```
lib/src
```
Maybe Agda thinks these pathes should be interpreted relative to the project root, while they should be interpreted relative to the current directory.  (The project root has already been taken into account, since the library-path is prepended to the include paths.)

Aren't you the author of the `RelativeTo` logic for handling paths? 1e04c0a6054599f2f06399eac5495f73ac7d6882
d8a809e8a99dabe2dfe7c914757858cda8c11a39

You owe me a beer for my fruitless hunting in the `Library.hs` file!

**Comment by nad** [comment]
That commit dates to 2010, `Library.hs` was added in 2015.

**Comment by UlfNorell** [comment]
This is working as intended. As @andreasabel points out the `--library-file` does nothing in any of the commands. Adding `name: lib` to `lib.agda-lib` and `--library=lib` to the last command makes it work.
