### ISSUE TITLE
Regression: With clause pattern x is not an instance of its parent pattern "eta expansion of x"

### ISSUE THREAD

**Issue by nad** [agda/agda#2998]
The following code is accepted by Agda 2.5.3, but not by Agda 2.6.0-47301dc:
```agda
open import Agda.Builtin.Equality

record R₁ : Set where

data D₁ : Set where
  c₁ : R₁ → D₁

data D₂ (x : D₁) : Set where
  c₂ : D₂ x

record R₂ : Set where
  constructor c₃
  field
    x : D₁
    y : D₂ x

postulate
  easy : (A : Set) → A

F : (x : R₁) → D₂ (c₁ x) → Set₁
F x y   with easy (c₃ (c₁ x) y ≡ c₃ (c₁ x) c₂)
F x .c₂ | refl with Set
F x .c₂ | refl | _ = Set
```
An excerpt from the error message:
```
With clause pattern x is not an instance of its parent pattern
record {}
```

**Comment by nad** [comment]
Bisection points to d9359139ab717397279af5719541ebb59c836702: "[ #2888 ] prefer EtaExpandVar over EtaExpandEquation in unification".

**Comment by jespercockx** [comment]
Simplified test case:
```agda
open import Agda.Builtin.Equality

record R : Set where

postulate
  easy : (A : Set) → A

F : (x : R) → Set₁
F x with easy (x ≡ x)
F x | refl with Set
F x | refl | _ = Set
```
The unifier's old strategy solved the equation `x = x : R` by eta-expanding the *equation*, leaving the variable `x` untouched. Now it instead eta-expands the *variable* `x`, instantiating it to `record {}`.

The proper solution would probably be to make with-stripping invariant under eta-expansion. However, we have to be a bit careful because with-abstraction may have changed the types of some of the pattern variables. For example:
```
F : (x : R) → Set₁
F x with easy (x ≡ x) | R
F x | refl | A with Set
... | _ = {!!}
```
Here the type of `x` in the with-clause is the variable type `A`, so it would not be right to instantiate it with `record {}`. I'm not sure yet what's the right solution here, the more I think about with-abstraction the less I understand it.

**Comment by andreasabel** [comment]
For
```agda
F : (x : R) → Set₁
F x with easy (x ≡ x) | R
F x | refl | _ with Set
F x | refl | _ | _ = Set
```
I get the error
```
With clause pattern x is not an instance of its parent pattern
record {}
when checking that the clause
.Issue2998.with-14 x refl _ with Set
.Issue2998.with-14 x refl _ | _ = Set
has type (x : R) → _≡_ {.Agda.Primitive.lzero} {R} x x → Set → Set₁
```
which means that the type `x` has not been abstracted.  Thus, this is not a problematic example.

**Comment by nad** [comment]
This bug affects several of my developments.

**Comment by jespercockx** [comment]
I think I have a clearer idea now of what should happen here. In particular, with-abstraction should never abstract over the type of a variable if:

- the variable has been instantiated by the unifier
- the variable has been eta-expanded by the unifier
- the variable is used in the return type
- the variable is used in the type of another variable
- the variable is used in the instantiation of another variable

Hopefully this is already enforced (as Andreas' example seems to show for the second point at least); if not we should really make it so since for each of those I can think of example breaking subject reduction.

Now with these guarantees there is no more risk that with-abstraction turns a record type into a variable, so it is safe to make with-stripping respect eta-expansion. In my simplified test case, this would mean that since `x` is eta-expanded to `record{}` in the parent clause, it is likewise expanded in the with clauses. I'll try to implement this next.

**Comment by nad** [comment]
> for each of those I can think of example breaking subject reduction.

Isn't the result of `with` expansion type-checked? In that case `with` on its own cannot break subject reduction, such breakage would rely on other problems.

**Comment by jespercockx** [comment]
The problem is that if we're not careful, a variable of the with clause could be instantiated (by parameter refinement) to a solution that only made sense in the context of the parent clause. My current plan is to add an extra double-check (using `checkInternal`) for all instantiations of variables that are passed from parent clause to child clause, which should at least make everything type-safe. The next step is then to make with-stripping more liberal, in particular to allow eta-expansion which would fix this issue.

**Comment by nad** [comment]
Does the user manual need to be updated?

**Comment by nad** [comment]
> This bug affects several of my developments.

And now they are accepted. Thanks.

**Comment by jespercockx** [comment]
> Does the user manual need to be updated?

Yes, I'll add a paragraph.
