### ISSUE TITLE
Interaction: iterated give encounters internal error

### ISSUE THREAD

**Issue by sattlerc** [agda/agda#3000]
On master; not sure if already on the issue tracker.

```agda
module Bug where

open import Agda.Primitive

Type : (i : Level) → Set (lsuc i)
Type i = Set i

postulate
  T : (i : Level) (A : Type i) → Set

-- Give 'T lzero ?', then give '? → ?'.
-- An internal error has occurred. Please report this as a bug.
-- Location of the error: src/full/Agda/TypeChecking/Rules/Term.hs:178
Bug : Set
Bug = {!T lzero ?!}
```

**Comment by poplmark-reloaded** [comment]
PLING! YOU ARE THE CHOSEN ONE! YOU SUBMITTED THE THIRD MILLENIUM BUG!

**Comment by andreasabel** [comment]
PLING! YOU ARE THE CHOSEN ONE! YOU SUBMITTED THE THIRD MILLENIUM BUG!

**Comment by UlfNorell** [comment]
And very worthy one to be bug number 3000 (or b3k as we like to call it).

If you give `T lzero {!!}` instead of `T lzero ?` there's no internal error!?!

Looking briefly at the debug output it looks like with `?` it (incorrectly) counts as an existing interaction point, confusing the code that's handling #707. It's amazing that there's a difference between `{!!}` and `?` that survives all the way to the type checker!

**Comment by jespercockx** [comment]
I fixed the internal error by adding a missing `reduce` statement, however now you get "failed to give" instead of an internal error. Interestingly, the problem only seems to occur in Emacs, but not when I add the test case to `test/interaction`. I have no idea what's going on here, except that it probably has something to do with the fix of #707 as @UlfNorell said. Maybe @andreasabel could take a look?

Anyway, since the internal error is gone now I'm bumping the milestone.

**Comment by nad** [comment]
> Interestingly, the problem only seems to occur in Emacs, but not when I add the test case to `test/interaction`.

Did you base the test case on the contents of the `*agda2*` buffer?

**Comment by jespercockx** [comment]
I don't know, I just did what I always do when adding an `interaction` test, which is copy-pasting an existing `.in` file and adapting it to the current test.

**Comment by nad** [comment]
I managed to trigger the internal error by using the following `.in` file:
```
top_command (cmd_load currentFile [])
IOTCM currentFile None Indirect (Cmd_give WithoutForce 0 (intervalsToRange (Just (mkAbsolute "<absolute path to the file>")) [Interval (Pn () 338 15 9) (Pn () 347 15 18)]) "T lzero ?")
IOTCM currentFile None Indirect (Cmd_give WithoutForce 1 (intervalsToRange (Just (mkAbsolute "<absolute path to the file>")) [Interval (Pn () 346 15 17) (Pn () 351 15 22)]) "? → ?")
```

**Comment by UlfNorell** [comment]
So, the problem is that to make #707 and similar situations work, there is logic in the scope checker to decide whether two interaction points are really the same. This is handled by `registerInteractionPoint` in `TypeChecking.Monad.MetaVars` and basically checks if there is already an interaction point with the same source location as the new hole.

In this example this results in the scope checker thinking that the first question mark in the function type we try to give is in fact the same interaction point as the hole we are filling. This also explains why there is a difference between `{!!}` and `?`: they have different source ranges.

A possible solution is to mark the original meta as solved before checking the solution, and not consider solved interaction points when checking if a hole already has an interaction point.

**Comment by andreasabel** [comment]
Thanks for fixing my bug!
