### ISSUE TITLE
Agda hangs on extended lambda

### ISSUE THREAD

**Issue by sattlerc** [agda/agda#3004]
Tested on master (194356b85).

```agda
module Bug where

postulate
  id : {X : Set} → X → X
  A : Set
  x : A

record S : Set where
  field
    a : A

postulate
  B : S → Set

record T : Set where
  field
    s : S
    b : B s

-- Agda hangs here
t : T
t = λ
  { .T.s .S.a → x
  ; .T.b → id ?
  }

{-
-- works when the extended lambda is made top-level
t : T
t .T.s .S.a = x
t .T.b = id ?
-}

```

**Comment by UlfNorell** [comment]
A quick look at the debug output suggests that it might be a printing issue. The implicit argument of `id` is `B (λ { ... } .T.s)` where `...` contains the call to `id` itself. If we are trying to print that implicit argument I can see how this might loop.

**Comment by sattlerc** [comment]
That seems plausible.

Simplifying the example a bit:

```agda
module Bug where

postulate
  id : (X : Set) → X → X
  A : Set
  B : A → Set
  x : A

record T : Set where
  field
    a : A
    b : B a

-- Agda hangs here
t : T
t = λ
  { .T.a → x
  ; .T.b → id ? ?
  }
```

**Comment by andreasabel** [comment]
I book that bug on the account _failure of the syntactic sugar philosophy_.

**Comment by UlfNorell** [comment]
I don't think accounting will accept that.

If pattern lambdas weren't sugar we would instead have to build an infinite term, so it seems to me the problem is more fundamental than that.

**Comment by andreasabel** [comment]
I rather think that if pattern lambdas were not sugar, this example would either fail to type-check or would work the same as records work now.  
```agda
r : T
r = record
  { a = x
  ; b = id ? ?
  }
```
The reason is that there would not be a name for the recursive function.  However, now, we have one, although it must not be named, and thus is unfolded eagerly by the printer.

That said, there is maybe something to be learned from this example, especially if we want to consider `record` expressions as a special form of pattern lambdas.  We should maybe eagerly reduce previous projection clauses in the type of a projection clause.  This would also help with issue #906.

Basically, when we are lhs checking a projection pattern `pi`
```
  self : R vs |- pi es : C
```
where the type of the projection would be `pi : (x : R vs) -> A` we now continue with
```
  self.pi : A[self/x] |- es : C
```
Instead, we could continue with
```
  self.pi : A[expand(self)/x] |- es : C
```
where `expand(self)` is a record eta expansion of `self` with clauses for the previous projections applied once.
In the example above, when checking projection pattern `.T.b`, we have `self = it-who-must-not-be-named`, but already know `it-who-must-not-be-named .T.a = x` thus, self would be expanded to
```
  record { a = x; b = it-who-must-not-be-named .T.b }
```
which leaves the unutterable out of the type of `b`.

**Comment by UlfNorell** [comment]
I'm not sure that would be enough for the original test case though, since there's an additional projection `.S.a` that's not being applied. In that case it would help if pattern lambdas were in the core language and could be partially applied (so that `you-know-who .T.s` could be expanded to `λ { .S.a → x }`.

**Comment by UlfNorell** [comment]
Another test case in #3069.

**Comment by sattlerc** [comment]
I seem to run into this issue quite frequently. Is there a workaround that allows me to continue using extended lambdas, copatterns, and interaction points?

**Comment by UlfNorell** [comment]
We should at least make it not loop. Simplest would be to print the internal name of the lambda when it appears inside its own body.

**Comment by UlfNorell** [comment]
I filed #3076 for continuing the discussion on how to properly handle copattern lambdas.

**Comment by sattlerc** [comment]
Thanks! At least I won't end up reducing test cases for the same bug anymore.
