### ISSUE TITLE
Build errors of hTags with GHC 8.4.1

### ISSUE THREAD

**Issue by asr** [agda/agda#3013]
Building `hTags` with GHC 8.4.1 generates various errors:

```haskell
$ make TAGS
Tags.hs:188:12: error:
    • Could not deduce (TagName (IdP name))
        arising from a use of ‘tagsLN’
      from the context: TagName name
        bound by the instance declaration at Tags.hs:187:10-50
    • In the expression: tagsLN (fdLName d)
      In an equation for ‘tags’: tags d = tagsLN (fdLName d)
      In the instance declaration for ‘HasTags (FamilyDecl name)’
    |
188 |   tags d = tagsLN (fdLName d)
    |       
...
```

Could someone to try to fix these errors, please.

**Comment by nad** [comment]
The (main?) problem seems to be that `Located name` has been replaced by `Located (IdP pass)`, where [`IdP`](https://downloads.haskell.org/~ghc/8.4.1/docs/html/libraries/ghc-8.4.1/HsExtension.html#t:IdP) is a type family mapping passes to name types.

GHC complains that it `Could not deduce (TagName (IdP name))`. I suspect that (for GHC 8.2.2) we only need to produce tags when `name` is `RdrName`, because `tags` is used at type `HsModule RdrName` in the main module. Perhaps one way forward is to make the `Tags` module less general by defining a new type synonym that stands for `RdrName` in previous versions of GHC, and `GhcRn` in GHC 8.4.1, and substituting this type synonym for `name`.

**Comment by asr** [comment]
If someone fix the issue, please also change in Travis

```bash
# ASR (2018-03-26). hTags is not supporting GHC 8.4.1. See #3013.
  - if [[ $TEST = "MAIN" && $GHC_VER != "8.4.1" ]]; then
       make BUILD_DIR=$BUILD_DIR TAGS;
    fi
```

by

```bash
  - if [[ $TEST = "MAIN" ]]; then
       make BUILD_DIR=$BUILD_DIR TAGS;
    fi
```
