### ISSUE TITLE
Missing highlighting in record modules

### ISSUE THREAD

**Issue by nad** [agda/agda#3020]
In the following code the final instances of `A` and `B` are not highlighted interactively:
```agda
record R : Set₁ where
  field
    A : Set

  B : Set
  B = A
```
This is a regression. Bisection indicates that the problem was introduced in 2dc68ac7743452958cb7bb9571c0548180b783de: "Fixed #2963 and at the same time #2975".

The problem already existed for record modules in mutual blocks (introduced using the `mutual` keyword). This problem seems to have been introduced in Agda 2.5.1.

**Comment by nad** [comment]
Bisection suggests that the second problem mentioned above was introduced in 89f6f5cb8ebdfd066091430b734765d4ba2b13c5: "[ Fixed #1790 ] Highlighting of record decl. under mutual".

**Comment by andreasabel** [comment]
This problem only shows up under _interactive_ highlighting (I updated the problem description accordingly).

**Comment by andreasabel** [comment]
Trying to fix this I would probably only play another game of whack-a-mole. 
There are two fundamental problems which need attention to make the highlighting feature more stable and save from regressions:
1. The regression testsuite for highlighting is not human-friendly and thus easily broken.  Instead of just dumping the whole communication of highlighting info with emacs and asking the developer to compare the diffs, it should be a collections of tests that give simple yes/no results whether the highlighting of a token came out correctly in the end.
2. The gathering of highlighting info should be monotone in the sense that _more_ calls to `generateAndPrintSyntaxInfo` (on declarations and subdeclarations) can only lead to _more_ highlighting, not less.  The current API expects the developer to know too much about the internal workings of the highlighter.

**Comment by nad** [comment]
> This problem only shows up under _interactive_ highlighting (I updated the problem description accordingly).

Oh, perhaps you're right. However, I only tested non-interactive highlighting when bisecting, so it seems as if the commits I pointed to affect the highlighting commands sent to Emacs in some way, even if non-interactive highlighting is used.

**Comment by andreasabel** [comment]
There seems to be also a problem with the HTML backend.  Definitions in records are not highlighted.

**Comment by nad** [comment]
If you take the code from the OP and type-check it in the Emacs mode, with non-interactive highlighting, then it is highlighted properly. However, if you then reload the file, then you get incorrect highlighting.

**Comment by andreasabel** [comment]
Thanks for fixing!
