### ISSUE TITLE
Travis error: Server does not allow request for unadvertised object 2a40a03

### ISSUE THREAD

**Issue by asr** [agda/agda#3037]
Travis is [failing]( https://www.travis-ci.org/agda/agda/builds/369129301) with the error in the issue title.

I could reproduce the error running the commands used by Travis:

```
$ git clone --depth=50 --branch=stable-2.5 https://github.com/agda/agda.git
$ cd agda/agda
$ git submodule update --init --recursive
error: Server does not allow request for unadvertised object 2a40a031e40042e72e245cce17956e5df49fcdd5
Fetched in submodule path 'std-lib', but it did not contain 2a40a031e40042e72e245cce17956e5df49fcdd5. Direct fetching of that commit failed.
```

Any idea how to fix the issue?

**Comment by asr** [comment]
The above commit fixed the issue but now we have some issues in the test-suite related to the changes in the standard library.

**Comment by MatthewDaggitt** [comment]
Hmm, yes I suspect the original problem,  is to do with the `push -f`s we're using to try and keep the non-compatible changes on the experimental branch floating alongside master (see [here](https://github.com/agda/agda-stdlib/commit/3dae60237d401dd918c3f12e8b7a61517fabccf1#commitcomment-28653067)).

As for non-backwards compatibility issues with the tests, after fast-forwarding the library version, I'll have time to fix them up tomorrow morning if no-one has got round to it by then.

**Comment by asr** [comment]
> Hmm, yes I suspect the original problem,  is to do with the `push -f`s we're using to try and keep the non-compatible changes on the experimental branch floating alongside master (see [here](https://github.com/agda/agda-stdlib/commit/3dae60237d401dd918c3f12e8b7a61517fabccf1#commitcomment-28653067)).

I have the same suspect. I think there is something wrong in the current work-flow but I don't know how to fix it.

> As for non-backwards compatibility issues with the tests, after fast-forwarding the library version, I'll have time to fix them up tomorrow morning if no-one has got round to it by then.

Thanks. I fixed a couple of issues. A remaining issue is #3040.

**Comment by asr** [comment]
We have the [same]( https://www.travis-ci.org/agda/agda/builds/370263649) problem. I'll run `make fast-forward-std-lib` again.

**Comment by gallais** [comment]
Is there a reason why the test is tied to a specific commit rather than, say,
whatever is on `experimental`?

**Comment by UlfNorell** [comment]
We have the standard library as a git submodule, which I believe means you have to tie it to a particular commit. It's also nice that if you check out some old commit you get a version of the standard library that works with that version of Agda.

Of course, that doesn't work if commits keep disappearing from the std-lib repo....

**Comment by UlfNorell** [comment]
What's the reason for rebasing `experimental` on `master` instead of merging?

**Comment by gallais** [comment]
As soon as a new version of Agda is released, we should be able to seamlessly
move `experimental` to `master` as `experimental = compat ++ master`.

**Comment by UlfNorell** [comment]
Merging the other direction on release seems like it would be pretty seemless too.

The other option is that we make a separate branch for the Agda test suite.

**Comment by UlfNorell** [comment]
Pinging @gallais and @MatthewDaggitt, what are your opinions on this. The current situation is untenable for the Agda test suite, so we need to either
- create a separate branch of the standard library for the test suite (and merge `master` into this on a regular basis), or
- switch to merging `master` into `experimental` instead of rebasing

**Comment by MatthewDaggitt** [comment]
So I'm not an expert git user. I'll just quickly again lay out the aims as I see it:

1. All additions that are compatible with the current version of Agda should be carried out on the `master` branch and the `experimental` branches.
2. All additions that are not compatible with the current version of Agda should be carried out on the `experimental` branch.
3. When it comes to a new Agda release, we want to be able to seamlessly merge `experimental` into `master`. 

Now I've got in my head that in order to carry out 3. the `experimental` changes not present on `master` need to be at the top of the `experimental` branch for some reason. However now I think about it, I can't quite work out why... Even if they're further down the history of `experimental`, it should still be fine to merge them in. @gallais am I forgetting anything we discussed?

If that is the case then couldn't we switch to the following workflow?

- Compatible changes - make on `master`
- Non-compatible changes - make on `experimental`
- Periodically merge `master` into `experimental` to keep `experimental` reasonably current.
- Agda released - merge `experimental` back into `master`.

The problem with the last one is that if we have some changes in experimental which still aren't compatible with the next release of Agda we have no way of picking them out...

As for Ulf's first suggestion, a third separate compatible branch is just going to run into exactly the problems as `experimental` in that the history is going to be messed up whenever we try and add the changes on master.

There *must* be a way of doing this... Maybe I should ask on stackoverflow and see if anyone has bright ideas?

**Comment by UlfNorell** [comment]
> The problem with the last one is that if we have some changes in experimental which still aren't compatible with the next release of Agda we have no way of picking them out...
 
This shouldn't happen. At least with the current release procedure we always release from the `stable` branch (or from `master` I guess if we ever get around to a major release). I suppose what might conceivably happen is that `stable` and `master` diverges to the point where you need one `experimental` branch for each, but we really try to avoid that situation.

> As for Ulf's first suggestion, a third separate compatible branch is just going to run into exactly the problems as experimental in that the history is going to be messed up whenever we try and add the changes on master.

The difference is that we wouldn't need to merge this branch back into `master` on a release. There'd be two copies of the experimental commits though.

**Comment by asr** [comment]
> 3. When it comes to a new Agda release, we want to be able to seamlessly merge `experimental` into `master`. 
>
> Now I've got in my head that in order to carry out 3. the `experimental` changes not present on `master` need to be at the top of the `experimental` branch for some reason. However now I think about it, I can't quite work out why... Even if they're further down the history of `experimental`, it should still be fine to merge them in.

I neither see any reason where merging `master` into `experimental` instead of rebasing `experimental` on `master` could be wrong.

**Comment by MatthewDaggitt** [comment]
Okay, I'd still like to hear from @gallais before I commit to anything, but in principle I'm happy to try switching to Ulf's 2nd proposal for the moment, and we can see how things go when the next Agda release happens. I'm a little bit more reluctant to start a third branch that needs maintaining.

**Comment by gallais** [comment]
I really can't see a way of getting a clean history once we make `experimental` the
new `master` (because a new version of Agda has been released) except for making
sure we keep things clean at all times by percolating the Agda-dev specific commits
to the top.

But I see the problem with the Agda builds referencing commits which do not exist
anymore. Maybe we do have to accept the fact the history is going to look awful.

**Comment by UlfNorell** [comment]
Is it going to be awful though? As far as I can tell it will look like this (M = master, E = experimental):
```
M E
| o  -- new non-compat commits
|/
o    -- new Agda release (experimental -> master)
|\
| o  -- merge master -> experimental
|/|
o |  -- work on master
| o  -- non-compat commit
|/
o
```

**Comment by asr** [comment]
Any news/decision on this?

It seems the `experimental` branch (of the standard library) is *behind* by some commits from the `master` branch so we are not testing the `stable-2.5`/`master` branches of Agda on the last bits of the standard library. We should make this test before the release.

**Comment by UlfNorell** [comment]
\*Pokes @gallais / @MatthewDaggitt\*

**Comment by gallais** [comment]
I guess the only solution is to have merge commits polluting the history à la Agda stable vs. master?

**Comment by UlfNorell** [comment]
I don't see a reasonable alternative. At least you don't have to merge as aggressively as we do with Agda stable/master, so you can keep the pollution levels low. It's not really a problem if `experimental` lags behind a week or two.

**Comment by MatthewDaggitt** [comment]
Sorry, had a paper deadline and haven't been keeping up with emails. So what I'm planning on doing is to merge `master` into `experimental` (to get the latest updates to master) and then `experimental` back into `master` and then release `master`. Anyone have any objections?

**Comment by asr** [comment]
Please note you should merge `experimental` back into `master` *only* after a new release of Agda.

For closing this issue it's enough merge `master` into `experimental` and update the submodule commit in the Agda repository.

**Comment by MatthewDaggitt** [comment]
> Please note you should merge experimental back into master only after a new release of Agda.
> 
> For closing this issue it's enough merge master into experimental and update the submodule commit in the Agda repository.

Good point! Okay I've merged `master` into `experimental`. Currently having fun trying to build Agda 2.5.4 and run the tests. I'm getting on a plane in an hour, but will try and finish it tonight and push the updated submodule. Just checking that I should push it to `stable-2.5` rather than `release-2.5.4`?

**Comment by asr** [comment]
> Just checking that I should push it to `stable-2.5` rather than `release-2.5.4`?

Yes. You should push it into `stable-2.5`. If Travis is green, I'll cherry-pick it into `release-2.5.4`.

**Comment by asr** [comment]
> You should push it into `stable-2.5`.

I'll make it.

**Comment by MatthewDaggitt** [comment]
Thanks!

**Comment by asr** [comment]
For the record, I just updated the std-lib commit in Agda to use the current master of the standard library. I have no problem updating the test suite because the CHANGELOG of the standard library is *very* complete. Great job @MatthewDaggitt and @gallais!
