### ISSUE TITLE
Another recent inference change

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda#3052]
There is a fairly recent (since 385e86c, 3 days ago) change to inference. The code below was accepted then, but is currently rejected:

```agda
open import Agda.Builtin.Nat renaming (Nat to ℕ) hiding (_+_)
import Agda.Builtin.Nat as N
open import Agda.Builtin.Equality renaming (_≡_ to _≡≡_)
open import Agda.Builtin.TrustMe

erase : ∀ {a} {A : Set a} {x y : A} → x ≡≡ y → x ≡≡ y
erase _ = primTrustMe

record Σ (A : Set) (B : A → Set) : Set where
  constructor _,_
  field
    proj₁ : A
    proj₂ : B proj₁

open Σ public

∃ : ∀ {A : Set} → (A → Set) → Set
∃ = Σ _

record Fin (n : ℕ) : Set where
  field
    m : ℕ
    .p : ∃ λ k → (ℕ.suc k N.+ m) ≡≡ n

pred : ℕ → ℕ
pred zero    = zero
pred (suc n) = n

sub : ∀ {ℓ₁ ℓ₂} {t₁ : Set ℓ₁} {t₂ : Set ℓ₂} {c : t₂} → (a : t₁) → (b : t₁) → (f : t₁ → t₂) → f a ≡≡ c → a ≡≡ b → f b ≡≡ c
sub a .a f refl refl = refl

infixr 2 _≡⟨_⟩_

_≡⟨_⟩_ : ∀ {a} {A : Set a} (x {y z} : A) → x ≡≡ y → y ≡≡ z → x ≡≡ z
_ ≡⟨ refl ⟩ refl = refl

infixr 2 _⟫_
_⟫_ : ∀ {ℓ₁ ℓ₂} {t₁ : Set ℓ₁} {t₂ : Set ℓ₂} {a b : t₁} → (f : t₁ → t₂) → a ≡≡ b → f a ≡≡ f b
_⟫_ _ refl = refl

infixr 2 ⟨⟩_
⟨⟩_ : ∀ {ℓ} {t : Set ℓ} {a : t} {b : t} → a ≡≡ b → b ≡≡ a
⟨⟩_ refl = refl


infixl 60 _+_
_+_ : ∀ {m n} → Fin m → Fin n → Fin (pred (m N.+ n))
_+_ {m} {n} record { m = a ; p = c₁ , p₁ } record { m = b ; p = c₂ , p₂ } = record {
    m = a N.+ b
  ; p = (c₁ N.+ c₂) , erase (p c₁ c₂ p₁ p₂)
  }
  where
    p : ∀ c₁ c₂ _ _ → suc (c₁ N.+ c₂ N.+ (a N.+ b)) ≡≡ pred (m N.+ n)
    p c₁ c₂ p₁ p₂ = ⟨⟩
        _ ≡⟨ pred ⟫ ⟨⟩ N._+_ m ⟫ p₂ ⟩
        _ ≡⟨ sub _ m (λ x → pred (x N.+ suc (c₂ N.+ _))) refl p₁ ⟩
        {!!}

```

As previously, I'm not sure which behavior is correct - I just want to make sure the new behavior is intentional.

**Comment by andreasabel** [comment]
Just looking at the recent commits, it seems likely that 0322242be8bee1a48c27602ed633bc08f8a27715 is responsible for this change, a fix for #2450.

**Comment by andreasabel** [comment]
Here is a shrunk test case.  The solution for the meta-variable can be given by hand, but if Agda is to infer it, it complains `Cannot instantiate the metavariable ?0 to solution (suc (k₁ + a)) since it contains the variable k₁ which ... irrelevant in the metavariable but relevant in the solution`.
```agda
open import Agda.Builtin.Nat
open import Agda.Builtin.Equality

record Σ (A : Set) (B : A → Set) : Set where
  constructor _,_
  field
    proj₁ : A
    proj₂ : B proj₁
open Σ public

record Fin (n : Nat) : Set where
  constructor fin
  field
    m : Nat
    .p : Σ Nat λ k → (suc k + m) ≡ n

test : ∀ m n → Fin m → Fin n → Fin (m + n)
test m n (fin a (k₁ , p₁)) (fin b (k₂ , p₂)) =
  fin (a + b) ((k₁ + k₂) , thm k₁ k₂ p₁ p₂)  -- Error at p₁
  where
    postulate
      thm : (k₁ k₂ : Nat) (p₁ : {! suc k₁ + a !} ≡ m) (p₂ : suc (k₂ + b) ≡ n)
        → suc (k₁ + k₂ + (a + b)) ≡ m + n
```

Here is a much shrunk test case:
```agda
record Foo A B : Set where
  constructor foo
  field
    .theFoo : Σ A B

test : ∀ A B → Foo A B → Foo A B
test A B (foo (a , b)) = foo (a , thm a b) -- Error at b
  where
    postulate thm : (a : A) (b : {! B a !}) → B a
    -- thm a b = b -- Works if definition is given
```
with error
```
Cannot instantiate the metavariable _16 to solution (B a) since it
contains the variable a which is not in scope of the metavariable
or irrelevant in the metavariable but relevant in the solution
when checking that the expression b has type ?0 A B _ _ a
```

**Comment by andreasabel** [comment]
Agda should actually not allow to match on `.p : Σ A B`.  Currently, this is allowed and yields context `.x : A, .y : B x` but the type `B x` is ill-formed since `x` is irrelevant.  `B` would need to be shape-irrelevant to allow such a match.

**Comment by andreasabel** [comment]
While https://github.com/agda/agda/commit/0322242be8bee1a48c27602ed633bc08f8a27715 exposed this problem, the fix was to define a proper monoid instance for `VarMap` in the free variable computation, such that irrelevant occurrences would not overwrite relevant occurrences only because they came before.  Now relevant occurrences are considered more precious and replace irrelevant occurrences.

**Comment by identicalsnowflake** [comment]
> Agda should actually not allow to match on .p : Σ A B. Currently, this is allowed and yields context .x : A, .y : B x but the type B x is ill-formed since x is irrelevant. B would need to be shape-irrelevant to allow such a match.

Can you explain what you mean? So it's not just an inference thing -- even if I wrote all the solutions in manually, what I'm doing is still fundamentally questionable/wrong?

What might a better approach look like?

**Comment by andreasabel** [comment]
The type `B x` is well-formed if `B` is shape-irrelevant in `x`.  This is actually the case for your application, the identity type.  However, Agda does not do the necessary checks. A proper implementation would only accept the matching if the Sigma type was defined with a shape-irrelevant `B`:
```agda
record Σ (A : Set) (B : ..A → Set) : Set where
```
However, shape-irrelevance is a bit too preliminary to recommend its use.

**Comment by identicalsnowflake** [comment]
I'm not quite sure what you mean by shape irrelevance. Would the following be an example of not-shape-irrelevant, because there is a pattern match on the first half to decide the type of the second half?

```agda
type : Bool → Set
type true = ⊤
type false = ⊥

record Bad : Set where
  constructor b
  field
    .f : Σ Bool type
```

So then it's intuitively kinda the same idea as parametric polymorphism?

**Comment by jespercockx** [comment]
That's indeed a good example of something that's not shape-irrelevant. If you match on an argument of type `Bad` with pattern `b (x , y)`, then currently we have `x : Bool` irrelevantly and `y : type x` (also irrelevantly), but the application `type x` in the type of `y` is ill-formed since `x` is irrelevant. So I think it would be better to prohibit matching on irrelevant variables of a dependent record type. I'll open a new issue for this.

Side note: shape irrelevance is not really the same as parametricity; instead shape irrelevance relates to irrelevance as parametricity relates to regular relevance. So an argument that's relevant at the term level can be used parametrically at the type level, and an argument that's irrelevant can be used shape-irrelevantly at the type level. A typical example of a shape-irrelevant function is the type `Vector : ..(_ : Nat) -> Set`, which is (or at least can be made) shape-irrelevant in the `Nat` if its `cons : .(n : Nat) -> A -> Vec A n -> Vec A (suc n)` constructor is irrelevant in its first argument. But as Andreas says the current implementation of shape-irrelevance is not really at the point where I would recommend anyone using it.

**Comment by identicalsnowflake** [comment]
Makes sense. Thanks!
