### ISSUE TITLE
Typecheck result inconsistent and depends on an unused import

### ISSUE THREAD

**Issue by semenov-vladyslav** [agda/agda#3100]
```agda
module test2 where

open import Data.Product using (_×_ ; _,_)
open import Data.Vec using (Vec ; [] ; _∷_)
-- uncomment the following line
-- open import Data.Vec.Relation.Equality.DecPropositional

open import Relation.Binary.PropositionalEquality using (_≡_ ; refl)

vec-prop : ∀ {c} {S : Set c} {a b : S} {n} {as bs : Vec S n}
  → a ∷ as ≡ b ∷ bs → a ≡ b × as ≡ bs
vec-prop refl = refl , refl
```

Without the DecPropositional import the module incorrectly(?) typechecks.
With the DecPropositional import uncommented Agda correctly(?) fails with the following error:
"I'm not sure if there should be a case for the constructor refl, because I get stuck when trying to solve the following unification problems (inferred index ≟ expected index):
  _11 ≟ _13
when checking that the pattern refl has type _11 ≡ _13"

Agda version 2.6.0-3717cc2-dirty. std-lib fdeed40111754a264d585514b7d9acf5c9b95e81.

**Comment by UlfNorell** [comment]
The difference is that with the import, `_∷_` becomes ambiguous causing the pattern match to fail. If you change the type to `a Vec.∷ as ≡ b ∷ bs` it works in both cases.

You might think that since `as : Vec S n` we'd be able to figure out that it's `Vec._∷_`, but it's not that easy. See #79 for some discussion.

**Comment by semenov-vladyslav** [comment]
Thanks. Error message was confusing here.
