### ISSUE TITLE
Case splitter produces end-of-comment

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#3161]
```agda
data Pol : Set where
  + - : Pol

f : {x : Pol} → Set
f {x} = {!x!}  -- Split on x here
```
gives a parse error after producing
```
f {+} = ?
f { -} = ? 
```
Apparently, someone thought of this case and made Agda print a space before the minus, but unfortunately, not after the minus.

**Comment by gallais** [comment]
> Apparently, someone thought of this case and made Agda print a space before the minus, but unfortunately, not after the minus.

I'm pretty sure the bug was unearthed by splitting an implicit integer `k` and getting one branch
with `{-[1+ k ]}` which caused a parse error. However I can't find the corresponding bug report. :/

Edit: Ah! #269

And the fix is here: https://github.com/agda/agda/commit/8c85bb65b6e46e33f0fc8be517afaae230031b4b
