### ISSUE TITLE
Use cpp instead of cpphs as the default preprocessor

### ISSUE THREAD

**Issue by Saizan** [agda/agda#3223]
Installing Agda on windows seems to require the installation of some bash equivalent, because the haskell platform no longer ships with old-time and old-locale, and old-time runs a configure script during installation.

The haskell platform, or even ghc?, does come with a cpp though, maybe the cpphs flag should be off by default on windows?

**Comment by asr** [comment]
See https://github.com/malcolmwallace/cpphs/issues/15.

**Comment by UlfNorell** [comment]
It's been suggested (https://github.com/agda/agda/issues/2736#issuecomment-328032454) to turn off the `cpphs` flag for all platforms.

I still don't know why we are using cpphs at all. It's better at handling single quotes, but since we don't *require* cpphs you still need to write code to work without it.

**Comment by asr** [comment]
It seems that in the current situation `cpphs` is unnecessary. I'll remove it.

**Comment by asr** [comment]
We started to use `cpphs` due to some problems with `Clang` on macOS.  Is `Clang` the default compiler in MacOS? Currently is there some problem using `Clang` and `cpp` when building Agda? I'm asking because I want to include the fix for this issue in 2.5.4.2 (see #3228).

**Comment by asr** [comment]
I just found 5ff3fc5155af087c3881915ed82e45c9d06523df which fixed some problems with `Clang`. Since we *have no* CI for `Clang` developers using this compiler are on their own.

It seems safer
1. revert the fix to this issue, i.e. to continue using `cpphs` by default and also testing `cpp`, and
2. following the OP, make `cpp` by default in Windows, if possible.

Any opinions?

**Comment by UlfNorell** [comment]
I think the best approach is to leave `cpp` as the default, but keep support for `cpphs`. It's a lot more common that people have problems with `cpphs` than that there is an issue with `cpp`. We might not have CI for MacOS, but we do have developers (me at least) using it, so I don't think catching the rare problems is an issue.

**Comment by asr** [comment]
Enough for me.
