### ISSUE TITLE
Constructor overloading question

### ISSUE THREAD

**Issue by tarmouu** [agda/agda#3227]
Hi,

With Agda 2.5.4 (it may have been with earlier versions):

```agda
module _ where

open import Data.Nat as DN
open import Data.Fin as DF

open import Relation.Binary.PropositionalEquality

peano5 : {n m : ℕ} → suc n ≡ suc m → n ≡ m
peano5 refl = refl
```

Agda says:

```
blah.agda:9,8-12
I'm not sure if there should be a case for the constructor refl,
because I get stuck when trying to solve the following unification
problems (inferred index ≟ expected index):
  _5 ≟ _7
when checking that the pattern refl has type _5 ≡ _7
```

The issue is, as one can find out after some messing, that 
Agda does not know if DN.suc or DF.suc is meant 
in the type of peano5, although we have said n m : ℕ 
in that very type expression.

One can fix this by writing DN.suc n instead of just suc n.

Is this right or should constructor overloading work a little 
better?

Thanks.

Tarmo U

**Comment by gallais** [comment]
At the moment the [disambiguation](https://github.com/agda/agda/blob/8f0447b55a4c415417257381b8418a6c3dcca8c8/src/full/Agda/TypeChecking/Rules/Application.hs#L740) only cares about the shape of the type pushed *onto* the
constructor (that's why adding a type annotation using [the standard library's `_∋_`](https://agda.github.io/agda-stdlib/Function.html#3061) also gets
Agda to make the right choice).

One could make the case that we could also look at the type of the arguments passed and
see whether that roots out all but one candidate.

**Comment by nad** [comment]
This issue comes up relatively often. I seem to recall that @UlfNorell stated that it might be expensive to do what @gallais suggests.

**Comment by UlfNorell** [comment]
It's complicated by implicit argument/lambda insertion. It might be possible to do something, but I'm not sure what a principled thing would be (that isn't *try to type check all candidates*, which could get exponentially expensive).

**Comment by JacquesCarette** [comment]
I was under the (potentially very naive) impression that matita had a principled way to deal with disambiguation that would apply here?

**Comment by andreasabel** [comment]
Maybe the common uses could be disambiguated with some form of _approximate typing_ that rules out the bad candidates.  In the present case, we have `suc n` with candidates
```agda
Nat.suc : Nat -> Nat
Fin.suc : {m : Nat} -> Fin m -> Fin (suc m)
```
All we need to know to disambiguate here is that `n` cannot have type `Fin _`.  We need to do an approximate type inference for `n` and trigger a mismatch of its type with `Fin _`.   My hunch would be that by being approximate enough we can keep the extra cost for disambiguation in check, at least for shallow constructor terms like `suc n`.  
It is less clear what should be done about nested ambiguous constructor applications such as `suc (suc (suc n)))`.  If we naively invoke the procedure I described, we get into quadratic behavior.  When trying to disambiguate the outermost constructor, we need to infer the type of `suc (suc n)` which involves disambiguating those constructors.  If we do not remember these disambiguations, we need to them again when checking the subterm `suc (suc n)`.  But currently, we have no facility to store disambiguations other than constructing the internal syntax (which has disambiguated constructors) from the abstract syntax (which has ambiguous constructors) after successful type checking.

Maybe the following approximate type system could be implemented to aid disambiguation:
1. There is a simple type system featuring data and record type names as base types, visible simple function types, a base type standing for a sort, and a base type standing for something unknown or something that cannot be expressed in the simple type system.
2. There is a function computing the simple type of a dependent type.  Types blocked on a meta or neutral types will simply be the `Unknown` simple type.
3. The signature stores simple types for all defined symbols. The simple types are computed at the end of mutual blocks, when metas are frozen.  This makes simple types relatively stable (otherwise, they would have to be refined whenever metas are solved). Of course, that means that during checking a mutual block, simple types for the new symbols are not yet available, and constructor disambiguation is weaker. 
4. There is a function to infer the simple type of a piece of abstract syntax. Only visible arguments are considered.  As a first implementation, a bidirectional simple type checking algorithm should suffice (we might implement ML type inference later). We need to have a simple typing context for this, which for reasons of performance should be computed lazily from the real, dependently typed context.  
5. The function inferring the simple type of an expression might disambiguate some constructors there, thus, the modified expression will be returned as well.

**Comment by nad** [comment]
The problem in the OP is somewhat confusing, and annoying, and comes up fairly often, so I think it makes sense to try to solve it, perhaps even imperfectly. However, still I  wonder if your suggested approach isn't too complicated.

**Comment by UlfNorell** [comment]
I prefer complicated over ad-hoc. Also I have a feeling type approximations might be useful in other places, like compiler optimisations.
