### ISSUE TITLE
Internal error at src/full/Agda/TypeChecking/Reduce.hs:148

### ISSUE THREAD

**Issue by omega12345** [agda/agda#3256]
While in the folder Weird, run
agda ImportTests/ExtractFunction.agda --allow-unsolved-metas

[Weird.zip](https://github.com/agda/agda/files/2452833/Weird.zip)

**Comment by fredrikNordvallForsberg** [comment]
Smaller test case:

File `A.agda`:
```agda
module A where

open import B
```

File `B.agda`:
```agda
{-# OPTIONS --allow-unsolved-metas #-}

module B where

f : (a : Set) -> a -> a
f a y = {!!} y
```

Loading `A.agda` (with Agda version 2.6.0-bc7c0b1) gives
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Reduce.hs:149
```

**Comment by andreasabel** [comment]
The bug must be newer than 2017-11-05 (the date of my last compilation of Agda-2.5.4 on the current machine).

**Comment by andreasabel** [comment]
Introduced by 9d6a6540aa4abb45b07f37d08dfc10e5dd340b4e in the context of adding `MetaS` to the `Sort`syntax.
`instantiate (MetaS x es)` calls `instantiate (MetaV x es)` and expects to get either a `Sort`or a `MetaV`, but apparently in this case it is something else, maybe a `Lam` or a neutral.
@jespercockx ?

**Comment by jespercockx** [comment]
`--allow-unsolved-metas` turns unsolved metas into postulates, including unsolved sort metas. However, there is no way to actually represent a postulated sort in the internal syntax, so Agda crashes.

One way to fix this, is to add postulated sorts to Agda (at least in the internal syntax). But this seems like a lot of work for the purpose of just making `--allow-unsolved-metas` work, especially since turning unsolved metas into postulates seems like a bit of a hack in the first place. Perhaps we could instead qualify metavariables with the module in which they were created, so we don't need to turn them into postulates at all?

**Comment by jespercockx** [comment]
Fixed by adding a constructor for postulated sorts. Things to think about in the future:

- Should `--allow-unsolved-metas` work as it does now (turning metas into postulates) or should we preserve metas as-is?
- Should we merge the `Sort` datatype into the `Term` datatype to get rid of the duplication between the constructors (`MetaS` and `MetaV`, `DefS` and `Def`, `DummyS` and `Dummy`, ...)?

**Comment by Saizan** [comment]
>     * Should we merge the `Sort` datatype into the `Term` datatype to get rid of the duplication between the constructors (`MetaS` and `MetaV`, `DefS` and `Def`, `DummyS` and `Dummy`, ...)?

Maybe `Sort' t` should have a single constructor `TermS :: t -> Sort' t`, replacing `MetaS`, `DefS`, and `DummyS`.
Compared to just merging `Sort` and `Term`, this solution would make it easier to write functions that mostly want to work with "canonical" sorts.

**Comment by jespercockx** [comment]
That would introduce a new invariant that has to be maintained, namely that the term inside a `TermS` should not itself be a `Sort`. I think it would be better to just merge everything in a flat structure and have a separate view type for when one wants to focus on canonical sorts.
