### ISSUE TITLE
--without-K inconsistency

### ISSUE THREAD

**Issue by ice1000** [agda/agda#3265]
Ref: https://cs.stackexchange.com/q/98460/79971

Code:

```agda
{-# OPTIONS --without-K #-}
module WithoutK-Test where

open import Data.Nat
open import Relation.Binary.PropositionalEquality

kksk : ∀ a → a ≡ ℕ → ℕ
kksk .ℕ refl = zero

kksk-wtf : ℕ ≡ ℕ → ℕ
kksk-wtf = kksk ℕ

kksk-why : ℕ ≡ ℕ → ℕ
kksk-why refl = zero
```

(Depends on agda-stdlib)

`kksk-why` doesn't check while `kksk-wtf` checks.

**Comment by jespercockx** [comment]
I don't understand why this is confusing: `kksk-why` is matching on `refl` of type `ℕ ≡ ℕ` so it's rejected (since there can be other proofs besides `refl` in HoTT), while `kksk-wtf` does no matching so it is accepted. Can you explain why you think this is inconsistent?

**Comment by ice1000** [comment]
I'm just confused: the prohibited pattern matching (`kksk-why`) can be done indirectly (`kksk-wtf` with `kksk`). IMO it's fine to pattern match `ℕ ≡ ℕ` with `refl` (since it's [accepted in Coq][1]).

 [1]: https://cs.stackexchange.com/a/98509/79971

**Comment by jespercockx** [comment]
I don't know why Coq would accept this definition, but it's definitely not possible to implement `kksk-why` in basic Martin-Löf type theory with just the `J` eliminator for the identity type, which is (roughly) the guideline I used for implementing `--without-K` (see my [thesis](https://jesper.sikanda.be/files/thesis-final-digital.pdf) for more details). If Coq goes beyond that, then that's some peculiarity of the Coq theory. I think the main use case for `--without-K` is when you care particularly about compatibility with (extensions of) basic MLTT, so I would be hesitant to add some feature that goes beyond it just because Coq does the same.

**Comment by ice1000** [comment]
I think I understand this. Even under the context of `kksk-wtf`, I can do nothing with the matched `refl` on `ℕ ≡ ℕ` (while in `kksk-why`, you can), because such matched result is inside the context of `kksk`, which does not know about the type parameter `a`, is that correct?

**Comment by ice1000** [comment]
It now makes sense to me.
