### ISSUE TITLE
Better error message when C-c C-m is used to declare or define something

### ISSUE THREAD

**Issue by nad** [agda/agda#3316]
I suggest that some kind of informative error should be raised when commands like `declareDef` or `defineFun` are invoked (directly or indirectly) by `agda2-elaborate-give`. At the moment you can get some not very informative errors:
```agda
module Example where

open import Agda.Builtin.List
open import Agda.Builtin.Reflection

macro

  easy : Term → TC _
  easy t =
    bindTC (freshName "A") λ A →
    bindTC (declarePostulate (arg (arg-info visible relevant) A)
                             (agda-sort (lit 0))) λ _ →
    unify (def A []) t

B : Set
B = {!easy!}
```
```
Parse error
;<ERROR>
Example.A...
```

**Comment by halfaya** [comment]
This is not really specific to `agda2-elaborate-give` since the intention is to give exactly the same feedback as you'd get if you entered the term manually, and if you insert `;Example.A` into the hole you'll get the identical error message, so perhaps that error message (and anything related) needs to be improved.

Incidentally what is the meaning of the ; prefix? It seems it was added recently but I don't know for what purpose--is it documented somewhere?

**Comment by halfaya** [comment]
One possible improvement for `C-c C-m` might be to display the raw term generated along with the error message, since that would give some extra context to help the user interpret the message. The raw term is would be what is displayed by `C-c C-;`.

**Comment by nad** [comment]
> Incidentally what is the meaning of the ; prefix? It seems it was added recently but I don't know for what purpose--is it documented somewhere?

See #3127.

**Comment by jespercockx** [comment]
Current error message:
```
Not in scope:
  Issue3316.A
```
Does this seem acceptable @nad?

**Comment by nad** [comment]
Yes, I think so.
