### ISSUE TITLE
Pattern matching out of Prop to a Set, but as an irrelevant function

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#3325]
I expected it to be possible to pattern match out of a `Prop` into a `Set` when the function is tagged as being irrelevant, but I am not sure how `Prop` and irrelevance are supposed to interact so I may be wrong.

```agda
{-# OPTIONS --prop #-}

postulate
  A : Set
  a : A

data Unit : Prop where
  tt : Unit

.f : Unit → A
f tt = a
```
```
Cannot split on argument of irrelevant datatype Unit
when checking the definition of f
```

**Comment by jespercockx** [comment]
It's not possible to construct a value of type `Squash (Unit -> A)` that pattern matches on the `Unit` (where `Squash : Set -> Prop` is defined as usual). Since I usually think of top-level irrelevant definitions as 'squashed values', I think your definition here should likewise not be accepted. Unless you have a strong argument why it should be?

**Comment by guillaumebrunerie** [comment]
I don’t have any strong argument for it. I have now looked at your POPL'19 paper and I understand better why it makes sense to reject it.

**Comment by asr** [comment]
@jespercockx, please add the label `status: working-as-intended`.
