### ISSUE TITLE
Attempting to comment out a pragma doesn’t do the right thing

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#3329]
If I select a pragma like `{-# BUILTIN EQUALITY _≡_ #-}` in Emacs and try to comment it out using `M-;`, it removes the `{-…-}` around it leaving `# BUILTIN EQUALITY _≡_ #`, which is certainly not the expected behaviour. It should add `-- ` in front of it instead.

**Comment by nad** [comment]
I don't think the Emacs syntax table is expressive enough to represent Agda's lexical syntax (where `{-` starts a comment, but only if it is not followed by `#`).

How do Haskell modes handle this?

**Comment by UlfNorell** [comment]
Maybe someone that uses Emacs to write Haskell code could investigate? @nad @jespercockx @andreasabel ?

**Comment by fredrikNordvallForsberg** [comment]
[haskell-mode](https://github.com/haskell/haskell-mode) version 16.1 fails in the same way as described above.

**Comment by nad** [comment]
We could presumably override the Emacs procedures related to comments, but the cost-benefit ratio seems way too high to me. I see two ways forward:
* We decide not to fix this.
* We remove the `{-`/`-}` syntax from the Emacs syntax table, so that (this part of) Emacs only knows about the `--` notation. I am not sure what other consequences this would have, but we could try it out for a while and see what we think.

**Comment by UlfNorell** [comment]
Option 2 seems reasonable to me. I don't think it's a common use case to remove block comments using <kbd>C-c C-;</kbd>.

@nad can you do the experiment and check that it doesn't break highlighting of comments?
