### ISSUE TITLE
Missing Definitions not recognised in instance search

### ISSUE THREAD

**Issue by m0davis** [agda/agda#3338]
While utilising the new nifty Missing-Definitions-now-treated-as-warning feature, I found a problem wrt instance search. In the following code, instance resolution fails (but succeeds if `RI` is given a dummy definition).

```agda
postulate
  R : Set → Set1
  r : {X : Set} {{ _ : R X }} → X → Set
  A : Set
  a : A

instance
  RI : R A
  -- RI = {!!} -- uncommenting lets instance resolution succeed

foo : r a
```
The failure in the type of `foo` is:
```
No instance of type R A was found in scope.
when checking that a is a valid argument to a function of type
{X : Set} ⦃ _ : R X ⦄ → X → Set
```

**Comment by gallais** [comment]
I see. I think the issue is that we should check for lone signatures at the end of each block
introduced by a layout keyword. Shouldn't be too hard to fix if it is indeed the problem.

**Comment by gallais** [comment]
Ok, I can't actually check for lone signatures at the end of an instance block
and turn them into axioms because they may actually receive their definition
later on thanks to the new-style mutual definitions!

Checking at the end of the block renders this kind of code invalid but it currently
is (and the way record declarations are elaborated seems to rely on it as my fix
makes `test/Succeed/Issue2117.agda` fail):

```agda
record A : Set where
  constructor a

instance i : A

b : A
b = a

i = b
```

It's not clear to me what the right move is. I suppose I could try to extract the
hiding info from the thing I'm replacing in `replaceSigs`. I'll have a try after dinner.
