### ISSUE TITLE
Make Emacs mode available as a normal package via MELPA

### ISSUE THREAD

**Issue by mrkkrp** [agda/agda#3360]
The title says it all. All these manual manipulations are not nice if there is a proper package manager and a repo with packages (MELPA).

**Comment by gallais** [comment]
Is this #3234?

**Comment by ice1000** [comment]
@mrkkrp You should first understand that different Agda versions has different agda2-mode for them. You should be aware that if you want to have agda2-mode in melpa you'll need to publish many many agda2-mode at the same time to ensure compatibility.

**Comment by mrkkrp** [comment]
All right, but then it is certainly not very handy. Even proof general is now on MELPA. Perhaps Agda has its own reasons to do things this way...

**Comment by ice1000** [comment]
@mrkkrp The API changes! This is a huge problem.

For me, it's acceptable to create different agda2-mode on melpa for different versions of Agda

**Comment by nad** [comment]
I think it would be great if the Agda mode could be available via MELPA. For some further discussion, see #3234.

**Comment by ice1000** [comment]
Is like to put the input method minor mode on melpa first.

**Comment by jespercockx** [comment]
This is a great idea. I'm assigning `icebox` not because I want to shoot it down, but because this doesn't have to be linked to a specific release of Agda.

**Comment by jappeace** [comment]
https://github.com/melpa/melpa/pull/7080

**Comment by jappeace** [comment]
@ice1000 
Melpa will version this automatically by date:

![image](https://user-images.githubusercontent.com/3874017/90433621-6c1cd300-e0cc-11ea-8a23-8777c1e0d9f0.png)

So if agda upgrades, this repository upgrade, the melpa will also upgrade automatically.
The entry file also contains a revision to whatever agda mode version is being used (for this repository):

![image](https://user-images.githubusercontent.com/3874017/90433734-9a021780-e0cc-11ea-807a-4945d77389cc.png)

So the big gain here is that this probably will work with whatever agda you have on your system, or you have a way of figuring it out, otherwise you can simply choose to not use melpa.
But most users will just get a working setup and forget about upgrading for a year or 2.

**Comment by jappeace** [comment]
This is finished https://github.com/melpa/melpa/pull/7080

I'm available for any questions or concerns on this.
