### ISSUE TITLE
Variable in constructor type is generalized too eagerly

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#3362]
MWE:
```agda
postulate
  A : Set
  P : A → Set

variable
  x : A
  y : P x

data D {x : A} : P x → Set where
  c : D y
```
This gives an error: 
```
y.x != x of type A
when checking the constructor c in the declaration of D
```
If the generalization would be postponed a bit longer, the meta would've been solved and no generalization over `x` would be necessary.

**Comment by xekoukou** [comment]
I have many instances of this problem in my code. I do not know why it does not work. I have to introduce y for it to work like this : 
```
postulate
  A : Set
  P : A → Set

variable
  x : A
  y : P x

data D {x : A} : P x → Set where
  c : {y : P x} → D y

```

In other words, the generalization over ```y``` is useless.

**Comment by UlfNorell** [comment]
The problem is that we check the constructor target (i.e. that `c` returns something of type `D {x} _`) outside the generalization. Before we do, the `x` argument is unsolved and thus gets generalized over.

**Comment by jespercockx** [comment]
Maybe we could add a new constraint kind that forces something to be a pi type ending in an application of the datatype? IIUC variables are not generalized if they are still mentioned in a constraint.

**Comment by andreasabel** [comment]
Generalization has already conditioned me to give up on data type parameters, and only use indices.  This works:
```agda
postulate
  A : Set
  P : A → Set

variable
  x : A
  y : P x

data D : ∀ {x : A} → P x → Set where
  c : D y
```
The problem is that generalization in the indices of a data signature is not supported, ideally I would like to write:
```agda
data D : P x → Set where
  c : D y
```
But I get the error:
```
Generalizable variable Issue3362.x is not supported here
when scope checking x
```
To solve the issue with generalization in parameters vs. generalization in indices, I am in favor to move towards Idris-style data, that is, fade out data parameters and do more serious forcing that also removes forced constructor arguments at compile time (with code to reconstruct them from the type).
This thinking about whether a data type argument should be an index or a parameter is anyway distractive.  (It is like programming in x86 where you had to think whether a local variable could be kept in a register or be stack-allocated.) 
Parameters for succinctness can be abandoned once generalization is working reliably.
For now, we need parameters for efficiency reasons, but if we do type-checking time forcing, we can dispose of them.

**Comment by UlfNorell** [comment]
I don't think we should use this issue as an excuse to embark on serious language changes. I expect it's reasonably straightforward to move the parameter check inside the generalization.
