### ISSUE TITLE
Update GitHub linguist syntax highlight file

### ISSUE THREAD

**Issue by ice1000** [agda/agda#3365]
We're continuously adding new syntax, but GitHub's syntax highlight doesn't know about that.

```agda
-- wrong
postulate
  A : Set
  f : a == b
variable a : A
postulate b : A

-- correct
data A
```

Highlighting for `==`, `postulate`, `b`, `a` and `variable` is wrong.

I'm opening an issue to collect similar issue, please comment to add more. Maybe I'll PR the linguist repo someday.

**Comment by ice1000** [comment]
Also, I want to add special highlights for built-in names like `Set`, `Prop` too

And non-built-in but very usual names like `Nat`, `Size`, `Size<`, `Bool`, `Int`, `List`, etc.

**Comment by brunoczim** [comment]
Quoting from [here](https://github.com/mokus0/Agda.tmbundle/issues/2)
> with is also a keyword and is not highlighted.

**Comment by guillaumebrunerie** [comment]
The `instance` keyword should be highlighted as well.

I looked at the instructions to update the syntax highlighting, and apparently the highlighting is taken from this repository: https://github.com/mokus0/Agda.tmbundle which hasn’t been updated since 2011…
Maybe there should be a more official repository (i.e. under `github.com/agda`) containing the Agda syntax highlighting instead? I couldn’t really figure out the format though, it seems to be a TextMate grammar, but I’m not sure how it is being generated/written.

**Comment by guillaumebrunerie** [comment]
I figured out how to write grammars, and I rewrote a grammar for Agda from scratch (taking some inspiration on https://github.com/mokus0/Agda.tmbundle). It is available at https://github.com/guillaumebrunerie/agda-syntax-highlighting.

You can try it on arbitrary code at https://github-lightshow.herokuapp.com/, just choose "URL of grammar file" and put https://github.com/guillaumebrunerie/agda-syntax-highlighting/blob/master/Agda.tmLanguage in the first field, and then you can either write/copy-paste some code, or provide any URL to an Agda file.

There are a couple of improvements over the previous grammar, in particular:
- new keywords are properly highlighted
- `Set`/`Prop` are highlighted differently from the rest
- in `data A`, the word `A` does not have the same color as the keyword `data`
- goals are colored green
- the grammar is in a more readable format (see `Agda.yml`) and should be easier to update when needed

Please try your favorite files and let me know if there are issues that should be fixed!

Known issues so far:
- if a fixity declaration spans several lines, the identifiers on the first line are purple and the others are black (I could easily make them all black instead, as it is currently, if it is deemed better)
- I tried to color function definitions, i.e. in
```agda
test : A -> B
test a = x
```
have both `test`s colored purple (currently only the first one is colored purple). But even though it works in many cases, it does not work for infix symbols and copatterns definitions, where it colors the first word instead of coloring the thing being defined. It's quite tricky to figure out what is the thing being defined via regexps when it’s not the first word on the line…


I could theoretically already open a pull request to the linguist repository so that they use this grammar file instead, but I feel like it would be better if the grammar were in a repository in `github.com/agda/…` instead, so that it would be more official, and so that other Agda developers could contribute to it as well.

So, if the main developers agree, could a new repository be created to host this syntax highlighting for GitHub?

**Comment by UlfNorell** [comment]
You should be able to create the repository under `agda/` yourself.

**Comment by guillaumebrunerie** [comment]
I created the repository (`agda/agda-github-syntax-highlighting`).

I will wait a couple of days in case anyone here has an objection or find issues that need to be fixed, and then I will open the pull request to the `linguist` repository. It’s always possible to fix additional issues afterwards, of course.

**Comment by guillaumebrunerie** [comment]
There does not seem to be any objections here, so I’ve open the pull request.
If it is accepted by the people at linguist (which I guess is likely), then the changes will automatically be applied to all Agda files on GitHub when the next version of linguist is released/deployed (approximately once a month but can be more irregular).

**Comment by ice1000** [comment]
\o/
