### ISSUE TITLE
Irrelevance and with

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#337]
What's the problem?
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Rules/Term.hs:469
```
```agda
module Bug where

data ℕ : Set where
  zero : ℕ
  suc  : (n : ℕ) → ℕ

{-# BUILTIN NATURAL ℕ    #-}
{-# BUILTIN ZERO    zero #-}
{-# BUILTIN SUC     suc  #-}

data _≡_ {A : Set}(x : A) : A → Set where
  refl : x ≡ x

postulate
  _≤_ : ℕ → ℕ → Set
  p₁  : 0 ≤ 1
  p₂  : 0 ≤ 1

data SList (bound : ℕ) : Set where
  []    : SList bound
  scons : (head : ℕ) →
          .(head ≤ bound) →
          (tail : SList head) →
          SList bound

l₁ : SList 1
l₁ = scons 0 p₁ []

l₂ : SList 1
l₂ = scons 0 p₂ []

l₁≡l₂ : l₁ ≡ l₂
l₁≡l₂ with _
... | _ = refl
```

What version of Agda are you using?

Current darcs version.

Original issue reported on code.google.com by `stevan.a...@gmail.com` on 28 Sep 2010 at 11:29

**Comment by andreasabel** [comment]
7 years later:  Since `with` is no longer implemented by going through printing to abstract syntax, irrelevant terms should not be needed now to make `with` work. We have to be careful about the _should_ however, since `with`-abstraction is not type-based, thus, abstracting in the presence of erasure might be too greedy, i.e., abstracting terms that have the wrong type.
