### ISSUE TITLE
HITs: clause compiler does not handle inserted missing hcomp clause

### ISSUE THREAD

**Issue by potato4444** [agda/agda#3378]
```agda
{-# OPTIONS --cubical #-}

module bugreport-1 where

open import Agda.Builtin.Cubical.Path

data Interval : Set where
  pos : Interval
  neg : Interval
  zeroes-identified : pos ≡ neg 

bad : Interval → Interval → Interval
bad pos pos = ?
bad neg pos = ?
bad (zeroes-identified i) pos = ?
bad x neg = {!!}
bad x (zeroes-identified j) = {!!}
```
I first arrived at this error by case splitting on the second argument followed by the first. This error happens both in the emacs mode and on the command line.

This is a minimization of from me trying to define addition on HIT integers.

agda version: 2.6.0-a40792b

**Comment by potato4444** [comment]
Possibly related to #3314, If I do my case splitting in the opposite order I trigger that bug.

**Comment by andreasabel** [comment]
Sigh, are we still using the partial function `Prelude.!!`?? There is `Agda.Utils.List` with safe functions like `(!!!)`, 
https://github.com/agda/agda/blob/a40792bbab282c7579cd8b778f0f5375d60a12ad/src/full/Agda/Utils/List.hs#L87-L88
and I am adding `indexWithDefault` for uses like 
```haskell
indexWithDefault __IMPOSSIBLE__ xs i
```

**Comment by andreasabel** [comment]
The exception is thrown in the coverage checker here:
https://github.com/agda/agda/blob/a40792bbab282c7579cd8b778f0f5375d60a12ad/src/full/Agda/TypeChecking/Coverage.hs#L228-L233

**Comment by gallais** [comment]
> Sigh, are we still using the partial function `Prelude.!!`??

Should we think about using `hlint` with [ad-hoc hints](http://community.haskell.org/~ndm/darcs/hlint/hlint.htm#customization) focusing on partial functions?

**Comment by asr** [comment]
> Should we think about using `hlint` with [ad-hoc hints](http://community.haskell.org/~ndm/darcs/hlint/hlint.htm#customization) focusing on partial functions?

+1

(You can run `make hlint` for running `hlint` without any customisation)

**Comment by andreasabel** [comment]
I think `hlint` would be useful, but only if it just gives the relevant warnings;  thus, we need a customization tailored to our needs.
I once tried hlint with the emacs-integrated refactoring facility on Agda, but this just revealed that that tool is not up to speed for realistic Haskell software products such as Agda.

**Comment by andreasabel** [comment]
This bug is really an instance where you would want dependent types to prevent it in the first case.  The set `noex` is a set of indices into the list of clauses `cs`.  With dependent types, this could be checked by the compiler.
What happens here is that this code
https://github.com/agda/agda/blob/2c4da0841d38a8c6af0083de3e635bac958168bc/src/full/Agda/TypeChecking/Coverage.hs#L341-L346
seems to add elements ("missing hcomp clauses") to `cs` locally which do not get propagated back.  As a consequence, the indices into these local, extended copies of `cs` become invalid as we return from `cover`. 
One way to address this could be to add the hcomp clauses also to the signature and reread `cs` from the signature upon return from `cover`.
UPDATE: this way did not work since it interferes with clauses inserted for instance fields, which would then be reported as unreachable.  Instead, I just ignore non-exact split warnings for added hcomp clauses.

**Comment by andreasabel** [comment]
The OP now crashes in the clause compiler.
This issue needs help of an expert, @Saizan .

**Comment by jespercockx** [comment]
@Saizan is this fixed now? Can you add a test case?

**Comment by ice1000** [comment]
Dunno if it's related:

```agda
open import Agda.Primitive.Cubical
open import Agda.Builtin.Cubical.Path renaming (_≡_ to _==_)
open import Agda.Builtin.Nat
  renaming (_==_ to _:==:_; _+_ to _:+:_; _*_ to _:*:_)

infixl 7 _÷_
data Q : Set where
  _÷_    : (a b : Nat) -> Q
  reduce : ∀ a b c     -> a ÷ b == (a :*: c) ÷ (b :*: c)

someTest : 2 ÷ 1 == 4 ÷ 2
someTest = reduce 2 1 2

_+_ : Q -> Q -> Q
(ax ÷ bx) + (ay ÷ by) = ?
(ax ÷ bx) + reduce ay by cy y = ?
reduce ax bx cx x + y = {!!}
```

Agda throws:

```
The result type is non-fibrant when generating hcomp clause: {φ :
I} (_ : I → Partial φ Q) (_ : Q) → Q
when checking the definition of _+_
```

**Comment by potato4444** [comment]
@ice1000 That is the #3314 that I mentioned at the start of the issue thread
