### ISSUE TITLE
Adding a tutorial set in the readthedocs frontpage

### ISSUE THREAD

**Issue by ice1000** [agda/agda#3379]
**Apart from language reference**,
Idris has this: http://docs.idris-lang.org/en/latest/tutorial/
But Agda only has: https://agda.readthedocs.io/en/latest/getting-started/

To be more new-comers-friendly, we may add a `tutorial` section as the front page of https://agda.readthedocs.io and put links like https://plfa.github.io/ https://people.inf.elte.hu/divip/AgdaTutorial/Index.html and add our own language tutorial

**Comment by ice1000** [comment]
Maybe me and @lwoo1999 have some interest on this.

**Comment by gallais** [comment]
We have a longer list of existing tutorials (some may be outdated now) on the wiki:
http://wiki.portal.chalmers.se/agda/pmwiki.php?n=Main.Othertutorials

**Comment by ice1000** [comment]
We should put them on the readthedocs site

**Comment by ice1000** [comment]
A friend just told me he considers Idris more new-comers-friendly because:

+ Idris doesn't use Unicode
+ Idris has a tutorial, while Agda's "tutorial" (it's actually the language reference) is hard to understand

These are all false-positive! 0. Agda **can** be used without any Unicode; 1. Agda has a lot of tutorials.
We should do something to stop them from thinking that way.

**Comment by xekoukou** [comment]
I personally first read the idris tutorial and then the brutal introduction to Agda by Jan Malakhovski.

I think that we need to look at the incentives of those that will want to maintain such a tutorial. I think  the best bet would be to create a tutorial / introduction that can at the same time be used as lecture notes. It would be a collaborative effort instead of each person writing his own lectures that become obsolete as the language changes.

**Comment by jespercockx** [comment]
There are already a few options for people wanting to learn Agda: there's Aaron Stump's Verified Functional Programming in Agda (https://dl.acm.org/citation.cfm?id=2841316), and Phil Wadler's Programming Language Foundations in Agda (https://plfa.github.io/Preface/). There's also a list of other tutorials on the wiki (http://wiki.portal.chalmers.se/agda/pmwiki.php?n=Main.Othertutorials), some of which may be outdated.

What the 'right' tutorial is depends a lot on one's personal motivation for learning Agda, so I'd rather give people a list of good options to choose from rather than one 'official' tutorial that's supposed to work for everyone. That maintaining a list is significantly less work is a nice bonus :)

**Comment by ice1000** [comment]
I agree. I'd like to create a list on the readthedocs site.

**Comment by ice1000** [comment]
Some useful scripts:

```js
.split("\n").map(_=>_.replace(
    /([^\[]+)\[\[([^\|]+)\|([^\]]+)\]\]([^]+)/,
    (xxx, yyy, b, c, d) => `- \`${c.trim()} <${b}>\`_
  ${d}`)).join("\n")
```

**Comment by asr** [comment]
I'm getting the following error:

```bash
$ make user-manual-html
...
Running Sphinx v1.7.0
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 57 source files that are out of date
updating environment: 57 added, 0 changed, 0 removed
reading sources... [100%] tools/package-system                                                                                                        

Warning, treated as error:
.../doc/user-manual/getting-started/tutorial-list.rst:5:Duplicate explicit target name: "dependently typed programming in agda".
Makefile:53: recipe for target 'html' failed
```

**Comment by ice1000** [comment]
I've just figured out how to install sphinx locally, will fix soon

**Comment by asr** [comment]
Now, I'm getting the error:

```bash
$ make fix-whitespace
...
Whitespace violation fixed in .../doc/user-manual/getting-started/tutorial-list.rst.
```
