### ISSUE TITLE
No error if mapping the empty type to non-empty Haskell type

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#3409]
Compiles without issue
```agda
data Empty : Set where
{-# COMPILE GHC Empty = data Bool () #-}
```
The cover function we generate to make ghc check that the types match is
```haskell
cover2 :: Bool -> ()
cover2 x = ()
```
which is clearly not right. For reference, if we have one constructor we get
```haskell
cover2 :: Bool -> ()
cover2 x =
  case x of
    True -> ()
```
We should turn on `{-# LANGUAGE EmptyCase #-}` and generate
```haskell
cover2 :: Bool -> ()
cover2 x = case x of {}
```

This led to user confusion in #3408.

**Comment by GregoryMorse** [comment]
Thank you very much for the reply there.  But now I cannot compile because I get endless kind errors - I have not seen any examples of how to deal with data type constructors which have kinds but must be postulated as Set.  The manual mentions this for type class instances via a dictionary method.

`    * Expecting one more argument to `T14'
      Expected a type, but `T14' has kind `* -> *'
    * In the type signature:
        d555 :: Bool
                -> T14 -> MAlonzo.RTE.Infinity AgdaAny MAlonzo.Code.IO.T6
     |
1148 |   Bool -> T14 -> MAlonzo.RTE.Infinity AgdaAny MAlonzo.Code.IO.T6
     |           ^^^`

In fact I had done exactly as you had suggested at first but I did not realize the encapsulated part just needed to be totally forgotten about - I tried to start moving as much Haskell code into Agda as I said to try to get down to purely foreign imports.  But all of the special hash tag terminated internal types and such cannot really be eliminated either.  There is a limit as to where such a task can go - and I think these are the magic hash unboxed types and foreign imports.

**Comment by GregoryMorse** [comment]
At this moment I am unsure if this can be done with type synonyms - its impossible to parameterize them in Agda and I cannot even find a trick to use lambdas to jacket the Haskell function calls when this involves the return values.

**Comment by UlfNorell** [comment]
Let's move this to #3408.

**Comment by nad** [comment]
Move what? Was there some comment here that was moved to another issue?

**Comment by nad** [comment]
@UlfNorell, it says that you deleted one of my comments. I have no idea what I wrote, or why it was deleted. There does not seem to be any history for deleted comments, so it is perhaps better to use the "Edit" functionality.

**Comment by UlfNorell** [comment]
You were confused about the discussion of #3408 being moved to that issue instead of taking place here. I didn't consider that important enough to preserve for posteriority, but here is what you wrote: 

> Move what? Was there some comment here that was moved to another issue?
