### ISSUE TITLE
No highlighting for code that fails termination checking when an error is encountered

### ISSUE THREAD

**Issue by nad** [agda/agda#3417]
Consider the following code:
```agda
A : Set
A = A

B : Set
B = Set
```
Agda rejects this code:
```
———— Warning(s) ————————————————————————————————————————————
[...]/Bug.agda:1,1-2,6
Termination checking failed for the following functions:
  A
Problematic calls:
  A (at [...]/Bug.agda:2,5-6)
———— Error —————————————————————————————————————————————————
[...]/Bug.agda:5,5-8
Set₁ != Set
when checking that the expression Set has type Set
```
However, the problematic call in `A` is not highlighted as such in Emacs. (I tried using both non-interactive and interactive highlighting.)

**Comment by gallais** [comment]
This is strange: if I throw in extra definitions then *at some point*, I start getting
highlighting for the first batch.

E.g. with the following code I get highlighting for the termination warnings in
A, B, and C but not D.

```agda
A : Set
A = A

B : Set
B = B

C : Set
C = C

D : Set
D = D

_ : Set
_ = Set
```

**Comment by andreasabel** [comment]
The same problem exists for positivity warnings.  In the following case, neither termination nor positivity issues are highlighted.
```agda
A : Set
A = A

data D : Set where
  abs : (D → D) → D

_ : Set
_ = Set
```
I do not fully understand the problem, but my hunch is that it has to do with the fact that termination and positivity warnings are only highlighted when we successfully check the next declaration (since these checks run after the type-checking which ends with highlighting the type-checked stuff).

It seems clearer if we directly generate the highlighting info when issuing a `warning`.  This might also help with #4348.
