### ISSUE TITLE
More lambda expressions could have their type inferred in applications.

### ISSUE THREAD

**Issue by caryoscelus** [agda/agda#3478]
```agda
-- rejected by default, but accepted by refine/give with --cubical
give-anything-cubical : ⊥
give-anything-cubical = {!(λ x → tt) tt!}

-- accepted by refine/fill
give-anything-extended : ⊥
give-anything-extended = {!(λ { tt → tt }) tt!}

-- this can also fill a hole
extended-λ-isn′t-checked : ⊥
extended-λ-isn′t-checked = {!(λ { tt → tt ; false → tt }) 1!}

empty-λ-is-fine-too : ⊥
empty-λ-is-fine-too = {!(λ ()) tt!}
```
All of these fail on reload with standard "Failed to solve the following constraints" message (even though some can seemingly be rejected on other basis)

Not sure whether it's related to #625 or not, but it seems to be much more specific case. Also might be related to #2515 / #2519, although those don't seem to be about holes.

(Using current master (98d6f195fe672e54ef0389b4deb62e04e3e98327) with a few unrelated changes)

**Comment by Saizan** [comment]
This is working as intended, but there could be improvements.
In particular, `give/refine` does not try to rule out unsolved constraints, since in many cases those will get solved by further `give/refine` calls (e.g. filling in an implicit argument or giving a type annotation).

applied lambdas fall outside of bidirectional typechecking so Agda won't do a great job with them. In general the problem is figuring out the intended codomain of the function type, especially how it depends (if at all) on the input.

In the cases above the code is specific enough that more could be inferred, though I don't know how easy it would be to change the typechecker to do so.

**Comment by andreasabel** [comment]
In general, beta-redexes like `(\ x -> t) u` are not type-checked by Agda.
However, it sometimes works by expanding them to `case u of \ x -> t` using the `case_of_` combinator from the standard library module `Function`.

**Comment by caryoscelus** [comment]
Ok, thanks for explanation.

> In general, beta-redexes like (\ x -> t) u are not type-checked by Agda.

I wonder if it would be possible to add custom warning for it. Something along the lines of "annotate lambda argument types or use case_of_" (neither would work for path lambda application though, but at least it would show basic direction of amending the issue; and writing caseI_of_ is trivial)

**Comment by jespercockx** [comment]
`case_of_` is a library function and not a language construct, so it would be a bit funny to see it in an error message if you're not using the standard library.

**Comment by caryoscelus** [comment]
I think it is small enough to include its definition in the message. Otherwise, general mechanism can be described
