### ISSUE TITLE
Elaborate-and-give shouldn't reduce solution

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#3486]
Test case:
```agda
open import Agda.Builtin.Unit
open import Agda.Builtin.List
open import Agda.Builtin.Reflection

id : {A : Set} → A → A
id x = x

macro
  tac : Term → TC ⊤
  tac hole = unify hole (def (quote id) (arg (arg-info visible relevant) (var 0 []) ∷ []))

test : {A : Set} → A → A
test x = {!tac!}
```
When running elaborate-and-give (C-c C-m) the hole is filled in with `x`, but it should be filled in with `id x` instead. 

In my real example I had an application of `case x of f`, which definitely should not be reduced to `f x` because that results in unsolved metas.

**Comment by nad** [comment]
Elaborate-and-give has not been released yet, so I suggest that this issue is fixed before this new feature is released.

**Comment by jespercockx** [comment]
The problem seems to be the automatic inlining -- if I add `{-# NOINLINE id #-}` then I get the expected result. So at least there's a workaround for the problem. Now the question is whether we should disable inlining during elaborate-and-give or leave the situation as it is:

- On one hand the specification of the command is just 'run the typechecker and print whatever the result is in the buffer', so if inlining is part of typechecking then we should do that as well.
- On the other hand the current behaviour is quite unintuitive since there's no way to tell that a particular function will be inlined or not (apart from putting an explicit pragma).

I'm thinking we should disable the inlining during elaborate-and-give. Anyone else has an opinion?

**Comment by nad** [comment]
What is the purpose of automatic inlining?

**Comment by jespercockx** [comment]
I guess for the purpose of compilation inlining certain definitions makes sense since it can be more efficient or result in smaller code (especially when not all arguments are used). I'm not sure why it's done also at typechecking time but I guess the reasons are similar.

**Comment by gallais** [comment]
I had a look at it and the Haskell code looks alright to me: it takes a `Rewrite`
argument and respects it when normalizing the term elaboration produces.

I think the problem comes from `agda-mode`:

* `agda2-elaborate-give` is defined using `agda2-maybe-normalised`
* [`agda2-maybe-normalised`](https://github.com/agda/agda/blob/fd533f1d3f20474acaf402383910a96ee129f194/src/data/emacs-mode/agda2-mode.el#L1259) interprets (just like `agda2-maybe-normalised-toplevel`):
  + no prefix as `Simplified`
  + `C-u` as `Instantiated`
  + `C-u C-u` as `Normalised`

In comparison:

* `agda2-maybe-normalised-global` (which is only used for `solveAll`) interprets:
  + no prefix as `AsIs`
  + `C-u` as `Simplified`
  + `C-u C-u` as `Normalised`

and its documentation is wrong, copy/pasted from `agda2-maybe-normalised`.

**Comment by gallais** [comment]
Just realised I could test the `AsIs` behaviour by putting a test case
in `test/interaction` with the following `Issue3536.in`:

```
top_command (cmd_load currentFile [])
goal_command 0 (cmd_elaborate_give AsIs) "tac"
```

And Agda does indeed generate only `x` even if we use `AsIs`. :/

**Comment by jespercockx** [comment]
This is not really a critical bug and there's an easy workaround, so I'm bumping it to 2.6.1

**Comment by jespercockx** [comment]
This issue is now fixed since the auto-inlining features has been removed. I'll add a test case.
