### ISSUE TITLE
Internal error src/full/Agda/TypeChecking/Rules/LHS.hs:294 after pattern matching

### ISSUE THREAD

**Issue by SimonBoulier** [agda/agda#3491]
Tested with Agda version 2.6.0-1a06536 (9 January 2019).
```agda
data _≡_ {ℓ}{A : Set ℓ} (x : A) : A → Set ℓ where
  refl : x ≡ x


record Box (B : Set) : Set₁ where
  constructor box
  field
    unbox   : B
open Box public


=box :{B : Set}{Γ₀ Γ₁ : Box B} → _≡_ {A = B} (unbox Γ₀) (unbox Γ₁) → Γ₀ ≡ Γ₁
=box {b} {box unbox} {box unbox'} p = ?
```
In the previous it is okay to use `unbox` as variable name even if it is the name of a projection. But when we do C-c C-c on `p` we get:
```agda
=box {b} {box unbox} {box .unbox} refl = ?
```
and this produces an error:
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Rules/LHS.hs:294
```

**Comment by gallais** [comment]
I have a potential fix (in the Abstract to Concrete translation) which prints
`A.DotP i (A.Var v)` as `.(v)` whenever `v` also happens to correspond to a the
name of a field in a record type.

I'll go to bed now but I'll try to prepare a PR tomorrow.

Edit: I should clarify that my "fix" means the code triggering an internal error won't
be generated via interactive programming. However if the user writes the broken thing
by hand then it'll still explode in their face.

**Comment by jespercockx** [comment]
This is a combination of two problems:
- `.unbox` is parsed as a postfix projection instead of as a dot pattern
- the LHS checker assumes that there are no projection patterns in 'nested' positions such as here

I'm not sure what to do about the former problem, maybe @andreasabel has an idea?

Meanwhile, I'll take a look if I can fix the latter problem.

**Comment by jespercockx** [comment]
It seems the problem was introduced by @andreasabel in his fix for https://github.com/agda/agda/issues/3130 

That fix actually does the right thing for printing a dot pattern with a projection as its body, but the subtle thing about the current issue is that `unbox` is actually a *variable name* which just happens to shadow the projection.

**Comment by jespercockx** [comment]
At the risk of stating the obvious: in hindsight, overloading `.` to mean 10 different things was perhaps not a great idea.

**Comment by gallais** [comment]
> the subtle thing about the current issue is that unbox is actually a variable name which just happens to shadow the projection.

Yep. I was planning to not only print `.(unbox)` but also raise a benign warning
advising users to NOT do things like this.

**Comment by jespercockx** [comment]
I pushed a patch to get rid of the internal error. @gallais once we can get the right thing printed by interactive case split we can close this issue!

**Comment by gallais** [comment]
I now raise a warning but it somehow never reaches the toplevel. Investigating.

Edit: I'm giving up on the idea of raising a warning. This would require a lot of changes
to the emacs mode (the response to make_case inserts the clauses and then promptly
reloads the file thus hiding any warning which is produced *when* splitting but not when
loading the resulting code).

**Comment by jespercockx** [comment]
Thanks!
