### ISSUE TITLE
Termination check failed for simple coinduction definition

### ISSUE THREAD

**Issue by ice1000** [agda/agda#3492]
```agda
variable A : Set
record List (A : Set) : Set where
  coinductive
  field
    head : A
    tail : List A
open List

data Nat : Set where
  zero : Nat
  succ : Nat -> Nat

ones : List Nat
head ones = succ zero
-- Gives unexpected termination error
tail ones = ones
```

I'm using a dev version of Agda, `agda --version` gives `2.6.0-c353977`

**Comment by nad** [comment]
From the changelog:

New options `--guardedness` and `--no-guardedness` [Issue [#1209](https://github.com/agda/agda/issues/1209)].

Constructor-based guarded corecursion is now only (meant to be) allowed if the `--guardedness` option is active. By default this option is not active. If `--guardedness` is used, then sized types are disabled (because this combination is known to be inconsistent). If you still want to use both constructor-based guarded corecursion and sized types, then you can use `--guardedness --sized-types` (in this order). The combination of constructor-based guarded corecursion and sized types is not allowed if `--safe` is used.

The option `--no-guardedness` turns off constructor-based guarded corecursion.

**Comment by ice1000** [comment]
Thanks!
