### ISSUE TITLE
Is the order in which variable-splitting occurs when building case-trees part of the language?

### ISSUE THREAD

**Issue by gallais** [agda/agda#3500]
I was looking at [Relation.Nullary.Product](https://agda.github.io/agda-stdlib/Relation.Nullary.Product.html):

```agda
_×-dec_ : ∀ {p q} {P : Set p} {Q : Set q} →
          Dec P → Dec Q → Dec (P × Q)
yes p ×-dec yes q = yes (p , q)
no ¬p ×-dec _     = no (¬p ∘ proj₁)
_     ×-dec no ¬q = no (¬q ∘ proj₂)
```

and was thinking that it may be worth putting the `yes/yes` case last in order to allow
Agda to not evaluate the second argument when the first is `no`. This short-circuiting
behaviour is crucial when using `_×-dec_` to implement e.g. the decidability of equality
on lists (we want to stop as soon as the heads differs without checking the tails). 

However both of these lists of clauses lead to the same case tree and thus the same
Haskell code. **For now**. Indeed AFAIU the left-bias is a direct consequence of the fact
that Agda translated `yes/yes` to splitting on the first variable first and then the second.
If at some point in the future that changes to splitting on the second first and
then the first second (:D) then we would get a right bias.

Hence my questions:

* Is the order in which variable-splitting occurs when building case-trees part of the language?
* Or should I send my patch re-ordering the equations to make sure the `no/_` case is the first one so that I will *always* get the left-biased function?

**Comment by andreasabel** [comment]
See #408. The current strategy is to scan left-to-right for a variable we can split on and then immediately split it.  Repeat this (left-to-right-scan, split) until done or stuck.
I'd say this strategy is to stay, it is too late to change it now.  All the code out there relies on it.

See also #408 for the discussion of a split strategy that prefers total columns (listing all and only the constructors) over partial ones (listing only some and/or some variables).  I never turned it on because of non-backwards compatibility, an also since a more clever strategy (as opposed to left-to-right) prevents users to work-around by reordering function arguments.

**Comment by jespercockx** [comment]
I think this is more of a question for the mailing list than an actual bug report/enhancement request, so I'm closing this. Feel free to re-open if there is a concrete bug.
