### ISSUE TITLE
Problem finding higher-order instances

### ISSUE THREAD

**Issue by mietek** [agda/agda#3534]
It seems that wrapping higher-order instances is still necessary in Agda 2.5.4.2, as suggested in https://github.com/agda/agda/issues/1322#issuecomment-129030137.  Is this intended?

```agda
module InstanceArgumentBug where

open import Agda.Builtin.Unit
open import Agda.Builtin.Bool

data ⊥ : Set where

T : Bool → Set
T true  = ⊤
T false = ⊥

module Good-FirstOrderInstance where
  module _ {{foo : Bool}} where
    data Bar : Set where
      bar : Bar
      baz : T (foo) → Bar

  module _ {{foo : Bool}} where
    bar′ : Bar
    bar′ = bar

module Good-HigherOrderInstanceWithWrapper where
  record Wrap : Set where
    field
      foo : ⊤ → Bool

  module _ {{w : Wrap}} where
    open Wrap w

    data Bar : Set where
      bar : Bar
      baz : ∀ {t} → T (foo t) → Bar

  module _ {{w : Wrap}} where
    open Wrap w

    bar′ : Bar
    bar′ = bar

module Bad-HigherOrderInstanceWithNoWrapper where
  module _ {{foo : ⊤ → Bool}} where
    data Bar : Set where
      bar : Bar
      baz : ∀ {t} → T (foo t) → Bar

  module _ {{foo : ⊤ → Bool}} where
    bar′ : Bar
    bar′ = bar

{-
InstanceArgumentBug.agda:47,12-15
No instance of type Bool was found in scope.
when checking that the expression Bar has type Set
-}
```

**Comment by jespercockx** [comment]
It works (at least on the current master branch of Agda) if you make the argument of `foo` into an instance argument as well:
```agda
  module _ {{foo : {{_ : ⊤}} → Bool}} where
    bar′ : Bar
    bar′ = bar
```
In general, it does not really make sense to have an instance with an explicit function type, as it will never actually be used by instance search. For top-level definitions there's already a warning if you try to add an instance of type `A -> B`, maybe we should have a similar warning for module parameters (and function arguments)?

**Comment by mietek** [comment]
> In general, it does not really make sense to have an instance with an explicit function type, as it will never actually be used by instance search.

That’s not obvious at all from the user perspective.  Why shouldn’t a higher-order instance be used by instance search?

**Comment by jespercockx** [comment]
Instance resolution only searches for elements of *named types* (i.e. data or record types). The technical reason for this is that the implementation looks up the set of initial instance candidates based on the name of the type, and then tries to prune these candidates until there's only one left.

If instance search is used to find an element of type `A -> B`, it will just introduce a lambda-abstraction and instead search for an element of type `B` for the body of this lambda. So even if you had an instance of type `A -> B`, it wouldn't be used because Agda is searching for an element of type `B` instead.

**Comment by mietek** [comment]
I’m trying to say that from the point of view of the user of Agda, and not the implementor of Agda, this limitation seems arbitrary and unexpected.  The documentation says:

> Instance arguments that do not have this form are currently accepted, but instance resolution may or may not work as described below for such arguments.

“May or may not work” is a bit frustrating.  It would be better to clearly state in the documentation, as you did just now, what are the specific cases in which the user of Agda can expect instance resolution to work or to not work.

Additionally, is there a reason why instance search must work the way you describe?  Could it not be improved?

**Comment by jespercockx** [comment]
> “May or may not work” is a bit frustrating. It would be better to clearly state in the documentation, as you did just now, what are the specific cases in which the user of Agda can expect instance resolution to work or to not work.

Good point, I will try to improve the documentation to make it clearer.

> Additionally, is there a reason why instance search must work the way you describe? Could it not be improved?

Do you have a proposal of what Agda should do instead to find an instance of a function type? Perhaps it is some form of developer blindness, but I don't really see an alternative to the current behaviour (or rather, anything that I can think of would be very brittle and/or slow).

**Comment by jespercockx** [comment]
The problem with printing a warning for instance arguments/module parameters whose type takes an explicit argument is that there are actually valid use-cases of this: the instance will never be used in the body of the function, but using the function somewhere else will still trigger instance search (which will introduce the lambda as I described above). Printing a warning when the code actually makes sense would be too annoying, so I will just update the documentation and leave the implementation as is.

**Comment by mietek** [comment]
Unfortunately, I don’t have any proposals for improvement at present.

**Comment by jespercockx** [comment]
I tried to improve the documentation to make it more explicit about when instance search will/won't work, let me know if it is clear now.

I also added a warning in https://github.com/agda/agda/commit/130977f45437e67c3a782e3969bf76362988acd9 when you have an instance argument whose type does not end in a named or variable type. I'm considering having a similar warning for instance arguments whose type is an explicit function type, but as mentioned before I'm not sure whether that would be a good idea since such instance arguments are actually not 100% useless.

**Comment by jespercockx** [comment]
We could consider to change instance search to *not* automatically introduce a lambda for an explicit function space. Then the rule would be much simpler for the user ('no higher-order instances with explicit function types') and we could actually raise a warning when this does happen.

**Comment by jespercockx** [comment]
I'm thinking now that maybe we *should* make this change before the release since there are many changes to instance search in this release already, so people would only have to update their code once.

**Comment by jespercockx** [comment]
I made some further changes to make the behaviour of instance search more consistent:
- Instance search is no longer run for goals that take explicit arguments
- You now also get a warning when an instance argument has an explicit function type (since now it is truly useless)
- Having a top-level instance declaration with the wrong type is no longer an error but only a warning saying that the instance will never be used
