### ISSUE TITLE
Patternmatching on coinductive record fields breaks

### ISSUE THREAD

**Issue by maltenmuller** [agda/agda#3536]
I have this piece of code defining a coinductive record and a function producing elements of this record type. 

```agda
data Unit : Set where
 true : Unit

record R : Set where
 coinductive
 field
   f1 : R
   f2 : R
open R public

foo : Unit -> R
f1 (foo true) = foo true
f2 (foo b) = foo b
```

When I compile the file I get this message:

```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/Compiler/ToTreeless.hs:376
```

I'm working with Agda 2.6 but this error also occurs with 2.5.4.1.

The error occurs when 
* the record has at least two fields
* the argument in the _first_ case of `foo` is being patternmatched on
    (if the two cases swap places, the problem is gone)

**Comment by gallais** [comment]
It compiles with 2.5.3. Therefore a regression.

**Comment by andreasabel** [comment]
The problem seems to be that the `Treeless` compiler reruns the clause compiler (instead of using the existing compiled clauses), but without the split tree from the coverage checker.  However, the split tree is necessary to direct the clause compiler.  As you can see from debug output, the recompiled clauses are garbage:
```
-- compiled clauses of foo
  case 0 of
    Issue3536.Unit.true ->
      record Issue3536.R.f1 -> done[] Issue3536.foo Issue3536.Unit.true
    _ -> record Issue3536.R.f2 -> done[ωru("b")] Issue3536.foo @0
```
Here, the first split is on the argument, leaving us with two incomplete copattern matches.
In contrast, the original compiled clauses from the coverage checking are correct.
```
compiled clauses (still containing record splits)
  record
    Issue3536.R.f1 ->
      case 0 of
        Issue3536.Unit.true -> done[] Issue3536.foo Issue3536.Unit.true
    Issue3536.R.f2 -> done[ωru("b")] Issue3536.foo @0
```
Regression introduced by commit 49978214d6.
@UlfNorell ?

**Comment by andreasabel** [comment]
One way to fix this would be to store the split tree for the second invokation of the case tree compilation.  But I do not understand why we compile twice, once _without_ and once _with_ forcing translation on.  Why not always do the forcing translation first, and then generate the case tree from that?

**Comment by jespercockx** [comment]
I guess the reason why we compile again is because the forcing translation is implemented on the clauses and not on case trees, so after we do the forcing translation we have to compile again to get the updated case tree.

**Comment by andreasabel** [comment]
Yes, but why not do the forcing translation already before the first compilation?

**Comment by jespercockx** [comment]
I guess because the forcing translation messes up the patterns in a way which is fine for Treeless but not for internal use by the typechecker, maybe? I don't really know, maybe @UlfNorell has a better answer.

Anyway, I implemented the fix where we remember the split tree computed by the coverage checker and use it when recompiling the clauses. I'm now taking a flight to Tokyo, but if Travis is green feel free to merge the PR and release 2.6.0 before I land, I will be very happy ^^
