### ISSUE TITLE
Document `--cubical` properly

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#3539]
The current documentation
https://github.com/agda/agda/blob/master/doc/user-manual/language/cubical.lagda.rst
only covers the interval type, but misses
- [ ] systems
- [ ] cubical primitives
- [ ] ... (what else?)

**Comment by mortberg** [comment]
One technical remark is that the interval is not a type, it's a "pre-type" as it does not have any hcomp/transp operations (i.e. it is not fibrant/Kan in the semantics). Because of this it is in `Setω`.

The documentation should also cover:

- `PathP`
- `Partial` and `PartialP` (as part of documentation for "systems")
- Kan operations (`hcomp` and `transp`)
- `Glue` types
- Cubical `Id` types
- Higher inductive types

This is partially done in https://github.com/agda/cubical/tree/master/Cubical/Core (in particular in `Primitives.agda`) and with more prose in https://homotopytypetheory.org/2018/12/06/cubical-agda/. I can take it upon me to try to fix this issue.

**Comment by Saizan** [comment]
> I can take it upon me to try to fix this issue.

@mortberg That would be great! every time I start I get stuck on how to organize things.
And if there's something about the implementation to clarify you can leave TODOs for me.

**Comment by nad** [comment]
> Because of this it is in `Setω`.

Is the intention to turn the interval into a type when `--omega-in-omega` is active, or is this just a hack? Perhaps you could use another sort, distinct from `Setω`.

**Comment by Saizan** [comment]
@nad The interval will still be a `pre-type` with `--omega-in-omega` because its universe will not change. `pre-type` is not the same as `sort` or `kind`, it's about whether there's both `primTransp` and `primHComp` for it. In Agda you can apply those primitives only for "types" in universes of the form `Set l`.

In the future it would be nice to have a universe for the interval so that function types `I -> A` can be in `Set l` if `A` is, but that would be a new feature.

**Comment by nad** [comment]
> The interval will still be a `pre-type` with `--omega-in-omega`

OK.

**Comment by jespercockx** [comment]
Since #3571 has been merged, I'm now closing this issue. Please create a new issue if there are still things missing.
