### ISSUE TITLE
Definitions in Prop are not accessible by reflection

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#3553]
Consider the code below, which defines `f` and then uses reflection to extract the definition of `f`. 
If you give the hole at the last line, you get the "error message" `The value of f is x₀`, which is the expected behaviour.
But if you now change `X : Set` to `X : Prop` and try again to give the hole at the last line, you get `The value of f is _`. The value of `f` is reified as `unknown` whereas it should be `x₀` as well.

```agda
{-# OPTIONS --prop #-}

open import Agda.Builtin.Reflection
open import Agda.Builtin.List
open import Agda.Builtin.Unit
_>>=_ = bindTC
return = returnTC

postulate
  X : Set
  x₀ : X

f : X
f = x₀

macro
  getValue : Name → Term → TC ⊤
  getValue s _ = do
    function (clause _ t ∷ []) ← getDefinition s
      where _ → typeError (strErr "Not a defined name" ∷ [])
    typeError (strErr "The value of" ∷ nameErr s ∷ strErr "is" ∷ termErr t ∷ [])

test = {!getValue f!}
```

**Comment by jespercockx** [comment]
Yeah, it would make sense to add support for `Prop` to the reflection machinery.

**Comment by L-TChen** [comment]
It seems relatively easy to add `Prop` to reflected syntax than other open issues. If @jespercockx is busy on something else (hopefully on cumulativity :wink:), I will take this.

**Comment by jespercockx** [comment]
I will probably not be able to work on this (or sadly, cumulativity) before **checks calendar** the Agda meeting in September. So if you want to take this, go for it!

**Comment by L-TChen** [comment]
I will try to work on this next week, but I have a design question regarding the reflected syntax for `Sort`. The following is the current data type for `Sort`: 

```agda
data Sort where
  set     : (t : Term) → Sort -- A Set of a given (possibly neutral) level.
  lit     : (n : Nat) → Sort  -- A Set of a given concrete level.
  unknown : Sort
```

There are few possible extension I can think of: 

1. Simply add another two constructors `prop` and `propLit` (and maybe rename `lit`to `setLit` as well). 

2. Extend `set` and `lit` with another argument for its relevance. 

3. Similar to `Arg`, let its declaration become `Sort (st : sortType) : Set` and encode all information in `sortType`. 

Any preference?

**Comment by jespercockx** [comment]
1. would be the closest to the current representation used internally by Agda, but otherwise I don't really have a strong preference.

**Comment by L-TChen** [comment]
I have been wondering if adding constructs manually to reflected syntax is a good design, after reading [(Berger et al, 2017)](http://drops.dagstuhl.de/opus/volltexte/2017/7277/) and talking to people at TyDe'19. 

If, say, we use internal (or abstract) syntax directly then the reflection framework would updates automatically with full access to all information for AST. 

Another drawback of using a different syntax is that many operations have to traverse through every node in order to work with two different syntaxes. For efficiency, it will be nice to eliminate these traversals. In particular, I expect that (un)-quotation can be an O(1) operation. 

Does anyone know any good reference on designing a reflection framework?

**Comment by jespercockx** [comment]
@L-TChen Do you have any plans to work on this in the next month or so? We're working towards a release of 2.6.2.

**Comment by L-TChen** [comment]
Oops, no. I don't think I have time to work on before the release of 2.6.2.

**Comment by jespercockx** [comment]
Ok, no worries. I'll see if I have time to work on it myself, otherwise I'll bump.
