### ISSUE TITLE
Cubical constraints on endpoints should be checked after termination checking

### ISSUE THREAD

**Issue by greatBigDot** [agda/agda#3572]
```
{-# OPTIONS --cubical #-}
module Prelude.Data.HInt where
open import Agda.Primitive.Cubical
open import Agda.Builtin.Cubical.Path
open import Agda.Builtin.Nat renaming (Nat to ℕ)
```

Say you define higher-inductive integers in the usual way, and say we add a couple of patterns for convenience:

```
data ℤ : Set where
  Pos Neg : ℕ → ℤ
  ζ       : Pos zero ≡ Neg zero

pattern PosS n = Pos (suc n)
pattern NegS n = Neg (suc n)
pattern PosZ   = Pos zero
pattern NegZ   = Neg zero
```

I would expect that, when defining a function `ℤ → Y`, you would only need to specify the behavior at `PosS n` , `NegS n`, and `ζ ı`. E.g.:

```
signum : ℤ → ℤ
signum (PosS _) =  PosS zero
signum (NegS _) = NegS zero
signum z@(ζ _)  = z
```

This seems reasonably total to me. Shouldn't Agda be able to infer that `signum` is the identity at the endpoints of `ζ`? But no, Agda doesn't like this and insists that you define it at `Pos zero` and `Neg zero` as well:

```
signum NegZ != NegZ of type ℤ
when checking the definition of signum
```

This doesn't make much sense to me; the value at `NegZ` hasn't been explicitly specified, so it seems a bit much to claim it's disequal to `0`. And it's been implicitly set to `0` already, no?

We can explicitly set `signum z@PosZ = z` and ditto for `NegZ` and everything works fine. But in the spirit of offloading as much work to the typechecker as possible, what if we tried this instead?:

```
[...]
signum z@(ζ _) = z
signum PosZ    = signum (ζ i0)
signum NegZ    = signum (ζ i1)
```

Those are the two computational equalities I expected to be inferred automatically. But Agda _**really**_ doesn't like this:

```
Checking Prelude.Data.HInt (/home/me/Agda/prelude/src/Prelude/Data/HInt.agda).
```

It doesn't seem to progress any further.

____

```
$ agda --version
Agda version 2.6.0-9444c31
```

**Comment by gallais** [comment]
Could you post a self-contained example? What are `1`, `-1`, `Z`, etc?

**Comment by greatBigDot** [comment]
Oops, sorry. `Z` and `S` are just `zero` and `suc`, respectively; I forgot that the standard library uses different names. I've now edited the example to use the standard names.

`1` and `-1` are builtin numeric literals that map to `Pos (S Z)` and `Neg (S Z)`, respectively. I didn't include the stuff that binds all the literals because it works just as well if you don't bother with primitives at all and I figured it would be clutter. So I've now removed all literals from the example and replaced them with their equivalents.

I've now included the import statements and whatnot too; it should be self-contained now.

**Comment by gallais** [comment]
Ok, I think I understand what you mean. There are actually two issues here:

* The side conditions in cubical seem to be checked rather than considered as
unification constraints that need to be satisfied. When seen as unification
problems, they could lead to some of the RHS left out by the user being solved.
It's a feature request.

```agda
{-# OPTIONS --cubical #-}

open import Cubical.Core.Prelude

data Interval : Set where
  a b : Interval
  eq  : a ≡ b

flip : Interval → Interval
flip (eq i) = eq (~ i)

-- NOW: flip b != a of type Interval
--      when checking the definition of flip

-- WANT: OK
```

* Because cubical has side conditions checked via normalisation, it is probably the
case that we need to interleave typechecking and termination checking. It is a bug
report.

```agda
{-# OPTIONS --cubical #-}

module loopy where

open import Cubical.Core.Prelude

data Circle : Set where
  base : Circle
  loop : base ≡ base

flip : Circle → Circle
flip (loop i) = loop (~ i)
flip base     = flip (loop i0)

-- NOW: loops
-- WANT: rejected by the termination checker
```

@Saizan does that look like sensible issues to open on their own?

**Comment by Saizan** [comment]
> This doesn't make much sense to me; the value at NegZ hasn't been explicitly specified, so it seems a bit > much to claim it's disequal to 0. And it's been implicitly set to 0 already, no?

@greatBigDot If you are not giving a clause that matches `NegZ` then `signum NegZ` behaves like a new axiom for Agda. i.e. it is equal only to itself. You are right that in this case there's only one value that could lead to a valid definition of `signum` but inferring function clauses is something that would need to be implemented (see below).

@gallais That's a fairly good analysis of the situation.

- I'm not sure what difference you are thinking of between "checked constraints" and "unification constraints" (maybe by the latter you mean those from matching on inductive families?), however it's true in some cases we could infer the definition for endpoints from the definition for a path, a bit like we infer implicit record fields. However note that we do not infer explicit record fields iirc. It's a design choice that would be nice to discuss in a separate feature request.

- Indeed the code imposing these constraints is a bit too optimistic wrt normalization, I was looking at it on Friday, but I guess I should have opened an issue myself. Postponing the checks after termination checking might be a solution, otherwise we might want to have better control of reduction and allow only one step for the function. Anyway one complication is that we need information from the `SplitClause`s, so we need to store them somewhere until we need them, since the coverage check is run too early for this.

 I suppose we can keep this one for termination, and have a feature request for inferring clauses.

**Comment by gallais** [comment]
> I'm not sure what difference you are thinking of between "checked constraints" and "unification constraints"

I expect unification to be able to instantiate metavariables. But here I have the
impression the constraints on endpoints are checked for equality instead.

> However note that we do not infer explicit record fields iirc. 

We actually do! We use it a lot in the standard library: a `setoid` is built by
specifying the `isEquivalence` field which is enough for Agda to figure out what
the `Carrier` and `_≈_` ones should be.

Edit: [for example list with pointwise equality forms a setoid](https://agda.github.io/agda-stdlib/Data.List.Relation.Binary.Pointwise.html#6298)

**Comment by Saizan** [comment]
> > I'm not sure what difference you are thinking of between "checked constraints" and "unification constraints"
> 
> I expect unification to be able to instantiate metavariables. But here I have the
> impression the constraints on endpoints are checked for equality instead.

Oh, ok. In that case these are unification constraints as well. 

The thing though is that the implementation doesn't generate a metavariable corresponding to the missing clauses, or at least not soon enough.
  
It does look quite nice to be able to omit `Carrier` and so on,  I guess it makes sense to do it for HITs too then.
