### ISSUE TITLE
Agda fails to recognize some definitionally equal terms

### ISSUE THREAD

**Issue by 3abc** [agda/agda#3628]
This is cubical mode. 

In the following snippet, `c i i1 k` is definitionally equal to `base` since the system in `hcomp` says so. However if I change the term `c i i1 k` in the type of `c'` into `base` it emits error. Weirdly enough just changing the order of the clauses in the definition of the system helps to bypass the bug.

```Agda
data S : Set where
  base : S

c : (i j k : I) → S
c i j k = hcomp (λ l → λ { (i = i0)(k = i1) → base
                         ; (j = i1) → base
                         }) base

c' : PathP (λ i → Path (base ≡ base) (λ k → base) (λ k → c i i1 k)) -- weird here
           (λ j k → c i0 j k)
           (λ j k → c i1 j k)
c' i j k = c i j k
```

**Comment by Saizan** [comment]
Thanks for the report.

Problem: `c i0 i1 k` does not reduce to `base`. Because the partial element given to `hcomp` doesn't.

It seems the bug should be fixed in `compileClause` as we are getting this case tree:

```agda
case i of
  i0 -> case k of
          i1 -> base
  _  -> case j of
          i1 -> base
          _  -> fail
```

While we want this one:

```agda
case i of
  i0 -> case k of
          i1 -> base
          _  -> case j of
                  i1 -> base
                  _  -> fail
  _  -> case j of
          i1 -> base
          _  -> fail
```

@andreasabel Do you know if this should be handled by `expandCatchAlls`? And if so, how does it work?
