### ISSUE TITLE
Using ill-typed terms (Setω) as module parameters

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda#3643]
I was trying to write a generalise this form of  [function extensionality](https://github.com/agda/agda-stdlib/blob/8f15d480bab00dc3c7e985436c438ee60db68010/src/Relation/Binary/PropositionalEquality.agda#L127) when I came across the following.

If I write
```agda
Ext : {!!}
Ext = ∀ {ℓ ℓ′} → Extensionality ℓ ℓ′
```
I get the error `Setω is not a valid type`.

However the following
```agda
module _ {x : ∀ {ℓ ℓ′} → Extensionality ℓ ℓ′} where
```
 type checks fine and indeed is [used](https://github.com/agda/agda-stdlib/blob/8f15d480bab00dc3c7e985436c438ee60db68010/src/Data/Container/Combinator/Properties.agda#L39) in the library. My intuition is that either they should both fail to type check or both pass? My experience with type theory isn't as extensive as most here, but it seems strange to me that Agda apparently doesn't seem to check whether the type of module parameters are themselves valid types.

**Comment by JacquesCarette** [comment]
Isn't this the difference between "has a type" and "is a type" ?  The `Ext` expression is a perfectly fine type, however it doesn't have a 'perfectly fine' type.  So the module parameter is fine, because `Ext` is a fine type. And, well, modules in Agda, as far as I know, are first elaborated then checked, so there is no need to ever check that `Ext` has a type.

At least, that's my understanding.  I could, of course, be quite wrong, and would love to be corrected on this point, as it is quite an interesting question!

**Comment by MatthewDaggitt** [comment]
Hmm that makes sense, I was confusing the two, thanks for the explanation. It's kind of weird that 95% of the types of the proofs in the standard library have no type :open_mouth: The non-closure of "has a type" is counter-intuitive but I guess that's the whole problem universe polymorphism is designed to hide most of the time.
