### ISSUE TITLE
Suggestion: A different resolution strategy for Prop

### ISSUE THREAD

**Issue by L-TChen** [agda/agda#3649]
It is fantastic that instance argument can be used for proof search and combining it with Prop, I think, opens a door for elegant proof search in dependently-typed programming. 

However, the current resolution strategy is rather limited for this purpose, because 

1. The option --overlapping-instances allow overlapping instances not only for Prop but also Set. I suggest to have another option like --overlapping-instances-prop which allow overlapping instances only for Prop. 

2. The current implementation does not consider instances with explicit arguments. This restriction should be lifted if instance argument is used to proof search. 

3. Perhaps, there should be a plug-in system for proof search engine in Prop? Komendantskya and her coauthors have been developing proof-relevant proof-search, for [example](https://www.cambridge.org/core/journals/theory-and-practice-of-logic-programming/article/proofrelevant-horn-clauses-for-dependent-type-inference-and-term-synthesis/FBC78F180407F1F043D8E8B7E1957B10). It would be nice to have an interface to play with different proof search methods without looking inside Agda's core system. It is possible via reflection e.g., [this](https://link.springer.com/chapter/10.1007/978-3-319-19797-5_14), but I am not sure about its performance ...(I failed to get it type checked.)

My last one is actually a question about the equivalent notion in HoTT (Cubical Agda): `Prop` is a syntactic approximation of the type `hProp` of mere propositions in HoTT, but `hProp`  lives in Set. Is it possible to allow overlapping instances or any proof-search features for some types only? Is there any way to move between `Prop` and `hProp`?

Hope the above (naive?) suggestions and the question make sense. Thanks!

**Comment by jespercockx** [comment]
Thanks for your interest in using `Prop`! I'm looking into possible ways to extend its power, but for the initial release I really wanted to have the simplest possible version to see what people do with it. After the release would be a perfect time to experiment with some new additions.

> The option --overlapping-instances allow overlapping instances not only for Prop but also Set. I suggest to have another option like --overlapping-instances-prop which allow overlapping instances only for Prop.

Could you explain (perhaps with an example) why you need the `--overlapping-instances` flag for instances in `Prop`? In my experience if you need `--overlapping-instances` you are probably doing something wrong, but I admit I haven't yet tested the combination of `Prop` with instance arguments very much.

> The current implementation does not consider instances with explicit arguments. This restriction should be lifted if instance argument is used to proof search.

The problem with explicit arguments to instances is that it's unclear whether they should be solved using the constraint solver (as for implicit arguments) or with (recursive) instance search. Is there a reason why you cannot just turn the arguments into implicit and/or instance arguments?

> Perhaps, there should be a plug-in system for proof search engine in Prop? Komendantskya and her coauthors have been developing proof-relevant proof-search, for example. It would be nice to have an interface to play with different proof search methods without looking inside Agda's core system. It is possible via reflection e.g., this, but I am not sure about its performance ...(I failed to get it type checked.)

During the Agda meeting in Tokyo, @UlfNorell started to work on a new kind of implicit argument which is solved by a custom macro. Your application seems to be a perfect use-case for this new feature, since it gives you much more freedom to guide the proof search than with instance search. Performance of reflection-based proof search is also something we are planning to look into in the future.

> My last one is actually a question about the equivalent notion in HoTT (Cubical Agda): Prop is a syntactic approximation of the type hProp of mere propositions in HoTT, but hProp lives in Set. Is it possible to allow overlapping instances or any proof-search features for some types only? Is there any way to move between Prop and hProp?

Any `Prop` is trivially a `hProp` so one direction is easy. For the other direction it is not possible in general to convert a `hProp` into a `Prop`; for example the singleton type `Σ A λ x → x₀ ≡ x` is a `hProp` but it cannot be made into a `Prop` because you can extract the first component from it (more about this and other examples in our [paper](https://hal.inria.fr/hal-01859964)).

**Comment by L-TChen** [comment]
Here is an example I have in mind. The list membership is usually defined as 
```agda
data _∈₁_ {A : Set} (x : A) : List A → Set where
  instance
    here  : ∀ {xs} → x ∈₁ x ∷ xs
    there : ∀ {y xs} ⦃ _ : x ∈₁ xs ⦄ → x ∈₁ y ∷ xs
```
and I would love to use the propositional squash type to derive its Prop version:
```agda
data ∥_∥ (A : Set) : Prop where
  instance
    ∣_∣ : (x : A) → ∥ A ∥
```
Since  `∣_∣` takes an explicit argument, another instance of  `∥ A ∥` is required 
```agda
instance
  pf : {A : Set} {x : A} → ∥ A ∥
  pf {A} {x} = ∣ x ∣
```
But the following instance search fails even with `--overlapping-instances`
```agda
it′ : {A : Prop} ⦃ _ : A ⦄ → A
it′ ⦃ x ⦄ = x
_ : ∥ 1 ∈₁ 2 ∷ 1 ∷ [] ∥
_ = it′ -- it′ ⦃ ∣ it ∣ ⦄ works instead
```
Of course, with `--overlapping-instances`, the following code works 
```agda
it : {A : Set} ⦃ _ : A ⦄ → A
it ⦃ x ⦄ = x
_ : ∥ 1 ∈₁ (2 ∷ 1 ∷ []) ∥
_ = ∣ it ∣ -- this requires --overlapping-instances 
```
Also, the following style also works as expected: 
```agda
module Membership {A : Set} (_==_ : A → A → Bool) where
  _∈₂_ : A → List A → Prop
  a ∈₂ []     = ∥ ⊥ ∥
  a ∈₂ (x ∷ xs) with a == x
  ... | true  = ∥ ⊤ ∥
  ... | false = a ∈₂ xs
  infix 4 _∈₂_
open Membership _≡ᵇ_

_ : 1 ∈₂ (2 ∷ 1 ∷ [])
_ = it′
```
If technically possible, I hope  `it′` can work for the squashed membership `∥ 1 ∈₁ 2 ∷ 1 ∷ [] ∥` so that the definition can be reused. Allowing overlapping instances is necessary but not sufficient in this case. 
I also fail to see how to define `_∈₂_` without a decidable equality.

My gut feeling is that the instance search should be more ambitious if the target is in Prop.

The complete code can be found [here](https://gist.github.com/L-TChen/82e225a4cf1c87aa9b7cd39d57d992c9).

>The problem with explicit arguments to instances is that it's unclear whether they should be solved using the constraint solver (as for implicit arguments) or with (recursive) instance search. Is there a reason why you cannot just turn the arguments into implicit and/or instance arguments?

Indeed, you are right. I was not aware of this problem. 

>Any Prop is trivially a hProp so one direction is easy. For the other direction it is not possible in general to convert a hProp into a Prop; for example the singleton type Σ A λ x → x₀ ≡ x is a hProp but it cannot be made into a Prop because you can extract the first component from it (more about this and other examples in our paper).

Thanks for this!

**Comment by jespercockx** [comment]
You should make the second argument to `pf` into an instance argument:
```agda
instance
  pf : {A : Set} {{x : A}} → ∥ A ∥
  pf {{x}} = ∣ x ∣
```
That way your example works with `--overlapping-instances` enabled. 

The reason why we don't solve the instance argument without `--overlapping-instances` is that instance search != proof search: we don't want to do unrestricted backtracking for resolving instances because it's unpredictable and can be extremely slow (see the list of issues referenced in https://github.com/agda/agda/pull/3419 for some examples).

For your example where you *want* actual proof search, I would recommend to take a look at writing your own [tactic using reflection](https://agda.readthedocs.io/en/latest/language/reflection.html) to find the proofs. That way you have precise control over how much/little backtracking you want.

**Comment by L-TChen** [comment]
Ooops, thanks for pointing it out.

True, instance search is not supposed to be proof search, but it is rather an abuse of feature and makes life a bit easier. 

I think I will have to use reflection-based approach in the end. Ta!
