### ISSUE TITLE
incomplete pattern match after case-split

### ISSUE THREAD

**Issue by m0davis** [agda/agda#3650]
In the code below, case-splitting results in a complaint about incomplete pattern matching.
```agda

data Tm : Set where
  tzero : Tm
  tsucc : Tm → Tm
  tdiff : Tm → Tm → Tm

variable
  m n n' : Tm

data NotZero : Tm → Set where
  nzsucc : NotZero (tsucc n)
  nzdiff : NotZero (tdiff m n)

data Equal : Tm → Tm → Set where
  esucc : NotZero n → Equal (tsucc (tdiff tzero n)) n
  ediff : Equal n n' → Equal (tdiff m n) (tdiff m n')

data Foo : Tm → Set where
  fleft : Foo m → Foo (tdiff m n)
  frght : Foo n → Foo (tdiff m (tsucc n))

foo : Foo n → Equal n n' → Foo n'
foo (fleft f) e = {!!}
foo (frght (frght f)) (ediff (esucc nz)) = {!nz!} -- case-split on nz replaces nz with nzsucc
```
The complaint after case-splitting is:
```
Incomplete pattern matching for foo. Missing cases:
  foo (frght x) (ediff (esucc nzdiff))
when checking the definition of foo
```
I am using the lastest from master (60ea60ae34e41c665ff10a41a853577c7db83cf2).

**Comment by jespercockx** [comment]
Seems that this could be caused by https://github.com/agda/agda/pull/3533. First Agda sees that the case `foo (frght (fright x)) (ediff (esucc nzdiff))` is impossible so it filters it out, but when re-loading it decides to do the case splitting in a different order which results in the missing clause `foo (frght x) (ediff (esucc nzdiff))`.

One possible solution would be to augment the coverage checker to not give up so easily when it encounters a missing clause. Instead, it could look at the other clauses to see if there is any argument that might be worth splitting on. In this example, we know that the clause `foo (frght (frght f)) (ediff (esucc nzsucc))` cannot cover `foo (frght x) (ediff (esucc nzdiff))`, but we could still take it as a hint that a further split on `x` could lead to an absurd clause.

Alternatively, we could try to simplify the splitting strategy: currently Agda prefers splits that result in a total covering, but in this case the strategy backfires since it prevents a further case split on `x`. Since we anyway filter out absurd clauses now, it seems that this additional cleverness might no longer be necessary and we could just rely on a simple and predictable left-to-right splitting order.

**Comment by jespercockx** [comment]
The second option (simplifying splitting strategy) on its own doesn't work but makes the situation worse: it already produces missing cases *before* you do any case splitting.

The first option (trying to split missing clauses further in the hope they go away) requires more changes to the coverage checker than I am comfortable making so close to the release.

Thus I propose we disable #3533 for now and take another look at it after the release.

**Comment by jespercockx** [comment]
I managed to fix the splitting strategy to take the new improved emptiness check into account: now a split doesn't count as partial unless at least one of the missing clauses is not impossible. This seems to fix the issue; however it's possible that we're doing a bit of double work. I'll leave any improvements to eliminating double work to when I finally get to finish my refactoring of the LHS checker.

**Comment by andreasabel** [comment]
Your commit seems to break the standard library test and could be causing #3652 !?

**Comment by andreasabel** [comment]
How about just reverting #3533 and restore the original behavior until after the release?

**Comment by jespercockx** [comment]
Not actually fixed yet since we have to undo the stopgap patch 16bce9b
