### ISSUE TITLE
Two out-of-scope variables are given the same name

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#3678]
Example by @Saizan in #572:
```agda
open import Agda.Builtin.Sigma
open import Agda.Builtin.Equality

postulate
  A : Set
  B : A → Set
  a : A

Pi : (A → Set) → Set
Pi B = {x : A} → B x

foo : Pi \ y →  Σ (B y) \ _ → Pi \ z → Σ (y ≡ a → B z) \ _ → B y → B z → A
foo = {!!} , (\ { refl → {!!} }) , {!!}
```
After loading the file, Agda displays the following:
```
?0 : B x
?1 : B x
?2 : B x → B x → A
```
However, the two `x`s in the type of `?2` are actually two *different* variables. This also shows in the context for the hole:
```
Goal: B x → B x → A
————————————————————————————————————————————————————————————
x : A  (not in scope)
x : A  (not in scope)
```
Note that if you replace one of the first two holes with an underscore, Agda prints the right thing. So somewhere interaction metas must be treated differently from regular metas.

**Comment by Saizan** [comment]
According to my understanding, what's happening is that during the printing of goal types for ?0 and ?1 the concrete name "x" is picked for each of the variables and stored in ```stConcreteNames```. This is allowed to happen because the context for each of ?0 and ?1 only mentions one of the two variables, not both at once.

Then when time comes to print the type for "?2" the already chosen concrete names stored in ```stConcreteNames``` are used, without ```toConcreteName``` realizing that there's shadowing going on.

**Comment by jespercockx** [comment]
Yeah, that explanation seems to make sense. However, I don't see why `toConcreteName` doesn't pick up on the shadowing: why doesn't `lookupNameInScope` return the shadowing variable in one of the cases, which would trigger the other one to be renamed?

**Comment by jespercockx** [comment]
Oh no, I see now: `lookupNameInScope` only looks at user-written variables but not at system-inserted ones. So we should look at the `takenVarNames` instead.
