### ISSUE TITLE
Inductive-inductive type nontermination

### ISSUE THREAD

**Issue by akaposi** [agda/agda#3683]
The following code was accepted by Agda 2.5.4.2 but Agda master says

```
/home/ambi/git/tt2/test/bug1.agda:15,3-20,11
Termination checking failed for the following functions:
  _.elimA, _.elimB
Problematic calls:
  elimA x
    (at /home/ambi/git/tt2/test/bug1.agda:16,34-39)
  elimB x
    (at /home/ambi/git/tt2/test/bug1.agda:19,21-26)
```

The code just defines the eliminator for a simple inductive-inductive type.

```agda
data A : Set
data B : A → Set

data A where
  a : A
  f : B a → A

data B where

module _
  (A' : Set)(B' : A' → Set)
  (a' : A')(f' : B' a' → A')
  where

  elimA : (x : A) → A'
  elimB : {x : A}(y : B x) → B' (elimA x)

  elimA a = a'
  elimA (f x) = f' (elimB x)
  elimB ()
```

**Comment by nad** [comment]
See #1556.

**Comment by andreasabel** [comment]
With counting calls in the type signature as well, we get
```
  elimA (f _) --> elimB a _ --> elimA a
```
which does not pass the naive termination checker, since `a` and `f _` are unrelated in size.

However a more sophisticated type checker (Hyvernat) will see that the composed call
```
  elimA (f _) --> elimA a
```
is not idempotent; it cannot be composed with itself.

Thus, it is to be discounted during termination checking.

Verdict: this test case should pass.
