### ISSUE TITLE
Cubical interaction: Display inferred type with interval variables instantiated

### ISSUE THREAD

**Issue by nad** [agda/agda#3690]
When working with Cubical Agda it might be nice if commands like `agda2-goal-and-context-and-inferred` (`C-c C-.`) included information about the value of the given expression for each relevant instantiation of interval variables.

**Comment by mortberg** [comment]
Yes, this would be especially useful when working with HITs. At the moment Agda only displays the type and not the boundary conditions which makes it extremely confusing as seemingly correctly typed terms doesn't fill holes because they don't have the right boundary. The same applies when building hcomp's interactively. I think @Saizan is working on fixing this?

Maybe cubical extension types (types like `[i j] A [(i = 0) -> u , (j = 1) -> v]`) will make this easier to implement?

**Comment by Saizan** [comment]
I don't want to reimplement constraint propagation in the typechecker, the unifier is doing a good job at it. That's why extension types do not seem like they would help.

Here I've been working on printing constraints out as you would expect them, there it's only for those coming from HIT splitting, but it can be generalized.

https://github.com/Saizan/agda/tree/interaction-constraints

However to handle more than the simplest cases we need to do something about blocking metas, otherwise you'll get a bunch of "_12" in your constraints.

https://github.com/agda/agda/issues/3606

**Comment by Saizan** [comment]
Pull request #4164 is also relevant when pattern matching on HITs
