### ISSUE TITLE
Remove primComp?

### ISSUE THREAD

**Issue by nad** [agda/agda#3698]
@mortberg has written that `Agda.Primitive.Cubical.primComp` [is **not** recommended to use](https://homotopytypetheory.org/2018/12/06/cubical-agda/). I suggest that this primitive is removed.

**Comment by andreasabel** [comment]
Moved this to 2.6.1 since it is not a severe bug or regression that need immediate attention.

**Comment by Saizan** [comment]
That blog post is outdated. ```primComp``` is now defined in terms of ```primTransp``` and ```primHComp```, so it's fine to use when you need the heterogeneity.

It's not necessary as a path-equal ```comp``` can be user-defined, however ```primComp``` is used internally in some places to create smaller terms, and also it could be optimized compared to the user-defined one.

**Comment by mortberg** [comment]
I've updated the blog post and deleted the comment about primComp now. 

I think the agda/cubical library should use the built-in comp instead of the user-defined one for the reasons @Saizan explain. One nice thing with this is that we can get rid of a lot of `inS`/`inc`. One thing I don't like is that the `φ : I` argument is explicit in the built-in `comp`, but that should be easy to change.

**Comment by mortberg** [comment]
I made a PR making the phi argument implicit in the builtin comp now: https://github.com/agda/agda/pull/3713
