### ISSUE TITLE
Parse empty field lists

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#3803]
A continuation of #2759. This gives a hard parse error:
```agda
record Foo : Set where
  field
```
```
Parse error field<ERROR> ...
```
It would be nicer if this was just a warning, as with other empty blocks.

**Comment by gallais** [comment]
Even though fields form a block in the concrete syntax, they are currently
recorded as a list of field declarations rather than a single declaration
containing a list of fields.

As a consequence if we happily parse an empty block, we simply output an
empty list of declaration and the nicifier will be blind to it. Thus it will
not be able to raise a warning.

I am going to try to introduce a block of fields.

**Comment by jespercockx** [comment]
I believe @ayberkt was also working on this issue at some point, is that still the case?

**Comment by andreasabel** [comment]
Thanks @gallais, for fixing this.  I had reserved this issue for @ayberkt, thinking it was as easy to fix as empty mutual blocks, but apparently, this was not the case. I'll remove the `easy` tag...
