### ISSUE TITLE
Pi type cannot depend on runtime-irrelevant argument

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#3853]
Minimal example:
```agda
postulate
  A : Set
  B : A → Set

T = (@0 x : A) → B x
```
This should work, but instead Agda complains that `x` is erased.

**Comment by Saizan** [comment]
I would argue that `T` as defined in the OP should not work, because for example the following wouldn't work:
```agda
Q : (@0 y : A) -> Set
Q y = (@0 x : A) → B y
```
So it's quite ad-hoc that we allow `x` but not `y`, there is really no semantic difference between the two. It's just that the typing rules make it easy to resurrect `x`.

What works in both cases however is to declare such definitions in an erased context:
```agda
@0 T : Set
T = (@0 x : A) → B x
@0 Q : (@0 y : A) -> Set
Q y = (@0 x : A) → B y
```

When `--with-K` is enabled we could always put definitions returning a `Set` in an erased context, though that would be brittle because of metas.

**Comment by anuyts** [comment]
In the line
```agda
Q y = (@0 x : A) → B y
```
there is definitely a difference between `x` and `y`: `x` is introduced by a Pi-type and `y` by a lambda-abstraction.
These should have different typing rules, see https://github.com/agda/agda/issues/6124#issuecomment-1342858971 .
