### ISSUE TITLE
Unnamed implicit non-dependent function space {A} -> B and {{A}} -> B

### ISSUE THREAD

**Issue by msuperdock** [agda/agda#3901]
I suggest that Agda should allow unnamed implicit arguments, which it currently seems not to. The code below, which is a variation on the example given in the "Irrelevance" documentation, is an example use case:

```agda
module Implicit where

open import Agda.Builtin.Unit using (⊤; tt)

data ⊥ : Set where

data Nat : Set where
  zero : Nat
  suc  : Nat → Nat

_≤_ : Nat → Nat → Set
zero ≤ _      = ⊤
suc m ≤ zero  = ⊥
suc m ≤ suc n = m ≤ n

data SList (bound : Nat) : Set where
  []    : SList bound
  scons : (head : Nat)
        → {_ : head ≤ bound}
        → (tail : SList head)
        → SList bound

xs : SList zero
xs = scons zero []
```

The code compiles, but I would like to write `{head ≤ bound}` in place of `{_ : head ≤ bound}`, in analogy with `(head ≤ bound)` as I would write if I wanted an explicit argument. When I do replace `{_ : head ≤ bound}` with `{head ≤ bound}`, I get the following error:

```
{head ≤ bound} cannot appear by itself. It needs to be the argument to a function expecting an implicit argument. when scope checking {head ≤ bound}
```

If it is intended to disallow implicit arguments, then an underscore should also be disallowed. In this case it would also be helpful to have a clearer error message; I spent a long time thinking that implicit arguments were not allowed in the places I was trying to use them, before finally realizing that it was because I did not give the implicit argument a name.

I'm using Agda version 2.6.0.1, on NixOS.

**Comment by andreasabel** [comment]
> If it is intended to disallow implicit arguments, then an underscore should also be disallowed. 

There is no facility that would disallow implicit quantification.  The user can decide which arguments are implicit as they* likes. (*Singular third-person gender-neutral pronoun.)

However, non-dependent implicit function space is not parsed.  
- In case of `{A} -> B`, this design decision is motivated by the fact that Agda will usually not be able to infer the implicit argument by unification.  Your example is an exception because eta-equality for the unit type kicks in.  However, as soon as you write functions manipulating `SList`, you have to provide the implicit argument in every single location. Thus, Agda takes the matronizing route in not supporting hiding there in the first place.  Of course, a better error message would be helpful!

- The case is different for instance arguments: `{{A}} -> B` would make sense since Agda can infer the implicit argument by instance search.

**Comment by UlfNorell** [comment]
I think part of the reason for it not being allowed is that it's a bit tricky to get it to parse unambiguously (although, I can't see any obvious ambiguities at the moment). Feel free to have a go at the parser and submit a PR.

**Comment by ghost** [comment]
Hello!

I always felt like a good reason to require implicit parameters (instance or otherwise) to have a name was to allow users to pass in arguments for the parameter more easily in functions with multiple implicit parameters.

If the person writing the function really does not care for that, then I feel like they should need to be explicit about it and give the parameter the name `_` (as it is currently possible).

**Comment by andreasabel** [comment]
Well, personally I name even most explicit arguments, since this has benefits for case-splitting (`C-c C-c`) and provides some rudimentary documentation.

But from a UX and learning perspective it is better to not have seemingly arbitrary restriction in a language.  If `A -> B` is supported by the syntax, then `{A} -> B` should be supported by the syntax as well.  If one wants to discourage the user from using it, one can give a warning.

**Comment by andreasabel** [comment]
Implementation of this feature was trivial, see PR #3915.
