### ISSUE TITLE
Print also hidden problematic unification terms

### ISSUE THREAD

**Issue by ggreif** [agda/agda#3943]
Agda version 2.6.0.1

``` agda
{- # OPTIONS --guardedness #-}

data Thrist {A : Set} (P : A -> A -> Set) : A -> A -> Set where
  nil : ∀ {a} -> Thrist P a a
  cons : ∀ {a b c} -> P a b -> Thrist P b c -> Thrist P a c

record Stream (A : Set) : Set where
  coinductive
  field
    hd : A
    tl : Stream A

open Stream

repeat : ∀ {A} → A → Stream A
hd (repeat x) = x
tl (repeat x) = repeat x

data _↓_ : ∀ {A} -> Stream A -> Stream A -> Set where
  forever : (A : Set) (x : A) -> repeat x ↓ repeat x


module Test1 where
  import Relation.Binary.PropositionalEquality as Eq
  open Eq using (_≡_)

  t2 : (A : Set) -> (x : A) -> Thrist _↓_ (repeat x) (repeat x) -> Thrist _↓_ (repeat x) (repeat x)
  t2 A x nil = cons (forever A x) nil
  t2 A x (cons x1 www) = {!!}
```
Try case-splitting on `x1`. You get
```
I'm not sure if there should be a case for the constructor forever,
because I get stuck when trying to solve the following unification
problems (inferred index ≟ expected index):
  {_} ≟ {_}
  repeat x₁ ≟ repeat x₂
  repeat x₁ ≟ b₁
when checking that the expression ? has type
Thrist _↓_ (repeat x) (repeat x)
```
Where does the `{_} ≟ {_}` constraint come from?

**Comment by jespercockx** [comment]
The `{_} ≟ {_}` constraint comes from the first (implicit) index of the `_↓_` datatype. The braces `{}` indicate the fact that it is implicit, but I'm not sure why Agda prints them as `_` rather than the actual term (I've seen this happen before). It goes away if you turn `A` into a parameter instead of an index, though.

The real reason why Agda cannot figure out the unification problem is because it doesn't see why `repeat` should be injective. However, there is a workaround: you can first prove `t2' : (A : Set) -> (s : Stream A) -> Thrist _↓_ s s -> Thrist _↓_ s s` for a general element `s : Stream A`, and then let `t2 A x = t2' A (repeat x)` (I'm not sure if that helps in the full version of your code, though).

**Comment by nad** [comment]
@jespercockx, why did you leave this issue open?

**Comment by jespercockx** [comment]
I was thinking we should improve the printing of unification problems so you can actually see the terms instead of just `_`.

**Comment by andreasabel** [comment]
@jespercockx  wrote:
> I'm not sure why Agda prints them as _ rather than the actual term (I've seen this happen before)

I'd say this is due to
https://github.com/agda/agda/blob/f21ed8c2fa088a5bc238dafe4c8cb5794d4d4e42/src/full/Agda/Syntax/Translation/InternalToAbstract.hs#L795-L799

**Comment by jespercockx** [comment]
Right, but the current situation where we print `{_}` is a bit crazy: either you want to not see anything, or else you want to see the actual term. Maybe we should disable this code for hidden arguments but leave it in for irrelevant ones?

**Comment by andreasabel** [comment]
Well, if you drop `{_}` entirely, you produce ill-formed terms sometimes, because the position of subsequent hidden arguments shifts.

**Comment by andreasabel** [comment]
In PR #3975 I changed the printer of unification constraints to look into hidden and irrelevant `Arg`.
