### ISSUE TITLE
Agda overwrites user-written dotted pattern

### ISSUE THREAD

**Issue by gallais** [agda/agda#3964]
```agda
open import Agda.Builtin.Equality
open import Agda.Builtin.Sigma

module _ {X : Set} {x : X} where

  test : (p q : Σ X (x ≡_)) → p ≡ q
  test (.x , refl) (z , q) = {!!}

-- C-c C-c q RET:
-- WAS: test (_ , refl) (_ , refl)
-- WANT: preserved user-written pattern
--       test (.x , refl) (_ , refl)


  test' : (p q : Σ X (x ≡_)) → p ≡ q
  test' (x , refl) (z , q) = {!!}

-- here it's fine!
-- C-c C-c q RET gives us:
-- test' (x , refl) (.x , refl) = {!!}
```

**Comment by jespercockx** [comment]
The problem is that Agda does not pick the right name for the variable `x` in the internal telescope of the clause: it is named `proj₁` (after the name of the field of `Σ`) rather than `x` (after the module parameter). When it prints back the clause after case splitting, it sees the dot pattern `.proj₁` where `proj₁` is a variable that's not in scope, so it replaces it by `._`, which is subsequently replaced by just `_`.

I have an attempt at a fix in https://github.com/jespercockx/agda/tree/issue3964, however this breaks the test case for #2183:
```agda

module _ (n : Nat) where

  foo : (m : Nat) → n ≡ m → Nat
  foo m refl = {!m!}
```
Case splitting on `m` should produce 
```agda
  foo zero refl = {!!}
  foo (suc m) refl = {!!}
```
but with my changes, the second clause is `foo (suc n) refl = {!!}` instead, shadowing the module parameter. Internally, the clause `foo m refl = {!m!}` has only one argument in its telescope, which is named both `n` and `m`. My new implementation arbitarily chooses `n`, which is then also used as the name of the recursive argument after the case split.

The frustrating part is that I cannot even explain *why* this is wrong, only the end result is not what we want.

The tracking of variable names during LHS checking has been a pain point for a long time: they are only propagated as raw strings in the clause telescope, and then fixed up after the fact using the user patterns. What we really need is a telescope where each variable is annotated with a list (or set) of user-provided abstract names in addition to the name we have now. Perhaps the time is finally there to make this change.
