### ISSUE TITLE
GHC 8.0.2 not warning for incomplete matches

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#3977]
See https://travis-ci.org/agda/agda/builds/569450616: GHC 8.0.2 does not warn about incomplete matches but newer versions do. 

I think this was introduced by https://github.com/agda/agda/commit/dc12aff892506d53ec61c03308b44a7a57908a02#diff-b771849a88d590a1da0b3a183b4f2be7, though I'm not sure what's wrong exactly.

**Comment by L-TChen** [comment]
:-( 

It looks like a GHC bug. Switching manually these flags is already problematic, as you can see from the comment. 

Is it possible for you to update your GHC to at least 8.2.2 to avoid this bug?

**Comment by jespercockx** [comment]
I could, but I'd rather not as long as we're still supporting 8.0.2. In the past, I've been burned too often by accidentally using some newer GHC feature that's not available in an older version, so now I prefer to stay on the oldest one we still support.

(We *could* have a discussion about dropping support for 8.0.2, but note that it is still the default GHC version in the latest LTS release of Ubuntu, and the next LTS is not here until next spring.)

**Comment by L-TChen** [comment]
I am not sure what the best practice should be in this case. 

As It mainly affects developers instead of end users,  dropping support for 8.0.2 entirely sounds too eager. It makes sense to me to use GHC 8.2.2 or later to develop but make sure that Agda is compatible with 8.0.2. 

Reverting back to the earlier `Agda.cabal` is an option. However, as I played with these GHC options last time, I didn't figure out how to turn on `unused-xxx` warnings with `-Werror` on.

**Comment by jespercockx** [comment]
Maybe we should then leave those warnings off until we drop support for 8.0.2, since it's more important to get errors for incomplete matches than warnings for unused definitions.

**Comment by L-TChen** [comment]
Okay, I will revert those changes later.
