### ISSUE TITLE
Irrelevant message for definition preceeding a top-level module  

### ISSUE THREAD

**Issue by mechvel** [agda/agda#4045]
This is on Agda 2.6.0.1, ghc-8.6.3.
Type checking of 
```
import M1 
...
f : Foo 
f = ...

module M where
...
```
produces a report
```
Failed to find source of module  M1  in any of the following locations:
...
```
Probably it needs to be "A definition before the top-level module ...".
?

**Comment by nad** [comment]
Consider the following code:
```agda
postulate

  A : Set

module M where
```
If you place this code in `M.agda` (and use `agda --no-libraries M.agda`), then you get the following error message:
```
Illegal declaration(s) before top-level module
```
However, if you place the code in `M2.agda`, then the code is accepted, because then `M` is a local module in the module `M2`.

I'm not sure I agree with this design, but I think what you see is intended.
