### ISSUE TITLE
Reflection: 'inferType' fails on functions

### ISSUE THREAD

**Issue by palkarz** [agda/agda#4117]
In the following code Agda is unable to infer types for the first three tests (only `namedWithPatternsTest` passes). 
```Agda
open import Agda.Builtin.Reflection
  renaming (bindTC to _>>=_)
open import Agda.Builtin.Unit

macro
  getTermType : Term → Term → TC ⊤
  getTermType fill hole = do
    type ← inferType fill
    unify type hole

named : ⊤ → ⊤ 
named x = tt

namedWithPatterns : ⊤ → ⊤
namedWithPatterns tt = tt

module Tests where

  unnamedTest : Set
  unnamedTest = getTermType (λ (t : ⊤) → tt)

  namedTest : Set
  namedTest = getTermType named

  unnamedWithPatternsTest : Set
  unnamedWithPatternsTest = getTermType (λ { tt → tt })

  namedWithPatternsTest : Set
  namedWithPatternsTest = getTermType namedWithPatterns
```
The reported failure is 
```
———— Errors ————————————————————————————————————————————————
Failed to solve the following constraints:
  unquote (λ hole → inferType _45 >>= (λ type → unify type hole))
  Set₁ = univSort (piSort _31 (λ _ → Set))
  piSort _31 (λ _ → Set) = Set
  Has bigger sort: piSort _31 (λ _ → Set)
  Set₁ = univSort (piSort _20 (λ _ → Set))
  piSort _20 (λ _ → Set) = Set
  Has bigger sort: piSort _20 (λ _ → Set)
```

**Comment by jespercockx** [comment]
Note that for `unnamedWithPatternsTest`, Agda already fails to infer the type of `λ { tt → tt }` without any macros involved. However, at least in the first two examples the macro should be able to return the inferred type.

**Comment by UlfNorell** [comment]
The reason `namedTest` failed was automatic inlining. Adding a `{-# NOINLINE named #-}` would have solved that. Now automatic inlining is turned off by default, so this succeeds. `unnamedTest` fails since we don't have typed lambda in the reflected syntax. I don't think it's worth adding it since it would complicate code manipulating reflected syntax, and you can work around it using named functions as above, or a "type annotation" identity function.
