### ISSUE TITLE
Agda gets confused by multiple anonymous definitions in a single mutual block

### ISSUE THREAD

**Issue by nad** [agda/agda#4157]
The following code is rejected:
```agda
mutual

  _ : Set₁
  _ = Set

  _ : Set → Set
  _ = λ A → A
```
Error message:
```
Set₁ !=< Set → Set
when checking that the expression Set has type Set → Set
```
It seems as if the second type signature is used when checking the first body.

Note that this kind of code is handled in a sane way when "new-style" mutual blocks are used:
```agda
_ : Set₁

_ : Set → Set

_ = Set

_ = λ A → A
```
```
Duplicate definition of _
```

**Comment by nad** [comment]
I stumbled over this problem again. Here is another test case:
```agda
open import Agda.Builtin.Equality

mutual

  F : Set → Set
  F = _

  _ : F ≡ λ A → A
  _ = refl

  G : Set → Set
  G = _

  _ : G ≡ λ A → A → A
  _ = refl
```

**Comment by andreasabel** [comment]
The problem is that `mutual` blocks are processed by the nicifier, which works with concrete names.  The explicit mutual block is turned into a new-style block _after_ it passed the nicifier.  This means you get the behavior of the new-style mutual block without the duplicate-definition warning.  An while the OP could make sense with old-style mutual blocks, it does not (robustly) make sense with a new style mutual block.

Interestingly, since 11 years we have `NoName` with a `NameId` also in concrete syntax (aafb9bdd4a22ea9af9ef76099dca86218085fec5).  If we could utilize them in the nicifier, we could fix the OP (to work, rather to complain about duplicate ids).

UPDATE: Indeed, this is how I fixed it: Assign unique `NameId`s to `NoName`s which are `LoneSig`s.
