### ISSUE TITLE
pattern matching in parametrized module leads to ill-typed definitions in where modules.

### ISSUE THREAD

**Issue by Saizan** [agda/agda#4163]
The following code leads to `TM.foo` being assigned a wrong type from inside the `Inner` module:

```agda
open import Agda.Builtin.Nat

data InU : Set → Set₁ where
  con : (X : Set) (B : X → Set) → InU ((x : X) → B x)

module Inner  (n : Nat) where

  bar : ∀ X → InU X → Set
  bar _ (con A B) = foo
    module TM where
      foo : Set
      foo = A

  test = {! TM.foo !}
```

`C-c C-d` reports `(n → Set) → Nat → Set` from inside the goal in `test`.

`C-c C-d Inner.TM.foo` reports a seemingly correct `(A₁ : Set) → (A₁ → Set) → Nat → Set`

Although it's a bit surprising that the `Nat` got moved to last place.

**Comment by andreasabel** [comment]
Works fine in 2.5.1.1 and below.  Broken from 2.5.2.

**Comment by sattlerc** [comment]
Here is a simplified test case.
```agda
postulate
  A B C I : Set
  b : B

data T : I → Set where
  con : (i : I) → T i

module M (a : A) where
  bar : (i : I) → T i → B
  bar .i (con i) = b
    module N where
      postulate
        foo : C

  -- Should not be accepted.
  -- Type signature should be 'I → C'
  test : A → C
  test = N.foo
```
This is accepted, but should be rejected.

**Comment by sattlerc** [comment]
And here is the obligatory inconsistency proof.
```agda
data ⊥ : Set where

record ⊤ : Set where
  constructor unit

data T : ⊥ → Set where
  con : (i : ⊥) → T i

module M (_ : ⊤) where
  bar : (i : ⊥) → T i → ⊥
  bar .i (con i) = i
    module N where
      foo : ⊥
      foo = i

  test : ⊤ → ⊥
  test = N.foo

false : ⊥
false = M.test unit unit
```
Perhaps this proof of false can be used as a workaround to several other Agda bugs.

**Comment by nad** [comment]
Given that this bug is rather serious, perhaps we should consider fixing it before 2.6.1 is released.

**Comment by jespercockx** [comment]
It seems the cause of this problem is an incomplete fix of https://github.com/agda/agda/issues/2897: the previous fix disallows named where modules if a parameter has been refined, but the example here shows that things can still go wrong if they are only reordered.

There are several things we could do here:
- Disallow named where modules if the module parameters have been reordered by pattern matching
- Change the pattern matching unifier so it keeps the order of the module parameters when they are not refined
- Give a better implementation of `instantiateDef` that can handle the cases where module parameters have been reordered and/or refined (hard)

cc @UlfNorell
