### ISSUE TITLE
Question about @0

### ISSUE THREAD

**Issue by nad** [agda/agda#4181]
Consider the following code:
```agda
postulate
  F : Set → Set

Works : Set₁
Works = (@0 A : Set) → F A

@0 Id : Set → Set
Id A = A

Fails : Set₁
Fails = (@0 A : Set) → F (Id A)
```
Agda accepts `Works`, but not `Fails`:
```
Identifier Id is declared erased, so it cannot be used here
when checking that the expression Id A has type Set
```
In `Works` `A` is erased. Why is that type OK, if `Fails` is not?

**Comment by UlfNorell** [comment]
As discussed in the proglog meeting this is the expected behaviour.

The `@0` annotation for the bound `A` in the domain of the function type applies to uses in the body of a function of that type, not to uses in the codomain. In contrast, `Id` is declared to be `@0` and cannot be used in a right-hand side.

One could imagine having special rules for function types, but you would get the same problem for other type constructors.
