### ISSUE TITLE
Fail when running `cabal repl`

### ISSUE THREAD

**Issue by asr** [agda/agda#4241]
I realised that there are `*.ghci` files for every supported version of GHC:

```bash
$  ls .ghci*
.ghci  .ghci800  .ghci820  .ghci860
```
I'm not familiar using Agda from GHCi/cabal repl. Using `cabal repl` I got the following error:

```bash
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.6.5

$ cabal -- version
cabal-install version 2.4.1.0
compiled using version 2.4.1.0 of the Cabal library 

$ cabal repl
...
setup: The 'repl' command does not support multiple targets at once.
```

@erydo, since you are the author of the '.ghci' files, I assigned you this issue.

**Comment by asr** [comment]
I had the same problem with GHC 8.8.3 and 8.10.1.

**Comment by rwe** [comment]
Wow, sorry! I did not even see that I was tagged here…

Googling for the error led me to these:
* https://github.com/haskell/haskell-mode/issues/458
* https://github.com/haskell/cabal/issues/4602

The issue is not related to the `.ghci` files: if you're going to use `cabal repl`, I believe you need to specify a target like `cabal repl lib:agda`.

Later versions of Cabal like 3.2.0.0 do not seem to have this issue with multi-target packages, so if you're running 2.4, you might be able to use `cabal new-repl` instead of specifying the package directly.

Let me know if that works for you.

**Comment by asr** [comment]
Using `cabal repl` from `cabal-install` 3.2.0.0 and GHC 8.10.1 works. Thanks!
