### ISSUE TITLE
Give triggers internal error

### ISSUE THREAD

**Issue by sattlerc** [agda/agda#4256]
On master (36b9448).
```agda
postulate
  admit : ∀ {i} {X : Set i} → X
  X Y Z : Set

data Id (z : Z) : Z → Set where
  refl : Id z z

record Square : Set₁ where
  field
    U : Set
    u : U
open Square

record RX : Set where
  field
    x : X
open RX

record M : Set where
  -- This module isn't used; without it, the internal error disappears.
  module _ where
    r : Square
    r .U = admit
    r .u = admit

  foom : (z₀ z₁ : Z) → Id z₀ z₁ → RX
  foom z₀ z₁ = f
    where
    f : Id z₀ z₁ → RX
    f refl = {!λ where .x → ?!}
```

Giving triggers the following internal error:
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Monad/Signature.hs:900
```

**Comment by andreasabel** [comment]
This worked fine until 2.6.0.  In principle, the offending patch can be found with agda-bisect, however, since this is an interactive error, the expert mode of agda-bisect is needed.

**Comment by nad** [comment]
Search the issues for `runAgda` for examples of how issues related to interaction can be handled by `agda-bisect`.

**Comment by UlfNorell** [comment]
The problem was that the termination checker tried to get the types of the functions to be termination checked applied to module parameters, but termination checking starts with a `inTopContext`, putting the current context and the current module out of sync.

Not quite sure why this was so hard to trigger.

PR: #4279
