### ISSUE TITLE
File order of checking matters (record disambiguation)

### ISSUE THREAD

**Issue by sattlerc** [agda/agda#4267]
On master (36b9448).

Create files A0.agda, A1.agda, B.agda, and C.agda with the following content.
* A.agda:
```agda
module A0 where

record RA0 : Set₁ where
  field
    A : Set

postulate
  T : RA0 → Set
```
* A1.agda:
```
module A1 where

record RA1 : Set₁ where
  field
    A : Set
```
* B.agda:
```
module B where

open import A0

record RB : Set₁ where
  field
    B : Set

  -- Crucial for bug: omitting signature of ra,
  -- letting Agda infer its type.
  ra = record {A = B}
  field
    t : T ra
```
* C.agda:
```
module C where

open import A0
open import A1
open import B
```

Removing all interface files and running `agda C.agda` gives an error:
```
Checking C (C.agda).
 Checking A0 (A0.agda).
 Checking A1 (A1.agda).
 Checking B (B.agda).
C.agda:5,1-14
Unsolved constraints
when scope checking the declaration
  open import B
C.agda:5,1-14
Unsolved metas at the following locations:
  B.agda:11,3-5
  B.agda:11,8-22
when scope checking the declaration
  open import B
```

Removing all interface files and running `agda B.agga` followed by `agda C.agda` goes through:
```
$ agda B.agda
Checking B (B.agda).
 Checking A0 (A0.agda).
$ agda C.agda
Checking C (C.agda).
 Checking A1 (A1.agda).
```

It looks like the code doing disambiguation of `record {...}` expressions has weird scoping issues, taking into account ambiguity with module files that are not even imported. This seems to happen when the module file containing the `record {...}` expression and a module file in whose scope the expression would be ambiguous are imported in a third module file and that file is the typechecking target.

**Comment by sattlerc** [comment]
Here is a simplified example.

* A0.agda:
```agda
module A0 where

record RA0 : Set₁ where
  field
    A : Set
```
* A1.agda:
```agda
module A1 where

record RA1 : Set₁ where
  field
    A : Set
```
* B.agda:
```agda
module B where

open import A0

postulate
  X : Set

-- Crucial for bug: omitting signature of ra,
-- letting Agda infer its type.
ra = record {A = X}
```
* C.agda:
```agda
module C where

open import A0
open import A1
open import B
```

**Comment by andreasabel** [comment]
I don't find this behavior surprising given how record type guessing is implemented: https://github.com/agda/agda/blob/4f3156b40ea931911c624010df12f1ba56921dc9/src/full/Agda/TypeChecking/Records.hs#L133-L148
It ignores scope entirely.  This has been since the original implementation of the feature in 5ada65958250c45929ca27d46277f14e035eefd5 .

One problem in fixing is that one cannot really use scope here, as the record field names need not be in scope (as projections) when forming the record expression.  Note that when you write `record {A = X}`, then `A` need not be in scope (and it is not in your case, as the records modules are not opened).

The absurdity is of course that `A1` is imported by `C` and not by `B`.  Agda's import handling is unhygienic as observed in another situation already (don't know if an issue exists already).

A better implementation may be to get all record types in scope and get all their fields.

**Comment by andreasabel** [comment]
PR #4273 fixes this issue by requiring record types for record expressions to be in scope.

**Comment by andreasabel** [comment]
After the change, the following still works:  First, an imported module, declaring a record type:
```agda
module Issue4267.M where

record R : Set₂ where
  field
    f : Set₁
```
Then, in the main module:
```agda
import Issue4267.M using ()

foo = record { f = Set}
```
Thus, even though we cannot write the type `Issue4267.M.R`, Agda can infer it.  

This behavior seems conservative enough.  I am going ahead and commit the PR.

**Comment by nad** [comment]
I'm not sure I agree that this change (as opposed to what you propose in #4272) is a good idea. It is perfectly fine for Agda to infer types that are not in scope (not even qualified). Why should record expressions be treated differently?

If we decide to keep this change, then it should be documented in the changelog.

**Comment by jespercockx** [comment]
@andreasabel wrote:

> Thus, even though we cannot write the type Issue4267.M.R, Agda can infer it.

So I think that means Agda *can* still infer the type. @nad did you misread what Andreas said?

**Comment by nad** [comment]
Sometimes Agda fails to infer previously inferrable types, some of my code broke. The following code is not accepted:
* `A.agda`:
  ```agda
  module A where

  record R : Set₂ where
    field
      A : Set₁
  ```
* `B.agda`:
  ```agda
  module B where

  open import A

  data U : Set where
    r : U

  El : U → Set₂
  El r = R

  F : (u : U) → El u → Set₁
  F r = R.A
  ```
* `C.agda`:
  ```agda
  module C where

  open import B

  OK : Set₁
  OK = F r (record { A = Set })

  Not-OK : Set₁
  Not-OK = F _ (record { A = Set })
  ```
The code is accepted if `import A using ()` is added to `C.agda` (before `Not-OK`).

**Comment by UlfNorell** [comment]
Call `B` a parent of `A` if `A` imports `B`. Then after the fix we only infer record types from parent modules. The bug was that we inferred record types from sibling and cousin modules, and what @nad is asking for is to infer record types from all ancestor modules.

I think the current behaviour is reasonable and already more liberal than other constructions which require things to actually be in scope.

> It is perfectly fine for Agda to infer types that are not in scope (not even qualified). Why should record expressions be treated differently?

The difference is that in these other cases you have scope checked identifiers driving the inference, whereas in `record { A = Set }` the scope checker has not been involved at all.

**Comment by nad** [comment]
> I think the current behaviour is reasonable and already more liberal than other constructions which require things to actually be in scope.

Perhaps, but if we fix the underlying problem properly (#4272), then we might avoid breaking some users' code.

I don't have a very strong opinion about this. As I wrote above, if we decide to stick to the new behaviour, then this should be documented in the changelog.

**Comment by UlfNorell** [comment]
After fixing #4373 `import Bla using ()` no longer works. The record type needs to be available qualified. I still think this is the right behaviour though. Reopened for discussion.

**Comment by nad** [comment]
I haven't tested anything yet, but it sounds to me as if the new behaviour makes more sense than the previous one.

**Comment by UlfNorell** [comment]
Okay then. Reopen if necessary.

**Comment by asr** [comment]
I added the label `documented-in-changelog` because the issue was documented in the CHANGELOG (good) and it should not be listed by the `closed-issues-for-milestone` program.
