### ISSUE TITLE
Test case for #4169 fails in JS backend

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#4280]
Spawned from #4169

@nad wrote:
```
/jAgda.Issue4169-2.js:90
exports["_NameId 98 9974603751767637182"]["⊥-elim"] = exports["M"]["⊥-elim"](exports["r₁"])(exports["r₂"]);
                                                                            ^

TypeError: exports.M.⊥-elim is not a function
    at Object.<anonymous> (/jAgda.Issue4169-2.js:90:77)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

Here is the generated definition of exports.M.⊥-elim:

```
exports["M"]["⊥-elim"] = undefined;
```

**Comment by andreasabel** [comment]
Seems like absurd matches are not eta-expanded enough:
```agda
module M r₁ r₂ where

  ⊥-elim : {A : Set} → ⊥ → A
  ⊥-elim ()

  p : P ⊥
  p x = ⊥-elim x
```
is translated into
```js
exports["M"]["p"] = a => b => exports["M"]["⊥-elim"](a)(b)(null)(null);
...
exports["M"]["⊥-elim"] = undefined;
```
Debug output `js.compile:30`:
```
compiling fun: M.⊥-elim
 compiled treeless fun: error "TUnreachable"
 compiled JS fun: Undefined
```

**Comment by andreasabel** [comment]
The treeless compiler doesn't take any typing into account so all it sees is `⊥-elim = Fail` and it has no information about the usage of arguments (as the arity is 0) so it thinks that all arguments are used.

Instead of patching around in the backend we should fix the "middle-end", the treeless compiler, to at least transport a reliable notion of arity for each defined function (better would be a simple type).

When compiling to a lazy language, the arity is not so important, since you can apply `undefined` to arguments, but JS isn't forgiving here.

Fazit:  This is really a treeless issue, not a backend issue.  Treeless gives the wrong information about used arguments about `M.⊥-elim`:  It gives `[]` (all argument are used) rather than `replicate 4 ArgUnused` (really none of the arguments is used).

**Comment by UlfNorell** [comment]
I don't see why we would need to carry this information through treeless. The backend has access to the signature and can look up the complete type of `⊥-elim` if it so chooses.

**Comment by andreasabel** [comment]
> I don't see why we would need to carry this information through treeless. The backend has access to the signature and can look up the complete type of `⊥-elim` if it so chooses.

As this can be done in the middle-end once, I don't think it should be burdened upon each backend.

See the [golden rule of software quality](https://www.haskellforall.com/2020/07/the-golden-rule-of-software-quality.html):
> Prefer to push fixes upstream instead of working around problems downstream

The middle-end is upstream here, the backends are downstream.  They should get better material to work with from the treeless compiler.  

In particular, the _argument usage_ information should be correct.  It isn't so for `⊥-elim`, though.  Treeless gives `[]`, which means that all arguments are supposedly used.  Correct would be a list containing `ArgUnused` for all arguments which are unused.
