### ISSUE TITLE
Agda can't infer level of a generalized Set variable.

### ISSUE THREAD

**Issue by semenov-vladyslav** [agda/agda#4367]
```agda
module Test where

open import Agda.Primitive using (Level; _⊔_; lsuc)

Pred : ∀ {a} → Set a → (ℓ : Level) → Set (a ⊔ lsuc ℓ)
Pred A ℓ = A → Set ℓ

private
  variable
    a p : Level
    A : Set a

data Y {A : Set a} (P : Pred A p) : Pred A (a ⊔ p) where

module _ {A : Set a} {P : Pred A p} where
  ok : A → Set (a ⊔ p)
  ok = Y P

module _ {P : Pred A p} where
  fail : A → Set (a ⊔ p)
  fail = Y P
  {-
A.a != p of type Level
when checking that the inferred type of an application
  A → Set (A.a ⊔ p)
matches the expected type
  A → Set (p ⊔ a)
  -}
```

Agda version 2.6.1-ab2cd05-dirty

**Comment by UlfNorell** [comment]
The reason for this is that the module telescope and the type signature of `fail` are generalized separately. So, first the module telescope is generalized to
```
module _ {A.a : Level} {A : Set A.a} {p : Level} {P : Pred A p} where
```
then the type of `fail` is generalized to
```
fail : {a : Level} → A → Set (a ⊔ p)
```
Note that there is no connection between the generalized `a` in the type of `fail` and the `A` from the module telescope.

In contrast, the `ok` case works because there no generalization happens in the type signature. All variables have been bound already in the module telescope.
