### ISSUE TITLE
Inconsistency with rewrite rules and assumptions in Prop

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#4371]
It seems like rewrite rules do not always check whether assumptions in Prop are bound in the left-hand side, see function `ok` the code below. Note that defining `ok` directly by an absurd pattern does fail as expected. Defining `⊥` as a `Set` instead of a `Prop` also makes it fail as expected.

```agda
{-# OPTIONS --rewriting --prop #-}

open import Agda.Builtin.Nat

data ⊥ : Prop where

data _≡_ {A : Set} (x : A) : A → Set where
  refl : x ≡ x
{-# BUILTIN REWRITE _≡_ #-}

infix 4 _≡_

⊥-elim : {A : Set} → ⊥ → A
⊥-elim ()

ok : (n : Nat) (p : ⊥) → (n + n) ≡ 0
ok n p = ⊥-elim p

{-# REWRITE ok #-}

notok : (n : Nat) → n + n ≡ 0
notok n = refl

absurd : 2 ≡ 0
absurd = notok 1
```

**Comment by jespercockx** [comment]
It's weird that defining `ok` directly with an absurd pattern does lead to the expected error message. Looking at the debug output, it seems that the rewriting machinery is doing the right thing but there is a mistake in the occurs check in the body of `ok`: the argument `p` is considered to be unused. Probably the reason is that internally it is hidden beneath a `dontCare` constructor. Working on a fix...
