### ISSUE TITLE
Confluence checking and parametrised modules

### ISSUE THREAD

**Issue by bafain** [agda/agda#4383]
In the following code the confluence checker warns about an inequality that seems to hold in the same scope:
```
{-# OPTIONS --rewriting        #-}
{-# OPTIONS --confluence-check #-}
module Error where

open import Agda.Builtin.Equality
open import Agda.Builtin.Equality.Rewrite

module _ (_ : Set) where
  postulate
    D : Set
    f : D → D → D
    r : (x y z : D) → f x (f y z) ≡ f x z

  -- WARNS:
  {-# REWRITE r #-}
  -- Confluence check failed: f x (f y (f y₁ z)) reduces to both
  -- f x (f y₁ z) and f x (f y z) which are not equal because
  -- y != y₁ of type D
  -- when checking confluence of the rewrite rule r with itself

  module _ (x y y₁ z : D) where
    -- SUCCEEDS:
    _ : f x (f y₁ z) ≡ f x (f y z)
    _ = refl
```
Agda version: `2.6.1-475c7e5`

**Comment by jespercockx** [comment]
The confluence checker is run `inTopContext`, but despite this fact it seems that it still tries to instantiate rewrite rules to the context of the parametrized module before applying them, which leads to an ill-typed application (the rule `r` is applied to module parameter `z`, which has type `D` instead of `Set`). This then causes the confluence checker to fail. It's actually a wonder that things don't go wrong more badly!

It seems pretty easy to fix this by adding a call to `withCurrentModule` in the confluence checker. However, it seems that this should also be done in other places where we use `inTopContext`, so I will try to modify the definition of `inTopContext` instead and see if this break anything.
