### ISSUE TITLE
Find space leaks

### ISSUE THREAD

**Issue by nad** [agda/agda#4423]
Has anyone tried to apply Neil Mitchell and Tom Ellis' [method for detecting space leaks](https://neilmitchell.blogspot.com/2015/09/detecting-space-leaks.html) to Agda?

**Comment by UlfNorell** [comment]
I have some vague memory that we tried something like this a while back without getting anything useful out. But it might be worth trying again. If nothing else to document the results for posterity.

**Comment by UlfNorell** [comment]
A quick test results in exactly what I remembered. 6,000 lines of this:
```
*** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace: 
  Agda.Utils.FileName.absolute..||.,
  called from Agda.Utils.FileName.absolute,
  called from Agda.Interaction.FindFile.findFile''.fileList,
  called from Agda.Interaction.FindFile.findFile'',
  called from Agda.TypeChecking.Monad.Base.liftIO.wrap,
  called from Agda.TypeChecking.Monad.Base.liftIO.\,
  called from Agda.TypeChecking.Monad.Base.liftIO,
  called from Agda.TypeChecking.Monad.Base.>>=,
  called from Agda.Main.runAgda',
  called from Agda.Main.runAgda,
  called from Agda.Main.main
*** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace: 
  Agda.Utils.FileName.doesFileExistCaseSensitive,
  called from Agda.Interaction.FindFile.findFile'',
  called from Agda.TypeChecking.Monad.Base.liftIO.wrap,
  called from Agda.TypeChecking.Monad.Base.liftIO.\,
  called from Agda.TypeChecking.Monad.Base.liftIO,
  called from Agda.TypeChecking.Monad.Base.>>=,
  called from Agda.Main.runAgda',
  called from Agda.Main.runAgda,
  called from Agda.Main.main
*** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace: 
  Paths_Agda.catchIO,
  called from Paths_Agda.getDataDir,
  called from Paths_Agda.getDataFileName,
  called from Agda.Interaction.Options.defaultLibDir,
  called from Agda.Interaction.Options.Lenses.isBuiltinModule,
  called from Agda.TypeChecking.Monad.Base.>>=,
  called from Agda.Main.runAgda',
  called from Agda.Main.runAgda,
  called from Agda.Main.main
*** Exception (reporting due to +RTS -xc): (base:GHC.Exception.Type.SomeException), stack trace: 
  Agda.TypeChecking.Serialise.decode.ar,
  called from Agda.TypeChecking.Monad.Base.liftIO.wrap,
  called from Agda.TypeChecking.Monad.Base.liftIO.\,
  called from Agda.TypeChecking.Monad.Base.liftIO,
  called from Agda.TypeChecking.Monad.Base.>>=,
  called from Agda.Main.runAgda',
  called from Agda.Main.runAgda,
  called from Agda.Main.main
*** Exception (reporting due to +RTS -xc): (base:GHC.Exception.Type.SomeException), stack trace: 
  Agda.TypeChecking.Monad.Base.catchError_.\,
  called from Agda.TypeChecking.Monad.Base.catchError_,
  called from Agda.TypeChecking.Monad.Base.finally_,
  called from Agda.Utils.Benchmark.billTo,
  called from Agda.Main.runAgdaWithOptions,
  called from Agda.TypeChecking.Monad.Base.fmap,
  called from Agda.TypeChecking.Monad.Base.<*>,
  called from Agda.TypeChecking.Monad.Base.>>,
  called from Agda.TypeChecking.Monad.Base.catchError.\,
  called from Agda.TypeChecking.Monad.Base.catchError,
  called from Agda.TypeChecking.Serialise.decode.ar,
  called from Agda.TypeChecking.Monad.Base.liftIO.wrap,
  called from Agda.TypeChecking.Monad.Base.liftIO.\,
  called from Agda.TypeChecking.Monad.Base.liftIO,
  called from Agda.TypeChecking.Monad.Base.>>=,
  called from Agda.Main.runAgda',
  called from Agda.Main.runAgda,
  called from Agda.Main.main
*** Exception (reporting due to +RTS -xc): (base:GHC.Exception.Type.SomeException), stack trace: 
  Agda.Utils.Impossible.catchImpossibleJust,
  called from Agda.Utils.Impossible.catchImpossible,
  called from Agda.Main.runTCMPrettyErrors,
  called from Agda.TypeChecking.Monad.Base.catchError_.\,
  called from Agda.TypeChecking.Monad.Base.catchError_,
  called from Agda.TypeChecking.Monad.Base.finally_,
  called from Agda.Utils.Benchmark.billTo,
  called from Agda.Main.runAgdaWithOptions,
  called from Agda.TypeChecking.Monad.Base.fmap,
  called from Agda.TypeChecking.Monad.Base.<*>,
  called from Agda.TypeChecking.Monad.Base.>>,
  called from Agda.TypeChecking.Monad.Base.catchError.\,
  called from Agda.TypeChecking.Monad.Base.catchError,
  called from Agda.TypeChecking.Serialise.decode.ar,
  called from Agda.TypeChecking.Monad.Base.liftIO.wrap,
  called from Agda.TypeChecking.Monad.Base.liftIO.\,
  called from Agda.TypeChecking.Monad.Base.liftIO,
  called from Agda.TypeChecking.Monad.Base.>>=,
  called from Agda.Main.runAgda',
  called from Agda.Main.runAgda,
  called from Agda.Main.main
```
The only one I could find that looks interesting (although I didn't look through all 6,000 lines) is `Serialise.decode.ar`, which is this function:
```haskell
  ar l = listArray (0, List.genericLength l - 1) l
```
This looks like a legit space leak, although I guess since we're storing the array in memory it should only be a constant factor overhead to build the entire list.

**Comment by andreasabel** [comment]
> This looks like a legit space leak

Could you explain what is the problem here?  The list is first constructed to compute its length, and then transformed into an array.  Is this a space leak? Temporarily, space for the whole list will be consumed, which can possibly be reclaimed after the array has been built (provided the list is not used otherwhere).

**Comment by UlfNorell** [comment]
Yes, that's what I meant. Most space leaks are only temporary.

**Comment by andreasabel** [comment]
Well, looking at the context where `ar` is used:
https://github.com/agda/agda/blob/e1cd4d0fee11ee76f4ff4612d5c8e447f37f8689/src/full/Agda/TypeChecking/Serialise.hs#L163-L173
I'd be surprised if the lists passed to `ar` are incrementally constructed.  They come from the deserializer which turns a ByteString into a tuple of lists and other stuff.  I'd assume these lists are not lazily constructed.  I mean, how could they, if they come as part of a tuple and the deserializer works left to right through the ByteString?  Or am I on the wrong track?

We could of course _serialize_ these arrays instead of lists, but then we would have to construct the arrays in the serializer instead.  But I have not clue what is more efficient...

(Btw, `runGetState` is deprecated...) UPDATE: Ah, my bad, this is our own implementation of `runGetState`.

**Comment by andreasabel** [comment]
Looking at the `Binary` implementation of:
- lists: https://hackage.haskell.org/package/binary-0.10.0.0/docs/src/Data.Binary.Class.html#line-578
- arrays: https://hackage.haskell.org/package/binary-0.10.0.0/docs/src/Data.Binary.Class.html#line-700

We can see that deserializing arrays goes via lists and `listArray`, thus, it implements a space leak by default (for whatever people consider a space "leak" nowadays --- in the olden days (and in C(++) today), space leaks used to be memory that is allocated but _never_ freed).
It seems the only way to not create a "space leak" when deserializing something into an array is to use a mutable array and directly dump deserialized elements into the array positions?
Or is just temporarily allocating the _spine_ of a list not considered a "space leak"?

That whole concept does not seem to click with me.  Also, in I/O, don't you want to be strict (and "leak space"), because otherwise you will "leak file handles"??

One thing that is of course stupid with the `ar` function is that we compute the `length` or a list that was just deserialized, and the serialized stored the length, and the deserializer used that length to deserialize.  Thus, (de)serializing arrays might still be better than lists, given that we serialize once and deserialize often.

**Comment by andreasabel** [comment]
b01211be1e28e327c67a04f61381a9cded0de10e is an experiment creating the array before serialization instead of after deserialization.  The serializer seems anyway strict in this list, getting it from `IO.HashTable` and subjecting it to `sort`.  Ideally, we could serialize a list as array to save the quite pointless step of creating an array first just to then serialize it.  Serializing a list as array would be a custom putter that should not be hard to write.  However, we should make sure that this complication buys anything at all.

**Comment by UlfNorell** [comment]
I don't expect it will make any difference. I just pointed to that as the only thing I could find that looked like a possible space leak.
