### ISSUE TITLE
"Possible reasons" for unification failure talk incomprehensibly about modalities

### ISSUE THREAD

**Issue by LuKuangChen** [agda/agda#4442]
An internal error has occurred. Please report this as a bug. 
Location of the error: src/full/Agda/TypeChecking/Records.hs:601

**Comment by UlfNorell** [comment]
Do you have a test case? And what version are you running?

**Comment by LuKuangChen** [comment]
I am working on a large project, not sure which part causes the error.
I will come back when I find a simpler test case.
The version is 2.6.0.1

**Comment by LuKuangChen** [comment]
Loading M1 gives the same error message. There are two Agda files (M1.agda and M2.agda).

M1.agda
```agda
open import Data.Bool

module M1
  (Link : Bool → Bool → Set)
  (id : (I : Bool) → Link I I)
  where

module L where
  data Data : Bool → Bool → Set where

module R where
  open import M2 Link public

mutual
  data Rel : ∀ {I1 I2} → L.Data I1 I2 → R.Data I1 I2 → Set where
    rel : ∀ {I3 lk rk}
      → (k : PreRel {I3} lk rk)
      ---
      → Rel lk (R.ccc (id _))
    
  data PreRel {Z} : ∀ {S} → L.Data S Z → R.PreData → Set where
  
f : ∀ {I1 I2}
  → {lk : L.Data I1 I2}
  → {rk : R.Data I1 I2}
  → Rel lk rk
  → Rel lk rk
f (rel k) = {!!}
```

M2.agda
```agda
open import Data.Bool

module M2
  (Link : Bool → Bool → Set)
  where

  data PreData : Set where

  record Data (I1 I2 : Bool) : Set where
    constructor ccc
    field
      {I} : Bool
      c   : Link I1 I
```

**Comment by LuKuangChen** [comment]
BTW, changing the record definition in M2 to a data definition fix the problem.

**Comment by andreasabel** [comment]
On the development version, there is no internal error.  Instead:
1. The reference to `PreRel` in `Rel` is yellow, there is an unsolved meta standing in for `S`.
2. Because of this, the  pattern match `f (rel k)` fails with error:
```
I'm not sure if there should be a case for the constructor rel,
because I get stuck when trying to solve the following unification
problems (inferred index ≟ expected index):
  {_S_28 (Link = Link) (id = id)} ≟ {I1}
  {I3} ≟ {I2}
  lk ≟ lk₁
  R.ccc (id (_S_28 (Link = Link) (id = id))) ≟ rk
Possible reasons why unification failed:
  Cannot solve variable I of type Bool with solution
  _S_28 (Link = Link) (id = id) because the solution cannot be used
  at relevant, unrestricted modality
  Cannot solve variable I1 of type Bool with solution
  _S_28 (Link = Link) (id = id) because the solution cannot be used
  at relevant, unrestricted modality
when checking that the pattern rel k has type Rel lk rk
```
What is worrying: the possible reasons talk about `the solution cannot be used at relevant, unrestricted modality` without there being any modalities involved in the source code.

**Comment by jespercockx** [comment]
> What is worrying: the possible reasons talk about `the solution cannot be used at relevant, unrestricted modality` without there being any modalities involved in the source code.

Is it because metas created at the type level are created as being "erased", which means they cannot be used in non-erased positions? Maybe one way to fix it would be to instead 'promote' the erased meta by creating a new meta of the same type that is not erased, and instantiating the erased one with it.

**Comment by UlfNorell** [comment]
For reference, this is the reason: #4174. And the issue for improving the situation is #4366.

Closing as duplicate.

**Comment by andreasabel** [comment]
Moved milestone 2.6.1 over to #4366.
