### ISSUE TITLE
Highlighting: use several lookups rather than merging hash-maps?

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#4451]
Coming across this code
https://github.com/agda/agda/blob/74d9fd53cd79e1d947b57952760946d24c8cfa8d/src/full/Agda/Interaction/Highlighting/Generate.hs#L451-L460
I wonder whether merging hash-maps to build a lookup function is a good idea performancewise, in particular if the maps can be big (all imports) and the lookups can be few (just looking up names contained in one declaration).  Wouldn't it be better merge the results of the individual look-ups instead?
As usual with laziness such questions are difficult to answer, but I doubt strict hashmaps have optimal lazy merging.  (Here, consider also that the merging is directed by the given structures of these maps and not the queries the merged map gets.)
The structure of the above code (merging to obtain a lookup function) comes from a 11-year old [commit](https://github.com/agda/agda/commit/3460f07ee474e65f71dd238fceb8fcd12f5ea4bb#r37326433). 
@nad, would you still write it like this today?

**Comment by nad** [comment]
Things have changed quite a bit since I wrote that code: I think that we used to run `nameKinds` at most once per module. Furthermore we used to use `Data.Map`, for which the time complexity of `union` is (now) described in the following way: ["O(m*log(n/m + 1)), m <= n"](https://hackage.haskell.org/package/containers-0.6.2.1/docs/Data-Map-Lazy.html#v:union).

**Comment by andreasabel** [comment]
It seems like the time spent on highlighting the standard library is reduced to 40% by this simple refactoring.

**Comment by nad** [comment]
Good catch.
