### ISSUE TITLE
Internal error if files cannot be written to the directory for temporary files

### ISSUE THREAD

**Issue by oisdk** [agda/agda#4516]
On typecheck I get the following error:

```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Monad/Base.hs:4124
```

However it only happens from within emacs, i.e. if I run `agda Test.agda` there is no problem.

**Comment by sattlerc** [comment]
Please supply additional information:
- a test case exhibiting the behaviour,
- the version of Agda you are using (`agda --version`).

**Comment by oisdk** [comment]
* Agda --version: 2.6.1
* Compiled from current commit (f7c0c359cd4ea0457bbd38c1e2c6a878ce8f9531) with `cabal v2-install`
* Test case: in `Test.agda`

```
module Test where
```

`agda2-load`

**Comment by oisdk** [comment]
It turned out to be an error with spacemacs (https://emacs.stackexchange.com/questions/51684/getting-permissions-errors-related-to-var-folders-directory-after-doing-mac-mig)

**Comment by nad** [comment]
Agda shouldn't raise an internal error if the problem is related to the file system.

> ```
> Location of the error: src/full/Agda/TypeChecking/Monad/Base.hs:4124
> ```

https://github.com/agda/agda/blob/f7c0c359cd4ea0457bbd38c1e2c6a878ce8f9531/src/full/Agda/TypeChecking/Monad/Base.hs#L4120-L4124

This definition is used once:

https://github.com/agda/agda/blob/f7c0c359cd4ea0457bbd38c1e2c6a878ce8f9531/src/full/Agda/Interaction/InteractionTop.hs#L135-L139

This definition is also used once:

https://github.com/agda/agda/blob/b0f6962faa05343451c076a92a428e1bba24096d/src/full/Agda/Interaction/InteractionTop.hs#L228-L244

I'm wondering if the problem is that an error is raised in `handleErr`:

https://github.com/agda/agda/blob/b0f6962faa05343451c076a92a428e1bba24096d/src/full/Agda/Interaction/InteractionTop.hs#L246-L271

I guess that in this case `putResponse` failed because an attempt is made to write highlighting information to a file. Perhaps the `method` should always be `Direct` in this error handler.

I managed to recreate the error message:
```
$ echo "module Set where" > Test.agda
$ echo 'IOTCM "Test.agda" None Indirect (Cmd_load "Test.agda" [])' | agda --interaction --no-libraries
Agda2> (agda2-info-action "*Error*" "/tmp/Test.agda:1,8-8\n/tmp/Test.agda:1,8: Parse error\nSet<ERROR>\n where\n..." nil)
((last . 3) . (agda2-maybe-goto '("/tmp/Test.agda" . 8)))
(agda2-highlight-load-and-delete-action "/tmp/agda2-mode1875-0")
(agda2-status-action "")
Agda2> $ 
$ echo 'IOTCM "Test.agda" None Indirect (Cmd_load "Test.agda" [])' | TMPDIR=/non-existent agda --interaction --no-libraries
Agda2> (agda2-info-action "*Error*" "/tmp/Test.agda:1,8-8\n/tmp/Test.agda:1,8: Parse error\nSet<ERROR>\n where\n..." nil)
((last . 3) . (agda2-maybe-goto '("/tmp/Test.agda" . 8)))
(agda2-info-action "*Error*" "An internal error has occurred. Please report this as a bug.\nLocation of the error: src/full/Agda/TypeChecking/Monad/Base.hs:4124\n" nil)
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Monad/Base.hs:4124
```

Another way to make `handleErr` fail would be to set things up so that Agda cannot write to stdout, but in that case the "internal error" message is presumably not delivered to the user.
