### ISSUE TITLE
[reflection] quoteTerm _∷_ does not typecheck

### ISSUE THREAD

**Issue by pnlph** [agda/agda#4523]
In the following code the first underscore typechecks but the second one not, any ideas why?
```haskell
open import Data.Nat using (zero)
open import Data.Vec using (_∷_)
open import Agda.Builtin.Equality using (_≡_; refl)
open import Agda.Builtin.Reflection using (con)
open import Data.List using ([])

_ : quoteTerm zero ≡ con (quote zero) []
_ = refl

_ : quoteTerm _∷_ ≡ con (quote _∷_) []
_ = refl
```
I get the message `*All Goals, Errors*` and:
```
_a_6 : Agda.Primitive.Level
_A_7 : Set _a_6
_a_10 : Agda.Primitive.Level
_A_11 : Set _a_10
```

**Comment by jespercockx** [comment]
Since `_∷_` is the constructor of a parametrized datatype, Agda tries to infer the values of the parameters but it fails because there are no arguments.

If you want to quote a lone name like here, it is recommended to use `quote` instead of `quoteTerm`, since this will not try to insert any hidden arguments.

**Comment by pnlph** [comment]
And could not `Term.unknown` be used?

For example `quoteTerm List._∷_` resolves to:
```
con (quote List._∷_)
(arg (arg-info hidden relevant) Term.unknown ∷
 arg (arg-info hidden relevant) Term.unknown ∷ [])
```

**Comment by jespercockx** [comment]
Is that not the same thing as what happens for the vector `_∷_`?

**Comment by pnlph** [comment]
No, when evaluating the normal form of `quoteTerm Vec._∷_` i get `_20` instead...

**Comment by jespercockx** [comment]
Yes, it's indeed strange that Agda treats the List cons differently from the Vec cons here. After looking a bit at the debug output, I think I understand now what is happening: When quoting a term, Agda currently refuses to quote any term that still has a metavariable. So the result of quoting a term with unsolved metavariables will just result in another unsolved metavariable, which is what you're observing for `Vector._∷_`. However, since Agda internally erases datatype parameters, any unsolved metavariables in the parameter arguments of the constructor are ignored by this check. So since all implicit arguments of `List._∷_` are parameters, Agda does not see any unsolved metavariables and the check passes.

To make Agda's behaviour more consistent, we could go into two directions: (1) also refuse to quote terms that still have unsolved metavariables in their types, or (2) allowing quoting of terms even if they contain unsolved metavariables. Option (1) would result in both `quoteTerm`s returning a metavariable, which is perhaps not what you'd want but at least is consistent. The problem with option (2) is that unsolved metavariables might still be solved later on, so we do not want to quote the term "too soon" or else we might get `unknown` terms even for arguments that are solved in the end.

**Comment by pnlph** [comment]
I also realized that applying `quoteTerm` to `List` or `Vec` gives the same definitional term as, say `Nat`, that is, without arguments:
```haskell
_ : quoteTerm List ≡ def (quote List) []
_ = refl
```
But I was expecting a non-empty list of unknown arguments for `List`and `Vec`.

On the other hand, should not be a difference between a completely unknown term and a term that is unknown, but from which at least we know its type? Then we could get a list of arguments like this:
```
arg (arg-info hidden relevant) (unknown Level) ∷
arg (arg-info visible relevant) (unknown Set) ∷ []
```
instead of just:
```
arg (arg-info hidden relevant) unknown ∷
arg (arg-info visible relevant) unknown ∷ []
```
Makes sense that the constructor unknown is of type `Term → Term`?

**Comment by jespercockx** [comment]
> I also realized that applying `quoteTerm` to `List` or `Vec` gives the same definitional term as, say `Nat`, that is, without arguments:
> 
> ```haskell
> _ : quoteTerm List ≡ def (quote List) []
> _ = refl
> ```
> 
> But I was expecting a non-empty list of unknown arguments for `List`and `Vec`.

Why would you expect a list of arguments when the type is not applied to any arguments?

> On the other hand, should not be a difference between a completely unknown term and a term that is unknown, but from which at least we know its type? Then we could get a list of arguments like this:
> 
> ```
> arg (arg-info hidden relevant) (unknown Level) ∷
> arg (arg-info visible relevant) (unknown Set) ∷ []
> ```
> 
> instead of just:
> 
> ```
> arg (arg-info hidden relevant) unknown ∷
> arg (arg-info visible relevant) unknown ∷ []
> ```
> 
> Makes sense that the constructor unknown is of type `Term → Term`?

As I said above, you're not really supposed to get `unknown` terms inside quoted things since normally quoting is delayed until all metavariables are solved. Constructor parameters are an exception because they are not stored in the internal representation used by Agda.

If you need the types of the arguments of a function (or a type constructor) you could instead try to use the reflection primitive `getType` to first get the type of the whole function and then pattern match (repeatedly) on the `pi` constructor to get the types of the arguments.

**Comment by pnlph** [comment]
> Why would you expect a list of arguments when the type is not applied to any arguments?

I think because of how is `quoteTerm List._∷_` resolved.

I guess also that I am trying to think about the representation that `Term` provides in a compositional way, in the sense that the representation of an expression can be determined by the representation of its constituent expressions and some application operation able to combine them in a meaningful way.

Is it adequate to think about compositionality of Terms? Is it possible or makes sense to define an application operation on Terms `_⊙_ : Term → Term → Term` such as `quoteTerm (u v) ≡ (quoteTerm u) ⊙ (quoteTerm v)`?

For example, given the meaning of `quoteTerm _≡_ 7`:
```ldif
def (quote _≡_)
(arg (arg-info hidden relevant) (def (quote zero) []) ∷
 arg (arg-info hidden relevant) (def (quote ℕ) []) ∷
 arg (arg-info visible relevant) (lit (nat 7)) ∷ [])
```

I think of `quoteTerm _≡_` as the definitional term named `quote _≡_` and equipped with two still unknown arguments. Its application to `quoteTerm 7` introduces the latter as a visible relevant argument, then resolves the two previously unknown arguments.

But agda is interpreting `quoteTerm _≡_` just as the definitional term named `quote _≡_` with an empty list of arguments. Then its application to `quoteTerm 7` introduces it as a visible relevant argument and also introduces the other two arguments that depend on how `_≡_` was defined.

**Comment by jespercockx** [comment]
> > Why would you expect a list of arguments when the type is not applied to any arguments?
> 
> I think because of how is `quoteTerm List._∷_` resolved.

The parameter `A` of `List` is an *explicit* argument of the type, but an *implicit* argument of the constructors. Implicit arguments are inserted automatically by Agda, but explicit arguments are not, so that explains the difference.

> 
> I guess also that I am trying to think about the representation that `Term` provides in a compositional way, in the sense that the representation of an expression can be determined by the representation of its constituent expressions and some application operation able to combine them in a meaningful way.
> 
> Is it adequate to think about compositionality of Terms? Is it possible or makes sense to define an application operation on Terms `_⊙_ : Term → Term → Term` such as `quoteTerm (u v) ≡ (quoteTerm u) ⊙ (quoteTerm v)`?

Defining such a function is hard because the first `Term` could be a lambda-expression, but the reflected syntax has no way to represent a beta-redex `(\x -> u) v`. So the operation `_⊙_ : Term → Term → Term` would have to do beta-reduction on the fly. However, the arguments are untyped terms so this is potentially non-terminating. Hence it is not possible to define such a function in Agda (without the use of `{-# TERMINATING #-}` or `{-# NON_TERMINATING #-}`).

In Ulf's prelude, he defines a tweaked version of this application where the first argument cannot be a lambda: https://github.com/UlfNorell/agda-prelude/blob/12f637889b1d251d5c6f7e9c09f879dbc8c24af7/src/Tactic/Reflection/Substitute.agda#L53-L64
(there is also another version `safeApply` in the same file where the head symbol is arbitrary but the arguments cannot be lambda's).

> 
> For example, given the meaning of `quoteTerm _≡_ 7`:
> 
> ```
> def (quote _≡_)
> (arg (arg-info hidden relevant) (def (quote zero) []) ∷
>  arg (arg-info hidden relevant) (def (quote ℕ) []) ∷
>  arg (arg-info visible relevant) (lit (nat 7)) ∷ [])
> ```
> 
> I think of `quoteTerm _≡_` as the definitional term named `quote _≡_` and equipped with two still unknown arguments. Its application to `quoteTerm 7` introduces the latter as a visible relevant argument, then resolves the two previously unknown arguments.

`quoteTerm` is built-in syntax with a very low binding priority (lower than function application), so you should think of `quoteTerm _≡_ 7` as `quoteTerm (_≡_ 7)` and not as `(quoteTerm _≡_) 7` (which would not be well-typed).

> 
> But agda is interpreting `quoteTerm _≡_` just as the definitional term named `quote _≡_` with an empty list of arguments. Then its application to `quoteTerm 7` introduces it as a visible relevant argument and also introduces the other two arguments that depend on how `_≡_` was defined.

**Comment by nad** [comment]
See #3821.

**Comment by pnlph** [comment]
Thank you @nad for the reference.

I have a question: the `apply` application function between terms should not just have type:
```agda
apply : Term → Term → Term
```
instead of
```agda
apply : Type → Term → List (Arg Term) → TC (Type × Term)
```
or is this another _kind_ of application function that you have in mind?

**Comment by jespercockx** [comment]
I think the differences between the two can be explained:

- The extra `Type` argument is the type of the head symbol and is needed for cases where it cannot be inferred (otherwise it's fine to just give `unknown` as the type).
- Having a list of arguments is more general than having a single argument (and it might be more efficient to give all arguments at once)
- The arguments have additional information from the `Arg` that indicates the kind of argument (e.g. `f x` vs `f {x}`)
- The result is returned in the `TC` monad because information from the typechecking environment might be needed to reduce a function (e.g. to look up the clauses of a defined function).
- The result also includes the type of the resulting application, this might be useful (and otherwise you can ignore it)

Given `apply : Type → Term → List (Arg Term) → TC (Type × Term)`, you could implement a simpler `apply' : Term → Term → TC Term` as follows:
```agda
open import Prelude
open import Tactic.Reflection

postulate
  apply : Type → Term → List (Arg Term) → TC (Type × Term)

apply' : Term → Term → TC Term
apply' u v = snd <$> apply unknown u (vArg v ∷ [])
```
(using Ulf's prelude)

**Comment by jespercockx** [comment]
There is now the new reflection primitive `withReconstructed` which you can use to fill in the constructor parameters with actual terms instead of `unknown`s. So I'm assuming this problem is now fixed, let us know if there's still problems.
