### ISSUE TITLE
Internal error due to new forcing translation

### ISSUE THREAD

**Issue by nad** [agda/agda#4528]
The following code triggers an internal error:
```agda
open import Agda.Builtin.Equality
open import Agda.Builtin.List

postulate
  A : Set

record R (B : Set) : Set where
  field
    f : A → B
    g : B → A
    h : ∀ x → f (g x) ≡ x

data D : List A → Set where
  nil  : D []
  cons : (x : A) (xs : List A) → D (x ∷ xs)

_ : (xs : List A) → R (D xs)
_ = λ _ → record
  { g = λ where
          nil        → ?
          (cons _ _) → ?
  ; h = λ where
          nil        → ?
          (cons _ _) → ?
  }
```
```
conApp: constructor Agda.Builtin.List.List.[] with fields
 and args
 projected by Agda.Builtin.List._∷_-0
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Substitute.hs:134
```

**Comment by nad** [comment]
Bisection points to 0539818a58dd049ccb2ede79ed304bc669fa1bf2 ("[ #3903 ] handle forcing translation in the unifier").

**Comment by Saizan** [comment]
I'm a bit concerned that the partial datatype projections like `Agda.Builtin.List._∷_-0` now seem to be promoted to full projection status (e.g. by inclusion in ConHead), was this a deliberate choice?

I originally introduced them only as an implementation aid for `hcomp`.

**Comment by andreasabel** [comment]
> by inclusion in ConHead

Which commit?

**Comment by UlfNorell** [comment]
Yes this was intentional, but I don't think they are actually used at the moment. It was done as part of the new forcing translation. The (as yet unimplemented) idea is that lazy matches, originating from the forcing translation, can use the projections instead of full matching.

**Comment by Saizan** [comment]
Here's the commit btw: 4df7f61ca2d57eb2aa0a8911ca067cd9c37ef65e

It seems that these projections are used in the elaboration of the pattern lambda that defines the `g` field. You can see them in the goal type if you replace the definition of `h` by a hole.

**Comment by Saizan** [comment]
Maybe you already figured this out, but the source of the bad projections term is that these lines assume the `ConP` patterns are always record patterns, while apparently this invariance got broken.

https://github.com/agda/agda/blob/93ea99a43f4b2b5a7d1f1da8a11bea3bbc34f6ce/src/full/Agda/TypeChecking/Substitute.hs#L450-L457

Now the `ConHead` stores whether the constructor `IsData` or `IsRecord`, so something different could be done for data constructors, but I'm not sure what.

**Comment by UlfNorell** [comment]
Here's a simplified example:
```agda
open import Agda.Builtin.Equality
open import Agda.Builtin.List

postulate
  A : Set
  nilA : A
  consA : A → List A → A
  w/e : {x y : A} → x ≡ y

data D : List A → Set where
  nil  : D []
  cons : (x : A) (xs : List A) → D (x ∷ xs)

foo : ∀ {xs} (d : D xs)
      (let f : D xs → A
           f = λ where nil         → nilA
                       (cons y ys) → consA y ys) →
      f d ≡ nilA
foo nil        = {!!}
foo (cons _ _) = w/e
```
The goal type before matching on `d` is
```agda
 (λ { nil → nilA ; (cons _ _) → consA (xs ._∷_-0) (xs ._∷_-1) }) d ≡ nilA
```
Compare this to the type without forcing:
```agda
 (λ { nil → nilA ; (cons y ys) → consA y ys }) d ≡ nilA
```
That is, what happens is that since the arguments of `cons` are forced we grab them from `xs` using the `::`-projections. This should be fine since in the `cons` case we know that `xs` is a `_::_`. Now the problem is that we want to look inside the pattern lambda when printing the type of the refined goal. In the `nil` case we have `xs = []` and `d = nil` so we get
```agda
 (λ { nil → nilA ; (cons _ _) → consA ([] ._∷_-0) ([] ._∷_-1) }) nil ≡ nilA
```
causing the internal error.

I'm not sure what the best solution is here...
- Reducing the pattern lambda isn't really an option because it might be stuck on an unrelated argument.
- One option might be to simple not fail and print the bogus projections, but this isn't very nice and it risks hiding legitimate bugs (that `conApp` impossible is probably the most triggered impossible we have).
- I think the ideal solution would be to drop the `cons` case from the lambda (since it's impossible), but that requires some non-trivial machinery.

**Comment by Saizan** [comment]
>     * One option might be to simple not fail and print the bogus projections, but this isn't very nice and it risks hiding legitimate bugs (that `conApp` impossible is probably the most triggered impossible we have).
> 

We could apply the data projections with a `Def f ...` since they are merely projections-like functions, not true projections to be applied with `Proj`. That would prevent triggering the `IMPOSSIBLE` in `conApp`.

However I think we should rather print `(λ { nil → nilA ; (cons y ys) → consA y ys })` to the user. since that's how the function is written.
Maybe we should keep the original version of the clauses around for an extended lambda, so that they can be used for this?

**Comment by UlfNorell** [comment]
Yes, that would make sense simply from a usability point as well.
