### ISSUE TITLE
[documentation] update hello world

### ISSUE THREAD

**Issue by pnlph** [agda/agda#4556]
Issue #4497 raised some controversy and also proposals about updating the contents of the page Getting started -> ['Hello World' in Agda](https://agda.readthedocs.io/en/v2.6.1/getting-started/hello-world.html)

I thought it would be good to start a new issue to discuss it. You can thumb up/thumb down this text if you feel the discussion of this is meaningful/not meaningful, or even close the issue if you consider the debate itself is not appropriate.

If appropriate, then we could gather all the improvements for this section and propose a corresponding PR.

**Comment by gallais** [comment]
I would be in favour of a self-contained hello world. The fact that anything else
than Agda needs to be installed seems to lead to confusion: users want to be
able to copy/paste the program and get an executable.

```agda
open import Agda.Builtin.IO
open import Agda.Builtin.String
open import Agda.Builtin.Unit

postulate putStrLn : String → IO ⊤
{-# FOREIGN GHC import qualified Data.Text as T #-}
{-# COMPILE GHC putStrLn = putStrLn . T.unpack #-}

main : IO ⊤
main = putStrLn "Hello world!"
```

This may look a bit verbose but it is an opportunity to highlight the fact that
Agda does not load an implicit prelude and lets users pick the one they like.
We can then add sections demonstrating the equivalent programs using the
standard library or Ulf's prelude.

**Comment by WolframKahl** [comment]
In many fonts, `T` (the letter) looks a lot like `⊤` (`\top`), and newcomers won't know where the latter comes from.

I'd recommend:
```agda
open import Agda.Builtin.IO
open import Agda.Builtin.String
open import Agda.Builtin.Unit using (⊤)

postulate putStrLn : String → IO ⊤
{-# FOREIGN GHC import qualified Data.Text as Text #-}
{-# COMPILE GHC putStrLn = putStrLn . Text.unpack #-}

main : IO ⊤
main = putStrLn "Hello world!"

**Comment by mietek** [comment]
I support the above suggestions.  However, as I said in #4497, I think the problem with the “Hello world” page is that it sets the wrong expectations.  It is great to have the option of compiling an Agda program and getting an executable, but that is not what Agda users do most of the time.

> users want to be able to copy/paste the program and get an executable.

I would amend this to say that the user wants to be able to copy/paste a program that is representative of the programs they will be writing, and get a useful result.  This is made more complicated by the interactive nature of the intended method of using Agda for theorem-proving, which differs from the usual method of programming.

Therefore, I would question the need to have a “Hello world” page at all.

**Comment by guillaumebrunerie** [comment]
I agree with @mietek that it should be made clear that most users never compile Agda programs. Instead of the Hello world page, there should be something testing loading a file in the emacs mode and unicode input, as this is what matters the most.
The Hello world example is still a useful example for when the user does actually want to get an executable (I definitely used it as a starting point when I wanted to use Agda as a programming language) but it should be more "hidden" so that newcomers don’t get the wrong idea that this is how a proof assistant work.

**Comment by jespercockx** [comment]
> Therefore, I would question the need to have a “Hello world” page at all.

I strongly disagree: there is definitely a need for a minimal example that beginners can use to answer the question "Have I set up my Agda correctly?" The fact that we get many questions about the current hello world example is a proof of that. 

I also want to remind some people here of the first sentence on the Agda wiki: "Agda is a dependently typed functional programming language." If it is to be used as a programming language, then you should be able to write programs that interact with the world. I do not think we should hide this fact from newcomers, lest they might get the idea that Agda is *only* usable as a proof assistant and/or executable specification language.

However, I definitely agree that this should not be the only thing beginning users see. Perhaps we could take some cues from [this page on the Haskell wiki](https://wiki.haskell.org/Haskell_in_5_steps)?

**Comment by mietek** [comment]
I agree there is a need for a minimal example for newcomers.  I thought that this example should show how to use Agda interactively to write a program that is also a meaningful proof, instead of showing a finished program that merely exercises the FFI.  However, I also agree that it is good to see that Agda can be used to write programs that interact with the world.  Perhaps there is room for two examples?

**Comment by jespercockx** [comment]
Maybe there's even room three examples (not necessarily in this order):

- An example of writing a "real program" in Agda (the current "Hello World")
- An example of writing a dependently typed program in Agda (Vectors with an append function are considered the standard hello world example for this)
- An example of how to use Agda to write proofs (maybe associativity of `_+_` would be a good standard example here? I'm open to other suggestions as well)

One important point of a "hello world" example is that it should be something that's familiar to as many people as possible, in order to make it easier to see what's *different* from other languages the user might already know.

This should also demonstrate nicely to newcomers that there is really no syntactic difference between programs and proofs in Agda, the exact same syntax (i.e. datatypes and pattern matching) is used for programs and proofs.

In addition, there should be some demonstration of how to use Agda interactively on one or more of these examples (including loading the file in emacs, introducing holes, giving, and case splitting).

**Comment by pnlph** [comment]
I have created [a new project](https://github.com/agda/agda/projects/8) to assemble the changes. You can add, edit, delete and move cards accordingly.

**Comment by gallais** [comment]
Another trap to be aware of: you can't just pull any version of the stdlib.
You have to download one that is compatible with the version of Agda you have
installed.

**Comment by jespercockx** [comment]
Since this is a quite common complaint among newcomers to Agda, I've removed the `priority: low` label. I hope we can get an updated version of the hello world example soon!

**Comment by pnlph** [comment]
OK, i will try to push soon a new version with the collected suggestions.

**Comment by pnlph** [comment]
The plan is to show the three examples that @jespercockx mentioned, but I have some questions about the first one (the program):
1. What is needed in order to compile the current `Hello World` example? I am trying to compile the `Hello World` both with `C-c C-x C-c` and `agda --compile hello-world.agda` and I am getting #3619 I did `cabal install ieee754`but I did not get rid of the error.
2. What is the result of the compilation? It seems that the `compile` command created a folder named `MAlonzo` with a file `RTE.hs` in it and a folder `Code` with lots of `*.hs` files and folder in it. One of them is named [QhelloZ45Zworld.hs](https://repl.it/@pnlph/hello-world-agda#MAlonzo/Code/QhelloZ45Zworld.hs) Is not possible just getting a simpler single file `hello-world.hs`?
3. How does one run the result of the compilation in order to check that the source code wrote in Agda is actually working as intended? Is needed another step `ghc -o hello hello.hs` to get a standalone executable?
4. I could compile with the JS backend `agda --js hello-world.agda` and results in many `.js` files generated by default in the same folder where the `.agda` file is. The resulting file is named `jAgda.hello-world.js`. Would not be better to put them in a folder eg. `jAgda` also? I cannot run [jAgda.hello-world.js](https://repl.it/@pnlph/hello-world-agda-js#jAgda.hello-world.js) also.

**Comment by UlfNorell** [comment]
2, 3: It should have made a binary `HelloWorld` in the top-level folder (where it put `MAlonzo`).

**Comment by Blaisorblade** [comment]
> The fact that we get many questions about the current hello world example is a proof of that.

From interacting with those questions on IRC, when I asked if people cared about programming in Agda, the answer was always "no"; they just wanted to test their install.

OTOH, fixing this example might lead to more users trying to program in Agda and bumping at some point into the next inconveniences, like @pnlph; that might be good for Agda if you want to evolve it in that direction, but annoying for those users, who'll get a bad impression, or learn that Idris avoids those problems?

**Comment by jespercockx** [comment]
I've done some further editing on the tutorial written by @pnlph and pushed the changes to https://github.com/agda/agda/pull/5223. The tutorial is now a separate section titled "A Tour of Agda" and the "Hello World" page has been restored for it's original purpose: testing if Agda has been set up correctly (now with two separate use cases). I would appreciate it if someone else could take a look at "A Tour of Agda" and the new "Hello World" page and check if there are any mistakes.
