### ISSUE TITLE
Agda unification problem with equality

### ISSUE THREAD

**Issue by berndlosert** [agda/agda#4558]
When I compile this program:

```agda
 open import Agda.Builtin.Equality

 works : {A B : Set} {F : Set -> Set} -> (A ≡ F B) -> A -> F B
 works refl x = x

 record R : Set1 where
   field A : Set

   worksToo : {B : Set} -> (A ≡ B) -> A -> B
   worksToo refl x = x

   doesntWork : {B : Set} {F : Set -> Set} -> (A ≡ F B) -> A -> F B
   doesntWork refl x = x
```
I get the following:.
```
Checking foo (/private/tmp/foo.agda).
/private/tmp/foo.agda:13,14-18
I'm not sure if there should be a case for the constructor refl,
because I get stuck when trying to solve the following unification
problems (inferred index ≟ expected index):
  A ≟ F B
when checking that the pattern refl has type A ≡ F B
```
This occurs in Agda 2.6.0.1 and 2.6.1. Am I doing something wrong or is this a known problem with the unifier?

**Comment by andreasabel** [comment]
> ```agda
>  record R : Set1 where
>    field A : Set
> 
>    worksToo : {B : Set} -> (A ≡ B) -> A -> B
>    worksToo refl x = x
> ```

This works because function argument `B` can be instantiated to `A` on the lhs of `worksToo`.

> ```agda
>    doesntWork : {B : Set} {F : Set -> Set} -> (A ≡ F B) -> A -> F B
>    doesntWork refl x = x
> ```

You can't instantiate `A` because it is a record field whose value is determined by how the record is constructed.  You could instantiate `B` and `F` to make `A = F B`, but there are several solutions, and Agda only picks unique solutions in the unifier.
