### ISSUE TITLE
Improve pattern matching on records in telescopes

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda#4596]
Type-checking the following
```agda
open import Agda.Builtin.Sigma

_×_ : Set → Set → Set
A × B = Σ A λ _ → B

module _ {A B C : Set} {P : A × B → Set} where

  test : ∀ {xy@(x , y)} → P xy → A
  test = {!!}
```
 gives the error `Cannot split on argument of non-datatype _834
when checking that the pattern x , y has type _834`. However if you change the function type to:
```
  test : ∀ {xy@(x , y) : A × B} → P xy → A
```
then it type-checks fine.

Given that Agda can infer the type of `xy`, ideally it should also be able to infer that `xy` is a valid candidate for pattern matching without having to annotate the type. Failing that, the error message should be improved as `xy` is a datatype despite what the error message says.

**Comment by gallais** [comment]
Interesting to note the different behaviours between the four following programs:

```agda
  test1 : ∀ xy (p : P xy) (let (x , y) = xy) → A
  test1 = {!!}

  test2 : ∀ xy (p : P xy) → let (x , y) = xy in A
  test2 = {!!}

  test3 : ∀ xy → let (x , y) = xy in (p : P xy) → A
  test3 = {!!}

  test4 : ∀ xy (let (x , y) = xy) (p : P xy) → A
  test4 = {!!}
```

* First two suceed
* In the third one, `xy`'s type is not inferred and the whole type is yellow
* In the last one, the hard error you observed

The `(let p = e)` are what the pattern-matching telescopes are desugared to.
Sounds like these should be allowed to delay some constraints being satisfied.
The fact that the third one has some unsolved metas is also puzzling to me.

**Comment by nad** [comment]
> ```agda
>   test3 : ∀ xy → let (x, y) = xy in (p : P xy) → A
> ```

Note that there is no whitespace between `x` and `,`.

**Comment by gallais** [comment]
My bad, edited: the whole type is highlighted yellow when I put the space in. :D

**Comment by andreasabel** [comment]
The problem can be explained by the lack of postponement forms.  The checking of `let (x , y) = xy` cannot be postponed.  If the type of `xy` cannot be inferred, we cannot make progress because we cannot compute the types of `x` and `y`.  The reason is that we use the left-hand-side checker to check pattern `(x , y)` and this needs its type.

One way out would be a custom procedure for record patterns, since they do not need the full power of dependent pattern matching (no unification).  We could have something simpler that assumes an unknown type for each pattern variable and tries to solve them via pattern typing, postponing if there isn't enough information yet.  The problem is that there might be hidden pattern variables, and then the unknown types need to depend on them as well.  This could still work if we can resolve the record constructor.  But the record constructor could be overloaded...

In the end, this would be a complicated procedure with many heuristics.

The current rule is quite simple:  If you want to write something like `let (x, y) = xy`, better make sure that the type of `xy` is known at this point.

**Comment by MatthewDaggitt** [comment]
Sounds like it's a matter of making the error message more informative then. I was definitely pretty confused by it for ~5 minutes.

**Comment by andreasabel** [comment]
How about this error?
```
Cannot split on argument of unresolved type _4
when checking that the pattern x , y has type _4
```

**Comment by gallais** [comment]
Why can the checking not be postponed?

**Comment by andreasabel** [comment]
> Why can the checking not be postponed?

Well, in my lenghty explanation I argue that if we want to postpone this, we need to give makeshift types to the bound variables, which is kinda difficult.

**Comment by andreasabel** [comment]
I pushed the above slightly more accurate error messaging.  

Please reopen if you are not happy with the error or are working on a better solution (postponing).
