### ISSUE TITLE
Literals and termination

### ISSUE THREAD

**Issue by tomdjong** [agda/agda#4677]
Consider the following code.

```Agda
data ℕ : Set where
  zero : ℕ
  succ : ℕ → ℕ

data _≡_ {X : Set} : X → X → Set where
  refl : {x : X} → x ≡ x

-- For simulating a term that is very slow to typecheck.
{-# TERMINATING #-}
stuck : ℕ
stuck = stuck

f : ℕ → ℕ
f n = stuck

-- Agda is OK with this, of course.
foo : f zero ≡ f zero
foo = refl

{-# BUILTIN NATURAL ℕ #-}

bar : f 0 ≡ f 0
bar = refl

-- Typechecking this takes forever.
baz : f zero ≡ f 0
baz = refl
```

Since `refl : 0 ≡ zero`, I thought that `0` and `zero` are defintionally equal, so why does Agda try to reduce `f zero` (or `f 0`) in `baz`? Can I (manually) prevent this from happening?

**Comment by andreasabel** [comment]
`f` is not defined.

**Comment by guillaumebrunerie** [comment]
When checking whether two terms of type `ℕ` are equal, Agda first checks if they are syntactically equal, as a shortcut, but otherwise it reduces them to weak-head normal form.
In your case, I assume that `f` is defined such that reducing `f zero` and `f 0` to weak-head normal form loops, so it’s expected that Agda loops.
There are definitely other ways of checking equality of terms, like checking if the arguments are equal instead of reducing, but it’s in general very difficult to know in advance which strategy will be the most efficient for a given situation.

If you want to make things more consistent, you can add the `--no-syntactic-equality` flag. It will disable the syntactic equality shortcut and then `foo` and `bar` will loop too :)

**Comment by tomdjong** [comment]
> `f` is not defined.

Apologies, I forgot to copy it in.
```
f : ℕ → ℕ
f n = stuck
```

I have also edited the original code.

**Comment by tomdjong** [comment]
> When checking whether two terms of type `ℕ` are equal, Agda first checks if they are syntactically equal, as a shortcut, but otherwise it reduces them to weak-head normal form.
> In your case, I assume that `f` is defined such that reducing `f zero` and `f 0` to weak-head normal form loops, so it’s expected that Agda loops.
> There are definitely other ways of checking equality of terms, like checking if the arguments are equal instead of reducing, but it’s in general very difficult to know in advance which strategy will be the most efficient for a given situation.
> 
> If you want to make things more consistent, you can add the `--no-syntactic-equality` flag. It will disable the syntactic equality shortcut and then `foo` and `bar` will loop too :)

Thank you for the explanation! Is it possible to (manually) tell Agda what strategy to use in this particular case?

**Comment by guillaumebrunerie** [comment]
> Is it possible to (manually) tell Agda what strategy to use in this particular case?

Not really, but depending on your use case you could for instance put `f` abstract, which would prevent it from being reduced.

**Comment by WolframKahl** [comment]
> Is it possible to (manually) tell Agda what strategy to use in this particular case?

Perhaps `cong f refl`? :wink:

**Comment by guillaumebrunerie** [comment]
> Is it possible to (manually) tell Agda what strategy to use in this particular case?
> Perhaps `cong f refl`?

I actually tried that, and for some reason it still looped, not sure why.

**Comment by UlfNorell** [comment]
You still need to solve the implicits to `cong`, i.e. `f _X = f zero` and `f _Y = f 0`. In this case you really can't avoid reducing `f`. If you give the implicits it checks quickly though: `cong f {zero} {0} refl`

**Comment by guillaumebrunerie** [comment]
Oh, I tried giving the implicits as well, and it still loops:

```agda
cong : {A B : Set} (f : A → B) {x y : A} → x ≡ y → f x ≡ f y
cong f refl = refl

-- Typechecking this takes forever.
baz : f zero ≡ f 0
baz = cong f {zero} {0} refl
```

Am I missing something?

**Comment by UlfNorell** [comment]
That's strange. This is my complete file which type checks instantly on adfc12d:
```agda
open import Agda.Builtin.Nat
open import Agda.Builtin.Equality

-- For simulating a term that is very slow to typecheck.
{-# TERMINATING #-}
stuck : Nat
stuck = stuck

f : Nat → Nat
f n = stuck

cong : {A B : Set} → (A → B) → ∀ {x y} → x ≡ y → f x ≡ f y
cong f refl = refl

baz : f zero ≡ f 0
baz = cong f {zero} {0} refl
```

**Comment by guillaumebrunerie** [comment]
Hmm, in my case (the code in the OP plus the two definitions of my previous comment) I can make it terminate if I disable the auto-inlining feature (`--no-auto-inline`), as apparently Agda realizes that `f` does not actually use its argument `n` and therefore decides to inline it. No idea why it’s different in your example.

**Comment by guillaumebrunerie** [comment]
The difference seems to be whether the first explicit argument of `cong` is given a name in the type signature (I call it `f`, but you leave it unnamed). This is probably not the expected behaviour :)

**Comment by UlfNorell** [comment]
Huh, that is interesting.

Aside: you can also use `{-# NOINLINE f #-}` to disable inlining for `f` specifically.

**Comment by guillaumebrunerie** [comment]
Actually, your definition of `cong` is not quite correct, you’re using the `f` defined above instead of the one given as an argument to `cong`.

**Comment by UlfNorell** [comment]
Lol, oops. Well that explains the difference I suppose :blush:

**Comment by tomdjong** [comment]
Could someone please explain why the proper `cong` does not work, but the "not quite correct" `cong` does the trick for `f 0 ≡ f zero`?

**Comment by guillaumebrunerie** [comment]
Agda has an auto-inlining feature that detects when it would be a good idea to inline a definition (and does it). In this case, Agda sees that `f` does not actually use its argument `n`, and therefore decides to inline it (sometimes). And of course, if it does get inlined, it becomes non-trivial to compare it with a non-inlined version. In the version that does not work, it tries to compare `f zero` with `stuck`, where the `stuck` is `f zero` that has been inlined, so it loops.

Note that this would not happen in an actually use case where `f` would use its argument, so the proper `cong` should work in practice.

Now I’m not exactly sure why auto-inlining is applied in one case and not in the other, but in the not-quite-correct `cong`, the only substitution happening is `(f x)[zero / x]`, which does not fire auto-inlining (maybe because it doesn’t touch `f`), whereas for the proper `cong`, the substitution is `(_f x)[zero / x ; f / _f]`, which does something non-trivial about the `f`, therefore auto-inlining fires.

But I think that auto-inlining is a very exotic feature that most people don’t need to know about, except when minimizing code for bug reports and ending up with a function that doesn’t use its argument :) That’s exactly how I learned about the existence of this feature myself.

**Comment by jespercockx** [comment]
See also https://github.com/agda/agda/issues/3486 for another issue where auto-inlining causes unexpected behaviour.

**Comment by tomdjong** [comment]
> Agda has an auto-inlining feature that detects when it would be a good idea to inline a definition (and does it). In this case, Agda sees that `f` does not actually use its argument `n`, and therefore decides to inline it (sometimes). And of course, if it does get inlined, it becomes non-trivial to compare it with a non-inlined version. In the version that does not work, it tries to compare `f zero` with `stuck`, where the `stuck` is `f zero` that has been inlined, so it loops.
> 
> Note that this would not happen in an actually use case where `f` would use its argument, so the proper `cong` should work in practice.
> 
> Now I’m not exactly sure why auto-inlining is applied in one case and not in the other, but in the not-quite-correct `cong`, the only substitution happening is `(f x)[zero / x]`, which does not fire auto-inlining (maybe because it doesn’t touch `f`), whereas for the proper `cong`, the substitution is `(_f x)[zero / x ; f / _f]`, which does something non-trivial about the `f`, therefore auto-inlining fires.
> 
> But I think that auto-inlining is a very exotic feature that most people don’t need to know about, except when minimizing code for bug reports and ending up with a function that doesn’t use its argument :) That’s exactly how I learned about the existence of this feature myself.

Thank you very much for your detailed response, @guillaumebrunerie!

I have one more (possible naive) question: could there be a flag/option so that `0` and `zero` are syntactically equal?

**Comment by guillaumebrunerie** [comment]
> I have one more (possible naive) question: could there be a flag/option so that `0` and `zero` are syntactically equal?

I don’t think it’s a good idea to have a development that relies on `0` and `zero` being syntactically equal, it will break very easily. It’s better to try to reorganize the code, using `abstract`, always using `0` instead of `zero`, and so on, for the problem to go away in a more principled way. So I feel like adding a specific flag for that would not be worth the trouble.

**Comment by UlfNorell** [comment]
Auto-inlining is now turned off by default, so using `cong` works.
