### ISSUE TITLE
Our handling of release notes loses history

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#4705]
> Unfortunately, this does not lead me to a commit since `doc/release-notes/2.6.1.md` has no history.

_Originally posted by @andreasabel in https://github.com/agda/agda/issues/4704#issuecomment-636901801_

@asr: We used to have a CHANGELOG.md file with everything in it.  This allowed to research its history with `git blame`.  Now we have individual files <version>.md, however, they have no history.  We should find a workflow that does not lose the editing history of the changelog file(s).

**Comment by guillaumebrunerie** [comment]
I think that the problem is that the renaming of `CHANGELOG.md` to `2.6.1.md` and the creation of a new `CHANGELOG.md` was made in the same commit, which confused git (git assumed that `CHANGELOG.md` had simply been modified and `2.6.1.md` was a new file created from scratch). It should be easy to avoid this issue in the future by splitting those operations in two different commits (first rename, and then create a brand new `CHANGELOG.md`), so that git can correctly track the history.

**Comment by nad** [comment]
> @asr: We used to have a CHANGELOG.md file with everything in it. This allowed to research its history with `git blame`. Now we have individual files .md, however, they have no history. We should find a workflow that does not lose the editing history of the changelog file(s).

Maybe it is not too late to restore some of the history, by using [somewhat convoluted merging](https://stackoverflow.com/a/57005385).
