### ISSUE TITLE
Just warn when `using` directive has repetitions

### ISSUE THREAD

**Issue by gallais** [agda/agda#4707]
It's raised in Agda.Syntax.Scope.Monad (line 745 at the moment)

```agda
open import Agda.Builtin.Nat using (zero; zero)
```

should not fail: it should emit a warning & highlight the second zero as dead code.

**Comment by andreasabel** [comment]
Relevant piece of code:
https://github.com/agda/agda/blob/5fef51422de811b2cd4bcfd1e937636e0b3d01eb/src/full/Agda/Syntax/Scope/Monad.hs#L742-L745

**Comment by andreasabel** [comment]
Actually, it is a _parse error_:
```
Issue4707.agda:1,37: Repeated name in import directive: zero
<EOF><ERROR>
```
This seems a relic from pre-enlightenment age when we thought that the parser would be a good place to ensure well-formedness conditions.
https://github.com/agda/agda/blob/06172256d1fc3668e35b694c696210f65987ad8c/src/full/Agda/Syntax/Parser/Parser.y#L2079-L2082
After removing the check in the parser, we end up at the place in Scope.Monad I thought we would end up.

**Comment by andreasabel** [comment]
The question is what to do in more complicated situations such as:
```agda
open import Agda.Builtin.Nat
  renaming (Nat to zero)
  using (zero)
  renaming (suc to zero)
  using (zero)
```
The parser already mangles these multiple `using` and `renaming` directives into single ones.  Further, it is not structurally visible in which order these directives came.  We could reconstruct the order of individual imports of `zero` by the range, though.

However, it is still unclear what you want `zero` to be bound to.  `Nat`, `zero`, or `suc`?  We have to design the rule here.  
- Should it be the first or the last binding of `zero` which is dominant?
- Or should we not bring `zero` into scope at all if it is ambiguous?
- Should ambiguity be determined extensionally (binding to different abstract names) or just by repeated mentions?

As usual, the issue is not as easy as imagined.  (Removing the tag.)

**Comment by andreasabel** [comment]
A simple fix of the OP would to just ignore duplicates in `using` (with a warning), and retain the error in more complicated situations.

**Comment by jespercockx** [comment]
> ```agda
> open import Agda.Builtin.Nat
>   renaming (Nat to zero)
>   using (zero)
>   renaming (suc to zero)
>   using (zero)
> ```

I have a strong opinion that this code should raise an error of some kind. More generally, I do not see a use case for allowing more than one `renaming` or `using` or `hiding` clause for a single `open`.

**Comment by gallais** [comment]
> I do not see a use case for allowing more than one `renaming` or `using` or `hiding` clause for a single `open`.

The only use-case I could see is someone really attached to the idea of listing
imports alphabetically.

**Comment by andreasabel** [comment]
> I have a strong opinion that this code should raise an error of some kind.

I am only fixing the OP now, duplicates in `using`.  Thus, my convoluted example will continue to raise an error.

>  I do not see a use case for allowing more than one `renaming` or `using` or `hiding` clause for a single `open`.

It allows the user to organize these listings according to their own aesthetics/logics.  Not sure how common this is, though.  (I personally have not used this feature as far as I remember.)

However, it has been allowed since the beginning and unless we have a strong reason, we should not suddenly disallow it.

**Comment by andreasabel** [comment]
Removing the check in the parser forces me to revisit #3331.  This is forbidden by the parser (`verifyImportDirective`) at the moment:
```agda
open import Agda.Builtin.Bool using (true) renaming (true to tt)

-- Expected error:
-- Repeated name in import directive: true
```
It is not hard to bring this check back into the scope checker.  Maybe I should just do it for separation of concerns.  Although it is not entirely clear to me why we forbid this.

P.S.: The Great Ulf Himself added the check back in the dawn of time (5ba14b647b9bd175733f9563e744176425c39126) when Agda 2 wasn't even believed to exist yet. 
As of today, only the keywords are untouched (https://github.com/agda/agda/blame/master/src/full/Agda/Syntax/Parser/Parser.y#L2094); still, I will make myself guilty of vandalizing archeological artifacts by removing it.

**Comment by andreasabel** [comment]
Fixed the OP.  I tried hard to preserve archeological artifacts, preserved most of the code of `verifyImportDirective`. 😉

**Comment by andreasabel** [comment]
> However, it has been allowed since the beginning and unless we have a strong reason, we should not suddenly disallow it.

Actually, not since the beginning, only since #493 (in 2013).
