### ISSUE TITLE
Duplicate actions run

### ISSUE THREAD

**Issue by gallais** [agda/agda#4729]
It looks like we have a special rule for branches named `issueN` and for PRs.
Unfortunately the builds seem to run more than once if more than one condition
is met.

Cf. #4719 for instance where every action is run twice, once with `(push)` and
once with `(pull_request)` as the justification. This leads to running 26 tests
instead of the 13 intended.

**Comment by EdNutting** [comment]
I don't think there's anything special about `issueN` branches. At the moment, the builds are configured to run on a push to any branch that touches files within `src/` and a few other select files. They will also run on any pull request that touch the same set of files. 

So when somebody pushes their issue branch, the CI runs. If they then decide to submit a PR, an entirely independent set of CI runs is triggered (as you noted).

In the documentation, I can't see a way to avoid this directly. I.e. you can't create an "on push but not if followed by a pull request in the next X minutes" condition - they're just not linked events.

My suggestion would be that the CI conditions are changed to:

push: Existing paths configuration but only on `master`, `releaseX` and `stabelX` branches
pull_request: Existing paths configuration

Thoughts?

**Comment by EdNutting** [comment]
(To be a little more technically accurate: While it would _technically_ be possible to create a hacked mechanism to effectively cancel `push` runs when `pull_request` ones occur or when a `pull_request` run already exists, it would be exceedingly brittle and, as I said, hacked. I don't recommend it at all, based on having read the documentation for Github Actions over the last couple of weeks. I much more recommend my suggestion above.)

**Comment by gallais** [comment]
Every time I pushed to the branch in the PR, all 26 tests would be re-run.
It was not just a one-time matter following the creation of the PR.

**Comment by EdNutting** [comment]
Yes, this is expected behaviour. The push triggers the push event which triggers the first batch of tests. The new commits cause the PR to be updated which thus triggers a pull request event. The pull request event is triggered for creation and for update to the PR branch. My proposal would avoid the unnecessary triggers for branch pushes.

**Comment by jespercockx** [comment]
I'm having the opposite problem now, I just pushed to my PR https://github.com/agda/agda/pull/4722 and there are *no* tests being run.

**Comment by gallais** [comment]
Oh I see, I had misunderstood your comment. Thanks for the clarification
(and the PR). I am systematically opening PRs so I am happy with the
proposed new behaviour but I'll let others who may have a different workflow
comment.

**Comment by andreasabel** [comment]
When I activated the (back then, travis) ci for `issueNNNN` branches, it was exactly because I wanted ci to run without opening a PR.  I am often fixing trivial issues which do need discussion/review, thus I do not want to open a PR.  (Also, it is a further manual interaction with github I can skip when not opening a PR.)

I think it is fine to have branches that are ci-checked.  I am not married to a specific prefix, so if people want to grab `issue` for non-ci branches, I am happy to call my branches `ciNNNN` or the like.

One problem that is not avoided that if a ci-branch is turned into a PR later, the duplication is created.  In some rare cases, this will happen.  Maybe at first I think a fix is minor, but then it grows and I change my mind and open a PR to get reviewing.  If this is very bad, I can push to a new branch without ci tracking.

I think the other szenario is more likely: that people create a PR to slowly implement a feature step by step, using the PR as a discussion forum. In this case, ci runs on the PR are pointless until the PR has matured to actually be tried on CI.  Does your proposal address this problem as well somehow?

**Comment by UlfNorell** [comment]
Is is possible to access the tags of a PR when deciding to run CI? It would be amazing if CI wouldn't run on branches marked `wip`.

**Comment by EdNutting** [comment]
Okay, I'll work on the following then (I'm not touching Travis - only Github Actions. I can look at Travis in future):

Github CI to:

1. Not run on `issueXXXX` branches
2. Run on `ci-issueXXXX` branches
3. Run on all PRs
4. Fast-abort operations if the PR is tagged with `wip`

In the case that a `ci-` branch is turned into a PR, it is easiest to just push a new non-ci branch (it's trivial to branch and push the new one).

**Comment by EdNutting** [comment]
~It turns out there was a significant misunderstanding.~

~Pull requests do not trigger CI runs (again, I don't know about Travis, I'm only talking about Github Actions). CI runs are linked to commits.~

~So:
A) If you create an `issueNNN` branch, and then push commits to it, Github CI will run against those commits. If you also create a PR, the PR simply refers to the CI runs of the related commits - it doesn't duplicate work.~

~B) If you commit stuff on a fork, then create a PR to the main agda repo, Github CI will run against the head commit of the request. If you subsequently push new changes to the branch of the PR, new CI runs are created for the new head.~

~Github doesn't duplicate work.~

Original:
In the process of discovering this, I now have a script/Github action that can short-circuit CI runs if they are for commits on branches that have a pull request with the label 'wip'. This may be useful - I'll follow up on Monday.

Added note: There is a much simpler way to solve this problem, as it turns out. It's buried in the documentation of the [`contains` operator](https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#contains) - see summary in comments below.

**Comment by andreasabel** [comment]
> Github doesn't duplicate work.

Travis does.  If I have a PR created from a branch on agda/agda and push to this branch, travis starts two instances, one for `push` and one for `pr`.  If after a successful CI I then push the branch to master, the same test run for a third time (of course, this is useful if some rebasing or merging happened, but often the push is clean).

Github should also have the latter duplication, i.e., when pushing a PR/branch to master, I suppose.

**Comment by EdNutting** [comment]
Okay I need to go back and review this again. When we were testing it yesterday we couldn't get Github to trigger PR events just from pushing commits. I can't understand why at the moment. But searching back through Github's Action logs:

https://github.com/agda/agda/actions?query=branch%3Aissue4704+workflow%3A%22stack+build%22

It's clear that two distinct kinds of event are occurring and it is duplicating work.

It's inexplicable to me at the moment that the simplified test case we created (which was just a cut-down version of the `stack.yml` script) didn't reproduce the issue.

**Comment by EdNutting** [comment]
The simplified test case didn't run because `pull_request` workflows need to be in the default branch of the repo for Github to recognise they exist. It seems that once they are in the default branch, Github will then run modified versions from head commits of a PR. I can't find any documentation that properly explains where Github chooses the Workflow files from though. Anyway, now that I have a working, simple reproduction of the original issue in my fork...

---
---

***It looks like we need some combination of the following applied to the jobs in each of the workflows:***

---

Skip a job if it was triggered by a `pull_request` that is merging from a branch in the same repo:

```yaml
jobs:
  Ubuntu:
    if: |
      (github.event_name != 'pull_request')
      || (github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id)
```

---

Skip a job if the commit message contains `skip ci`:

```yaml
jobs:
  Ubuntu:
    if: |
      (github.event_name != 'push')
      || !contains(github.event.head_commit.message, 'skip ci')
```

---

Skip a job if the pull request was labeled as `wip` (work in progress)

```yaml
jobs:
  Ubuntu:
    if: |
      (github.event_name != 'pull_request')
      || (!contains(github.event.pull_request.labels.*.name, 'wip')
```

---

*Again, I don't know how to translate this to Travis.*

**Comment by EdNutting** [comment]
(It's also possible to skip a `push` job if there exists a `pull_request` labeled with `wip` but it requires a custom action which I have working but is a bit complicated. It might not be what we want either. Running CI on `push`es of WIP stuff seems like a desirable thing).

**Comment by gallais** [comment]
> Running CI on pushes of WIP stuff seems like a desirable thing

I am of the opinion that we should let people say what they mean instead of
guessing based on already existing workflows: we can add a new label "No CI"
for PRs that should not get built.

**Comment by andreasabel** [comment]
> new label "No CI" for PRs that should not get built.

Why not the old label `[ci skip]`?

**Comment by gallais** [comment]
I thought we were talking about the kind of labels you attach to issues and PRs?
If we are talking about labels inside of commit messages then yeah `[ci skip]` is
good.

**Comment by andreasabel** [comment]
Ah, ok, thanks.  How about `ci skip` then as label name (since it has the same semantics).

**Comment by EdNutting** [comment]
Shall I go ahead then and add `[ci skip]` (and `[skip ci]`) as "if this is in the commit message, skip Travis and GH Actions"?

Edit: According to this page, `[skip ci]` (and variants) should already work for Travis (when included in the head commit message of a push): https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build

**Comment by asr** [comment]
I haven't followed the discussion, but I use `[ci skip]` for skipping Travis but no GitHub workflows. What would I use instead?

**Comment by EdNutting** [comment]
@asr Continue as you do normally. The proposal is to add a check to the Github workflows so that `[ci skip]` will also skip the GH workflows (in addition to skipping Travis).

**Comment by andreasabel** [comment]
I think `[ci skip]` would be sensible to also skip the github workflows.  @asr seems to use `[ci skip]` for only skipping travis, if I understand correctly?

**Comment by asr** [comment]
> @asr seems to use `[ci skip]` for only skipping travis, if I understand correctly?

Right.

**Comment by rwe** [comment]
Regarding the original duplicate actions issue described by @gallais (vs. the `[ci skip]` enhancement, which solves a problem but not the original one here): when I put together the hlint workflow (#4802), I separated out `push` versus the specific `pull_request` sub-events:
https://github.com/rwe/agda/blob/608edb44958a00f370c3dd3603790c8440be6175/.github/workflows/lint.yaml#L3-L23

Otherwise even things like `edited`, `labeled`, will trigger the actions: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request

I believe that avoids the "multiple suites run on each push to a PR" problem.

**Comment by rwe** [comment]
Ah, I'm dumb, I just explicitly did what the docs said:
> By default, a workflow only runs when a pull_request's activity type is `opened`, `synchronize`, or `reopened`.

Though I wonder if those defaults are being overridden to "any" since path filters are being provided to the triggers, and so you _do_ need to explicitly list the events?

**Comment by EdNutting** [comment]
By my reading of the docs and some (limited) testing, providing one parameter does not result in an (undocumented) override of the defaults for other parameters. 

The problem is simply that Github runs the workflow twice: once for the commits pushed and once for the PR update (triggered by the new commits). It doesn't de-duplicate by noticing that the runs overlap. Hence my suggestion of the various options for limiting when the CI runs / skipping a Github workflow if it's going to be in both a PR and a branch - but this appears to be overly complicated and is tied to the various different workflows people are using. Hence the decision to keep things simple for now with a `ci skip` command.

Personally I think it's slightly odd that people are pushing issue branches directly into the repo. GitHub is setup for people use forks for working on stuff and then make PRs when they're ready, with the root repo being "golden" and branches in the root repo being for "projects". This way of using GitHub is baked into the Workflows - Github explicitly switches of workflows for fork repos by default, thus stopping the excessive duplication. Developers are expected to test locally when they're ready, then PR, CI runs on the root repo's PR and maintainers can then accept/reject the PR. (I.e. the CI isn't intended to be part of the edit-test development cycle. It's meant as a last-check/test-suite, final-build/nightly-build, etc use cases).

Edit: Other use cases include triaging issues, branch management, etc - essentially, management/delivery/devops tasks, not in-the-development-cycle.

**Comment by rwe** [comment]
> The problem is simply that Github runs the workflow twice: once for the commits pushed and once for the PR update (triggered by the new commits)

You're right: I didn't see a double-run in my hlint workflow, but I just overlooked it: https://github.com/rwe/agda/pull/1/checks

So it still happens there.

> Personally I think it's slightly odd that people are pushing issue branches directly into the repo. GitHub is setup for people use forks for working on stuff and then make PRs when they're ready, with the root repo being "golden" and branches in the root repo being for "projects".

I agree. Forking is the better approach, it prevents root repos from being overrun by dangling branches with unclear ownership or prunability, and prevents accidental work stompage. Though since Agda is still a small community, and branches are sometimes collaboratively developed, in those cases there are reasons to have those be in shared repo. Not sure how often that comes up, but I think I've seen more of that here than some other projects.

**Comment by gallais** [comment]
> dangling branches with unclear ownership or prunability

Extensions such as https://github.com/sindresorhus/refined-github allow you to auto-delete
a branch upon merging a PR. That is what I use.

**Comment by andreasabel** [comment]
I don't see this issue fixed, e.g. look at https://github.com/agda/agda/pull/5158/checks .
Even though I did not push to some "blessed" branch, like `issue*`, the CI ran `on: push`, and in parallel also `on: pull_request` for the same commit set.
I thought branches didn't get CI by default unless their names falls into a special pattern. See these patterns e.g. in the travis config:
https://github.com/agda/agda/blob/5672440c6e97c0c821176e4900dc64b1a9cc15a2/.travis.yml#L17-L27

Regarding the discussion on whether to work on a fork or on the upstream repo:
- Opening branches in the main repo, I save myself from maintaining a fork of Agda.
- My commits are all in the main repo, so the links within github are stable.  This isn't the case if commits were on a fork, then referenced in some comments, and then deleted with or on the fork.  GitHub then complains that it couldn't find the commits.  It is not that this couldn't happen with deleted branches in the main repo, but in my gut feeling this is less common...

**Comment by UlfNorell** [comment]
* It's also makes it a lot easier for other people to try your branch if they don't have to set up a remote to your fork.

**Comment by gallais** [comment]
> Opening branches in the main repo, I save myself from maintaining a fork of Agda.

I don't think there is any maintaining to do: you can have both `agda/agda`
and `andreasabel/agda` as remotes to the same local repo (with agda/agda the
blessed `origin` one). When you want to work on a new feature you can:

* git checkout master
* git pull
* git checkout -b my_cool_branch
* [work & commit]
* git push andreasabel -u my_cool_branch

and then open a PR to `agda/agda`.

The branches on your fork will go stale but you don't care because the
`master` in your local repo will be the blessed `origin` one rather than
the one of your fork.

> It's also makes it a lot easier for other people to try your branch
  if they don't have to set up a remote to your fork.

I used to think that too but I got used to it while working on idris where
we don't have the logic to avoid duplicated runs. It's a simple

* git remote add thiscontributor git@github.com:thiscontributor/agda (here you need to be careful that thiscontributor has not named their fork something else than agda but that's very rare)
* git fetch thiscontributor
* git checkout -b thebranch thiscontributor/thebranch

and you're there! The first step can be skipped if you have already added
the remote (which happens often in practice because we mostly get repeat
contributors rather than one shots, especially for the big PRs that you
want to test / touch yourself before merging).

**Comment by andreasabel** [comment]
Er, we haven't made much progress.  In principle, there are two standard workflows:
- PR: push to a branch (here or in a fork) and open a PR
- NoPR: push to a branch because I want to run CI, but I don't want to open a PR yet

So maybe we can set up CI as follows:
- by default, only run on `pull_request` (supports PR)
- if the branch name starts with a dedicated prefix, like `ci-`, then also run on `push` (supports NoPR)

Since we are more and more switching to a `PR` workflow, maybe this default is the right one.

**Comment by andreasabel** [comment]
Discussion 2021-04-21:  Let's implement this:

> So maybe we can set up CI as follows:
> 
>     * by default, only run on `pull_request` (supports PR)
> 
>     * if the branch name starts with a dedicated prefix, like `ci-`, then also run on `push` (supports NoPR)

Pushes to `master` should also run CI.

Update: In PR #5338 I left the old prefixes 'issue' and 'release' in place rather than introducing a new one like `ci-`.
Ironically, this means that the OP won't be fixed (which talked about an `issueXXX` branch).

**Comment by UlfNorell** [comment]
(continuing discussion from #5393)

@andreasabel Can motivate *why* you decided to not implement the change we agreed on. What's the use case you wanted to preserve where you need to run CI but don't want to make a PR and a more natural name for the branch is `issueXYZ`, rather than `ci-ABCD`.

**Comment by andreasabel** [comment]
No, I was just conservative.  Changing this to `ci-*`...

**Comment by asr** [comment]
> No, I was just conservative. Changing this to `ci-*`.

@andreasabel, why you didn't make the change in `github/workflows/lint.yaml`?

**Comment by andreasabel** [comment]
@asr: I think I grepped in `*.yml`, but `lint.yaml` does fall out of this pattern, so I missed it.
