### ISSUE TITLE
primShowQName creates not-in-scope names

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#4735]
My silly counter to #4734:
```agda
open import Agda.Builtin.Nat renaming (Nat to Nombre)
open import Agda.Builtin.Equality
open import Agda.Builtin.Reflection

test : primShowQName (quote Nombre) ≡ "Agda.Builtin.Nat.Nombre"
test = refl

fails : primShowQName (quote Nombre) ≡ "Agda.Builtin.Nat.Nat"
fails = refl
```
All the way through 2.5.1.1 - 2.6.1 `primShowQName` shows a somewhat meaningless qualified name `Agda.Builtin.Nat.Nombre`. I suppose it should show a valid qualified name instead.

**Comment by andreasabel** [comment]
I think `primShowQName` only exposes the weirdness of `QName`s inside Agda.  Usually one does not see them printed literally, but beautified for he current context, thus, the issue stays internal.

**Comment by UlfNorell** [comment]
Yeah, the problem is that the `QName` stores the concrete name it was referenced by. The same doesn't seem to be true for the module names though:

```agda
module A where
  module B where
    postulate X : Set

open A renaming (module B to B₂)

test : primShowQName (quote B₂.X) ≡ "Issue4735.A.B.X"
test = refl
```

Two options:
- store the original name in the `QName` (either replacing the current concrete name or adding it)
- fix the implementation of `primShowQName`

For the latter there are four separate implementations to fix:
- the primitive binding in `TypeChecking.Primitive`
- the shortcut in `TypeChecking.Reduce.Fast` (which would would fall back to the primitive binding if removed)
- the ghc backend in `Compiler.MAlonzo.Primitives`
- the js backend in `src/data/JS/agda-rts.js`

For the compiler backends we would need to do some work up front when compiling a `QName` literal.

**Comment by UlfNorell** [comment]
I'm checking to see what breaks if we simply store the original concrete name in the `QName`.

**Comment by UlfNorell** [comment]
For the record (@gallais will you reset the counter?):
```agda
open import Agda.Builtin.Nat renaming (Nat to Nombre)
open import Agda.Builtin.Equality
open import Agda.Builtin.String
open import Agda.Builtin.Reflection

cong : {A B : Set} (f : A → B) → ∀ {x y} → x ≡ y → f x ≡ f y
cong f refl = refl

q₁ = quote Nombre
q₂ = quote Agda.Builtin.Nat.Nat

q₁≡q₂ : q₁ ≡ q₂
q₁≡q₂ = refl

f : String → Nombre
f "Agda.Builtin.Nat.Nombre" = 0
f _                         = 1

boom : 0 ≡ 1
boom = cong (λ q → f (primShowQName q)) q₁≡q₂
```

**Comment by UlfNorell** [comment]
Update: The only thing (in the test suite) that fails if we change to the original concrete name is the error for ambiguous constructors. There we no longer have the concrete name the user wrote.

**Comment by UlfNorell** [comment]
It also breaks #1792 if you rename to a mixfix name.

**Comment by UlfNorell** [comment]
PR: #4758

I settled for adding the original concrete name as a separate field and use that in the `Pretty` instance for `QName` (which is what is used by `primShowQName`). That way we don't have to worry about cases where we do want the concrete name the user wrote, and we don't have to do scope gymnastics to retrieve it during evaluation/compilation.
