### ISSUE TITLE
Rename definitional equality?

### ISSUE THREAD

**Issue by pnlph** [agda/agda#4748]
Would it be possible/useful the ability to rename definitional equality, like with `Set`? Did this discussion take place already?

For example, in [1304.0809](https://arxiv.org/abs/1304.0809) @gallais et al. use the right squig arrow `\leadsto` to represent what we denote in Agda statically by `=`.

**Comment by guillaumebrunerie** [comment]
I think the problem with that is that the parser would need to be completely rewritten (unlike for `Set`, which is just an identifier), and that nobody has put forward strong enough arguments for why it would be worth it.

**Comment by gallais** [comment]
Caveat: in Agda you may write equations that do not actually hold definitionally
because the definitions by pattern-matching allow overlapping patterns & use a
first-match semantics. That is the point of the `--exact-split` option.

**Comment by andreasabel** [comment]
Both for Haskell and Agda it would be more economic to use `->` instead of `=`.  In Haskell, I often turn a set of clauses into a `\case` and then need to turn all the `=`s into `->`s.  In Agda, we also have the pattern lambda which uses a different separator than the function clauses.

However, we cannot turn the clock back 15 years.  Also, having too many configurable parts in a language definition leads to the _Babylonian language confusion_, where everyone will use a different syntax and no one will understand the code written by a peer.

**Comment by pnlph** [comment]
Thank you for the answers. I now know how hard the specification of this feature would be both conceptually and technically.

In life, one has to say no sometimes, and this may well be one of such a prototypical situation. 😅 

IMHO, the confusion responsibility lies on the user who produces code. E.g., the ability to rename `Set` was an excellent feature that put both more freedom and responsibility, i.e., possibly more weight, on the shoulders of Agda users. One user may ignore it; another user may use it appropriately like renaming `Set` to `Type` [to avoid some hack](https://github.com/agda/cubical/issues/327); another may misuse it when renaming to `refl` or `Bool`.

I think in Agda, most of the responsibility devolves upon the user. It is always possible though to understand with peers just by exercising that responsibility and using the same convention. When a peer has strong reasons to name/rename a commonly widespread notion, it is her responsibility also to communicate and justify that choice thoroughly.

I will close now the issue. Hopefully someone will be able to find a strong use case to reopen it again in the future.
