### ISSUE TITLE
Internal error when trying to use incorrect lambda syntax to pattern match

### ISSUE THREAD

**Issue by JakobBruenker** [agda/agda#4775]
```agda
open import Agda.Builtin.Sigma

data Foo : Set where
  foo : Foo → Foo

data Bar : (y : Foo) → Set where
  bar : ∀ y' → Bar y' → Bar (foo y')

baz : (x : Foo) → Σ Foo Bar → Foo
baz (foo x) with baz x
... | g = λ (f , bar y' s) → g (y' , s)
-- fixed line
-- ... | g = λ { (f , bar y' s) → g (y' , s) }
-- another fixed version
-- ... | g = λ where (f , bar y' s) → g (y' , s)
```

produces

```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/RecordPatterns.hs:68
```

While I don't think this should compile, I suppose it shouldn't throw an internal error either.

Tested on 2.6.1.

**Comment by andreasabel** [comment]
Here is a shrunk version not using `with`:
```agda
open import Agda.Builtin.Nat
open import Agda.Builtin.Sigma

data IsSuc : Nat → Set where
  isSuc : ∀ y → IsSuc (suc y)

test : Σ Nat IsSuc → Set
test = λ (_ , isSuc _) → Nat
```

**Comment by gallais** [comment]
Unsurprisingly this is inherited from `let ... in`:

```agda
open import Agda.Builtin.Nat
open import Agda.Builtin.Sigma

data IsSuc : Nat → Set where
  isSuc : ∀ y → IsSuc (suc y)

test : Σ Nat IsSuc → Set
test = λ p → let (_ , isSuc _) = p in Nat
```

**Comment by andreasabel** [comment]
For some reason, internally the `suc` pattern in the reconstruction `(suc y, isSuc x)` ends up being declared with `conPRecord = True`, which is bogus.  This prevents the `recordPatternToProjections` to throw a proper error, and subsequently it crashes since the type of the "record" pattern is missing unexpectedly.
https://github.com/agda/agda/blob/01e51b23d83c32a6a89bf603a683585f9d757211/src/full/Agda/TypeChecking/Rules/Term.hs#L1579-L1594
The wrong information seems to come from `checkLeftHandSide`, likely from the unifier.

**Comment by andreasabel** [comment]
There is a suspicious unconditional setting of `conPRecord = True` in function
https://github.com/agda/agda/blob/528a9fd3788245d6d2f4d33d394e3305ae3f5bbc/src/full/Agda/TypeChecking/Rules/LHS/Unify.hs#L1250-L1253
here:
https://github.com/agda/agda/blob/528a9fd3788245d6d2f4d33d394e3305ae3f5bbc/src/full/Agda/TypeChecking/Rules/LHS/Unify.hs#L1281-L1283
I guess the question "Is this a problem?" can be answered slightly in the affirmative, if it lead to this crash. 😆 

Commit which introduced this: https://github.com/agda/agda/commit/51659d8479d6265e280fd8253a9efff7a9d3fd4b#r40131953

Removing the setting `conPRecord = True` fixes the OP and seems to pass the testsuite (fingers crossed).

**Comment by andreasabel** [comment]
My fix changed some output in the interaction suite.  Some changes have been waived through before (https://github.com/agda/agda/commit/e531104ecdfd9efc1e76bf0e9b5f9690f31bcaab#r40133390) I suppose in connection to dot-shuffling.
I leave the investigation to the printer to another issue, as this issue is fixing a bug which might have been unintentionally exploited to get nicer printing.  Likely, 51659d8479d6265e280fd8253a9efff7a9d3fd4b has to be redone, properly.

**Comment by andreasabel** [comment]
Slain Hydra head #4775 regrew three fresh heads: #4776 #4778 #4779
