### ISSUE TITLE
Emacs agda-mode setup command failing.

### ISSUE THREAD

**Issue by capn-freako** [agda/agda#4814]
What do I need to do, to fix this?

```
$ agda-mode.exe setup
agda-mode.exe: emacs: rawSystem: does not exist (No such file or directory)
```

Emacs: v. 26.3
Agda: v. 2.6.1

**Comment by andreasabel** [comment]
I think this issue was closed on error (by fixes that addressed #4812).

@capn-freako : Did you manage to fix the problem?  (If not, we need more information to help.)
But it looks like `emacs` is not on the `PATH` when `agda-mode` tries to run it.

**Comment by capn-freako** [comment]
It looks like I fixed the problem manually, but then realized that I’d inadvertently wiped out my Emacs installation, which might explain why I was having the problem in the first place:

Run agda-mode setup.

$ agda-mode setup
agda-mode.exe: emacs: rawSystem: does not exist (No such file or directory)
Same result in PowerShell.

Adding .emacs.d/ to home directory doesn’t help: (Real one is in: ~/AppData/Roaming/.)

$ echo $HOME
/c/Users/capnf

$ pwd
/c/Users/capnf

$ mkdir .emacs.d

$ agda-mode setup
agda-mode.exe: emacs: rawSystem: does not exist (No such file or directory)
Added the following to ~/AppData/Roaming/.emacs.d/init.el, instead:

(load-file
 (let ((coding-system-for-read 'utf-8))
   (shell-command-to-string "agda-mode locate")))
Install Emacs

I think the old one got removed when I uninstalled the two Agda Bundle s.
(Oh, maybe, that’s why the trouble above?)

**Comment by UlfNorell** [comment]
So fixed? Closing for now, reopen if needed.

**Comment by capn-freako** [comment]
Yes, sorry. I'd forgotten this.
I am running under Windows 10 w/o issue (well, except for font support, but that's a separate issue).

**Comment by JacquesCarette** [comment]
I am encountering this issue myself right now (Agda v2.6.1.2, emacs v27,2, Windows 10 with WSL2, running inside a Ubuntu container).

@andreasabel 's guess:
> But it looks like `emacs` is not on the `PATH` when `agda-mode` tries to run it.

is quite likely part of the issue.

**Comment by rwe** [comment]
@JacquesCarette The cause that @andreasabel described would just be that emacs is not installed and configured correctly on that system. If you cannot run the `emacs` command directly, `agda-mode` cannot either.

Are you able to run `emacs` as a command?

**Comment by JacquesCarette** [comment]
Yes, I can run `emacs` as a command, from a WSL2 shell. I cannot run it from a cygwin or DOS shell.

I think the problem is that I have a linux version of `emacs` but a previously installed "windows" version of `agda`, and these don't like each other. I can see `agda` (and `agda-mode`) just fine from the WSL2 shell, but since `agda-mode` uses `rawSystem` which uses Windows' `CreateProcess` under the hood, that's where things go off the rails.

I'm thinking I might be better off installing Agda also on the Ubuntu side of WSL2.

**Comment by rwe** [comment]
Oh, wow, that's an interesting interaction! I haven't used WSL, but I can imagine how those could confuse each other. If I understand correctly, that's expecting "Windows Agda"  to run "WSL2 emacs", but it fails because the latter isn't part of the Windows `%PATH%`. I imagine even if it could be found, there might be some surprises related to differing filesystem layouts? Maybe not? https://docs.microsoft.com/en-us/windows/wsl/interop

It seems one shortcut might just be to add a batch script `emacs.bat`:
```bat
wsl emacs %*
```
There are probably less hacky ways of doing that, though, and I agree with your assessment that you might be better off installing Agda on the Ubuntu side.

**Comment by JacquesCarette** [comment]
Continuing to learn... do **not** attempt to install the haskell tool chain with ghcup if you've got some other pieces already installed (either via the Windows installer or via apt-get; I had some of both still around). That fails miserably, with super obscure error messages.

**Comment by JacquesCarette** [comment]
Further information: looks like WSL can give you WSL 1 unless you prod it really hard to always do WSL 2, even though WSL 1 is quite broken and unsupported by Microsoft.

Setting up an X server on Windows that works properly is also challenging.

But anyways, as far as this particular issue is concerned: I think to close it, what's needed is a much better error message. For example, if the full $PATH value was output as part of a message that read "emacs can no be found anywhere on ...", then at least you'd know what PATH value `agda-mode` has. The rest of the 'fix' is entirely outside `agda-mode`.

**Comment by andreasabel** [comment]
> what's needed is a much better error message. For example, if the full $PATH value was output as part of a message that read "emacs can no be found anywhere on ...", then at least you'd know what PATH value `agda-mode` has.

I implemented your suggestion as:
```
$ PATH=foo:bar dist-2.6.3-ghc-9.0.1-quick/build/agda-mode/agda-mode setup

FAILED: emacs --no-desktop -nw --no-splash --eval '(with-temp-file "/var/folders/lg/qcd3v89j59l3m6520kr42bdm0000gn/T/askEmacs1089-0" (insert (expand-file-name user-init-file)))' --kill
Exception: emacs: rawSystem: runInteractiveProcess: exec: does not exist (No such file or directory)
Executable emacs at: (not found)
PATH:
  - foo
  - bar
```

**Comment by JacquesCarette** [comment]
Wonderful, thank you.  (There has been other comments about `agda-mode` and PATH on the Zulip, and I think this error would have helped them somewhat too.)
