### ISSUE TITLE
Replace biginteger.js with native BigInt

### ISSUE THREAD

**Issue by wenkokke** [agda/agda#4878]
Arbitrary precision integer arithmetic as [BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) was standardised in JavaScript, and is pretty much implemented across the board. Currently, we package `agda-rts.js` with an implementation of arbitrary precision integer arithmetic, `biginteger.js`. We should consider migrating to using BigInt.

**Comment by phile314** [comment]
Yeah, I think the standardised BigInt was not yet around when that code was written. Of course, now that it's there it would make sense to use the builtin BigInts.

Edge seems the latest to catch up and only supports it since January 2020 [1], but I think it would still be okay to move to builtin BigInts as browsers should be updated regularly anyway for security reasons.

[1] https://caniuse.com/#feat=bigint

**Comment by mastarija** [comment]
Would this be a good first issue for someone with "medium" experience with Haskell and some Agda (and a decent amount of JS knowledge)?

**Comment by gallais** [comment]
That sounds like the perfect first issue for such a person!
(Or the perfect first person for such an issue)

**Comment by mastarija** [comment]
@gallais Ok, I guess I'll get on it. I'm assuming `agda-rts.js` is the main file of interest? Do we want a fallback support with `biginteger.js` or is it Ok to just replace everything with native `BigInt`? Also, I should replace the use of `primIntegerFromString` with `BigInt` constructor where possible, right?

**Comment by wenkokke** [comment]
What PR closed this?

**Comment by jespercockx** [comment]
https://github.com/agda/agda/pull/5636 presumably
