### ISSUE TITLE
Regression

### ISSUE THREAD

**Issue by nad** [agda/agda#4893]
The following code is accepted by Agda 2.6.1, but not by Agda 2.6.2-d30045f:
```agda
open import Agda.Primitive

variable
  ℓ       : Level
  A B C   : Set ℓ
  u v x y : A
  P       : A → Set ℓ
  f g     : (x : A) → P x

record R a : Set (lsuc a) where
  field
    _≡_  : {A : Set a} → A → A → Set a
    cong : {A B : Set a} {x y : A}
           (f : A → B) → x ≡ y → f x ≡ f y

module _ (r : ∀ {a} → R a) where

  open module R′ {a} = R (r {a})

  postulate
    cong₂ : (f : A → B → C) → x ≡ y → u ≡ v → f x u ≡ f y v
    _     : {x≡y : x ≡ y} {u≡v : u ≡ v} →
            cong₂ (λ x → f (g x)) x≡y u≡v ≡ cong₂ f (cong g x≡y) u≡v
```
```
Unsolved metas at the following locations: […]
```

**Comment by andreasabel** [comment]
Still type checks with agda compiled on 24 August 2020.  I'll try a bisect.

**Comment by andreasabel** [comment]
@jespercockx, agda-bisect seems to blame the skipping of sort comparison:
> d867f5741d85c0f77e7822a289368d8d8107d625 is the first bad commit
> Date:   Tue Aug 25 12:38:04 2020 +0200
>
>    [ fix #4615 ] Enable --no-sort-comparison by default

**Comment by jespercockx** [comment]
Here's a minimized version with all records, modules, implicit arguments, and unused arguments removed:
```agda
open import Agda.Primitive

variable
  ℓ : Level
  A : Set ℓ
  P : A → Set ℓ
  f : (x : A) → P x

postulate
  R : (a : Level) → Set (lsuc a)
  r : (a : Level) → R a

  Id : (a : Level) (A : Set a) → A → A → Set a
  cong₂ : (a b c : Level) (A : Set a) (B : Set b) (C : Set c) (x y : A) (u v : B)
          (f : A → B → C) → Id c C (f x u) (f y v)

  foo   : (x y u v : A) (g : A → A) →
          let a = _ in
          Id a (Id _ _ _ _)
               (cong₂ _ _ _ _ _ _ x y u v (λ x → f (g x)))
               (cong₂ _ _ _ _ _ _ (g x) (g y) u v f)
```

It's suspicious that the type arguments are solved, but their universe levels are not. This is supposed to be prevented by the extra check on the sort of metavar solutions. It seems like the problem has something to do with the `variable`s, perhaps they circumvent this extra check in some way.

**Comment by jespercockx** [comment]
I'm a bit at a loss. First it seemed that the problem was caused by the fact that variable generalization makes direct use of `assignTerm'` (which doesn't check for the sorts of solutions) instead of `assign` (which does). But since generalization explicitly constructs the type of its solution from the type of the meta itself, I don't see how this could ever be a problem. But I don't understand the code in `Generalize.hs` well enough to be really certain the problem isn't somewhere there either.

**Comment by UlfNorell** [comment]
I can have a look ~~tomorrow~~ next week.

**Comment by UlfNorell** [comment]
Looks like this is the problem:
```
adding constraint _C.ℓ_34 ⊔ _c_70 = _C.ℓ_34 ⊔ _62
                    (blocked on any(_C.ℓ_34, _62, _c_66))
```
That's the constraint that's preventing the level variable from being generalized.

It's blocking on `_c_66` instead of `_c_70`. It so happens that `_c_66` was instantiated to `_c_70` shortly before the constraint is created, so there's a missing `instantiate` somewhere. With the wrong blocking tag the constraint isn't woken up when `_c_70` is solved to `_62`, making the constraint trivially true.

I think `agda-bisect` wrongly blamed @jespercockx here, and this is my bad.
