### ISSUE TITLE
Travis hanging on stack build size-solver

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda#4900]
Both #4895 and #4898 got hit by this, but other builds are passing so seems like an intermittent problem. Not sure how to debug.

**Comment by rwe** [comment]
Example of failing build: https://travis-ci.org/github/agda/agda/jobs/722914016

Not sure if it's 8.10.2 specific or not.
The command is:
```sh
stack build "${ARGS[@]}" "${FLAGS[@]}" size-solver
```
where:
```
GHC_VER=8.10.2
FLAGS=(--flag Agda:enable-cluster-counting --ghc-options '+RTS -M4G -RTS')
ARGS=(--silent --stack-yaml "stack-${GHC_VER}.yaml" --no-terminal --system-ghc)
```

The only recent change there was the increased RTS options, which were need to get 8.10.2 to build Agda at all, but shouldn't cause an issue here. GHC-8.10.2 builds slower than previous versions. The main Agda build is not run with `--silent`, but building `size-solver` does. Maybe it's just taking longer than before, and because of the silent flag it's timing out due to no output? I'll give that a shot.
