### ISSUE TITLE
Internal error in Agda.TypeChecking.Sort

### ISSUE THREAD

**Issue by nad** [agda/agda#4907]
The following code is accepted by Agda 2.6.1, but Agda 2.6.2-d30045f throws an internal error:
```agda
_∘_ : {A : Set} {B : A → Set} {C : {x : A} → B x → Set₁} →
      (∀ {x} (y : B x) → C y) → (g : (x : A) → B x) →
      ((x : A) → C (g x))
f ∘ g = λ x → f (g x)

postulate
  R : {A : Set₁} → A → A → Set₁

_≡_ : {A : Set₁} → A → A → Set₁
_≡_ = R

data D (A : Set) : Set where
  c : A → D A

postulate
  cong  : {A B : Set₁} {x y : A} (f : A → B) → x ≡ y → f x ≡ f y
  refl  : {A : Set₁} {x : A} → x ≡ x
  A     : Set
  P     : D A → Set
  p     : (F : A → Set) → (P ∘ c) ≡ F → (P ∘ c) ≡ F
  eq    : P ≡ P

_ : p (P ∘ c) (cong (_∘ c) eq) ≡ p (P ∘ c) (cong (_∘ c) eq)
_ = cong (λ eq → p _ eq) (cong (cong (_∘ c)) refl)
```
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Sort.hs:195
```

**Comment by nad** [comment]
Bisection points towards d867f5741d85c0f77e7822a289368d8d8107d625 ("[ fix #4615 ] Enable --no-sort-comparison by default").

**Comment by nad** [comment]
I have also encountered the following error:
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Sort.hs:201
```

**Comment by jespercockx** [comment]
It seems that the conversion checker is trying to instantiate a meta with a solution whose type is not (yet known to be) equal to the type of the meta. The new check introduced by d867f57 however assumes that if the type of the meta is a sort, then the type of the solution should also be (syntactically) a sort. So the problem is caused by the fact that the conversion checker is very liberal wrt solving heterogeneous equations (at least more than I assumed).

The obvious fix is to allow not only solutions whose type is a sort, but also those whose type is still a meta that will later be instantiated by a sort. I've implemented that and it seems to fix the problem, running the full test suite now.

**Comment by jespercockx** [comment]
My fix seems to work but the double-checker now complains:
```
_106 (_ = x) should be a sort, but it isn't
when checking that the solution P (c x) of metavariable _110 has
the expected type _106 (_ = x)
```
The problem seems to be again that the double-checker is run "too early", when the type of the solution is not yet known to be a sort. This is confirmed by the debug output:
```
double checking solution
checking solution for meta _110
  _110  :  _106 (_ = x) := P (c x)
{ 
checking internal  P (c x) : _106 (_ = x)
checking spine  (P : D A → Set) [$ c x] : _106 (_ = x)
{ 
checking internal  c x : D A
checking spine  (c : A → D A) [$ x] : D A
{ 
checking internal  x : A
variable x has type A
checking spine  (x : A) [] : A
}
}
}
```
A possible solution would be to make `shouldBeSort` throw a pattern violation when its argument is not yet known to be a sort b/c of a metavariable.

**Comment by jespercockx** [comment]
In #4065, @Saizan writes:

> I mean, I wonder if `[5] _6 := (_ : _4) [ℓ] :? Set` contains any useful information, however I suppose we can print such constraints when they get elevated to an error?

Actually this constraint gives me plenty of information, assuming I know the origin of the two metavariables `_4` and `_6`. The fact that Agda currently makes it very hard to trace back the origin of a metavariable should not be an excuse to hide information, but rather to *add more* so the user can make sense of the error. (There is the separate question of how difficult it is to interpret the information in an error, but the information has to be there in the first place.)

**Comment by jespercockx** [comment]
Phew, this turned out to be a lot harder to fix than I thought. In the end, only the second part of the fix turned out to be necessary (making `shouldBeSort` and compatriots throw a pattern violation) but this seems to have some unintuitive effect on the double-checker. I'm *reasonably* sure that this is an issue with the double-checker and not with my fix (after all there's still quite a few test cases that don't pass with `--double-check`) but feel free to take a closer look if you want. https://github.com/agda/agda/issues/4519 makes it very hard to see what's going wrong when `--double-check` fails.
