### ISSUE TITLE
The caching machinery is broken

### ISSUE THREAD

**Issue by nad** [agda/agda#4917]
Caching does not work for the following code:
```agda
{-# OPTIONS -vtc:5 #-}

data D (A : Set) : Set₁ where
```
Debug output when the code is loaded the first time:
```
Checking D.
Checked D.
Positivity graph: N=0 E=0
Positivity graph (completed): E=0
```
Debug output when the code is reloaded:
```
Checking D.
Checked D.
Positivity graph: N=0 E=0
Positivity graph (completed): E=0
```
Debug output when an interface file exists, Agda is restarted and the code is loaded:
```
```
Debug output when the code is reloaded:
```
Checking D.
Checked D.
Positivity graph: N=0 E=0
Positivity graph (completed): E=0
```

**Comment by nad** [comment]
The following files can perhaps be used as a test case:
* `Issue4917.agda`:
  ```agda
  {-# OPTIONS -vtc:5 #-}

  data D (A : Set) : Set₁ where
  ```
* A test script:
  ```haskell
  #!/usr/bin/env runhaskell

  {-# LANGUAGE RecordWildCards #-}

  import Data.List
  import System.Exit

  import RunAgda

  main :: IO ()
  main = runAgda [ "--no-libraries"
                 , "--ignore-interfaces"
                 , "--caching"
                 ] $ \(AgdaCommands { .. }) -> do

    -- Discard the first prompt.
    echoUntilPrompt

    -- Load the module.
    loadAndEcho "Issue4917.agda"

    -- Reload.
    output <- loadAndEcho "Issue4917.agda"

    -- Check the output.
    if "Checking D" `isInfixOf` unlines output
    then exitFailure
    else exitSuccess
  ```
For some reason the test case succeeds for Agda 2.6.1 even if `--caching` is replaced by `--no-caching`. I wonder if the flag is implemented incorrectly.

**Comment by nad** [comment]
Bisection points to 053a682276d0c1570dd6da38d224014744aa9def ("[ fix #4093 ] Make Set and Prop from keywords into builtins, enable auto-import of Agda.Primitive using (Set; Prop)").

**Comment by nad** [comment]
When I replace `--caching` with `--no-caching` in the test case, then bisection points to 549f939bcef2c36f98a0f7cee97a00553a324199 ("[ fixed #4647 ] top-level interaction: access to private decls."). Was some problem related to the `--caching` flag fixed in this commit?

**Comment by andreasabel** [comment]
> Was some problem related to the `--caching` flag fixed in this commit?

No, this commit implements the machinery to re-typecheck when an interactive command is used that may want to access the private declarations (which are zapped from the interface files).

**Comment by uncle-betty** [comment]
As I understand the Agda code, loading the currently edited file is supposed to always ignore an existing interface file and trigger a type-check. This behavior seems to have been introduced for #4647. More technically, when `getInterface'` is evaluated with `MainInterface (TypeCheck TopLevelInteraction)`, then an existing interface file is ignored.

I'd thus say, the issue at hand is rather: Why isn't the interface file ignored when loading the currently edited file for the first time after restarting Agda?

I took a look and loading the currently edited file right after restarting Agda gets us a `MainInterface (TypeCheck RegularInteraction)` in `getInterface'`. Hence, the interface file is loaded. Subsequent reloads of the file then correctly use `TopLevelInteraction` instead of `RegularInteraction`. Hence, the interface file is ignored.

As far as I can tell, the `--caching` flag shouldn't factor into this, as it affects a different kind of caching that is not related to interface files. The cache that's enabled or disabled with the flag, the `LoadedFileCache`, is used to speed up the process of type-checking. So, this cache only comes into play once Agda has decided to actually type-check a file.

As I understand it, the `LoadedFileCache` speeds things up when repeatedly type-checking the same currently edited file. It allows Agda to (quickly) "replay" the state changes effected by the previous type-check of the currently edited file. Agda keeps "replaying" from the cache up to the source code location where a modification has been made since the previous type-check. At this location Agda then falls back to a (slower) "full" type-check of the remaining file.

**Comment by andreasabel** [comment]
Thanks for the great analysis, @uncle-betty !

> Subsequent reloads of the file then correctly use `TopLevelInteraction` instead of `RegularInteraction`. Hence, the interface file is ignored.

There is a choice to make:
1. Either, we keep the current behavior and close this issue as working-as-intented.  Then it means that if you reload a file that you want to type check it.
2. Or, we change the current behavior to stay in `RegularInteraction` when reloading.  This means that reloading a file may do nothing, and re-type-checking is only triggered when you use a top-level interaction command that accesses a private declaration (switching to `TopLevelInteraction`). This should bring back the old behavior before #4647.

**Comment by uncle-betty** [comment]
The interface file is used not only after restarting Agda, it's also used when switching to a different file. `RegularInteraction` is in effect - and an available current interface file is used - whenever Agda's idea of what the current main file is changes, i.e.,

* when it changes from "no file" to some file X after having restarted Agda, or
* when it changes from file X to file Y.
 
So, it seems like C-c C-l is generally treated as a top-level interaction, but immediately after a file change it is treated as a regular interaction. Hence the different behavior.

**Comment by nad** [comment]
> There is a choice to make:
> 
>     1. Either, we keep the current behavior and close this issue as working-as-intented.  Then it means that if you reload a file that you want to type check it.
> 
>     2. Or, we change the current behavior to stay in `RegularInteraction` when reloading.  This means that reloading a file may do nothing, and re-type-checking is only triggered when you use a top-level interaction command that accesses a private declaration (switching to `TopLevelInteraction`). This should bring back the old behavior before #4647.

I'm not quite sure what you are suggesting above. However, I do think that we should support caching properly. With Agda 2.6.1 caching ensures that performance is often decent when I work at the end of a large file.

**Comment by uncle-betty** [comment]
Oh, wait a second. Maybe then there isn't any problem after all. I don't think that the collected data allows us to conclude that there's an issue with caching.

When given C-c C-l for unmodified source code (as in the above instructions for reproducing the issue), Agda does one of the following two things:

* It either type-checks the source code and creates an interface file, or
* it loads an existing interface file.

Compared to 2.6.1, current master more often prefers type-checking over loading when given C-c C-l. In other words, Agda prefers the recently introduced top-level interaction mode over regular interaction mode for C-c C-l. This was a side-effect of the #4647 changes.

This doesn't change anything about caching, though. Caching does not mean "load an existing interface file instead of type-checking." Caching means "speed up type-checking." So, the fact that current master type-checks in situations in which 2.6.1 would simply have loaded the interface file doesn't say anything about caching.

So, when current master type-checks a file, then this should be just as fast as it was with 2.6.1. Do you have reason to believe that this is not the case? E.g., do you see degraded type-checking performance compared to 2.6.1?

**Comment by uncle-betty** [comment]
Just to be clearer and relate what I said to the provided debug output:

* `Checking D.` is Agda chosing to type-check. This should still involve caching.
* The empty output is Agda chosing to load the existing interface file.

This can be confirmed by increasing the verbosity for `import` instead of `tc`. However, I'd do this in my `.emacs` file rather than via `OPTIONS`. When pragmas in the source code are processed, Agda is already past the point where it decided whether to type-check or load.

I'd do something like this: `(setq agda2-program-args '("--verbose" "import:10"))`

To double-check that caching is in effect, increase the verbosity for `cache`.

**Comment by nad** [comment]
> So, when current master type-checks a file, then this should be just as fast as it was with 2.6.1. Do you have reason to believe that this is not the case? E.g., do you see degraded type-checking performance compared to 2.6.1?

Yes, I see degraded performance.

**Comment by nad** [comment]
> When pragmas in the source code are processed, Agda is already past the point where it decided whether to type-check or load.

When you write "load" I guess you mean loading the interface file, rather than type-checking every declaration in the source file. I'm mainly interested in the second scenario. Take the following code:
```agda
data D (A : Set) : Set₁ where

A : Set
A = {!!}
```
If I repeatedly load the file, and change the definition of `A` every time, Agda should type-check `D` at most once.

Here's another example:
```agda
open import Agda.Builtin.Equality
open import Agda.Builtin.Nat

data D : Set₁ where

fib : Nat → Nat
fib 0             = 0
fib 1             = 1
fib (suc (suc n)) = fib n + fib (suc n)

_ : fib 27 ≡ 196418
_ = refl

A : Set
A = {!!}
```
With interactive highlighting on it is clear that Agda normalises `fib 27` every time the file is loaded. However, if the data type is removed from the file, or if `D : Set₁` is replaced by `D : Set`, then caching works as it should.

**Comment by uncle-betty** [comment]
Ooooh, I see. Thank you for the details. I think I get it now. So, you're saying that the declaration of `D` kicks Agda out of "replay the cached previous type-check log" mode and makes it fall back to full type-checking mode - even though `D` did not change at all between type-check runs. Yes, I now see that this would be a caching bug.

I had looked at the wrong `Checking` and `Checked` messages in the Agda code, but now I see the light! I guess I need to do something about my Haskell code navigation. Sorry about the confusion.

**Comment by uncle-betty** [comment]
I think that the `Def'` data constructor for `Expr` introduced into `Agda/Syntax/Abstract.hs` in 2ee3cd0b01 has an issue: `Expr`'s `Eq` instance definition still uses the old data constructor, `Def`, instead of the new one, `Def'`. So comparing a `Def'` to another `Def'` always falls through to the catch-all, which yields `False`.

So, no two `Def'`s are ever considered to be equal.

So, when Agda finds a declaration in the cache that contains a `Def'`, it will erroneously think that this declaration was changed, even if it wasn't. Agda will thus fall back to full type-checking (as opposed to replaying the cache).

Maybe @jespercockx can confirm real quick whether the `Eq` instance for `Expr` should say `Def'` instead of `Def`? If so, then the fix for the caching issue should be pretty straight forward.

**Comment by jespercockx** [comment]
Yes, that seems to be a shameful omission on my part. The `Eq` instance should definitely use `Def'` rather than `Def`!

**Comment by uncle-betty** [comment]
And I have to correct myself: No two `Def'`s **with a suffix** are ever considered to be equal. I guess that's why `Set` works, but `Set₁` doesn't.

**Comment by jespercockx** [comment]
Right, I *did* set `Def f` to be a pattern synonym for `Def' f NoSuffix`. It seemed like a good idea at the time :S

**Comment by nad** [comment]
Perhaps more bugs can be uncovered or avoided if `Def` is removed.

**Comment by uncle-betty** [comment]
I issued a pull request with a proposed fix: #4918. I'll leave the even bigger question of whether to completely get rid of `Def` to people more familiar with the Agda code. I just enjoy learning my way around the code base through fixing bugs.

**Comment by nad** [comment]
Thanks for the fix!

**Comment by uncle-betty** [comment]
I'm glad I could help. It's a good way for me to get familiar with Haskell in general and the Agda code base in particular.

Thanks for the merge and for bearing with me while I figured things out.
