### ISSUE TITLE
Incorrect HTML generated for renaming clause

### ISSUE THREAD

**Issue by nad** [agda/agda#4952]
Consider the following code:
* `A.agda`:
  ```agda
  module A where

  postulate
    A : Set
  ```
* `B.agda`:
  ```agda
  module B where

  import A renaming (A to B)

  postulate
    A : Set
  ```
If we generate HTML for `B`, then `B.html#A` points to the line with the renaming clause. Agda generates the following HTML for this clause:
```html
<a id="26" class="Keyword">renaming</a> <a id="35" class="Symbol">(</a><a id="36" href="A.html#29" class="Postulate">A</a> <a id="38" class="Symbol">to</a> <a id="A"></a><a id="41" href="B.html#41" class="Postulate">B</a><a id="42" class="Symbol">)</a>
```
Note the presence of `<a id="A"></a>`.

**Comment by andreasabel** [comment]
Its the HTML backend where this manifests, but the problem is more fundamental.  The concrete name `B` is associated directly to the abstract name `A.A` rather than to its own abstract name that links to `A.A`.  Concrete names are handled in the scope checker, in the abstract syntax we will see just
```
... renaming (A.A to A.A)
```
This abstract syntax is what the highlighter sees, and from this, we cannot create any sensible HTML anchor for the target `B` of the renaming.

One way to address this is issue would be to store better information in `A.ImportDirective` which currently is just an anlogue of `C.ImportDirective` but with abstract names instead of concrete names.
https://github.com/agda/agda/blob/ab10df5fc070271be683e626a0209ca5e90269f5/src/full/Agda/Syntax/Abstract.hs#L191-L193

Another, rather easy way to fix this issue is to remove the wrong HTML anchors.  @nad: Is it that you are offended by the garbage anchors (and happy to see them removed) or do you want to link to these names (so just removal would not satisfy you)?

**Comment by nad** [comment]
> @nad: Is it that you are offended by the garbage anchors (and happy to see them removed) or do you want to link to these names (so just removal would not satisfy you)?

In the example in the OP the incorrect anchor shadows a correct anchor. Removing the "garbage" would fix this particular problem. I do not currently have a strong need to link to a renamed name.

**Comment by nad** [comment]
I looked at one of the changed test cases. We used to generate the following HTML:
```html
<a id="SurroundingText._+_"></a><a id="643" href="InfixDeclaration.html#643" class="Postulate Operator">_+_</a>
```
Now we generate the following HTML instead:
```html
<a id="643" class="Postulate Operator">_+_</a>
```
Why did you remove `href="InfixDeclaration.html#643"`? It would have sufficed to remove `<a id="SurroundingText._+_"></a>`. Now it is non-trivial to find the numbered link for this token, if someone really wants to link to it.

**Comment by andreasabel** [comment]
The original html was:
```html
<a id="627" href="InfixDeclaration.html#492" class="Postulate Operator">_+_</a> <a id="631" class="Symbol">to</a> <a id="634" class="Keyword">infixl</a> <a id="641" class="Number">5</a> <a id="SurroundingText._+_"></a><a id="643" href="InfixDeclaration.html#643" class="Postulate Operator">_+_</a>
```

> Why did you remove `href="InfixDeclaration.html#643"`?

That's collateral damage. ;-)  The identifier following `to` is no longer a binding site, there is also no jump-to-definition feature (for that, you have to move to the identifier preceding `to`).

Note that this removed `href` pointed to itself.

> Now it is non-trivial to find the numbered link for this token, if someone really wants to link to it.

Not really.  You still have `id="643"`, from which you can trivially reconstruct the string `"InfixDeclaration.html#643"`.

**Comment by nad** [comment]
> > Now it is non-trivial to find the numbered link for this token, if someone really wants to link to it.
> 
> Not really. You still have `id="643"`, from which you can trivially reconstruct the string `"InfixDeclaration.html#643"`.

Previously you could just copy the link. One can still find the anchor by looking at the source code, but it is less obvious that there is an anchor to link to. However, I suppose that it is uncommon to want to link to this kind of thing, so we can leave things as they for now.
