### ISSUE TITLE
No Cycle should not look under lambdas.

### ISSUE THREAD

**Issue by Saizan** [agda/agda#4995]
The No Cycle rule for pattern matching unification looks under lambdas and so refutes function extensionality.

```agda
open import Agda.Builtin.Equality

cong : ∀ {A B : Set} → (f : A → B) → ∀ {x y} → x ≡ y → f x ≡ f y
cong f refl = refl

data ⊥ : Set where

data N : Set where
  ze : N
  su : (⊥ → N) → N

foo : N
foo = su (\ ())

postulate
  ext : ∀ {A : Set} → (f g : ⊥ → A) → f ≡ g

foo-suc : foo ≡ su (\ _ → foo)
foo-suc = cong su (ext (λ ()) (λ _ → foo))

-- bad!
no-cycle : ∀ {n} → n ≡ su (\ _ → n) → ⊥
no-cycle ()

false : ⊥
false = no-cycle foo-suc
```

**Comment by jespercockx** [comment]
I wonder where the construction of the proof of `noCycle` fails exactly for this datatype.

**Comment by turion** [comment]
I'm assuming you found this by investigating the bug involving sized types https://lists.chalmers.se/pipermail/agda/2020/012327.html, and realized that the sized types were incidental complexity there.

**Comment by andreasabel** [comment]
This would have an excellent candidate for issue #5000.

**Comment by jespercockx** [comment]
> This would have an excellent candidate for issue #5000.

Better prepare for disappointment

**Comment by jespercockx** [comment]
Actually the construction of `noCycle` itself is still 100% in this case, and we do actually have a proof `noCycle : (x : N) → x ⊀ x`. However, the problem here is that it is not possible to project out a proof of `⊥` out of a proof of `noCycle (su (\ _ → n))`: the type `su (\ _ → n) ⊀ su (\ _ → n)` is defined as `(x : ⊥) → (su (λ _ → n) ⊀ (λ _ → n) x) × (¬ su (λ _ → n) ≡ (λ _ → n) x)`, so one needs to have a term `x : ⊥` in the first place to get the contradiction.

In general, it seems the "No Cycle" rule is only valid for cycles where the telescope of each recursive argument position on the cycle is inhabited. This is something of a new insight to me, though it makes a lot of sense that this would be the case in hindsight (these recursive arguments with non-inhabited telescopes are really 'fake' arguments, since they're equivalent to a unit type). I wish I'd found this when I was working on the new unifier!

To fix this, a conservative approach would be to exclude higher-order types from the  "No Cycle" rule. A less conservative approach would be to try to detect a safe subset of inhabited types, but this would be quite some work depending on how precise we want the analysis to be.

**Comment by andreasabel** [comment]
Maybe just let occurrences under lambdas not be _strongly_ rigid.

**Comment by jespercockx** [comment]
Here's a refutation of funExt that does not rely on occurrences under lambdas being strongly rigid:
```agda
open import Agda.Builtin.Equality

data ⊥ : Set where

cong : {A B : Set} (f : A → B) {x y : A} → x ≡ y → f x ≡ f y
cong f refl = refl

postulate
  funExt : ∀ {A B : Set} {f g : A → B}
         → (∀ x → f x ≡ g x) → f ≡ g

data D : Set where
  c1 : D → ⊥ → D
  c2 : (⊥ → D) → D

cycle : ∀ {n} → c2 (c1 n) ≡ n → ⊥
cycle ()

d : D
d = c2 λ ()

only-one-D : (x : D) → x ≡ d
only-one-D (c2 x) = cong c2 (funExt (λ ()))

boom : ⊥
boom = cycle (only-one-D (c2 (c1 d)))
```
Here the problematic thing is the partially applied constructor `c1 n : ⊥ → D`. So we should *also* not count occurrences constructor arguments as strongly rigid unless they are fully applied.
