### ISSUE TITLE
Broken windows build: missing packages in the repositories

### ISSUE THREAD

**Issue by gallais** [agda/agda#5012]
Some dependencies have been removed from the msys2 repos and now the build
reliably fails. I have tried to bump the icu version number to no avail: the
more recent releases use a `.zst` format which is not supported by the `msys2`
used by `stack` (cf. https://github.com/commercialhaskell/stack/issues/5300).

My understanding is that there is no hope atm.
I suggest disabling the windows builds.

Edit: Unfortunately we can't just switch to cabal for another windows build
because of #4513 which we had hoped would be solved by 8.10.2 but [is still
there](https://gitlab.haskell.org/ghc/ghc/-/issues/18634#note_308267) (although may get solved by 8.10.3 according to that thread :crossed_fingers:).

**Comment by andreasabel** [comment]
> I suggest disabling the windows builds.

Agreed.

**Comment by rwe** [comment]
I've pushed through #5021 which removes the `text-icu` installation from the Windows CI build, and removes the `cluster-counting` flag there and from the default Windows Makefile options. I recommend keeping this issue open (or at least marking it as unresolved) because it is currently not possible to build with cluster-counting on Windows until it's resolved upstream.

**Comment by gallais** [comment]
Fixed! Thanks @snoyberg!

**Comment by andreasabel** [comment]
> Fixed! Thanks @snoyberg!

Why snoyberg?  Link?  (UPDATE: see https://github.com/commercialhaskell/stack/issues/5300#issuecomment-721492825)
Did we reenable cluster-counting on the windows build?  If yes, which commit? (UPDATE: in 14311f60243909492ba1791267ebbf489738f777, thanks @L-TChen!)

**Comment by gallais** [comment]
Because of https://github.com/commercialhaskell/stack/issues/5300
