### ISSUE TITLE
Enable wiki pages

### ISSUE THREAD

**Issue by banacorn** [agda/agda#5063]
Following discussions from https://github.com/agda/agda/pull/5052 and https://github.com/agda/agda/pull/5052#issuecomment-728185329,
it would be nice if we can have wiki pages enabled for documenting internal implementation-related stuff.

**Comment by gallais** [comment]
What are the benefits compared to a bunch of `.md` files in a `wiki/`
directory of the repository? These would be versioned, could be edited
offline and would be easier to move if/when we have to leave github
in the future.

(e.g. it's very annoying that issues do not meet any of these criteria
at the moment).

**Comment by jespercockx** [comment]
Note that we already have a bunch of (mostly horribly outdated) design documents under https://github.com/agda/agda/tree/master/notes

**Comment by jespercockx** [comment]
Actually it seems that Github wiki's are actually their own repository (e.g. for Agda it would be `https://github.com/agda/agda.wiki.git`). So in fact a github wiki *would* be versioned and editable offline. So given the fact that the current documentation we have is horribly outdated and this is at least partially caused by the fact that it's not very easy to edit, I'm willing to give the Github wiki a try.

**Comment by jespercockx** [comment]
I figured there is no harm in giving it a try, so I enabled the wiki pages: https://github.com/agda/agda/wiki Consider this a trial period, so it is possible that we disable it again if there are objections or we find a better alternative. I'll keep this issue open until we decide that the trial period has ended.

**Comment by UlfNorell** [comment]
I think it's fine as long as we keep the scope of the wiki limited. Trying to keep some comprehensive developer documentation up-to-date on the wiki is doomed to failure, but for specific things like the json API it could work well.

**Comment by andreasabel** [comment]
I think a good place for developer documentation is our .hs source files, because there we are most likely to stumble over some outdated information.  However, the wiki could contain some more fundamental explanations, give an overview, and link to the more detailed information as found in the source files etc.
And if folks want to use the wiki (as opposed to issue discussions)to develop features and specs that's maybe not bad either.
