### ISSUE TITLE
Failing to infer the type of the reflected term

### ISSUE THREAD

**Issue by ashinkarov** [agda/agda#5075]
The following code:
```agda
open import Reflection
open import Reflection.Term
open import Data.List as L using (List; []; _∷_)
open import Data.Vec as V using (Vec; []; _∷_)
open import Data.Unit
open import Data.Nat
open import Data.Product
open import Function using (_$_)

macro
  rtest : Name → Term → TC ⊤
  rtest f a = do
     (function (_ ∷ clause tel₂ _ t₂ ∷ [])) ← getDefinition f where
        _ → quoteTC "ERROR" >>= unify a
     t₂ ← inContext (L.reverse $ L.map proj₂ tel₂) $ normalise t₂
     quoteTC t₂ >>= unify a

transp : ∀ m n → Vec (Vec ℕ n) m → Vec (Vec ℕ m) n
transp 0 n []       = V.replicate []
transp _ n (x ∷ xs) = V.zipWith _∷_ x (transp _ n xs)

_ : Term
_ = rtest transp
```
dies with the following error:
```
/home/tema/src/agda-extractor/Bug.agda:23,5-17
x != x₁ of type ℕ
when checking that the expression x₂ has type Vec ℕ x₁
```
It works fine if you get rid of call to `normalise` in the macro.  The reason is that Agda is failing to infer the type for `t₂`, however, there are no `unknown`s in neither term or the telescope.

I am on `Agda version 2.6.2-fd5ab4a`.

**Comment by ashinkarov** [comment]
It was noticed by @jespercockx that if we write `suc m` explicitly in the second case, the problem disappears:
```agda
transp : ∀ m n → Vec (Vec ℕ n) m → Vec (Vec ℕ m) n
transp 0       n []       = V.replicate []
transp (suc m) n (x ∷ xs) = V.zipWith _∷_ x (transp _ n xs)
```

**Comment by ashinkarov** [comment]
This actually might have something to do with #5044 .

**Comment by jespercockx** [comment]
Oh, I think I found the cause. If I'm correct it's quite surprising no-one had problems with this before. It seems the quoting for clauses was still using the de Bruijn indices based on the order in which the pattern variables appear in the pattern, rather than the indices that are (now) embedded in the pattern variables. It's a good thing this was found before we actually released a version with the clause telescopes, as that would've been very embarrassing ;) 

Luckily the fix is very easy as it just requires deleting two lines of code.
