### ISSUE TITLE
Error lost when --only-scope-checking in invalid combination

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#5101]
Seems like refactoring #5020 dropped the check that `--only-scope-checking` isn't used meaninglessly.

Agda 2.6.1:
```
$ agda-2.6.1 --only-scope-checking --interactive Bla.agda
Error: The options --interactive, --interaction, --interaction-json and
--only-scope-checking cannot be combined with each other or
with --html or --dependency-graph. Furthermore
--interactive and --interaction cannot be combined with
--latex, and --only-scope-checking cannot be combined with
--vim.
```

Current `master`:
```
$ agda --only-scope-checking --interactive Bla.agda
                 _ 
   ____         | |
  / __ \        | |
 | |__| |___  __| | ___
 |  __  / _ \/ _  |/ __\     Agda Interactive
 | |  |/ /_\ \/_| / /_| \
 |_|  |\___  /____\_____/    Type :? for help.
        __/ /
        \__/

The interactive mode is no longer under active development. Use at your own risk.
Main> S
Set
Main> :q
```
Seems like `--only-scope-checking` is now ignored without error:  `Bla.agda` contains
```agda
S = Set
```
and if it were only scope-checked, it could not know that the value of `S` is `Set`.

Same for `--interaction`:
```
$ agda-2.6.1 --only-scope-checking --interaction 
Error: The options --interactive, --interaction, --interaction-json and
--only-scope-checking cannot be combined with each other or
with --html or --dependency-graph. Furthermore
--interactive and --interaction cannot be combined with
--latex, and --only-scope-checking cannot be combined with
--vim.

$ agda --only-scope-checking --interaction 
Agda2> 
```

Ping @rwe.

**Comment by andreasabel** [comment]
The `checkOpts` implementation
https://github.com/agda/agda/blob/0d6ff44f9cb5c5caea5fe05da4fd6ded7cc0b513/src/full/Agda/Interaction/Options/Base.hs#L323-L343
should be revisited.  I think part of the error message is dead:
> The options --interactive, --interaction, --interaction-json and --only-scope-checking cannot be combined with each other.

I think when this error is displayed, it does not apply to the situation.  
- It is not triggered when it should (OP).
- When it is displayed, the user did not mix the options described there.

Further, since `exclusive` is now a singleton list, a lot of the code is meaningless and should be simplified to the new situation.  Of course, if `exclusive` is still a singleton after fixing the OP.

**Comment by rwe** [comment]
Huh. Will take a look. I do recall a commit that I considered including in that PR related to additional interactor option validation, but did not include because I convinced myself it was redundant. But I might have been wrong, in that it was only redundant for the backends, not the interactors.

That said: are you certain that `--only-scope-checking` would not know that value? (Direct assignments are fairly special-cased, no?).

The reason I'm suspicious of that is that the repl's "typecheck" action is invoked here:
https://github.com/agda/agda/blob/0d6ff44f9cb5c5caea5fe05da4fd6ded7cc0b513/src/full/Agda/Interaction/CommandLine.hs#L119

which comes from this:
https://github.com/agda/agda/blob/0d6ff44f9cb5c5caea5fe05da4fd6ded7cc0b513/src/full/Agda/Main.hs#L198-L202

which should be `ScopeCheck`.

**Comment by rwe** [comment]
In other words: I agree with this issue that there's an options validation + error message bug.

But tangentially, is there a reason the `repl` would not work under scope-only mode? I suppose most of the commands except for `scope` would be useless or incomplete, but that might still be useful for doing the where-is/apropos-like lookups, maybe. Eh. Maybe not.

**Comment by rwe** [comment]
Ugh, I see what went wrong. The error message is not wrong, it _was_ checking the interaction modes there.
I think the issue was not #5020, it was #5082 as I removed the backends from that list.

Here's the original code: https://github.com/agda/agda/blob/250427ac7a8bd3f26e133aaed6cce7c473860d80/src/full/Agda/Interaction/Options.hs#L347-L363
And here's with the backends removed:
https://github.com/agda/agda/blob/339aa5a7616e05d587718928e7fa5caec93cdb31/src/full/Agda/Interaction/Options/Base.hs#L330-L337

That `atMostOne` thing included in all of the `snd` elements contains all of the `fst` elements. So it's a one-level recursive check. Super confusing…

**Comment by andreasabel** [comment]
> That `atMostOne` thing included in all of the `snd` elements contains all of the `fst` elements. So it's a one-level recursive check. Super confusing…

Indeed, this code is super convoluted and confusing.  I was reading `checkOpts` and didn't understand why it is so complicated.  So I looked at the history and found your changes and had the impression that something in the refactoring mightn't have been rounded off.  
I agree that it wasn't #5020, I mis-attributed.

There had been no checks in `test/Fail` to check for conflicting command-line options of that sort;  I already added one.  Please check whether more tests are needed to cover the respective error messages.  We are aiming at that each error message that Agda throws should have at least one representation in `test/Fail`.

**Comment by rwe** [comment]
@andreasabel There's now a PR fix out for that. See #5105
