### ISSUE TITLE
Parse error using underscores

### ISSUE THREAD

**Issue by heades** [agda/agda#5125]
The following gives a parse error:

```
foo_open : Set
foo_open = ⊤
```

Error:

```
... in the name foo_open, the part open is not valid because it is a keyword: <ERROR>
 Set
foo_open = ⊤
...
```

Agda version 2.6.1.2

If I change it to `foo-open` or `fooOpen` it works.

**Comment by jespercockx** [comment]
Names with underscores have a special meaning in Agda, they are used to construct mixfix operators where the underscores indicate where the arguments should go. As the error indicates, you cannot use `open` as part of a mixfix name since it is a keyword. So this seems to be working as intended to me.

**Comment by heades** [comment]
Yeah, my bad. Sorry about that.
