### ISSUE TITLE
GitHub workflow test.yml (Build, Test, and Benchmark): Could not find module ‘System.FilePath.Find’

### ISSUE THREAD

**Issue by asr** [agda/agda#5138]
The workflow is generating the [error](https://github.com/agda/agda/runs/1713733185?check_suite_focus=true):

```bash
GenerateEverything.hs:12:1: error:
    Could not find module ‘System.FilePath.Find’
    Perhaps you meant
      System.FilePath.Windows (from filepath-1.4.2.1)
      System.FilePath (from filepath-1.4.2.1)
      System.FilePath.Posix (from filepath-1.4.2.1)
```
@L-TChen, why the missing dependency in `std-test` if the `filepath` library is a dependency of Agda?

**Comment by L-TChen** [comment]
The required package to run `GenerateEverything.hs` is actually `filemanip` instead of `filepath`. 

My guess is that it was merely lucky to have `filemanip` installed as required by some dependency, but now that mysterious package does not require `filemanip` any more. Perhaps `GenerateEverything` should be built properly using `stack` or `cabal` to solve the dependency.

**Comment by asr** [comment]
> Perhaps `GenerateEverything` should be built properly using `stack` or `cabal` to solve the dependency.

I guess the current easier solution is to use `cabal-install` via the `GNUMakefile`. I'll try it.
