### ISSUE TITLE
Rewrites are conjuring elements out of thin air

### ISSUE THREAD

**Issue by jonsterling** [agda/agda#5238]
The following code compiles in Agda 2.6.2:

```agda
{-# OPTIONS --rewriting #-}

open import Agda.Builtin.Equality
open import Agda.Builtin.Equality.Rewrite

data ⊥ : Set where

postulate
  T : Set
  t0 : T
  t1 : T

postulate
  foo : ⊥ → t0 ≡ t1
  {-# REWRITE foo #-}

test : t0 ≡ t1
test = refl
```

The rewrite should not apply in this case, because we don't have an element of `⊥` on hand. Now, I am not sure what I am asking this to actually do (since we can't just do proof search), but some possible behaviors could be:

1. Reject rewrite rules where the variable `x : ⊥` does not appear somewhere in the pattern
2. Potentially, allow this when `⊥` is quantified as an instance argument.

Behavior (2) above would be very useful to me, but I realize it is kind of hard and maybe not possible. Anyway, I just wanted to point out that this rewrite rule should either not be allowed, or it should not apply.

**Comment by jespercockx** [comment]
Well, yes, this is by design but I can see why it is undesirable. The reason why this is accepted is because to turn an algorithm into a rewrite rule, Agda will drop all arguments that are not used in the LHS of the rule. This is very useful when you are in a parametrized module and there are some parameters that are not involved in the rewrite rule, but there is no check that the types of the parameters are actually inhabited before they are dropped. So I see a couple of solutions:

1. Do not drop any arguments from rewrite rules. This would cause this rule to be rejected because the argument of type `⊥` is not bound on the LHS
2. Implement a check for inhabitation and only drop arguments when they are of an inhabited type. Possibly the inhabitation check could make use of instance search to find an inhabitant.

Option 1 is definitely the easiest but will break some code. Option 2 is harder to implement (depending on how sophisticated we want the inhabitation check to be) and will likely *still* break some code.

**Comment by jespercockx** [comment]
Actually the declaration of `foo` as a rewrite rule is rejected if you actually give a definition of `foo` (as `foo ()`) instead of giving it as a `postulate`. This is because of the logic introduced in https://github.com/agda/agda/commit/d3068a60ffaf3a784342e6b0dfe6b32efb6a6ffe for fixing #1980, which was further tweaked to ignore unused parameters in https://github.com/agda/agda/commit/aaa8ea508167ab8b1aaf56fd448ee84b6431e1e1. Perhaps another way to fix it would be to counts all arguments to a `postulate` as "used" by the definition.

**Comment by jespercockx** [comment]
I have implemented my proposed fix, but this causes some examples in the test suite to fail:

- The following example from #1652 is no longer accepted:
```agda
module _ (A : Set) where

  postulate
    plus0p :  ∀{x} → (x + zero) ≡ x

  {-# REWRITE plus0p #-}
```
- The examples with postulated rewrite rules in parametrized modules from #3211 and #3538 no longer work, which will probably make @andreasabel sad.
- Likewise, two more examples in `test/Succeed/RewriteConstructorParsAreGeneral.agda` and `test/Succeed/RewritingIgnoreUnusedParameter.agda` now fail because they use postulated rewrite rules in a parametrized module (where the parameter is not actually used in the rewrite rule).

To fix these test cases, we'd need to have some kind of check that certain types are inhabited so we can safely drop them from the rewrite rule. At the very least, we'd have to detect that `Set i` is inhabited. However, I'm a bit afraid of this approach as I'm not sure where we should draw the line for what types we can drop automatically. In general, I'm a bit allergic to these kind of analyses that try to be too smart for their own good, so I'd prefer to avoid introducing a new one if possible.

**Comment by andreasabel** [comment]
If rewrite rules are to be subjected to a more strict discipline, we should give the user a way to opt out of security, like we have for the termination and positivity checker.

>  I'm a bit allergic to these kind of analyses that try to be too smart for their own good

Yeah, these can be a problem.  
In situations where you have a check that reports an error, but you can override the check by force, this is maybe not too bad, though.

That reminds me that we have an inhabitation check, called Agsy; maybe you want to bring that up to speed (dirty laughter)?

**Comment by jespercockx** [comment]
To make the examples from #3211 and #3538 work, we could reconstruct the parameters of the constructor when we check the rewrite rule, and consider all the pattern variables in these parameters as "bound" for the purpose of checking that all arguments of the rewrite rule are bound in the LHS.

**Comment by jonsterling** [comment]
Hmmm, I am not sure why this ticket has been closed. In Agda 2.6.2, I can still typecheck my erroneous example. Did I misunderstand what the intention was with this?

**Comment by jespercockx** [comment]
That's really strange, I've added your example to the (failing) test suite in https://github.com/jespercockx/agda/commit/f6359f059be1459633c2c1c98889b36d4757150e, you should be getting the following error:
```
foo  is not a legal rewrite rule, since the following variables are not bound by the left hand side:  x
when checking the pragma REWRITE foo
```
Perhaps you need to delete the corresponding .agdai file? (Normally these are invalidated automatically for new versions of Agda, but you never know..)

**Comment by jonsterling** [comment]
ok, let me check that i haven’t messed something up on my end :)

>

**Comment by jonsterling** [comment]
OK it looks like I was on some pre-release version of Agda 2.6.2 somehow haha; I wiped out my Agda and installed fresh and now I get the correct behavior. Sorry for the false alarm and thanks for your help!!
