### ISSUE TITLE
github cabal build fails for macOS because of text-icu

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#5259]
The github workflow "cabal build" fails for macOS because of `text-icu`:
https://github.com/agda/agda/runs/2033568733?check_suite_focus=true

See #5012 and #5021 (PR) for the Windows instance.

Upstream issue: https://github.com/haskell/text-icu/issues/49

**Comment by L-TChen** [comment]
What’s the status of this? As it doesn’t look good, I propose to solve this temporarily by maintaining a repo containing fixes and specify the git repo as the dependency to use (at least for `stack`). Once the permission is transferred we can create a pull request to merge changes back. 

In the following few days, I’d like to look into ways to release binary distributions with the support `cluster-counting` enabled so that end users don’t have to deal with this.
