### ISSUE TITLE
Termination error reporting crashes with symlinks

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#5268]
Scenario:
- A file `a/b/c/Foo.agda` with content
  ```agda
  S : Set
  S = S
  ```
- A symlink `c` pointing to `a/b/c`.
- Loading `c/Foo.agda` into emacs.
- `C-c C-l`.

Results in:
```
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/TypeChecking/Errors.hs:295:18 
```
The crash occurs when termination errors as supposed to be printed at
https://github.com/agda/agda/blob/8d2c172cc2bc700e6eed993557ae11b19cedf682/src/full/Agda/TypeChecking/Errors.hs#L293-L295
and a module name for the current file is not found in `sourceToModule`.

I suppose I introduced this regression when fixing #4828.

**Comment by andreasabel** [comment]
`agda-bisect` says: 055e7a295fb65c7810102f76ad7895fddb653550 is the first bad commit.
Ping @rwe. 
> Date:   Thu Oct 15 17:08:28 2020 -0700
>
>   imports: Include origin path in SourceInfo
>    
>   This avoids some unnecessarily redundant lookups when that information is already available.
>
>   Note that `SourceInfo` is not serialized.

**Comment by andreasabel** [comment]
A test script to reproduce the problem is here: https://github.com/agda/agda/blob/4f87d3902b5b33a4ad05277b3275170b9efd20e3/test/interaction/Issue5268.sh

**Comment by rwe** [comment]
Argh. Thanks @andreasabel for the diagnosis and test case. This is clearly my fault somehow.

Unfortunately I won't likely have a chance to work on this for a little while. It's on my backlog when time frees up, unless someone gets to it first.

**Comment by andreasabel** [comment]
If this commit is just an optimization we could revert it for now, and you could fix it when you have time.  Or does something depend on it?

**Comment by uncle-betty** [comment]
Just to provide a few more data points:

  * The module-to-file mapping makes it into `stModuleToSource` as follows:

    * `checkModuleName` is evaluated for `.../tmp-issue-5268/sym/Issue5268.agda`, which passes the module name to `findFile'`.
    
    * `findFile'` in turn passes the module name to `findFile''`, along with a list of directories to search. The directories are `.../tmp-issue-5268/src/a` as well as the directory that holds Agda's built-in primitives. They seem to come from the include directory options.
    
    * `findFile''` finds the source code file in `.../tmp-issue-5268/src/a` and thus maps the module `Issue5268` to  `.../tmp-issue-5268/src/a/Issue5268.agda` in `stModuleToSource`.

  * The `lookupModuleFromSource` reverse lookup in `Errors.hs` that triggers the `__IMPOSSIBLE__` does a reverse lookup not for `.../tmp-issue-5268/src/a/Issue5268.agda`, but for `.../tmp-issue-5268/sym/Issue5268.agda`, which fails.

  * When changing the `.sh` file in the test case as suggested by the `No problem here` comment, then `findFile'` passes `.../tmp-issue-5268/sym` to `findFile''` instead of `.../tmp-issue-5268/src/a`. Now the reverse lookup for `.../tmp-issue-5268/sym/Issue5268.agda` succeeds.

I see a change around `findFile` in 055e7a2. The experiment of changing this line back to `file <- findFile x` indeed makes the issue go away. It somehow makes `findFile'` pass `.../tmp-issue-5268/sym` instead of `.../tmp-issue-5268/src/a` to `findFile''` when doing `checkModuleName` for `Issue5268`.

So, as far as I can see at this point, for some reason a change to `getInterface` - which changes whether `findFile` gets evaluated unconditionally or not - changes the directories searched by `checkModuleName`. Even though `checkModuleName` happens before `getInterface` in `typeCheckMain`. Odd. I must be missing something.

In any case, I think that a hacky temporary fix might possibly be to make `lookupModuleFromSource` look not just for `f` bust also for `canonicalizePath f`. Thus a module would be found by the original given path as well as the path's canonicalized version.

**Comment by uncle-betty** [comment]
Correction: While `file <- findFile x` does make the issue go away, it is not because this somehow magically changes the search paths. The search paths stay identical. Good. The world is logical again. (I had modified the test case's `.sh` file in a way that produced this red herring.)

I'll poke around a little more.

**Comment by andreasabel** [comment]
@uncle-betty See also be5cafa4a47d5952d3bc259ba076ce042c67027b where I dropped canonicalization of paths by default.  

> In any case, I think that a hacky temporary fix might possibly be to make `lookupModuleFromSource` look not just for `f` bust also for `canonicalizePath f`. Thus a module would be found by the original given path as well as the path's canonicalized version.

This does not sound too bad, but it should be marked with some comments as temporary solution.  

A more thorough fix could be to keep both a canonical and a non-canonical path around per module, where the non-canonical is only used to access the interface files.

**Comment by uncle-betty** [comment]
Ooooh, I see! So the truth is way more prosaic than what I was cooking up.

The `srcOrigin` member of `Source` is the source code path with the symlink intact. However, module source code lookup via `checkModuleName` / `findFile'` constructs the source code path that has the symlink resolved. This version of the source code path gets stashed into `stModuleToSource` by `findFile'`.

Doing the reverse lookup based on the `srcOrigin` member fails, because it has the symlink and the path in `stModuleToSource` doesn't.

`file <- findFile x` in `getInterface` makes the issue go away, because it unconditionally sets `file` to the path with the resolved symlink, whereas the actual code uses the `srcOrigin` member with the symlink intact.

Hmm. Regarding the proposed hack - I'm wondering: wouldn't this lead to a proliferation of `MonadIO`s all the way down to `lookupModuleFromSource`? Maybe littering all over the code is a little invasive for a temporary kludge like this.

**Comment by andreasabel** [comment]
> Hmm. Regarding the proposed hack - I'm wondering: wouldn't this lead to a proliferation of `MonadIO`s all the way down to `lookupModuleFromSource`? Maybe littering all over the code is a little invasive for a temporary kludge like this.

I had the impression that `lookupModuleFromSource` isn't used in many places, and sometimes, like in the OP, it is anyway a hack.  Some of these could be removed if we stored not only the `currentFile`, but also a `currentTopLevelModule`.

**Comment by rwe** [comment]
> If this commit is just an optimization we could revert it for now, and you could fix it when you have time. Or does something depend on it?

I believe it was just an optimization, but related to @uncle-betty's comment, around that time I was trying to reduce the scope of required `MonadIO`/`TCM` usage where possible.

**Comment by uncle-betty** [comment]
I started to add `MonadIO` type class constraints, but stopped after touching a dozen or so functions. This just seemed a bit much.

Instead, I'd like to propose a different fix. See pull request #5275.

The issue with canonicalization in #4828 is that in a path `/a/b/c/Foo.agda` the file name part, `Foo.agda`, is a symlink that gets resolved. In contrast, it seems okay to canonicalize any part of the directory, `/a/b/c`.

What the proposed fix does is strip off `Foo.agda`, canonicalize `/a/b/c`, and then re-append `Foo.agda`.
