### ISSUE TITLE
Performance regression on master

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#5279]
In #1625, @martinescardo reports the following:

> I am still having trouble with this issue. 
> 
> The files that @tomdjong mentions above in his experiments now take forever without the flag --experimental-lossy-unification in Agda 2.6.2 9599ddf (I waited for 30min), whereas in agda 2.6.1 the *whole* repository type checks in 3 min 30 sec only (without that flag, which is not available).
> 
> Moreover, the behaviour of this experimental flag is a bit strange: *with* the flag, some files don't type check. So the way to get everything to type check with the current development version of Agda 2.6.2 9599ddf is to alternate between running with and without the flag until everything type checks, with appropriate uses of ctrl-c for the modules that take a long time and need the flag. Something like this:
> ```
> $ rm *.agdai
> $ agda-2.6.2-2021-03-16 --version
> Agda version 2.6.2-9599ddf
> $ agda-2.6.2-2021-03-16 AllModules.lagda
> <ctrl-c after a module gets stuck for several minutes>
> $ agda-2.6.2-2021-03-16 --experimental-lossy-unification AllModules.lagda
> <we get an error in another module>
> $ agda-2.6.2-2021-03-16 AllModules.lagda
> <success>
> ```
> 
> So at the moment the development version of Agda is not usable in this repository. (To make things a bit worse, in Agda 2.6.1, I can't import a module that uses --cubical and the cubical library, as this needs 2.6.2.)
> 
> Moreover, as many of you know, I (deliberately) use a tiny fragment of Agda, and except for one module that disables non-termination and another that enables --type-in-type (to prove the famous contradiction), all modules are --safe. (By the way,  the module that uses type-in-type gives an error with this experimental flag.)
> 
> Additional information: I also had to change a few modules to make the above type checking succeed, to fix a number of unsolved constraints with Agda 2.6.2 9599ddf. The modified version still works with the current version 2.6.1.
> 

I think this is probably a separate issue, which is why I'm creating this one.

**Comment by martinescardo** [comment]
Thanks, @jespercockx . 

In the repository [TypeTopology](https://github.com/martinescardo/TypeTopology), adding --experimental-lossy-unification in just the module DcpoConstructions.lagda makes the whole repository type check in 4m43s with Agda 2.6.2. After removing DcpoConstructions.agdai and running Agda 2.6.2, we get 13 seconds to type check just this module. Without that flag, I waited for 78m without getting a result. 

In Agda 2.6.1, the whole repository takes 3m43s. Just the module DcpoConstructions.lagda with everything else already type-checked, and without the non-existing --experimental-lossy-unification flag, takes 25s (rather than 13s with the experimental flag in 2.6.2). 

So, overall, the whole repository takes about 1m more (or 1m10s more if we count the effect of the experimental flag) with the new version 2.6.2, which is a significant increase of more than 27% given the original time of 3m43s. This becomes more apparent when we run this in a (fairly decent) laptop, where the total time for 2.6.2 jumps to 7m32s.

**Comment by martinescardo** [comment]
I know exactly where this is happening. It is in the function `S₀ᵈᶜᵖᵒ` in the module DcpoConstructions.lagda. After the helper definition `γ₁ = ∐-is-lowerbound-of-upperbounds 𝓕 ε₁ y γ₂`, type checking gets stuck with Agda 2.6.2. If I replace `γ₂` by a hole, and delete all the helper functions after that, needed to define `γ₂`, type checking succeeds. Now if we just add ` γ₂` with its type by a hole in its body, type checking takes forever. If I rewrite the type, by manually expanding `underlying-function 𝓔 𝓕 (f (∐ 𝓓 δ))) (g (α i)) ⊑⟨ 𝓕 ⟩ y` to `underlying-order 𝓕 ((underlying-function 𝓔 𝓕 (f (∐ 𝓓 δ)) ∘ (g ∘ α)) i) y`, then type checking succeeds again, with another hole. However, at this point I don't know how to further expand the definitions to make Agda 2.6.2 succeed in a reasonable amount of time. 

What seems to be happening (as exemplified above) is that, as @tomdjong said in the other issue, Agda is expecting a different, definitionally equal, type, and determining the definitional equality is what is causing the time problem. When we can guess a particular expression of the type Agda wants, things go fast. We already encountered this problem in Agda 2.6.1. But then in 2.6.2 we have that Agda seems to want *another* expression of the same type to succeed fast enough.

**Comment by jespercockx** [comment]
Right. I guess that if you use `--no-syntactic-equality`, then things are slow on both versions of Agda? If that's the case then this is really caused by the fundamental brittleness of the shortcut rule in the conversion checker.

**Comment by martinescardo** [comment]
In Agda 2.6.1, this fails in 0.2s with `Failed to solve the following constraints: univSort 𝓤ω = univSort 𝓤ω` in a module that defines the empty type. 

(What does this flag do?)

**Comment by martinescardo** [comment]
Then in Agda 2.6.2 I get
```
time agda-2.6.2-2021-03-16 --no-syntactic-equality AllModulesIndex.lagda 
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/TypeChecking/Monad/Builtin.hs:452:31 in Agda-2.6.2-D6YsWFhUzLT43K1LQPcvAG:Agda.TypeChecking.Monad.Builtin

real	0m0.057s
user	0m0.025s
sys	0m0.025s
```

**Comment by martinescardo** [comment]
But then this is strange. I also compiled Agda 2.6.2 today in a laptop, and it didn't give the impossibility error, but it is stuck forever in the type checking of another module (MGS-Subsingleton-Theorems) with the flag you asked.

**Comment by martinescardo** [comment]
So far none of the versions of Agda I have has managed  to terminate  with `--no-syntactic-equality`, except the ones which gave an error.

**Comment by martinescardo** [comment]
Interestingly, they get stuck at different modules.

**Comment by jespercockx** [comment]
It turns off the syntactic equality shortcut in the conversion checking. The idea is that this makes typechecking probably slower, but the performance becomes less dependent on small changes between different versions of the code. Unfortunately (as you have noticed) there are some bugs that cause typechecking to fail when syntactic equality checking is turned off. If you do find such a case (preferably with a small test) it would be very useful to report it as a bug.

**Comment by nad** [comment]
I could make your code typecheck with Agda 2.6.2-0eaf439 by replacing
```agda
e₂ : ∐ (𝓔 ⟹ᵈᶜᵖᵒ 𝓕) ε₂ ≡ f (∐ 𝓓 δ)
```
with the following code:
```agda
e₂ : ∐ (𝓔 ⟹ᵈᶜᵖᵒ 𝓕) {α = underlying-function 𝓓 (𝓔 ⟹ᵈᶜᵖᵒ 𝓕) (f , cf) ∘ α} ε₂ ≡ f (∐ 𝓓 δ)
```
Using interactive highlighting I could observe that Agda had trouble typechecking `e₂`, and when I commented out its body (and some other code) Agda failed to infer the value of `α`.

**Comment by jespercockx** [comment]
While trying to find what could be the cause of this regression, I stumbled upon a small bug in the syntactic equality checker: in https://github.com/agda/agda/blob/0eaf4390361dce47e1200c4676d4b67c17710085/src/full/Agda/TypeChecking/SyntacticEquality.hs#L170-L173, the modalities should be compared using `sameModality` rather than `==`. While I've tested that this is not the actual cause of the regression here, this made me realize that small bugs like these in the syntactic equality checker are likely to go unnoticed for a long time, as their only effect is to make typechecking slower in certain cases. I wonder if we could set up an internal test for syntactic equality that would catch issues such as this one.

**Comment by martinescardo** [comment]
> I could make your code typecheck with Agda 2.6.2-0eaf439 by replacing
> 
> ```agda
> e₂ : ∐ (𝓔 ⟹ᵈᶜᵖᵒ 𝓕) ε₂ ≡ f (∐ 𝓓 δ)
> ```
> 
> with the following code:
> 
> ```agda
> e₂ : ∐ (𝓔 ⟹ᵈᶜᵖᵒ 𝓕) {α = underlying-function 𝓓 (𝓔 ⟹ᵈᶜᵖᵒ 𝓕) (f , cf) ∘ α} ε₂ ≡ f (∐ 𝓓 δ)
> ```
> 
> Using interactive highlighting I could observe that Agda had trouble typechecking `e₂`, and when I commented out its body (and some other code) Agda failed to infer the value of `α`.

Excellent. 

With this modification, the whole repository type checks in 

 * 3m45s in Agda 2.6.1 (same time as before) and  
 * 5m2s with Agda 2.6.2 (which before was infinity for all practical purposes (without --experimental-lossy-unification)).

But I wonder why 2.6.1 can infer this implicit argument and 2.6.2 can't. By the way, I had already fixed two files for which 2.6.2 couldn't infer undeclared types but 2.6.1 can.

(And, by the way, this file is not mine but @tomdjong's as part of his ongoing PhD, for the record.)

**Comment by martinescardo** [comment]
> Then in Agda 2.6.2 I get
> 
> ```
> time agda-2.6.2-2021-03-16 --no-syntactic-equality AllModulesIndex.lagda 
> An internal error has occurred. Please report this as a bug.
> Location of the error: __IMPOSSIBLE__, called at src/full/Agda/TypeChecking/Monad/Builtin.hs:452:31 in Agda-2.6.2-D6YsWFhUzLT43K1LQPcvAG:Agda.TypeChecking.Monad.Builtin

This error was not one of Agda but of installing too many Agda's with cabal - I got it afterwards also without the flag --no-syntactic-equality. So I had to recompile the development version of Agda to perform the above time measurements.

**Comment by martinescardo** [comment]
I am adding one more example. This file takes for ever in agda-2.6.2-0eaf439 (and about 1min in the same machine used for the above tests): https://github.com/martinescardo/HoTT-UF-Agda-Lecture-Notes/blob/master/HoTT-UF-Agda.lagda

**Comment by nad** [comment]
I suspect this is related to the fix of #418 (which is [documented](https://github.com/agda/agda/commit/0bd2e684b58c40dd07be7d0453902b4d0b96b66f)). Agda no longer infers the types of `i`, `ii` and `iii` in the following piece of code:
```agda
 univalence→' : (X : 𝓤 ̇ ) → is-subsingleton (Σ Y ꞉ 𝓥 ̇ , X ≃ Y)
 univalence→' X = s
  where
   abstract
     e : (Y : 𝓥 ̇ ) → (X ≃ Y) ≃ (Lift 𝓤 Y ≡ Lift 𝓥 X)
     e Y = (X ≃ Y)                 ≃⟨ i   ⟩
           (Y ≃ X)                 ≃⟨ ii  ⟩
           (Lift 𝓤 Y ≃ Lift 𝓥 X)   ≃⟨ iii ⟩
           (Lift 𝓤 Y ≡ Lift 𝓥 X)   ■
      where
       i   = ≃-Sym fe₀ fe₁ fe
       ii  = Eq-Eq-cong' fe₁ fe fe₂ fe₁ fe fe fe fe₃
               fe fe fe fe (≃-Lift Y) (≃-Lift X)
       iii =  ≃-sym (univalence-≃ ua' (Lift 𝓤 Y) (Lift 𝓥 X))

     d : (Σ Y ꞉ 𝓥 ̇ , X ≃ Y) ≃ (Σ Y ꞉ 𝓥 ̇ , Lift 𝓤 Y ≡ Lift 𝓥 X)
     d = Σ-cong e

     j : is-subsingleton (Σ Y ꞉ 𝓥 ̇ , Lift 𝓤 Y ≡ Lift 𝓥 X)
     j = Lift-is-embedding ua ua' (Lift 𝓥 X)

     s : is-subsingleton (Σ Y ꞉ 𝓥 ̇ , X ≃ Y)
     s = equiv-to-subsingleton d j
```
If you give the type signatures explicitly, then Agda has no problem checking your code.

If Agda had printed a warning as soon as it left a mutual block with unsolved meta-variables, then it might be easier to find the cause of this kind of problem. (See [#2514](https://github.com/agda/agda/issues/2514#issuecomment-324138217).) @martinescardo, do you think this would have helped?

**Comment by martinescardo** [comment]
I see. Certainly it would help a lot if we got a warning rather than an infinitely long wait.  If this is easy to implement, it would be most welcome. Thanks.

**Comment by martinescardo** [comment]
On a side note, it would be helpful to document more precisely what `abstract` (doesn't) do. Sometimes I find myself trying to use `abstract` to speed-up type-checking, but it feels like shooting in the dark.  What is precisely the semantics of abstract?

**Comment by martinescardo** [comment]
OK. So, instead of adding the type signature to `i`, `ii`, and `iii`, I can move down the `abstract` keyword to make only `s` abstract. With Agda 2.6.1, this makes type checking to take 1m3s for this giant file, and  Agda 2.6.2-0eaf439 to take 1min5s, which can be considered to be the same amount of time. This is great.

I wonder if the proposed warning above could help me to improve the performance of the repository `TypeTopology` with Agda 2.6.2 to match the performance I get with 2.6.1. Of course, what I could do is to grep `abstract` and try to inspect manually. I also wonder if you have any hints documented somewhere to identify performance bottlenecks. Thanks again.

**Comment by nad** [comment]
> Sometimes I find myself trying to use `abstract` to speed-up type-checking, but it feels like shooting in the dark.

Perhaps you could try the following workflow:
* Turn on interactive highlighting.
* Whenever any piece of code typechecks slowly (when it is highlighted more than momentarily), find the cause of this, and change the code so that it is typechecked quickly.

If you have trouble finding the cause, feel free to ask. Using `abstract` is one way to make code typecheck faster, but not the only one. Did you see my [talk](http://www.cse.chalmers.se/~nad/publications/danielsson-aim32-talk.txt) at AIM XXXII?

> I wonder if the proposed warning above could help me to improve the performance of the repository `TypeTopology` with Agda 2.6.2 to match the performance I get with 2.6.1.

If your code is currently accepted without any unsolved meta-variables, then I guess this warning would not be of much help to you.

> I also wonder if you have any hints documented somewhere to identify performance bottlenecks.

There is something in the [user manual](https://agda.readthedocs.io/en/latest/tools/performance.html). However, that page does not document my main technique: turn on interactive highlighting, then you can often find problematic parts of the code using visual inspection.

**Comment by martinescardo** [comment]
Thanks. Now `TypeTopology` takes for ever after Tom de Jong added the circle following  Bezem, Buchholtz, Grayson and Shulman. In Agda 2.6.1, this adds 15s. In 2.6.2 it requires a larger heap, and then takes for ever. There seems to be a fundamental change from 2.6.1 to 2.6.2. What is it?

**Comment by nad** [comment]
Now I'm only guessing, but perhaps an implicit argument is solved differently due to some change to Agda's unification machinery, and perhaps this means that Agda works hard to try to establish whether two expressions, that were previously syntactically equal, reduce to the same normal form.

If you want to avoid this particular problem, then you could develop your code using `--no-syntactic-equality`. However, then you might have to make quite a few changes to the code.

It could also be the case that the code typechecks more slowly due to some other change to Agda. Have you tried to find out what the cause of the slowdown is?

**Comment by martinescardo** [comment]
@tomdjong managed to make the circle work in the development version of Agda in reasonable time by a few changes including `abstract`. Still, the time is much slower than in Agda 2.6.1. I tried `--no-syntactic-equality`. This makes Agda 2.6.1 fail, and the development version to go for ever after requiring an increased heap. I did try to find out the cause of the slow down. But there are 74k lines of code (and 56k after comments are removed), and so this is not easy.

**Comment by martinescardo** [comment]
The attached file [times-modules-comparison-sorted.txt](https://github.com/agda/agda/files/6266401/times-modules-comparison-sorted.txt) has a side-by-side comparison of the time taken for each of the 228 modules in `TypeTopology` with Agda 2.6.1 and the development version of Agda (2.6.2-0eaf439). You can see that the development version takes consistently longer in each module, and significantly more in many modules.

**Comment by nad** [comment]
> I tried `--no-syntactic-equality`. This makes Agda 2.6.1 fail, and the development version to go for ever after requiring an increased heap.

If you want to use `--no-syntactic-equality`, then I think you have to drop support for Agda 2.6.1. Furthermore you will have to change the code: the point of `--no-syntactic-equality` is not to make Agda faster, but less brittle. If you manage to make your code typecheck quickly using `--no-syntactic-equality`, then I think it is less likely that you will encounter massive performance regressions.

**Comment by martinescardo** [comment]
It may not be very practical to rewrite 56k lines of code, though...

**Comment by martinescardo** [comment]
And given that all of the 228 modules got slower, I would expect everybody's developments to get slower. Has the Agda standard library been compared for performance with 2.6.1 and 2.6.2?

**Comment by nad** [comment]
I don't think the standard library builds using both versions of Agda.

I tested your code (commit f79683638d8783180994a0543a9a3795959dae44) using Agda 2.6.1 and 2.6.2-0a98fe0, and the slowdown was about 22%, whereas in your case it was about 52%. Did you run anything else while running the tests?

**Comment by martinescardo** [comment]
I've run `git bisect` on the Agda code base, and found that a commit that caused the performance regression in `TypeTopology` is 2f212bf5568a8d408f3b3a8d3cb87a6fa6e6b3a1 ("Add --auto-inline and make it off by default"), addressing issue #4681. 

Before that commit, `TypeTopology` type checks in 4m. At that commit (and for many commits afterwards), `TypeTopology` type checks in 4m30s. 

In the current development version 044fba0, `TypeTopology` type checks in 5m, or in 4m30s with `--auto-inline`. So there is a second culprit between the above commit and the current development version. When I have a chance I will do another bisection to try to find it.  

(Speculation: maybe auto-inline is doing something in TypeTopology because we use iterated Sigmas rather than records to define mathematical structures.)

**Comment by nad** [comment]
> (Speculation: maybe auto-inline is doing something in TypeTopology because we use iterated Sigmas rather than records to define mathematical structures.)

I noticed that you use code of the following form:
```agda
p ∙ q = transport (lhs p ≡_) q p
```
Here, if `p ∙ q` is reduced, but `lhs p` is not inlined, then you get two copies of `p`. I tried to make functions like `lhs`, which just return one of their arguments, inlined, and this on its own seems to have led to a speedup of about 10%. (I made the following functions inlined: in `GeneralNotation`: `type-of`, `-id`, `need_which-is-given-by_`, `have_so_`, `have_so-use_`, `have_and_`, `mapsto`, `Mapsto`; in `Id`: `lhs`, `rhs`; in `LiftingUnivalentPrecategory`: `dom`, `cod`; in `MGS-MLTT`: `domain`, `codomain`, `type-of`, `lhs`, `rhs`; in `Pi`: `id`, `domain`, `codomain`; in `Type-in-Type-False`: `domain`, `codomain`; in `Universes`: `universe-of`.)

**Comment by martinescardo** [comment]
Interesting, thanks. It seems that --auto-inline is doing this:

```
commit 2a3495289d5ee089abc9a7c041c5b05dbc472f37
Author: Ulf Norell <ulfn@chalmers.se>
Date:   Thu Apr 5 11:50:05 2018 +0200

    [ inlining ] auto-inline simple definitions
    
    Auto-inline if all of these:
    - no pattern matching
    - no argument used more than once
    - some arguments not used at all
```

**Comment by martinescardo** [comment]
Strange. The result of the `git bisect` promised above is this:
```
git bisect good
7716754f2ae5501d595821a89c98f3061fafb6ce is the first bad commit
commit 7716754f2ae5501d595821a89c98f3061fafb6ce
Author: Nils Anders Danielsson <nad@cse.gu.se>
Date:   Tue Feb 23 12:29:03 2021 +0100

    [ #4521 ] Added the flag optimise-heavily to Agda.cabal.

 .ghci-8.0                                        |  2 --
 Agda.cabal                                       | 29 ++++++++++++++----------
 CHANGELOG.md                                     | 15 ++++++++++++
 Makefile                                         |  6 +++--
 doc/user-manual/getting-started/installation.rst |  5 ++++
 5 files changed, 41 insertions(+), 16 deletions(-)
```

**Comment by martinescardo** [comment]
Ah. Maybe that's not strange. That commit sets `optimize-heavily` to `False`.

**Comment by martinescardo** [comment]
Fantastic. Now, the current development version 2.6.2-044fba0-dirty (what is this "dirty"?) type checks `TypeTopology` in the same amount of time as the released version 2.6.1 (in my machine this is 4m), *provided* we

1. build agda with `optimise-heavily` set to `True` in `Agda.cabal`, and
2. run `agda` using the flag `--auto-inline`.

We have that

* If we drop both, the time goes up from 4m to 5m27s in my machine. 
* If we drop `--auto-inline` and keep `optimise-heavily`, the time is 4m36s.
* If we keep `--auto-inline` and drop `optimise-heavily`, the time is 4m52s. 

Moreover, for the above to be the case, we had to make some changes in `TypeTopology`:

* Give the types of things defined in abstract blocks. 
* Make (only) one definition `abstract`.
* Add a couple of implicit parameters explicitly.

These were minor changes, but difficult to find (some of them were found and fixed by @tomdjong and @nad). 

It was also difficult to identify the causes of the performance regression, which required two bisections.

So I think this issue is more or less closed. Perhaps something should be added to the documentation.

(Question: how do I add an option such as `--auto-inline` in my .emacs file?)

**Comment by martinescardo** [comment]
I corrected the times in the previous comment and added the missing fourth possible combination.

**Comment by martinescardo** [comment]
(And the actual time in 2.6.1 is 3m52s.)

**Comment by jespercockx** [comment]
@martinescardo You can set default flags to use in Emacs by pressing `M-x customize-group RET agda2 RET` and adding the flags you want to the "Agda2 Program Args" field. Starting from Agda 2.6.2, you can also add default flags directly to the `.agda-lib` file of your project (under the new `flags:` tag).

**Comment by martinescardo** [comment]
More timing information, for the record, with a slower machine. 

```
Core i5 laptop (2015), ghc 8.6.5, ubuntu 20.04.02

Agda version 2.6.2-044fba0-dirty

100% 10m31s without --auto-inline and without Haskell optimizations
 87%  9m 8s with    --auto-inline and without Haskell optimizations
 82%  8m36s without --auto-inline and with    Haskell optimizations
 73%  7m40s with    --auto-inline and with    Haskell optimizations

Agda 2.6.1

 71% 7m31s
```

**Comment by nad** [comment]
> So I think this issue is more or less closed. Perhaps something should be added to the documentation.

The changes related to `optimise-heavily` and `--auto-inline` are already documented, but we could stress the risk for slowdowns.

> I tested your code (commit f79683638d8783180994a0543a9a3795959dae44) using Agda 2.6.1 and 2.6.2-0a98fe0, and the slowdown was about 22%, whereas in your case it was about 52%.

Presumably this was because I built Agda using `optimise-heavily`.

**Comment by martinescardo** [comment]
> Presumably this was because I built Agda using `optimise-heavily`.

Yes, this is what I suspected.

**Comment by martinescardo** [comment]
@nad I noticed that you added some information in a recent commit about optimization flags and --auto-inline. Perhaps it could also be added that abstract definitions should include signatures and that if this is not done then type checking can take an extremely long time (infinite in practice). I could add this myself, but I am not sure how to phrase it so that it is accurate.

**Comment by nad** [comment]
I think we should reject abstract definitions without type signatures, like you suggested elsewhere (#418).
