### ISSUE TITLE
Order of filling holes changes whether Agda accepts a program (via Give)

### ISSUE THREAD

**Issue by googleson78** [agda/agda#5281]
I have no idea how to search for this, so sorry if this is a dupe.

For the following program:
```agda
module agdabug where

data _==_ {A : Set} : A -> A -> Set where
  refl : {x : A} -> x == x

{-# BUILTIN EQUALITY _==_ #-}

data Nat : Set where
  zero : Nat
  suc : Nat -> Nat

{-# BUILTIN NATURAL Nat #-}

data Vec (A : Set) : Nat -> Set where
  [] : Vec A zero
  _,-_ : {n : Nat} -> A -> Vec A n -> Vec A (suc n)

data _<=_ : Nat -> Nat -> Set where
  ozero : {n : Nat} -> 0 <= n
  osuc : {n m : Nat} -> n <= m -> suc n <= suc m

infix 9 _<=_

vTake : {A : Set} {m : Nat} -> (n : Nat) -> n <= m -> Vec A m -> Vec A n
vTake _ ozero _ = []
vTake _ (osuc n<=m) (x ,- xs) = x ,- vTake _ n<=m xs

<=-refl : (n : Nat) -> n <= n
<=-refl zero = ozero
<=-refl (suc n) = {!osuc (<=-refl n)!}

vTake-id : {A : Set} (n : Nat) (v : Vec A n) -> vTake n (<=-refl n) v == v
vTake-id zero [] = refl
vTake-id (suc n) (x ,- xs) rewrite vTake-id n xs = refl
```

I cannot fill (via Give) the hole. However, if I first delete the `refl` in the second case of `vTake-id`, then fill the hole, and then reintroduce the `refl`, everything works fine. (I can also manually delete the hole and input the correct program, and Agda will accept it.)

**Comment by UlfNorell** [comment]
The problem is that without filling the hole in `<=-refl`, the rewrite doesn't fire properly (since the call to `vTake` does not reduce). That means that the constraint you get on the `refl` in the last clause (notice how it's yellow) is not the one you want, and it fails once you fill in the hole.

I'm not sure there's anything that we can do about this. It's not feasible to recheck the entire rest of the file every time you fill a hole, but in order to avoid this problem I think we would have to. Filling a hole changes reduction behaviour, which in turn can change the behaviour of `with` and `rewrite`, leading to different constraints.

To work around the problem, the clue that something is not right is the yellow on the `refl`.
