### ISSUE TITLE
Warn about abstract definitions without type signatures

### ISSUE THREAD

**Issue by nad** [agda/agda#5314]
Agda no longer infers types of abstract definitions, and this can lead to [problems in existing code](https://github.com/agda/agda/issues/5279#issuecomment-813984791). In order to make it easier to discover the cause of such problems I think that Agda should raise a warning or error for each abstract definition without a type signature. (This idea is based on one [due to](https://github.com/agda/agda/issues/418#issuecomment-816588417) @martinescardo.)

I don't really care if Agda uses a warning or an error to notify users, as long as they get the notification before Agda starts typechecking the body of the definition.

**Comment by UlfNorell** [comment]
Is the existing warning not working?

https://github.com/agda/agda/blob/3e079614f2b4810ff5920ae69a389da91c855217/src/full/Agda/TypeChecking/Rules/Def.hs#L103-L104

**Comment by UlfNorell** [comment]
@martinescardo wrote in https://github.com/agda/agda/issues/418#issuecomment-817657908
> The manual says that we should give type signatures of abstract definitions. Then why are we allowed not to give them, with the penality being an infinitely long computation rather than an outright error?

Typically the penalty isn't infinite type checking times. You could make a similar argument for throwing an error for frozen unsolved metas rather than continuing type checking, since we know they can never be solved, and type checking with lots of unsolved metas can be expensive. The disadvantage of hard failures is that you lose all interactions with the type checker (in the case it *doesn't* take forever to finish).

**Comment by martinescardo** [comment]
> Is the existing warning not working?
> 
> https://github.com/agda/agda/blob/3e079614f2b4810ff5920ae69a389da91c855217/src/full/Agda/TypeChecking/Rules/Def.hs#L103-L104

It is not working in the example @nad linked above.

**Comment by nad** [comment]
> You could make a similar argument for throwing an error for frozen unsolved metas rather than continuing type checking, since we know they can never be solved, and type checking with lots of unsolved metas can be expensive.

#5306.

> The disadvantage of hard failures is that you lose all interactions with the type checker (in the case it _doesn't_ take forever to finish).

Warnings don't have that disadvantage. However, I don't know if they are reported soon enough. (If they are not, then that could perhaps be changed.)

**Comment by UlfNorell** [comment]
This sounds like a general issue with warnings not being reported right away, rather than a problem with abstract definitions. Can this be folded into #5306?

**Comment by nad** [comment]
I don't know if early reporting of unsolved meta-variables would have helped @martinescardo identify the cause of the problem mentioned in the OP. Given that the semantics of `abstract` has changed I think it makes sense to give an explicit warning to users.

**Comment by UlfNorell** [comment]
There already is an explicit warning (see source code link above).

If it doesn't show up soon enough that (as I said) sounds like a more general problem that could perhaps be taken care of in #5306 (expanding it's scope to warnings in general, not just unsolved metas).

**Comment by nad** [comment]
OK, let's do that.

However, I suggest that we reformulate the warning. Instead of writing "Cannot infer the type of abstract definition i" we could write something like "Types of abstract definitions are not inferred, in particular not the type of i", to emphasise that this problem is not restricted to this particular definition.

**Comment by martinescardo** [comment]
The following gives the error `Failed to solve the following constraints` and then a warning `Cannot infer the type of abstract definition three`
```
f : ℕ → ℕ
f n = n

abstract
 three = f 3

n : ℕ
n = three
```
I see the following issues with this: 
1. `abstract three = f 3` should never be considered legal code. This is because (1a) the manual already says so, but also because (1b) whenever we use `three` we are guaranteed to get an error.
2. Neither the error message nor the warning above indicate what is going on. I wouldn't think of adding a type signature to `three`, given that all typing information is in the term. I would just be rather puzzled. Particularly because this works in 2.6.1. The immediate reaction is that this would be a bug, where actually now it is a design decision.  Because it is a design decision, it should give an error not a warning, and at the point of definition of `three` rather than when `three` is used.

**Comment by UlfNorell** [comment]
The second point would be addressed by a rewording of the warning. Would you be happy with @nad's proposed change, or do you have other suggestions?

Regarding errors vs warnings, the current policy is to avoid fatal errors in favour of non-fatal errors or warnings when possible, in order to allow the user to interact with the type checker even when things go wrong. If the warnings were issued promptly I don't see any advantage in hard-failing instead.

**Comment by gallais** [comment]
That being said we could have `-wFatal` as a step up from `-wError` so
that the process not only exits with an error code if at least one warning
is encountered but also stops as early as possible.

**Comment by martinescardo** [comment]
I don't know. It is up to you. I would have considered illegal code to be an error not a warning.

**Comment by UlfNorell** [comment]
Fixed by the commit above (I put the wrong issue number in the commit message). The warning now says
```
Missing type signature for abstract definition x.
Types of abstract definitions are never inferred since this would
leak information that should be abstract.
```

**Comment by martinescardo** [comment]
Thanks. In my case this warning wouldn't have been useful. The file linked by @nad at the very top of this issue type checks in 1min in Agda 2.6.1. With your fix above, I never get to see the warning. The omission of the type signature for an abstract definition causes Agda 2.6.2 to take more than 10min (I don't know how long and I've just aborted my attempt). I still would like to see a use case where it is better to accept the faulty abstract definition without a type signature and carry on rather than give an error. Luckily I know now what causes the infinite computation. I guess many people, like me, are going to see their code taking infinitely long to type check, before they see any warning, when they try to migrate to 2.6.2.

**Comment by nad** [comment]
Issue #5306 is about reporting warnings more eagerly.
