### ISSUE TITLE
Open goal inside record causes internal error (eta-contraction)

### ISSUE THREAD

**Issue by mr-ohman** [agda/agda#5478]
The following code produces an internal error:
```agda
open import Agda.Builtin.Sigma

record R1 (A : Set) : Set where

instance
  prodR1 : {A : Set} {B : A → Set} → ⦃ {a : A} → R1 (B a) ⦄ → R1 (Σ A B)
  prodR1 = record {}

record R2 (A : Set) ⦃ aR1 : R1 A ⦄ : Set₁ where
  field
    f : A → Set
open R2 ⦃...⦄ public

record R3 (A : Set) (B : A → Set) : Set₁ where
  instance
    bR1 : {a : A} → R1 (B a)
    bR1 = {!!} -- record {}
  field
    ⦃ r2 ⦄ : R2 (Σ A B)
    fab : ∀ {a} {b : B a} → f (a , b)
```
```
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/TypeChecking/Records.hs:734:11 in Agda-2.6.3-D2V0PkTCBiXC7IJuWrP7mz:Agda.TypeChecking.Records
```
If the goal of `bR1` is replaced with `record {}` then the code type checks. This error occurred with Agda versions 2.6.2 and master branch at commit 23e07c0389182121332ca89b92390497aa95504e.

**Comment by andreasabel** [comment]
The error already occurs with
```agda
record ⊤ : Set where

record R : Set₁ where
  foo : ⊤
  foo = ?  -- works with _ instead of ?
  field X : Set
```

**Comment by andreasabel** [comment]
Bisection says: 56c804c51a22de785c6465a66564f4b363e99118 is the first bad commit.
```
Date:   Fri Jul 8 20:09:47 2016 +0100

    Add warnings machinery
```
(Patch comprises _14 changed files with 380 additions and 97 deletions_ - sigh...)
Ping @fredrikNordvallForsberg @gallais .

UPDATE: This patch isn't the problem, maybe it exposed the problem, or it is a false alarm.

**Comment by andreasabel** [comment]
It seems like the crashing eta-reduction happens during this `instantiateFull`: https://github.com/agda/agda/blob/8e4a198399a0455ff121a224021de043ea6313d3/src/full/Agda/TypeChecking/Rules/Def.hs#L342
It is called on `foo r = _1 r` and I supposed `_1 := record{}` so we end up with the ill-formed `record{} r`.
I suppose when the meta is created during computing the type of the constructor (hello #434) there is no record variable `r` in the context, but when we check the declaration `foo` there is.  This would explain why the problem does not surface with `_` instead of `?`.  With an interaction meta, we are trying to not create two metas (one an in each path), and instead reuse the meta created on the first run-through, which happens to be created in a context without record variable `r`.

**Comment by andreasabel** [comment]
I suppose the heuristics here:
https://github.com/agda/agda/blob/8e4a198399a0455ff121a224021de043ea6313d3/src/full/Agda/TypeChecking/MetaVars.hs#L365-L375
blows up in this case.  We need to use a meta-variable created in one context (without the `r` variable) in an extended extension (with the `r` variable)?  Is this something we can do with checkpoints @jespercockx @UlfNorell ?

**Comment by andreasabel** [comment]
While #5483 fixed my shrunk MWE, the OP still produces an internal error (but a new one):
```agda
record R3 (A : Set) (B : A → Set) : Set₁ where
  instance
    bR1 : {a : A} → R1 (B a)
    bR1 = {!!} 
```
```
expecting meta-creation context (with fields instead of record var)
  [B, A]
to be an expansion of the meta-reuse context (with record var)
  [a, r, B, A]
  glen  = 2
  g1len = 1
  g0len = 2
  frontMatch = False
  rearMatch  = True
```
It seems that on the first pass, Agda did not insert the hidden binding `{a}`, but on the second pass.
