### ISSUE TITLE
Parameter order breaks eta reduction with Prop

### ISSUE THREAD

**Issue by isti115** [agda/agda#5488]
While writing a formalization I have encountered a weird issue with not being able to eta reduce a definition.
I have managed to iteratively extract the critical part from the huge context and I arrived at the following minimal example:

As you can see, eta reduction does not work with my original list of parameters, but I have discovered that the reduced variation is accepted if I reorder them. Is this a bug, or if not, can someone please give me an insight on why it might behave this way?

```agda
{-# OPTIONS --prop #-}

-- Lifting from Prop to Set
record Lift (P : Prop) : Set where
  constructor lift
  field unlift : P
open Lift public


{- Original parameter order -}

foo : {Γ : Set} → Γ → {A : Set} → A → A
foo σ t = t

bar : {Γ : Set} → Γ → {A : Prop} → Lift A → Lift A
bar σ t = foo σ t
-- bar = foo -- This does NOT work


{- Parameter order reversed -}

foo' : {Γ : Set} → {A : Set} → Γ → A → A
foo' σ t = t

bar' : {Γ : Set} → {A : Prop} → Γ → Lift A → Lift A
-- bar' σ t = foo' σ t
bar' = foo' -- This works
```

**Comment by jespercockx** [comment]
Eta-reduction here is actually not valid because of the implicit arguments that are inserted. Making them explicit, your definition of `bar` is as follows:
```agda
bar : {Γ : Set} → Γ → {A : Prop} → Lift A → Lift A
bar {Γ} σ {A} t = foo {Γ} σ {Lift A} t
```
while the fully explicit definition of `bar'` is as follows:
```agda
bar' : {Γ : Set} → {A : Prop} → Γ → Lift A → Lift A
bar' {Γ} {A} = foo' {Γ} {Lift A} -- This works
```
In other words, by changing the position of the implicit arguments Agda got the chance to insert the right implicit argument to `foo'`, while this was not possible in the original definition of `bar`.

I hope this answers the question, please reopen this issue if there's still a problem.

**Comment by isti115** [comment]
Oh, I see, so if I understand it correctly, the issue is esentially due to the fact that partial application is only possible for arguments in the beginning of the parameter list and cannot be done by name. (Which as a wild guess might be a limitation due to dependent typing, since the type of latter parameters sometimes aren't even fixed until all the former ones are known?)
Thank you very much for the clarification!
