### ISSUE TITLE
`make install-bin` should always add a version suffix

### ISSUE THREAD

**Issue by L-TChen** [agda/agda#5500]
First, it seems that `make install-bin` is used mainly for development purposes. Second, the development version of Agda should not replace the stable version. So, very often some people use the `cabal` option `--program-suffix` to have a different version of Agda. Unfortunately `stack` does not support this option and the developer of `stack` was not keen to have this option (see https://github.com/commercialhaskell/stack/issues/4621).

So, to make life easier, I propose that `make install-bin` should always add a version suffix (or even with git commit hash) to the executables installed on the path (`~/.local/bin` for stack and `~/.cabal/bin` for cabal by default). Does it sound reasonable?

**Comment by andreasabel** [comment]
>  `make install-bin` should always add a version suffix 

I am not opposed to that, although, as a developer, I will always use the latest version of Agda that I built, and I am fine with it being simply `agda`.

> (or even with git commit hash)

This is a bit problematic because many versions will pile up in `.cabal/` and take my precious hard drive space.  This should come with an automatic solution to garbage-collect old development versions of agda.

**Comment by L-TChen** [comment]
Thanks. I think I will go with adding a version suffix only.

The stable version is always the version I used to communicate with my collaborators, students, or colleagues; the experimental version is of course for experiments. ;-)

**Comment by andreasabel** [comment]
@L-TChen you overshot, imo, by also modifying the developer quick-and-dirty targets `quicker-install-bin` etc.
Can you please motivate why you also want to differentiate these throw-away products by version?  They were not in conflict with executable name `agda`.  I think this differentiation causes more friction than gain.

Also since `quicker-install-bin` does not produce `agda-quicker` anymore, the heuristics at https://github.com/agda/agda/blob/c9c20bf3683f9eaf9987b80257369be2a45d452b/Setup.hs#L77-L80 is now broken, and it now isn't much quicker than `fast-install-bin`.

**Comment by L-TChen** [comment]
Ooops, I changed them for consistency. I wasn't aware that the suffix `-quicker` changes the behaviour of Agda, too. I will change this part back.

**Comment by andreasabel** [comment]
Thanks for changing this back in #5511.
