### ISSUE TITLE
Panic when showing module contents with pattern synonym

### ISSUE THREAD

**Issue by laMudri** [agda/agda#5551]
Pressing `C-c C-o` (`agda2-module-contents-maybe-toplevel`) on the hole produces a panic. `Agda version 2.6.2`

```agda
module Scratch where

module Foo where
  pattern pat x = x

foo : Set
foo = {!Foo!}
```

```
/sharedhome/home/james/Documents/agda/Scratch.agda:7,7-14
Panic: Unbound name: Scratch.Foo.pat[0,2,6]@ModuleNameHash
10507650244568858286
when retrieving the contents of a module
```

**Comment by andreasabel** [comment]
@laMudri : I dimly remember there was a code sprint on pattern synonyms at a recent Agda Meeting.  Part of this was to make pattern synonyms proper declarations.  This would likely also fix the OP.  Atm, pattern synonyms live in their own structure rather than in the signature with all other declarations.
