### ISSUE TITLE
Failing to solve a trivial empty clause when pattern-matching in extended lambda

### ISSUE THREAD

**Issue by omelkonian** [agda/agda#5606]
```agda
open import Function
open import Data.Fin
open import Data.List
open import Data.Bool
open import Data.Product
open import Relation.Binary.PropositionalEquality

p : ∀ {xs : List Bool} {i : Fin (length xs)} → lookup xs i ≡ true → xs ≢ (false ∷ [])
-- p {i = zero} () refl
p {i = i} x≡ xs≡ = case (xs≡ , i ,′ x≡) of λ where (refl , zero , ())
```
The commented clause works, but to my surprise not the second one:
```
Failed to solve the following constraints:
  Is empty: lookup (false ∷ []) i ≡ true (stuck)
```

This is particularly annoying when `i` is a module parameter and one cannot use `with` to pattern match on it:
```agda
module _ {xs : List Bool} {i : Fin (length xs)} where
  p′ : lookup xs i ≡ true → xs ≢ (false ∷ [])
  p′ x≡ xs≡ = case (xs≡ , i ,′ x≡) of λ where (refl , zero , ())
```

**Comment by jespercockx** [comment]
Well, the proof that `true` is not in the list `false :: []` requires some kind of case analysis, so I am not sure if it is reasonable to expect Agda to solve this automatically. It feels to me that any attempt at doing so would very quickly lead to either typechecking looping in some cases or there being an arbitrary cutoff in how deep Agda does the case analysis before it gives up, and neither option seems especially appealing.

By the way, there is a workaround to pattern match on a module parameter: instead of matching on `i` directly, you can do a `case` or `with` on `[ i ]`, where `[_]` is the constructor of the `Is` datatype:
```agda
data Is {A : Set} : A -> Set where [_] : (x : A) -> Is x
```

**Comment by omelkonian** [comment]
>Well, the proof that true is not in the list false :: [] requires some kind of case analysis, so I am not sure if it is reasonable to expect Agda to solve this automatically.

But Agda **does** solve it in the first clause, which I expected to be equivalent-ish.

>By the way, there is a workaround ...

Nice workaround :)

**Comment by omelkonian** [comment]
Let me modify the initial example to make this a bit more clear:
```agda
p : ∀ {xs : List Bool}
  → Σ[ i ∈ Index xs ]
      (L.lookup xs i ≡ true) × (xs ≡ (false ∷ []))
  → ⊥
p (0F , () , refl)                                                 -- 1) works
p = λ where (0F , () , refl)                                       -- 2) works
p x = case x of λ where (0F , () , refl)                           -- 3) works
p (i , x≡ , xs≡) = case (i , x≡ , xs≡) of λ where (0F , () , refl) -- 4) error
```
Isn't this behaviour unintuitive?

**Comment by gallais** [comment]
It's not too surprising that when you're unwrapping/rewrapping you may be rewrapping
at a different type. I'm actually surprised the last line does not fail already with
an unsolved meta on the `case (i , x≡ , xs≡) of λ p ->` part because it's not clear
to me what type Agda should infer e.g. `Index xs × (L.lookup xs i ≡ true) × (xs ≡ (false ∷ []))`
would be a valid solution.

You should add a type annotation making sure you are rebuilding a dependent pair
if you want the pattern on `i` to inform the value of the type `L.lookup xs i ≡ true`.

**Comment by omelkonian** [comment]
>You should add a type annotation making sure you are rebuilding a dependent pair
>if you want the pattern on i to inform the value of the type L.lookup xs i ≡ true.

Nice, now this works!
```agda
p {xs} (i , x≡ , xs≡) = case (Σ[ i ∈ Index xs ] (L.lookup xs i ≡ true) × (xs ≡ (false ∷ []))) ∋ (i , x≡ , xs≡) of λ where (0F , () , refl)
```

So, TIL that you need dependent pairs to inform other values, whereas I previously thought non-dependent ones sufficed.
