### ISSUE TITLE
is the lexer / alex remarks about how unicode support is done out of date?

### ISSUE THREAD

**Issue by cartazio** [agda/agda#5729]
i was looking at https://github.com/agda/agda/blob/a0b3eea0c19c47ffbe2be525316311f5795d760d/src/full/Agda/Syntax/Parser/Lexer.x#L40-L42

and it mentions a "foolAlex" function, which i cant seem to find in the code base? is unicode support in place now?

**Comment by nad** [comment]
I removed `foolAlex` back in 2018 (c8995d54295b68cf73bd3f99de5b181c35c64212). The commit comment:

> [ refactoring ] Removed foolAlex.
>
> Moved the hack into alexGetByte.

Feel free to update the outdated comment.

[Currently the lexer uses `String`s.](https://github.com/agda/agda/blob/a0b3eea0c19c47ffbe2be525316311f5795d760d/src/full/Agda/Syntax/Parser/Alex.hs#L29-L35) Perhaps it would make sense to switch to some kind of bytestring instead, and remove the hack.

**Comment by andreasabel** [comment]
@nad wrote:
> Feel free to update the outdated comment.

I'd say fixing the comment is part of the task when changing the code.

**Comment by nad** [comment]
I guess I wasn't aware of this comment when I made the change, because the comment was in a different file. Do you have some reasonable workflow that ensures that all comments are always up to date? In this case I removed a definition, so I could have searched for its name in the code base. In general I guess one could try to attach a test case to each comment that refers to a non-adjacent piece of code, with the intention that the test case should fail if the comment becomes out of date, but the main effect of that might be less documentation.

**Comment by andreasabel** [comment]
Thanks for fixing the comment.  
I suppose it happens that we fail to update comments, but if someone notices, it is appropriate to deliver the update then.
I am afraid I do not have a recipe to keep comments up-to-date.  A careful proof-reading of the commit I am preparing often helps me to spot such issues, though.
