### ISSUE TITLE
Lambda with irrefutable pattern is not rejected when used on Path

### ISSUE THREAD

**Issue by szumixie** [agda/agda#5856]
The following code is accepted by Agda:
```agda
{-# OPTIONS --cubical #-}

open import Agda.Builtin.Cubical.Path

postulate
  A E : Set
  a : A

data C : Set where
  c : E → C

p : a ≡ a
p = λ (c e) → a
```

While the following results in `Panic: unbound variable`:
```agda
{-# OPTIONS --cubical #-}

open import Agda.Builtin.Cubical.Path

postulate
  A E : Set
  a : A

data C : Set where
  c : E → C

p : a ≡ a
p = λ (c e) → e
```

**Comment by andreasabel** [comment]
These examples fail on 2.6.0, e.g.
```
(e : _8) → A !=< A of type piSort _7 (λ _ → Set)
when checking that the expression λ e → a has type A
```
This is probably because the irrefutable pattern lambda wasn't implemented yet, and Agda 2.6.0 interpreted `\ (c e) -> _` as `\ c e -> _`.

When you expand the sugar manually to `λ i → let (c e) = i in _`, then you get the expected error:
```
Cannot split on argument of non-datatype Agda.Primitive.Cubical.I
when checking that the pattern c e has type Agda.Primitive.Cubical.I
```
So, I'd rather blame a hackish implementation of irrefutable pattern lambdas than Cubical Agda.

**Comment by andreasabel** [comment]
Links:
- PR https://github.com/agda/agda/pull/3884
- commit https://github.com/agda/agda/commit/2fbef7d4bb4b2060aa10d0a14f0c42e53aa43cb2

**Comment by andreasabel** [comment]
The culprit seems to be https://github.com/agda/agda/commit/2fbef7d4bb4b2060aa10d0a14f0c42e53aa43cb2#r69718062 :
https://github.com/agda/agda/blob/c5b4e202bf59f4f1fcb9cd73303a752385502a48/src/full/Agda/TypeChecking/Rules/Term.hs#L423-L425
The pattern contained in `x'` is just discarded when checking a path-lambda.

**Comment by andreasabel** [comment]
With #5857, we now error out if a path-lambda has a pattern.
