### ISSUE TITLE
quoting/unquoting changing unexpected subterms

### ISSUE THREAD

**Issue by WhatisRT** [agda/agda#5982]
Consider the following code:

``` agda
{-# OPTIONS -v test:10 #-}

module ArgTurningIntoUnknown where

open import Data.List
open import Data.Unit
open import Level
open import Reflection

variable l : Level

record Test (A : Set l) : Set l where
  field a : A

f : (A : Set) ⦃ _ : Test A ⦄ → A
f _ ⦃ t ⦄ = Test.a t

abstract
  g : {A : Set l} → A → A
  g x = x

pattern def₁ n a = def n (vArg a ∷ [])

test : TC ⊤
test = let t = def₁ (quote g) (def₁ (quote f) (var 1 [])) in
  reduce t >>= λ t' → debugPrint "test" 10 [ termErr t' ]

module _ {A : Set} ⦃ _ : Test A ⦄ where
  unquoteDecl = test
```

Loading this will print `g (f A)` into the debug buffer. However, if we remove the level parameter from `Test`, turning its type into `Set → Set`, it will print `g (f _)` instead. The same is true if we make `g` a postulate instead.

What is going on here? I don't think `reduce` should ever turn an argument that isn't `unknown` into an `unknown`.

**Comment by andreasabel** [comment]
Thanks for reporting.

> I don't think `reduce` should ever turn an argument that isn't `unknown` into an `unknown`.

Could you add more evidence for your claim?  From the bug report, it does not become clear that
- `reduce` is to blame
- the argument is actually an `unknown` (Agda also prints not-in-scope things as `_`).

**Comment by jespercockx** [comment]
Also note that `reduce` does not do just reduction: it will first unquote the term, then run it through the typechecker, *then* reduce it, and finally quote the result again. Currently, this is how all primitive `TC` operations on terms work. So perhaps the typechecker is to blame instead of the evaluator.

**Comment by WhatisRT** [comment]
It seems that this is indeed not the fault of `reduce`. I changed `test` to this:
``` agda
test : TC ⊤
test = let t = def₁ (quote f) (var 1 []) in do
  T ← unquoteTC {A = Set} (var 1 [])
  t' ← unquoteTC {A = T} t >>= quoteTC
  debugPrint "test" 10 [ strErr (showTerm t') ]
```
This shows that `f` is applied to a visible `unknown` and an instance `var 0` without the level on `Test`, and the only difference with the level on `Test` is that the `unknown` is a `var 1`, the terms are identical otherwise. Removing the line that unquotes and quotes t prints exactly the term that is bound from the let-binding. This example also doesn't require `g` to block reduction anymore.

So it seems that this probably happens with all `TC` primitives that work with terms. I also tried `checkType`, which has the same behaviour.

I could imagine that a fix for this might be to throw away the result of typechecking and work on the terms supplied by the user, potentially with a flag that controls this behaviour. I don't know whether that'd break any assumptions on the structure of terms that functions make though.

**Comment by jespercockx** [comment]
The reason why the argument to `f` is replaced by `unknown` is because Agda detects `f` to be a projection-like function, which means it will internally erase the first argument. You have two options to work around it:

- You can turn off the optimization by using the `--no-projection-like` flag. This will give you the term `g (f A)` as expected
- You can wrap the whole `test` macro in a call to `withReconstructed` from `Agda.Builtin.Reflection`. This will instead give you the (more reduced) term `g (Test.a _)` where the `_` is not unknown but `var 0 []` (which happens to be named `_`). 

For the reason why `f` gets reduced in the second case but not in the first, I am not 100% sure but my guess is that Agda tends to replace projection-like functions by their "original" form, which in the case of `f` is `Test.a`.
