### ISSUE TITLE
Non-linear matching is too eager to give up

### ISSUE THREAD

**Issue by plt-amy** [agda/agda#6027]
Honestly I relate to the matcher here. Reported and minimized by @FrozenWinters; Many thanks!

```agda
{-# OPTIONS --rewriting -v rewriting.rewrite:50 --show-implicit -v rewriting.match:60 #-}

module CtxTest where

open import Agda.Primitive
open import Agda.Builtin.Nat
open import Agda.Builtin.Equality

{-# BUILTIN REWRITE _≡_ #-}

postulate
  Foo : Nat → Set
  _▸_ : {n m : Nat} → Foo n → Foo m → Foo (m + n)
  π : {n : Nat} → Foo (suc n) → Foo n
  π-▸ : {n m : Nat} (Γ : Foo n) (Δ : Foo (suc m)) →
    π (Γ ▸ Δ) ≡ Γ ▸ π Δ

{-# REWRITE π-▸ #-}

postulate
  Γ : Foo 2
  Δ : Foo 2

eg : Foo 3
eg = π (Γ ▸ Δ)

_ = {! eg !}
```

When normalizing `eq`, we match these telescopes/eliminations against each other, which fails because `m + n` isn't `3`. But imagine that we postponed this matching and kept going, looking at the rest of the eliminations (justified because all of the variables appear _again_ in the rest of the eliminations).

```
(m + n) (_▸_ n (suc m) Γ Δ)
   3    (_▸_ 2    2    Γ Δ)
```

We'd figure out `n = 2`, `suc m = suc 1` from matching the latter two terms, and after these instantiations, we could go back and retry the postponed problem `(m + n) =? 3`, which would succeed (because `(m + n)[n/2, m/1]` is indeed `3`).

**Comment by mikeshulman** [comment]
I encountered a very similar issue recently, and my conclusion was that as annoying as it sometimes is, this is what we should expect.  The LHS of a rewrite rule is a *pattern* to be matched against, which means that all non-pattern-variables appearing in it must appear *literally* in a term that it gets matched against.  This includes even things that are "volatile", i.e. have their own reduction rules like defined functions and postulates with rewrites.  Matching doesn't allow reduction to happen in the pattern.

In a way it feels to me like a version of "green slime" -- it never works very well to try to match against a volatile function, since in a concrete application that volatile function may have gotten reduced and hence no longer match.  The workaround I found is to incorporate an equality, just as you can do to avoid green slime in indices of datatypes:
```agda
suc-inj : {m n : Nat} → suc m ≡ suc n → m ≡ n
suc-inj refl = refl

postulate
  Foo : Nat → Set
  ▸ : {n m : Nat} → Foo n → Foo m → {m+n : Nat} → (m + n ≡ m+n) → Foo m+n
  π : {n : Nat} → Foo (suc n) → Foo n
  π-▸ : {n m : Nat} (Γ : Foo n) (Δ : Foo (suc m)) {m+n : Nat} (e : suc (m + n) ≡ suc m+n) →
    π (▸ Γ Δ e) ≡ ▸ Γ (π Δ) (suc-inj e)

{-# REWRITE π-▸ #-}

postulate
  Γ : Foo 2
  Δ : Foo 2

eg : Foo 3
eg = π (▸ Γ Δ refl)

_ = {! eg !}
```
Now `eg` reduces as expected to `▸ Γ (π Δ) refl`.

**Comment by jespercockx** [comment]
Well, there is also a confluence issue here: `--confluence-check` reports the following two critical pairs:
```
Global confluence check failed: π {zero + n} (_▸_ {n} {1} Γ Δ) can
be rewritten to either _▸_ {n} {zero} Γ (π {zero} Δ) or
π {n} (_▸_ {n} {1} Γ Δ).
[...]
Global confluence check failed:
π {suc n + n₁} (_▸_ {n₁} {suc (suc n)} Γ Δ) can be rewritten to
either _▸_ {n₁} {suc n} Γ (π {suc n} Δ) or
π {suc (n + n₁)} (_▸_ {n₁} {suc (suc n)} Γ Δ).
```
so I don't think it is reasonable to expect Agda to be able to handle this case.

**Comment by mikeshulman** [comment]
Yes, that makes sense!  My workaround appears to pass the confluence check.

**Comment by plt-amy** [comment]
I'm closing this issue, rather than leaving it in the icebox, since Mike's point about not performing reduction _in patterns_ is very sensible, even in hypothetical cases without confluence problems.
