### ISSUE TITLE
Don't recolor all the labels

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#6070]
@plt-amy : Please be conservative in the label colors.  The colors of at least the old labels have been fitted for aethestics.

E.g. these new different reds are dissonant:
<img width="355" alt="Screenshot 2022-09-01 at 00 29 08" src="https://user-images.githubusercontent.com/1155218/187796492-a339766f-6740-4cd6-8162-b27f56843c62.png">

**Comment by andreasabel** [comment]
@plt-amy : You asked in our meeting whether you could add descriptions to the labels.  That's not a mandate to single-handedly rework the label system.  Please coordinate changes with me.

**Comment by plt-amy** [comment]
I understand. Apologies, I got carried off.. won't happen again. But now that the call-out has been received, can we repurpose this issue to discuss the tagging system? I'm kinda embarrassed about it...

Of our tags (counted on my phone, so numbers are approximate)

1. Well over a third have no open issues/PRs; Of these, I think another third have _never_ had open issues (but this is an impression from randomly clicking around.. did not count them)

2. Colours are inconsistent (and yes, some of this is my fault.. again, sorry): Green means both "help wanted" (also "PRs welcome"), 2ltt, guarded cubical, upstream issues, workaround exists; Basically the same shade of salmon is used for branches ("master", "maint-2.4") and `parameter-refinement`

3. There's both "status: work-in-progress" and "do not merge"; The other status tags are essentially unused ("blocked by issue" is the most popular; abandoned, already fixed, being-reviewed, changes requested and working as intended all have no open issues ATM; some of these have no closed issues, either)

**Comment by nad** [comment]
I suspect that some of the tags are default GitHub tags that we never used.

**Comment by andreasabel** [comment]
Red color is to alert, I think we are rather consistent with that.
Dark green is to either green light for contribution (`help wanted`, `PR welcome`).  Light green is for things that are "fine", e.g. already fixed, or upstream issues, or existing workarounds.
Yellow is for tasks like refactoring that are not addressing bugs directly.
Grey (code #EDEDED) is for semantic tags, identifying the component/concept of Agda that is affected.

The rest might not be so principled.  Andres @asr used to enforce a strong discipline that all semantic tags are grey, but people have deviated from that to make recent or notorious components stand out more prominently (eg. `erasure`, `parameter-refinement`, `open-public`).  I my opinion, if we want to normalize this, these can all become grey eventually.

Tags that have neither closed nor open issues nor PRs are of course obsolete.

Some status tags _only_ apply to closed issues/PRs: `abandoned`, `already-fixed`, `working-as-intended`.
`changes requested` could be given up in favor the github review mechanism. 

> There's both "status: work-in-progress" and "do not merge"

These can be unified if need be, but should have strong color to prevent accidential merging.  I like the current brown.

**Comment by plt-amy** [comment]
> but people have deviated from that to make recent or notorious components stand out more prominently

I believe this makes sense.. and it also makes some sense to have each component be a different colour, but ideally these wouldn't overlap with the "canonical" meanings: 2LTT green is almost the same as the "green light" green; guarded-cubical green is almost the same as the "fixed" green; `piSort` cyan/`devx` cyan; `singleton-types` green looks like the `priority: low` green.

Would it make sense to have a "major component" colour, e.g. lilac (random example, chosen because I'm pretty sure it's not used already), for tags like `cubical` `without-K` `conversion` `pattern matching` (etc.), and use `#EDEDED` for all other semantic tags?

Should "refactor yellow" also apply to e.g. `github-workflows`, `test-suite`, `not-in-changelog`?

I tried to separate UX improvements from the implementation of elaboration using the `ux` prefix. Of course it's hard to draw a hard line between these. Should I roll back the `ux` prefix? (should we have a different colour for the stuff I prefixed `ux`, e.g. `emacs`?)

---

Another thing to consider would be e.g. having alphabetical prefixes on the labels [akin to how rustc does it](https://github.com/rust-lang/rust/issues?page=2&q=is%3Aissue+is%3Aopen) to make sure tags of a similar colour/meaning are sorted together. In a sense the `ux` prefix is something in this direction, since few semantic tags start with `u`, but accidentally.

**Comment by jespercockx** [comment]
I think it would be good to have a prefix (such as `type: `) for all the labels. Currently we have `type: `, `backend: `, `difficulty: ` (not sure if we need those), `infra: `, `platform: `, `priority: `, `status: `, `ux: `. We also have `ghc-` and `regression in` as prefixes. We could have more prefixes such as `feature: ` for labels about specific features, `dev: ` for development-related labels (e.g. `agda-bisect`), `component:` for labels for a specific component of the Agda implementation (lexer, parser, type checker, termination checker, ...) and another prefix for labels related to specific types of bugs such as `de-Bruijn` or `missing normalise`.

**Comment by andreasabel** [comment]
Yes, these prefixes are good when they suggest themselves.
We shouldn't make this a _must_ though, since all categorizations are incomplete in the real world...

**Comment by andreasabel** [comment]
Ok, this issue went cold...
