### ISSUE TITLE
Agda input mode (emacs): Minibuffer display for `\;` is strange

### ISSUE THREAD

**Issue by mikeshulman** [agda/agda#6076]
The minibuffer display in Emacs when I type `\;` behaves strangely.  It looks like this to start with:
![minibuffer](https://user-images.githubusercontent.com/646600/188281008-4ca90426-ce0e-4869-89a7-93fa6acd1921.png)
After one `C-f` it looks like this:
![minibuffer-2](https://user-images.githubusercontent.com/646600/188281063-90846122-e1cf-423d-990e-0a6b9cd7d9be.png)
And after two `C-f`s like this:
![minibuffer-3](https://user-images.githubusercontent.com/646600/188281080-04fdaca6-b38e-4da9-89ee-9b6e5a006cd8.png)
Further `C-f`s behave more normally, with the cursor moving to the character after the 4, then after the 5, etc.  This also happens with `--no-init-file`, and @andreasabel confirmed it.

_Originally posted by @mikeshulman in https://github.com/agda/agda/issues/6064#issuecomment-1236165389_

**Comment by sattlerc** [comment]
That's because the alternatives include Unicode characters with differing bidirectional class. Specifically:
* The first alternative ARABIC SEMICOLON' (U+061B) has bidirectional class "Arabic Letter", causing the display order to switch to right-to-left.
* The direction resets to left-to-right once the third alternative THIOPIC SEMICOLON (U+1364) with bidirectional class left-to-right is reached.

The Agda input method is based on Quail package. And Quail seems to lack support for properly displaying alternatives with different bidirectional classes.

Maybe Quail could use [directional formatting characters](https://www.unicode.org/reports/tr9/#Directional_Formatting_Characters) to fix this display problem.

**Comment by mikeshulman** [comment]
I suspected it might be something like that.  Should the Agda input-mode really be including characters with bidirectional classes other than left-to-right?  That seems potentially dangerous in source code.

**Comment by andreasabel** [comment]
Apparently, this problem was introduced first in https://github.com/agda/agda/commit/4d7076a89665335428d3952beb20a36bbacec4c3, so I label this issue as fixed in 2.6.3.
