### ISSUE TITLE
Agsy gives up when no HIT is present

### ISSUE THREAD

**Issue by Trebor-Huang** [agda/agda#6101]
MWE:
```agda
{-# OPTIONS --with-K #-}  -- will occur with or without this, also occurs with --without-K
module MWE where
open import Agda.Builtin.Equality using (_≡_)
open import Data.Nat using (ℕ; _≟_)
open import Relation.Nullary using (yes; no)

F : ℕ → ℕ
F p with p ≟ p
... | yes _ = {!   !}
... | no _ = {!   !}

swap-inj : ∀ {p} → F p ≡ F p → ℕ
swap-inj eq = {!   !}
```

When the cursor is in the last hole and <kbd>C-c C-a</kbd> is pressed, agda complains "Not implemented: The Agda synthesizer (Agsy) does not support HITs yet". If `--without-K` is enabled, then the same code works with `Bool`.

Agda version 2.6.3, using VSCode on OS X.

**Comment by wilbowma** [comment]
Think I just ran into this, in the following code when upgrading from 2.6.2.2 to 2.6.3.
```agda
open import Data.Nat

-- Represent vars as de Bruijn indexes
Var = ℕ

data Type : Set where
  -- object-language Nat
  oNat : Type

data Term : Set where
  var : Var -> Term

open import Data.List

Env = List Type

well-bound : Env -> Var -> Set
well-bound Γ n = (n < (length Γ))

open import Data.Fin hiding (_<_; _+_)

env-lookup : (Γ : Env) -> {n : Var} -> (well-bound Γ n) -> Type
env-lookup Γ p = lookup Γ (fromℕ< p)

data _⊢_::_ : Env -> Term -> Type -> Set where
  Rule-Var : ∀ {Γ n} ->
    (x : (well-bound Γ n)) ->
    ------------------------
    Γ ⊢ (var n) :: (env-lookup Γ x)

foo : (oNat ∷ []) ⊢ var 0 :: oNat
foo = {!!}
```

**Comment by andreasabel** [comment]
Maybe a workaround is to use `standard-library-1.7.1` which uses `--without-K` instead of `--cubical-compatible`.
This is the better choice if you are not planing to use cubical features in your development, because it spares you such cubical conundrums.

**Comment by nad** [comment]
> This is the better choice if you are not planing to use cubical features in your development

If you are developing code that is intended to be used by others, then it might make sense to also consider what features are used in the importing code.

**Comment by jamesmckinna** [comment]
Suggest that while implementation of a tool (Agsy) lags behind that of the main system (Agda), but that using `--without-K` solves the problem, then use that flag. 

AFAIU, Agda won't complain about imports of `--cubical-compatible` modules (eg from stdlib) into a `--without-K` one (vice versa seems to generate a warning), so during proof development, if you don't use cubical features, and/or wish to use Agsy, then stick with `--without-K`? 

In any case, there is/ought to be a separation between development time, when search tools/tactical support may be helpful, and deployment time when perhaps they no longer play a role. And such deployments, if intended to be merged into stdlib, should (then and only then?) be made cubical compatible?
 
The current real issue is, at least AFAIUI, for stdlib maintainers, but I can imagine a time when even this isn't...? 

But forking the library, or else asking users to make do with an outdated one, seems a bad price to pay?

**Comment by andreasabel** [comment]
Both MWEs work with Mimer.
