### ISSUE TITLE
Regression related to Cubical Agda and generalisable variables

### ISSUE THREAD

**Issue by nad** [agda/agda#6211]
The following code is accepted by Agda 2.6.2, but not by a recent development version:
```agda
{-# OPTIONS --cubical #-}

open import Agda.Primitive

_∘_ :
  ∀ {a b c} {A : Set a} {B : Set b} {C : Set c} →
  (B → C) → (A → B) → (A → C)
(f ∘ g) x = f (g x)

postulate
  F : ∀ {a} (A : Set a) → A → Set a

variable
  a : Level
  A : Set a

postulate
  _ : (f : A → A) → F ((_ → A) → _) (_∘ f)
```
```
Unsolved metas at the following locations:
  […]/Bug.agda:18,12-13
```
For some reason there is no regression when `--without-K` is used.

@jespercockx, bisection points to 3dd609efb8a61aa34a11cc9b690eb42da107d596 ("[ re #5894 ] Compute proper blocking tags when comparing sorts"). Is the regression intended?

**Comment by jespercockx** [comment]
No this was not intended to have any change on the semantics of Agda, I'll have a look.

**Comment by jespercockx** [comment]
This is again a case where a constraint ends up being postponed on a metavariable that is already solved, like in https://github.com/agda/agda/blob/931edcc11e0d1bfb8bc48678993ed4cc9df4cf44/src/full/Agda/TypeChecking/Reduce.hs#L410-L414

I have a fix for this issue, but adding a check to `addConstraint` for solved metas in the blocker suggests that this still happens in other places as well. Options are to either go and fix those other cases too, or to add a call to `instantiateFull` on the blocker when postponing the constraint.

**Comment by nad** [comment]
I think we should aim to remove all uses of `instantiateFull`.

**Comment by jespercockx** [comment]
Yes, I definitely agree. However, right before the release might not be the best time to rip off a band-aid that might be covering an unknown number of bugs. What I will do now is to fix as many of the issues that I can find right now and then re-apply the band-aid. Then after the release we can remove the band-aid again and give ourselves a bit more time to fix the other issues that it might uncover (as well as do the necessary refactoring to remove usages of `instantiateFull`).

**Comment by jespercockx** [comment]
Also there is a tradeoff to be made here (at least on the short term): the problem here is that constraints might get postponed on a metavariable that is already solved, and thus will never get reattempted. If introducing a call to `instantiateFull` is the easiest way to get rid of this bad behaviour, then I think it is worth it (though we should separately still try to get rid of the `instantiateFull`).

**Comment by nad** [comment]
> However, right before the release might not be the best time to rip off a band-aid that might be covering an unknown number of bugs.

Sure. Let's hope that the new call to `instantiateFull` does not degrade the performance of existing code too badly.

**Comment by jespercockx** [comment]
Another option is that I only add the `instantiateFull` calls where we currently already use `unblockOnAnyMetaIn` (and hence are already traversing the term). Then we could leave the behaviour on other cases as-is until after the release (and then do the proper thing by computing the right Blocker rather than relying on `unblockOnAnyMetasIn` and `instantiateFull`).
