### ISSUE TITLE
CHANGELOG: Document handling of indexed data types in Cubical, plus the warning `NoEquivWhenSplitting`

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#6227]
E.g. the test case for #4725 generates this warning:
```
Could not generate equivalence when splitting on indexed family,
the function will not compute on transports by a path.
  Reason: UnsupportedYet Injectivity
                           position:    0
                           type:        D
                           datatype:    D
                           parameters: 
                           indices:    
                           constructor: d
when checking the definition of g
```
I dimly remember we discussed adding a flag to switch off these warnings. Shouldn't we provide such a flag with 2.6.3?
@plt-amy @jespercockx @nad @Saizan

**Comment by gallais** [comment]
If it is really a warning then can't you use `-WnoNAMEOFTHEWARNING`?

**Comment by andreasabel** [comment]
Indeed it is `NoEquivWhenSplitting`! We should print the warning names like GHC does.

This warning should be announced in the CHANGELOG, along with some text describing the new feature of Cubical Agda: support for indexed data types.
@plt-amy : Could you write such a text?

**Comment by nad** [comment]
> This warning should be announced in the CHANGELOG, along with some text describing the new feature of Cubical Agda: support for indexed data types.

Partial support. Can one write any pattern-matching definition that does not trigger `NoEquivWhenSplitting`?

Should we use the word "experimental" in the description of this new feature?

**Comment by nad** [comment]
Issue #3733 is still open, and there is some discussion about what remains to be done. The text in the changelog could mention that the feature is unfinished, and in what sense it is unfinished.

**Comment by nad** [comment]
There are a number of comments in the source code labelled with `#3733`. Perhaps one or more of these point to other things that could be mentioned in the changelog:

https://github.com/agda/agda/blob/96883ab502ee23d19ea6531fc2acb124e29e76eb/src/full/Agda/Compiler/MAlonzo/Compiler.hs#L674

https://github.com/agda/agda/blob/96883ab502ee23d19ea6531fc2acb124e29e76eb/src/full/Agda/Compiler/ToTreeless.hs#L259

https://github.com/agda/agda/blob/96883ab502ee23d19ea6531fc2acb124e29e76eb/src/full/Agda/TypeChecking/Coverage.hs#L1007-L1008

https://github.com/agda/agda/blob/96883ab502ee23d19ea6531fc2acb124e29e76eb/src/full/Agda/TypeChecking/Coverage.hs#L1020

https://github.com/agda/agda/blob/96883ab502ee23d19ea6531fc2acb124e29e76eb/src/full/Agda/TypeChecking/Positivity.hs#L412

https://github.com/agda/agda/blob/96883ab502ee23d19ea6531fc2acb124e29e76eb/src/full/Agda/TypeChecking/Quote.hs#L326

**Comment by plt-amy** [comment]
Very few definitions will escape the `NoEquivWhenSplitting` curse, so I think we should turn that warning off by default. 

Namely they can't use anything other than `EtaExpandVar` and `Solution` steps during unification of indices on the LHS (there might be failure modes other than not being able to generate a left). That's because the least complete part of the implementation is `buildEquiv` in `TypeChecking.Rules.LHS.Unify.LeftInverse`, which is meant to turn a unification log into an actual left-inverse that can be used in the generated `transp` clause.

This excludes pretty much every function which matches on an indexed type with indices instantiated by a constructor.  Essentially, only very generic helper functions will work, e.g. this will compute fine in all situations:

```agda
data _≡_ {a} {A : Type a} (x : A) : A → Type a where
  refl : x ≡ x

sym : ∀ {a} {A : Type a} {x y : A} → x ≡ y → y ≡ x
sym refl = refl
```

However, the annoying warnings aside, this is a strict improvement over the Cubical status quo, where even a simple definition like `sym` would be stuck on everything that's not `refl`!

**Comment by nad** [comment]
> Very few definitions will escape the `NoEquivWhenSplitting` curse, so I think we should turn that warning off by default.

I think the warning should be on by default, because it signals that a key feature of Agda is broken: things do not compute properly.
