### ISSUE TITLE
Cubical: should generated code corresponding to erased constructors be erased?

### ISSUE THREAD

**Issue by nad** [agda/agda#6271]
When `--cubical-compatible` is used Agda generates code for each constructor (in `defineProjections` and `defineCompData`). If a constructor is erased, should the generated code also be erased?

**Comment by nad** [comment]
I don't know a lot about this generated code, but I think I read that some generated code (extra clauses for definitions by pattern matching) is not type-checked. Can the double-checker handle the generated code? In that case one could perhaps catch some problems by using `--double-check`.

Another question is if there are theoretical reasons for erasing, or not erasing, these things.

**Comment by nad** [comment]
> Can the double-checker handle the generated code?

Maybe not, see issue #4455. I tried to type-check some code that does not use any (other) options with `--double-check` turned on, and then Agda failed. Is the double-checker not maintained?

**Comment by nad** [comment]
I don't know a lot about the internals of Cubical Agda, but I guess it makes sense for the projections to be erased, because it should not be possible to project something from an erased constructor in run-time mode. When one normalises an expression involving `primHComp`/`primTransp`, which are not erased, then one can end up with an application of an hcomp constructor. However, I would hope that it is not possible, in run-time mode, to end up with an hcomp constructor in head position, if that hcomp constructor corresponds to an erased constructor. (I know even less about the constructors that are added for inductive families.)

**Comment by nad** [comment]
My understanding is that we have the following situation:

* The generated code is not type-checked.
* The generated code is not compiled.

If names are made erased, then they mostly become harder to use. However, if a constructor is made erased more code can become type-correct, because when you match on an erased constructor (in a non-erased position) the right-hand side is checked in compile-time mode.

In this case I don't think it is possible to explicitly match on the generated constructors, and the generated code is not type-checked anyway. Thus I suggest that we make the generated code erased: I don't know if this is the "correct" approach, but as things stand I suspect that it does not make Agda accept more code, and perhaps it rules out some code that should not be accepted.

**Comment by plt-amy** [comment]
I think it's fine to mark the definitions associated _with a constructor_ with the same modality as that constructor. That's because those functions (the projections, etc) for an erased data constructor can only be accessed through use of `primHComp` or `primTransp` applied **to one of those constructors**. 

---

For a bit more background, Cubical Agda generates the following internal definitions:

- For a `data T Δ : Γ → Set _` declaration:
  - Each constructor `c : Φ → X Δ ixs` has:
    - If Γ is empty: A function `transp-c` implementing `transp (λ i → T (Δ i)) φ (c as)` (`defineKanOperationD DoTransp`)
    - If Γ is empty and `c` is a point constructor: a function `hcomp-c` implementing `hcomp (λ i .o → c (as i)) (c bs)` (`defineKanOperationD DoHComp`).
    - (Partial) projections for each argument in `Φ`, named `c-0`, `c-1` etc (`defineProjections`). The projections are used in the implementation of the functions above. That's because data constructors are, for the purposes of defining hcomp and transp, treated as though they were record constructors.
  - If `Γ` is non-empty, a "function" `transpX-T` implementing `transp (λ i → T (Δ i) (Γ i)) i1 x`. For `φ ≠ i1`, this "function" is essentially used as a constructor (`defineTranspIx`).
  - If `Γ` is non-empty, a function `transp-T` implementing `transp (λ i → T (Δ i) (Γ i)) φ x` for all other cases (`defineTranspFun`)
- For functions which split on a weak (hgierh/indexed) data type: The coverage checker will insert, at each split, a clause to deal with `hcomp`. If the weak type is actually indexed, then there will be clauses to deal with `transpX ... (hcomp ...)` (`createMissingTrXHCompClause`), `transpX ... (transpX ...)` (`createMissingTrXTrXClause`), and `transpX ... (c ...)` for each constructor of the type (`createMissingTrXConClause`)
- For functions which split on `reflId`, a clause will be generated to cover `conid` (`createMissingConIdClause`).

None of this extra code is type-checked or compiled, as you point out. The `transpX ... (c ...)` clauses are still _modality_ checked, but they are not type-checked. Also note that when we explain higher inductive types as having an "`hcomp` constructor", that's a slight lie: it's not that each HIT gets its own `hcomp`, at the moment, they just match on the `Def` `primHComp`. Same for the `transpX` "constructor". That's what `DefP` is for.

**Comment by nad** [comment]
> I think it's fine to mark the definitions associated _with a constructor_ with the same modality as that constructor.

OK, then I'll commit my changes (see #6294).

**Comment by jpoiret** [comment]
> > Can the double-checker handle the generated code?
> 
> Maybe not, see issue #4455. I tried to type-check some code that does not use any (other) options with `--double-check` turned on, and then Agda failed. Is the double-checker not maintained?

The internal checker doesn't have feature parity with the usual one, and modalities are one of the omissions. Basically, it only checks that the `Elims` from the internal syntax have a usable `Modality` in their `ArgInfo` for the type of the function being applied, but doesn't actually check that variables are used in a way compatible with that above `ArgInfo` from what I understand.
