### ISSUE TITLE
Put Level type in a different sort

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#6272]
Currently Agda has `Level : Set`, which is a bit dubious since it allows a number of things that are not possible in most versions of type theory, such as computing the maximum of a list of universe levels. It also leads to some issues in practice, in particular a loss of subject reduction in #5810. Hence I believe it would make sense to consider moving `Level` to a different sort. Options here are:

- Move it to `Setω`. Advantage: this is the simplest and clearest solution, both from an implementation perspective and for the user.
- Move it to its own new sort `LevelSort` (name tbd). Advantage: this would give us more fine-grained control over when we allow/disallow functions into `Level` and datatypes that can contain a `Level` (without changing the rules for other things in `Setω`).
- Move it to `SSet`. Advantages: `SSet` is a kind of "internalized metatheory" and universe polymorphism could be seen as a "meta" thing and not part of the core type theory. But I have not yet really thought through the implications of this option.

Any opinions? (This might also be a good discussion topic for the upcoming AIM)

**Comment by sattlerc** [comment]
Move it to its own new sort!

**Comment by plt-amy** [comment]
I think I'm missing something, but I don't see how any of these solutions would address the failure in subject reduction from #5810?

Edit just to save some space: Would the sort of `Level` admit record definitions, so there's some hope of recovering e.g. [these definitions](https://github.com/agda/agda-stdlib/blob/master/src/Function/Nary/NonDependent/Base.agda#L50-L52)? Or would code like this be outlawed forever? (For consistency with our other dubiously-named sorts it should definitely be `LevelUniv` 😛)

**Comment by JacquesCarette** [comment]
I would think that that would seriously break some code that @gallais has written (and is integrated in the standard library).

**Comment by andreasabel** [comment]
> I think I'm missing something, but I don't see how any of these solutions would address the failure in subject reduction from #5810?

I also don't see how that would help.  Wouldn't you still have to place `(x : A) -> Set (f x)` into `Setomega` (which is the cause of the subject reduction problem)?  What prevents us from writing a function `f : A -> Level` when `Level : Setomega`?

I also fail to see why operations on levels should be so terrible.  We could as well have `Level = Nat`, just to point in the opposite direction.  There wouldn't be any problem with that, but this would block the door to larger level hierarchies.
`Level : Set` limits the size of the level hierarchy more than `Level : Set1` etc., but so far no one has voiced demand for a _big_ level type.

Also, I think that cumulativity is the most natural choice for universes.  Cumulativity restores subject reduction for #5810.  Placing things in Setomega is often a cautionary decision (since we don't know a concrete level our type lives at), so it should not be a _lower bound_ of some sense, only an _upper bound_.

**Comment by jespercockx** [comment]
@plt-amy and @andreasabel the reason why I'm proposing to move it to its own sort is that it would allow us to be stricter on what sorts universe-polymorphic things can live at by tuning the PTS rules. For example, in the issue of #5810 
```agda
bad : Setω
bad = λ (ℓ : ⊤ → Level) → ∀ t → Set (ℓ t)) (λ _ → lzero) 
```
we could disallow the type `⊤ → Level` by removing the PTS rule `(Set,LevelUniv,LevelUniv)` (in other words, by disallowing functions from a `Set` into a `LevelUniv` type). We could then still have the PTS rule `(Setomega,LevelUniv,LevelUniv)`, since any pi type that has a `Setomega` as its codomain will anyway be in `Setomega` (or higher) itself.

Regarding cumulativity, I think this is a good direction to explore as well but I believe we still need an alternative solution that makes Agda's theory *simpler* rather than more complex (and then cumulativity can be an option for people who are fine with the extra complexity).

**Comment by jespercockx** [comment]
A concrete proposal here would be to introduce a sort `LevelUniv` in `Agda.Primitive` that by default is just an alias for `Set`, but to also introduce a flag `--simple-universe-polymorphism` (name subject to future bikeshedding) that makes it separate from `Set` and also disables most of the PTS rules for functions into it.

**Comment by sattlerc** [comment]
It is strange for a finely typed language such as Agda to be so "unsorted" (when it comes to levels).

In addtion to what Jesper said, more finely grained sorts have a number of benefits:
* The theory arguably become simpler (in the same sense that the typed λ-calculus is simpler than the untyped λ-calculus).
* The theory becomes more configurable.
* The theory has more models. Models become easier to establish (e.g., you may not need to model levels as first-class objects).
* Related to the previous point, the theory becomes easier to translate to other languages (e.g. Coq).
* Universe level analysis becomes easier if `LevelUniv` is restricted. With full restrictions, `Setomega` becomes unnessary.

**Comment by andreasabel** [comment]
@jespercockx :
> we could disallow the type ⊤ → Level by removing the PTS rule (Set,LevelUniv,LevelUniv) (in other words, by disallowing functions from a Set into a LevelUniv type).

This would help in this case, admitted.
How about
```agda
.... (f : Level -> Level) ... 
T = (x : Level) -> Set (f x)
```
where does `T` live now?

**Comment by nad** [comment]
> A concrete proposal here would be to introduce a sort `LevelUniv` in `Agda.Primitive` that by default is just an alias for `Set`, but to also introduce a flag `--simple-universe-polymorphism` (name subject to future bikeshedding) that makes it separate from `Set` and also disables most of the PTS rules for functions into it.

Is the idea to fix the problem with subject reduction? If not, then I think you should have to opt in to not having subject reduction, that should not be the default.

I use record types parametrised by functions of type `(a : Level) → …`. Will those be supported when `--simple-universe-polymorphism` is used? In my main developments I do not explicitly use `Setω`, so for me a simple fix of the problem with subject reduction would be to hide `Setω` behind a flag that is incompatible with `--safe`.

**Comment by andreasabel** [comment]
@jespercockx wrote:
> introduce a flag `--simple-universe-polymorphism` (name subject to future bikeshedding)

Started the bikeshedding in https://github.com/agda/agda/pull/6505#pullrequestreview-1298950010.  Something like `--level-universe` would be more telling.  
(NB. In general, I don't like names that do not give away the meaning, and these should be avoided where possible.  For "simple types" it is too late, I am afraid.  But if you tell a Java programmer that function types of any order are "simple", they might be surprised.)

> we could disallow the type `⊤ → Level` by removing the PTS rule `(Set,LevelUniv,LevelUniv)` (in other words, by disallowing functions from a `Set` into a `LevelUniv` type)

What actually happens in this situation?
```agda
module M (A : Set) (a : A) where

  lev : Level
  lev = ?
```
Agda represents this internally as `?0 : (A : Set) (a : A) -> Level`, but this is now an ill-sorted type, is it?

**Comment by sattlerc** [comment]
> Agda represents this internally as `?0 : (A : Set) (a : A) -> Level`, but this is now an ill-sorted type, is it?

I think this is showing some flaws of both the module and the sort system.

A workaround would be to replace the PTS rule `(Set,LevelUniv,LevelUniv)` by `(Set,LevelUniv,Setω)`.

**Comment by arthur-adjedj** [comment]
> A workaround would be to replace the PTS rule `(Set,LevelUniv,LevelUniv)` by `(Set,LevelUniv,Setω)`.

Unless I'm mistaken, this still wouldn't solve the SR issue, would it ? `bad`'s type would still be `Setω` before reduction, and `Set₁` after

**Comment by plt-amy** [comment]
I still think the sort system isn't the right tool for this problem... It's possible to make utter nonsense with the `Level` type, granted, but there are many entirely unproblematic, _useful_ functions from `Type`s into `Level` that a blanket ban would disallow.

The typical use-case ([A](https://github.com/plt-amy/1lab/blob/main/src/Algebra/Monoid.lagda.md#L35), [B](https://github.com/plt-amy/1lab/blob/main/src/1Lab/Equiv.lagda.md), [C](https://github.com/plt-amy/1lab/blob/main/src/Data/Set/Coequaliser.lagda.md#L26), [D](https://github.com/plt-amy/1lab/blob/main/src/Data/Sum/Properties.lagda.md#L52), [E](https://github.com/agda/agda-categories/blob/master/src/Categories/Adjoint.agda#L173-L178), [F](https://github.com/agda/agda-stdlib/blob/master/src/Level.agda#L30-L34)) is naming the level of a generalized variable, which is otherwise impossible:

```agda
level-of : {ℓ : Level} → Type ℓ → Level
level-of {ℓ} _ = ℓ

variable
  l : Level
  A B C : Type l

data Foo (f : A → B) : Type (level-of A ⊔ level-of B) where ...
```

Other than making generalized variables easier to use, I also use functions like these to abbreviate complex level expressions, using visible arguments (in `Type _`) to drive unification: [A](https://github.com/plt-amy/1lab/blob/main/src/Cat/Functor/Adjoint.lagda.md#L27-L29), [B](https://github.com/plt-amy/1lab/blob/main/src/Cat/Functor/Kan.lagda.md#L24-L26). These would be a lot worse to lose than `level-of`.

Anyway, 

> Unless I'm mistaken, this still wouldn't solve the SR issue, would it ? bad's type would still be Setω before reduction, and Set₁ after

You're correct.

> I think this is showing some flaws of both the module and the sort system.

Modules make it worse (since you can refer to `M.lev` by the type Andreas mentioned), but keep in mind that metas stand for functions, and are solved with lambdas: it would be impossible to infer levels on the RHS of _any definition_, in a parameterised module or otherwise, without the generated metas having ill-sorted types.

**Comment by jespercockx** [comment]
I think we should see this PR as an experiment as to how usable universe polymorphism still is with a much more restricted Level type. So from that perspective, I think it makes sense to start with something very restricted and extend it if needed.

> Modules make it worse (since you can refer to M.lev by the type Andreas mentioned), but keep in mind that metas stand for functions, and are solved with lambdas: it would be impossible to infer levels on the RHS of any definition, in a parameterised module or otherwise, without the generated metas having ill-sorted types.

Perhaps what we need to do instead is to allow function types such as `A -> Level` where `A : Set`, but not allow the argument to appear inside level expressions. So the only functions `A -> Level` that we could define would be constant functions, and dependencies of level metavariables could be aggressively pruned if their sort is not `LevelUniv`.
