### ISSUE TITLE
Code is rejected with `--cubical-compatible`, but not with `--without-K`

### ISSUE THREAD

**Issue by nad** [agda/agda#6298]
The following code is accepted when `--without-K` is used, but rejected when `--cubical-compatible` is used:
```agda
open import Agda.Builtin.Equality

J :
  ∀ {@0 A : Set} {@0 x : A}
  (P : {y : A} → x ≡ y → Set) →
  P (refl {x = x}) →
  {y : A} (eq : x ≡ y) → P eq
J P p refl = p
```
Error message with `--cubical-compatible`:
```
This clause has target type
Agda.Primitive.Cubical.primTransp
(λ i →
   Agda.Primitive.Cubical.primTransp
   (λ i₁ →
      {y : A} →
      x
      (Agda.Primitive.Cubical.primIMin i₁
       (Agda.Primitive.Cubical.primINeg i))
      ≡ y →
      Set)
   (Agda.Primitive.Cubical.primIMax i φ) P
   (Agda.Builtin.Equality.transpX-_≡_
    (λ j →
       x
       (Agda.Primitive.Cubical.primIMax j
        (Agda.Primitive.Cubical.primINeg i)))
    (Agda.Primitive.Cubical.primIMax
     (Agda.Primitive.Cubical.primINeg i) φ)
    refl))
φ
(J
 (Agda.Primitive.Cubical.primTransp (λ i → {y : A} → x i ≡ y → Set)
  φ P)
 (Agda.Primitive.Cubical.primTransp
  (λ i →
     Agda.Primitive.Cubical.primTransp
     (λ j → {y : A} → x (Agda.Primitive.Cubical.primIMin i j) ≡ y → Set)
     (Agda.Primitive.Cubical.primIMax
      (Agda.Primitive.Cubical.primINeg i) φ)
     P refl)
  φ x₁)
 refl)
which is not usable at the required modality @irrelevant.

Note: to maintain compatibility with Cubical Agda, the target type
must be usable at the modality in which the function was defined,
since it is used for computing transports

when checking the definition of J
```
The error message's range matches that of the only clause of `J`, so it is natural to assume that "this clause" refers to that clause, but perhaps it actually refers to some generated clause.

@plt-amy, can you explain what is going on here?
* The code does not use irrelevance, so why does the error message state that the "target type […] is not usable at the required modality @irrelevant"?
* Does the error message refer to some generated code?
* I thought that the idea was that, after your changes, one should get this kind of error message also when `--without-K` is used. Why is that not the case for this code?

**Comment by plt-amy** [comment]
@nad I can explain 2/3 of those points and I'm looking into the third:

1. Irrelevance comes up because of [this line](https://github.com/agda/agda/blob/master/src/full/Agda/TypeChecking/Coverage/Cubical.hs#L898). So I think we're running into this snippet from the discussion in #5611:
  > It might be the case that some existing code that uses @0 and --without-K is rejected with an incomprehensible error message, but at least the standard library is not affected.

2. Yes, that is the code generated for `J P x (transpX x₁ φ refl)` (`tc.cover.trxcon:20` to print the actual clause).

As for 3, that was the idea, but the implementation there is approximate (as you've seen). I can think of a couple of ways to make it more accurate (of course, short of generating the full cubical clause and checking that :sweat_smile:) but they'd be a bit more invasive to the pattern-matching unifier.

**Comment by nad** [comment]
> 1. Irrelevance comes up because of [this line](https://github.com/agda/agda/blob/master/src/full/Agda/TypeChecking/Coverage/Cubical.hs#L898).

Which I implemented…

> 2. Yes, that is the code generated for `J P x (transpX x₁ φ refl)` (`tc.cover.trxcon:20` to print the actual clause).

I think that the error message should make clear that it refers to generated code.

**Comment by plt-amy** [comment]
> I think that the error message should make clear that it refers to generated code.

Agreed; I'll change it.

I also want to fix the LHS modality check to catch this, but there's actually a _surprisingly interesting_ combination of things going on here: When the pattern-matching unifier encounters `x = y` (from matching on `refl`), it'll normally set `y := x` (don't ask why), so the only transport that needs to happen is for the actual result type.

But when `x` is `@0`, it'll set `x := y` instead! That means anything which refers to `x` now needs to be transported, which is why the generated clause in the error message is so massive. That's **bug 2**: the LHS modality check only considers the target type, but really it needs to look at the unification trace and consider everything which happens after the variable which changed, and which has that variable free.

So with your original code, that's where the modality error comes from: it needs to use `A` in an ω context, to transport `P`, but `A` is marked `@0`. But interestingly _this_ variant also fails:

```agda
J :
  ∀ (A : Set) (@0 x : A)
  (P : (y : A) → x ≡ y → Set) →
  (prefl : P x refl) →
  (y : A) (eq : x ≡ y) → P y eq
J A x P prefl rhs refl = {!   !}
```

It's surprising because the generated clause doesn't appear to mention `x` at all! But if you look closely enough, the `LeftInv` generation code uses `IApply` copatterns, and _that's_ where the use of `x` is hiding. That's **bug 3**, the left inverse should just `Apply` the interval variable (since the generated clause binds an `I → A`, not a `PathP A x y`).

**Comment by plt-amy** [comment]
You can spot the difference in solutions by looking at which patterns got forced:

```
lhs: final checks with remaining equations
  A = A : Set
  x = x : A
  P = P : (y : A) → x ≡ y → Set
  prefl = prefl : P x refl
  y = x : A
qs0 = [A, .x, P, prefl, x, refl]
```

vs

```
lhs: final checks with remaining equations
  A = A : Set
  x = x : A
  P = P : (y : A) → x ≡ y → Set
  prefl = prefl : P x refl
  y = x : A
qs0 = [A, x, P, prefl, .x, refl]
```

First one is with `@0 x`, second is with `@ω x`.

**Comment by nad** [comment]
As I noted in the pull request (#6299) this change broke some code. I think this should be investigated before the release.

**Comment by nad** [comment]
Here is a small test case:
```agda
{-# OPTIONS --erased-cubical #-}

data Unit : Set where
  unit : Unit

data D : Unit → Set where
  c : D unit

data P (_ _ : Unit) : Set where

F : (@0 x y : Unit) → @0 P x y → D x → Set₁
F _ _ _ c = Set
```
The code was accepted before the change, but is now rejected:
```
The argument x has type
  P unit y
which is not usable at the required modality @ω.

Note: in Cubical Agda, this argument's type must be usable at the
modality in which the function was defined, since it will be used
for computing transports

when checking that the pattern c has type D x
```

**Comment by plt-amy** [comment]
@nad Thank you for the small test case, I'll investigate ASAP. But I'm worried that making the LHS modality check more accurate might require duplicating a large part of the --cubical-compatible work, which we've seen is expensive. I'm afraid that it might not be feasible to have all three of:

- `--without-K` rejects every program which `--cubical-compatible` would
- `--without-K` rejects no more programs than `--cubical-compatible` would
- `--without-K` is a significant savings in elaboration work over `--cubical-compatible`

**Comment by jespercockx** [comment]
Couldn't we just run *also* the `--without-K` checks when `--cubical-compatible` is enabled to make `--without-K` accept all files that are accepted under `--cubical-compatible` by definition? It seems to me that the computational overhead of the checks is relatively light compared to generating the cubical code, so this wouldn't be so bad performance-wise. (Of course, this gives up on the first item on your list, but this seems like the least bad one to give up.)

**Comment by plt-amy** [comment]
Right now, all "cubical compatibility" checks (incl. the LHS modality check) that _don't_ involve generating the internal code are run when any of `--without-K`, `--cubical-compatible`, `--cubical` or `--erased-cubical` are on. 

The original problem raised by this issue is that `--cubical-compatible` then goes on to check its internal generated code, thus rejecting a program that `--without-K` doesn't (The original `J` example).

My fix (#6299) over-corrected, so either of `--without-K`/`--cubical-compatible` _with the new check_ rejects a program that only running `--cubical-compatible`'s internal checks would _not_. To clarify, I suppose my list of wants should say, instead of `--cubical-compatible`, _the internal checks performed by `--cubical-compatible`_.

My specific worry is that making the LHS modality check perfectly accurate to the internal checking of the generated clauses might not be possible without doing much of the work responsible for generating those clauses.

**Comment by plt-amy** [comment]
Trying to debug my code without looking directly at it (ah, the wonders of train internet), it seems that the relevant difference is:

- The original `J` example has the unifier eliminate `@0 x` in favour of `y`. `x` appears in the type of `P`, which in turn appears in the target type. Might be a red herring: Since `x` appears in `P`'s domain(s), `P` is transported as a function in an `@ω` context, so `A` must be usable `@ω`.
- @nad's revised example has the argument of type `P x y`, which is fibrant and has `x` free. Since `x` is the first forced variable, my check insists that `P unit y` be usable at `@ω`, since it _might_ be transported. But it'll only appear in `@0` positions in the generated term (because "the `P x y` argument" is not used in the target type), so it's quite alright for its type only to be well-formed `@0`.

**Comment by jespercockx** [comment]
Do you happen to be on the train that left at 11:30 from London? I'm in coach G (also, at least 5 other AIM attendees should be hiding somewhere on it.)

**Comment by nad** [comment]
> * `--without-K` rejects every program which `--cubical-compatible` would
> * `--without-K` rejects no more programs than `--cubical-compatible` would
> * `--without-K` is a significant savings in elaboration work over `--cubical-compatible`

If possible I think we should have 1 and 3. It is perhaps a little strange if code is rejected with `--without-K`, when one can get the code to type-check using `--cubical-compatible`, and then import it in a module that uses `--without-K`. However, I don't currently see any fundamental problems with this.

**Comment by nad** [comment]
Here is another piece of code which used to be accepted but is now rejected:
```agda
{-# OPTIONS --erased-cubical #-}

open import Agda.Builtin.Sigma

const : {A : Set₁} {B : Set} → A → (B → A)
const x = λ _ → x

data ⊥ : Set where

I : Set
I = Σ ⊥ (const ⊥)

data C : @0 I → Set where
  c : ∀ {@0 x y} → C (x , y) → C (x , y)

data D : {@0 x : I} → @0 C x → Set where
  d : {@0 x : I} {@0 y : C x} → D y → D (c y)

P : {@0 x : I} → C x → Set
P (c x) = P x

f : {@0 x : I} (y : C x) → D y → P y
f (c x) (d y) = f x y
```
Tiny changes to the code make it acceptable to Agda:
* Replacing `const ⊥` with `λ _ → ⊥`.
* Replacing `∀ {@0 x y}` with `∀ {@0 x y : _}`.

The new check seems to make Agda rather sensitive to small changes. Is a call to `reduce` (say) missing somewhere?

**Comment by nad** [comment]
The following code is also rejected:
```agda
{-# OPTIONS --erased-cubical --safe #-}

data I : Set where

data D : I → Set where
  c : (x : I) → D x

@0 f : (@0 x : I) → D x → D x
f .x (c x) = c x
```
It seems as if the check ignores the fact that `f` is declared as erased.

**Comment by nad** [comment]
@plt-amy: Thanks. Now all my main developments are accepted.

We might encounter more problems down the road, but perhaps this is good enough for Agda 2.6.3.

The following things remain to be addressed:
* Given that the new check is conservative, should it be turned on when `--cubical-compatible` is used? I suggest that it should not be used. One might imagine using the conservative check to generate an error message if the more precise check fails for generated code, but that error message could be misleading. (If the check is not used when `--cubical-compatible` is turned on, then the recent test cases should use `--without-K`.)
* I think the new check should be documented.

**Comment by plt-amy** [comment]
I think the check should still be enabled in both cases, since the intended semantics of `--cubical-compatible` is that it accepts exactly the same programs as `--without-K` (but generates the internal support code), and running the check post-hoc just to get an error message would be fairly complicated: it needs information that we only have handy when near calls to `unifyIndices`.

I'll try to write documentation for it early in the morning tomorrow.

**Comment by nad** [comment]
> I think the check should still be enabled in both cases, since the intended semantics of `--cubical-compatible` is that it accepts exactly the same programs as `--without-K` (but generates the internal support code), and running the check post-hoc just to get an error message would be fairly complicated: it needs information that we only have handy when near calls to `unifyIndices`.

My suggestion is to not run the check at all, not even to generate error messages, when `--cubical-compatible` is used. However, I can see your point. Can we at least agree to turn off the check for `--erased-cubical` and `--cubical`?

**Comment by plt-amy** [comment]
I don't think either of those is a good idea: there's a possibility that there is code which would generate modality-**correct** internal clauses, but which are rejected by the LHS modality check: checking this code with `--cubical` would result in a different result than checking it with `--cubical-compatible`, even if it doesn't use any actual cubical features.

**Comment by nad** [comment]
We have at least the following options:
1. Never use this check. In that case we might accept too much code when `--without-K` is used (perhaps depending on the viewpoint of the user).
2. Only use this check when `--without-K` is used. Then we might accept less code with `--without-K` than with `--cubical-compatible`. However, the check is only an approximation of another check that is run when `--cubical-compatible` is used.
3. Use this check for `--without-K` and `--cubical-compatible`, but not `--erased-cubical` or `--cubical`.
4. Use this check for `--without-K` and `--cubical-compatible`, including `--erased-cubical` and `--cubical`.

I think we should go with option 2.

**Comment by jespercockx** [comment]
I strongly prefer option 4 for reasons of having a consistent user experience.

**Comment by nad** [comment]
OK, I guess we can make the conservative check more lenient in the future if it turns out to be a problem.
