### ISSUE TITLE
Build failure for Agda-2.5.2 with cabal in EdisonCore-1.3.1.1

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#6331]
Looks like Agda-2.5.2 does not build anymore because of dependency bitrot (CC @wenkokke).

Upstream issue:
- https://github.com/robdockins/edison/issues/21

```
$ cabal get Agda-2.5.2
$ cd Agda-2.5.2
Agda-2.5.2$ cabal build -O0 -w ghc-8.0.2 -f enable-cluster-counting

Warning: this is a debug build of cabal-install with assertions enabled.
Resolving dependencies...
Build profile: -w ghc-8.0.2 -O0
In order, the following will be built (use -v for more details):
 - EdisonCore-1.3.1.1 (lib) (requires build)
 - equivalence-0.3.5 (lib) (requires build)
 - Agda-2.5.2 (lib:Agda, exe:agda, exe:agda-mode) (first run)

Building library for EdisonCore-1.3.1.1..
[ 1 of 26] Compiling Data.Edison.Seq.Defaults ( src/Data/Edison/Seq/Defaults.hs, dist/build/Data/Edison/Seq/Defaults.o )

src/Data/Edison/Seq/Defaults.hs:203:39: error:
    • Could not deduce (Control.Monad.Fail.MonadFail Identity)
        arising from a use of ‘lookupM’
      from the context: Sequence s
        bound by the type signature for:
                   lookupUsingLookupM :: Sequence s => Int -> s a -> a
        at src/Data/Edison/Seq/Defaults.hs:202:1-51
    • In the first argument of ‘runIdentity’, namely ‘(lookupM i s)’
      In the expression: runIdentity (lookupM i s)
      In an equation for ‘lookupUsingLookupM’:
          lookupUsingLookupM i s = runIdentity (lookupM i s)
```

**Comment by wenkokke** [comment]
Yes, that's one of the issues I was going to submit :)

**Comment by andreasabel** [comment]
@wenkokke: But all largest major versions >=2.5.3 just built with `cabal` out-of-the box for me (on macOS), given a matching GHC version.  Did you have problems with them?  (Maybe on Windows?)

**Comment by andreasabel** [comment]
Fixed upstream!

**Comment by wenkokke** [comment]
There’s several more issues:

- There’s the errors with `text-icu`. Are you building with `--enable-cluster-counting`? If so, what is your local version of icu4c? There’s the issues with text-icu >=0.7 && <0.7.1.0 building with icu4c 68+, which are more prominent as most distributions no longer ship versions before 68. These might be addressed by bumping the constraints for text-icu to >=0.7.1.0.
- There’s the issue that some of the GHC versions listed in `tested-with` or are no longer easily available, e.g., 8.0.1 and other versions which aren’t the final minor version, or any version before 7.10 (and I’m having trouble with 7.10, see [this log](https://github.com/wenkokke/setup-agda/actions/runs/3451403901/jobs/5760599612#step:3:17962).) When building with older or newer versions, I ran into a number of `MonadFail` errors or issues with `base` or `template-haskell` version restrictions.
  _I’d be interested to know what GHC versions you used for each Agda version! :)_
- There’s the issue that when older versions of Agda were published, support for `build-tool-depends` wasn’t as solid, and so building requires installing appropriate versions of `alex` and `happy`. I’m using the `pre-build-hook` option to try and install `alex` and `happy` for those versions, but I’m currently just guessing at the appropriate versions.
  _I’d be interested to know if the appropriate versions if `alex` and `happy` are documented somewhere! :)_

There’s a number of Windows specific errors:
- There’s the memory issues, which can be fixed with variants of `ghc-options: +RTS -M6G -RTS`.
   _I assume we can’t retroactively add to the cabal file, conditionally based on OS?_
- There’s several issues with several GHC versions. Really not an Agda issue, but several older GHC versions are broken on Windows Server 2019 due to a mismatch between the MSYS versions installed on GitHub runners and those bundled with GHC, resulting in errors building native packages.
- There’s a number of other errors which still elude me, such as [this access violation](https://github.com/wenkokke/setup-agda/actions/runs/3457729973/jobs/5771442097#step:4:5407), [this `text-icu` error](https://github.com/wenkokke/setup-agda/actions/runs/3457729973/jobs/5771442506#step:4:5291) or [this build plan resolution error](https://github.com/wenkokke/setup-agda/actions/runs/3457729973/jobs/5771442575#step:3:892) which only seems to show up on Windows.

For versions prior to 2.5.2 there’s no `stack-X.Y.Z.yaml` files, and prior to 2.4.2.2 there’s no `tested-with` field, so `setup-agda` cowardly refuses to try and build. Is there any hope for building these versions, or are the GHC versions required simply too old?

**Comment by wenkokke** [comment]
There’s several of issues for Windows. Off the top of my head:
- **memory**: fixed with variants of `ghc-options: +RTS -M6G -RTS`.
   I assume we can’t retroactively add to the cabal file, conditionally based on OS?
- **ghc**: really not an Agda issue, but several older GHC versions are broken on Windows, especially on Windows Server 2019 and the equivalent desktop version, resulting in errors building native packages.

**Comment by wenkokke** [comment]
There’s also the issue that some of the GHC versions listed in `tested-with` or are no longer easily available, e.g., 8.0.1 and other versions which aren’t the final minor version, or any version before 7.10 (and I’m having trouble with 7.10, see [this log](https://github.com/wenkokke/setup-agda/actions/runs/3451403901/jobs/5760599612#step:3:17962).)

**Comment by wenkokke** [comment]
The `setup-agda` action automatically tries to build with the latest GHC versions that is listed as `tested-with` or which have an included `stack-X.Y.Z.yaml` file, so I am curious what versions you used? When trying other versions, one frequently runs into `MonadFail` errors or issues with `base` or `template-haskell` version restrictions.

**Comment by wenkokke** [comment]
FYI there’s a `pre-build-hook` option for `setup-agda`, which I use to, e.g., patch the `stack-X.Y.Z.yaml` file or install `alex` and `happy`. So far, I’ve not managed to build 2.5.3 (trying on Ubuntu with GHC 7.10.3 and 8.0.2) but the latest error is with installing the `alex` and `happy` versions (whose version numbers I’ve copied from @omelkonian’s action).

**Comment by andreasabel** [comment]
> The `setup-agda` action automatically tries to build with the latest GHC versions that is listed as `tested-with` or which have an included `stack-X.Y.Z.yaml` file, so I am curious what versions you used?

I have used the latest GHC that the respective Agda version supports.  I am not sure the `tested-with` is so reliable and always up-to-date, but the `base < ...` bound is.  This is also the one that gets updated by Hackage revisions, e.g. https://hackage.haskell.org/package/Agda-2.6.2.2/revisions/ (Ok, here I also revised `tested-with`).

Also, I only use latest GHC minor versions: 9.0.2 8.10.7 8.8.4 8.6.5 8.4.4 8.2.2 8.0.2 7.10.3 7.8.4... Superseded minor versions can be ignored, as far as I know.  

I did use `-f enable-cluster-counting`.  And I used `cabal install` rather than `cabal v1-install`.  And I have `happy` and `alex` installed.

**Comment by wenkokke** [comment]
> Also, I only use latest GHC minor versions: 9.0.2 8.10.7 8.8.4 8.6.5 8.4.4 8.2.2 8.0.2 7.10.3 7.8.4... Superseded minor versions can be ignored, as far as I know.

I provide that as an option, but the fact that stack seems to have moved away from that (they used to use allow-newer-minor as the default for ghc-version-match, but moved to match exact) made me believe that may not always be the case. But if it works for all Agda versions, that should still be fine!

I guess I could use the `base` bound, but I’m hesitant to include another mapping file (`base` bounds to GHC versions). It might help to unify the GHC version resolution between Cabal and Stack builds, though.

Would it be possible (and not too much effort) to update the `tested-with` fields of each legacy version to the latest minor versions of each supported GHC version? Perhaps after we verify that the builds do indeed work with those versions?

**Comment by wenkokke** [comment]
I guess I could use the `base` bound, but I’m hesitant to include another mapping file (`base` bounds to GHC versions).

**Comment by wenkokke** [comment]
> And I have `happy` and `alex` installed.

I assume that means the exact versions of `alex` and `happy` don’t matter too much, or that the latest versions simply work? I’ve had some issues installing `alex` and `happy` with the older versions of GHC, but I assume those could be sorted out easily by picking different versions.

**Comment by wenkokke** [comment]
> I did use `-f enable-cluster-counting`.

Is your icu4c version is <68? I believe that circumvents a lot of the issues with text-icu, but it gets tricky to get those older versions set up and registered with pkg-config on Windows.
