### ISSUE TITLE
Experiment with pointer equality

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#6351]
Some say that, despite the name, `reallyUnsafePointerEquality` is safe if used in the pattern `reallyUnsafePointerEquality a b || a == b` (where `==` is some sort of "extensional" equality check while `reallyUnsafePointerEquality` is "intensional").

Tasks:
- [ ] experiment with pointer equality to see whether it could speed us up
- [ ] find a modular way how to make it available, e.g.
  ```haskell
   (===) :: Eq a => a -> a -> Bool
   a === b = reallyUnsafePointerEquality a b || a == b
   ```

Lifted from https://github.com/agda/agda/issues/6274#issuecomment-1315242105.

**Comment by jespercockx** [comment]
Pointer to the function in question: https://hackage.haskell.org/package/base-4.17.0.0/docs/GHC-Exts.html#v:reallyUnsafePtrEquality (it is called `reallyUnsafePtrEquality`, not `reallyUnsafePointerEquality`)

**Comment by nad** [comment]
> - [ ] find a modular way how to make it available, e.g.
>   ```haskell
>    (===) :: Eq a => a -> a -> Bool
>    a === b) = reallyUnsafePointerEquality a b || a == b
>    ```

I think you should be careful with this pattern. In particular, only use it when you know that `(==)` will return either `True` or `False`, to avoid making the result of the program depend on accidents of the representation of data in memory:
```
ghci> :set -XMagicHash
ghci> import GHC.Exts
ghci> let x === y = isTrue# (reallyUnsafePtrEquality x y) || x == y
ghci> let xs = repeat 'a' in xs === xs
True
ghci> repeat 'a' === repeat 'a'
Killed
```
(I manually killed GHCi.)

Do you plan to use `(===)` (for some type `a`) in the implementation of `(==)` (for type `a`)? In that case I think you should make sure that you get exactly the same result with `(===)` as with `(==)`, for all inputs that will occur in practice.

**Comment by jespercockx** [comment]
I think the idea is not to use `(===)` for the implementation of `Eq` for any type, but just use it directly in a few well-chosen places. The first one that comes to mind is in the syntactic equality check used in the conversion checker shortcut. Since we do not construct infinite terms, here it should be fine to use pointer equality as a shortcut.

**Comment by andreasabel** [comment]
@nad wrote:
> only use it when you know that `(==)` will return either `True` or `False`, to avoid making the result of the program depend on accidents of the representation of data in memory:
> 
> ```
> ghci> :set -XMagicHash
> ghci> import GHC.Exts
> ghci> let x === y = isTrue# (reallyUnsafePtrEquality x y) || x == y
> ghci> let xs = repeat 'a' in xs === xs
> True
> ghci> repeat 'a' === repeat 'a'
> Killed
> ```

Could you elaborate more on what is the problem here?  
Why should I worry that `t === t` gives `True` for terms `t` that have no finite normal form?  Why is it a problem that `===` is smarter than `==`?

Or saying it more abstractly: If program X gives me either a true statement, no statement, or a false statement, I would consider a program Y better if it behaves like X with the exception that it sometimes gives me a true statement when X stays silent.

**Comment by andreasabel** [comment]
> Could you elaborate more on what is the problem here?

Let me guess: You think `===` could seduce us to use it on infinite structures, and we would get away with it by chance, but then a new testcase comes along that makes Agda loop?  Feels improbable, if you ask me...
For sure, we shouldn't use `===` on things other than we use `==` on.

**Comment by nad** [comment]
> Let me guess: You think `===` could seduce us to use it on infinite structures, and we would get away with it by chance, but then a new testcase comes along that makes Agda loop?

Something like that. You wrote about "find[ing] a modular way how to make it available", and if that thing does not come with enough warnings someone might come along and start using the construction for things which it was not intended for. I think we could include `reallyUnsafe` in the name, like GHC does.

**Comment by knisht** [comment]
## A report on what I have found
First, some details about `reallyUnsafePtrEquality`:
- This function is a part of base-4.17. In base-4.16 there is only [reallyUnsafePtrEquality#](https://hackage.haskell.org/package/base-4.16.0.0/docs/GHC-Exts.html#v:reallyUnsafePtrEquality-35-), which is essentially the same, but starting from 4.17 it is levity-polymorphic. It does not concern us, since the types we are interested in are all lifted. What might concern us is the presence of possible failures of this function, according to its documentation. Well, the docs are inconsistent here. According to [ghc sources](https://gitlab.haskell.org/ghc/ghc/-/blob/master/compiler/GHC/Builtin/primops.txt.pp#L3455), it is _marked_ as failing to prevent some optimisations on it.
- GHC sources advice that the comparison might have higher rate of success if the compared objects are evaluated. So I added `seq` before invocation of the referential equality check and gained 15x more positive results. I guess `seq` won't harm us in the places where we want to apply this check, since the compared objects are becoming subject of a structural equality check  anyway, so they will be evaluated to WHNF in the pattern matching.  

### Places
Having that in mind, I analyzed all places where we can benefit from referential equality. I didn't consider simple enum-like sum types for this optimisation, because they are often compared with a constant, so the references in the arguments of `==` will be different most of the time. Also, overriding `Eq` manually for everything seems like an unnecessary complication of the code base. 
- [Agda.Termination.TermCheck#1403](https://github.com/agda/agda/blob/66e6a032017832646db026fbe73ad4e4338732de/src/full/Agda/Termination/TermCheck.hs#L1417) -- Unlikely to get any benefit. I believe it is uncommon to meet a syntax tree from a pattern somewhere outside the pattern, so I didn't even try to measure the effects of the check here.
- [Agda.TypeChecking.Abstract.equalSy](https://github.com/agda/agda/blob/66e6a032017832646db026fbe73ad4e4338732de/src/full/Agda/TypeChecking/Abstract.hs#L270) -- In fact, this might be optimised, but I collected the statistics of the referential equality successes here, and found insanely few hits.
- [Agda.TypeChecking.Conversion.compareAs](https://github.com/agda/agda/blob/66e6a032017832646db026fbe73ad4e4338732de/src/full/Agda/TypeChecking/Conversion.hs#L154) -- The conversion checker (comparison of terms), the most interesting place. I actually got some meaningful results here.
- [Agda.TypeChecking.Conversion.equalSort](https://github.com/agda/agda/blob/66e6a032017832646db026fbe73ad4e4338732de/src/full/Agda/TypeChecking/Conversion.hs#L1679) -- The conversion checker (comparison of sorts). We compare sorts a lot in the codebase, and I got some statistics here also. Interestingly, there is a complement function `leqSort`, and I didn't get any hit of referential equality there.
- [Agda.TypeChecking.Conversion.compareAtom](https://github.com/agda/agda/blob/66e6a032017832646db026fbe73ad4e4338732de/src/full/Agda/TypeChecking/Conversion.hs#L464) -- No hits. I don't know why.
- [Agda.TypeChecking.Conversion.[equalLevel, leqLevel]](https://github.com/agda/agda/blob/66e6a032017832646db026fbe73ad4e4338732de/src/full/Agda/TypeChecking/Conversion.hs#L1508) -- No hits. I don't know why.
- [Agda.TypeChecking.SyntacticEquality](https://github.com/agda/agda/blob/66e6a032017832646db026fbe73ad4e4338732de/src/full/Agda/TypeChecking/SyntacticEquality.hs#L151) -- Another interesting place. While the referential equality check might fail for two terms in general, there is still a possibility for some _subtrees_ of these terms to be referentially equal. This is actually the case, but I am struggling to interpret the number of hits in this place.

### Metrics 
I used the expression `\x y -> seq x (seq y (isTrue# (reallyUnsafePtrEquality# x y)))` in the places above.
The results below are from the type-checking of std-lib.

| Metric name               | Number of hits |
----------------------------|-----------
| Attempt to compare terms  | 977,318 |
| Referentially equal terms  | 18,071  |
| Syntactically equal terms | 439,084 |
| Referentially equal subterms in syntactic eq check| 14,465 | 
| Attempt to compare sorts | 136,180 |
| Referentially equal sorts | 5,540 |

The results below are from the type-checking of agda-categories

| Metric name               | Number of hits |
----------------------------|-----------
| Attempt to compare terms  | 2,669,994 |
| Referentially equal terms | 59,002 |
| Syntactically equal terms  | 886,858  |
| Referentially equal subterms in syntactic eq check | 47,638 |
| Attempt to compare sorts | 67,609 |
| Referentially equal sorts | 2,964 |

### Conclusion
We can see that referential equality allows us to bypass 3.9% (6.2% in agda-categories) successful syntactic checks of equality on terms. I didn't measure the time improvement, because I don't think such it can be noticed. Of course, I might try to dig up the reasons why there is no hits in the places where they are expected, but does it really make sense? I personally don't expect that we can gain a lot from referential equality, since GHC juggles heap addresses quite freely.
In fact, given that this check is instantaneous and easy to implement (and safe in case of internal terms, I believe), I think it worth using it in the codebase.
