### ISSUE TITLE
Instance candidates filtered out by type errors

### ISSUE THREAD

**Issue by omelkonian** [agda/agda#6364]
The use case is the following:
- We want to bundle up a (raw) typeclass (e.g. `Semigroup`) with a superclass containing its laws (e.g. `Semigroup-Laws`) into a single constraint `Lawful-Semigroup`, so that we don't have to write `⦃ _ : Semigroup A ⦄ ⦃ _ : Semigroup-Laws A ⦄` every time.
- Instead of creating ad-hoc records for each case, do this once and for all via `_⊗_`.

In the code below, `Lawful-Semigroup` and ` Semigroup A ⊗ Semigroup-Laws A` behave quite differently on what terms they admit. 

```agda
open import Agda.Primitive using (Level; _⊔_) renaming (Set to Type)
open import Agda.Builtin.Equality

private variable ℓ ℓ′ : Level

it : ∀ {A : Type ℓ} → ⦃ A ⦄ → A
it ⦃ x ⦄ = x

record Semigroup (A : Type ℓ) : Type ℓ where
  field _◇_ : A → A → A
open Semigroup ⦃...⦄

record Semigroup-Laws (A : Type ℓ) ⦃ _ : Semigroup A ⦄ : Type ℓ where
  field ◇-assoc : ∀ {x y z : A} → (x ◇ y) ◇ z ≡ x ◇ (y ◇ z)
open Semigroup-Laws ⦃...⦄

record _⊗_ (A : Type ℓ) (B : ⦃ A ⦄ → Type ℓ′) : Type (ℓ ⊔ ℓ′) where
  field ⦃ ↜ ⦄ : A
        ⦃ ↝ ⦄ : B
open _⊗_ ⦃...⦄
instance
  mk⊗ : ∀ {A : Type ℓ} {B : Type ℓ′} → ⦃ A ⦄ → ⦃ B ⦄ → A ⊗ B
  mk⊗ = record {}

Lawful-Semigroup : Type ℓ → Type ℓ
Lawful-Semigroup A = Semigroup A ⊗ Semigroup-Laws A

module _ {A : Type} ⦃ s : Semigroup A ⦄ ⦃ l : Semigroup-Laws A ⦄ where

  -- ** all of these work
  ✓ : Semigroup A ⊗ Semigroup-Laws A
  ✓ = it -- mk⊗ -- mk⊗ ⦃ s ⦄ ⦃ l ⦄

  -- ** the two types involved are definitionally equal :S
  _ : Lawful-Semigroup A ≡ (Semigroup A ⊗ Semigroup-Laws A)
  _ = refl

  -- ** none of these work
  ✖ : Lawful-Semigroup A
  -- ✖ = it
{-
No instance of type Lawful-Semigroup A was found in scope.
when checking that the expression it has type Lawful-Semigroup A
-}
  -- ✖ = mk⊗
{-
Cannot instantiate the metavariable _85 to solution
Semigroup-Laws A since it contains the variable x
which is not in scope of the metavariable
when checking that the expression mk⊗ has type Lawful-Semigroup A
-}
  -- ✖ = mk⊗ ⦃ s ⦄ ⦃ l ⦄
{-
s != x of type Semigroup A
when checking that the expression mk⊗ ⦃ s ⦄ ⦃ l ⦄ has type
Lawful-Semigroup A
-}
  ✖ = {!!}
--- Goal type in the above context context:
-- ∙ [C-,]         Lawful-Semigroup A
-- ∙ [C-u C-u C-,] Semigroup A ⊗ Semigroup-Laws A

  -- ** this suprisingly works!
  ✓✓ : Lawful-Semigroup A
  ✓✓ = record {}
```
So the same term (`mk⊗`) typechecks in one, but not both def.equal types. Isn't that peculiar?

---
**Agda: 2.6.2.1**
*(sorry if this has already been fixed in a more recent version)*

**Comment by andreasabel** [comment]
Interestingly, this fails uniformly for Agda 2.6.0 to 2.6.3.  Only the error messages changes, from:
```
No instance of type Semigroup A ⊗ Semigroup-Laws A was found in scope.
when checking that the expression it has type Lawful-Semigroup A
```
to (from 2.6.2):
```
No instance of type Lawful-Semigroup A was found in scope.
when checking that the expression it has type Lawful-Semigroup A
```
I don't think we have `TypeSynonymInstances` or the like, so I'd guess this is a bug.

**Comment by jespercockx** [comment]
Yes, definitely a bug.

**Comment by jespercockx** [comment]
Ah actually this is NOT a bug, just a really confusing twist in the semantics of instance search. Here is a more explicitly annotated version of the relevant part of @omelkonian 's code:
```agda
module _ {A : Type} ⦃ s : Semigroup A ⦄ ⦃ l : Semigroup-Laws A ⦄ where

  ✓ : Semigroup A ⊗ (λ {{s'}} → Semigroup-Laws A {{s}})
  ✓ = mk⊗ -- mk⊗ ⦃ s ⦄ ⦃ l ⦄

  _ : Lawful-Semigroup A ≡ (Semigroup A ⊗ (λ {{s'}} → Semigroup-Laws A {{s'}}))
  _ = refl
```
Note that the two types are actually NOT definitionally equal (!): the first one uses the instance `s` from the module telescope, while the second one uses the *locally bound* instance `s'`. The two instances `s` and `s'` are not definitionally equal, hence the types `Semigroup A ⊗ Semigroup-Laws A` and `Lawful-Semigroup A` are not definitionally equal, hence they behave differently wrt to instance search.

Now you may ask, how in the world can we have two different instances in scope but Agda not complaining about that? Surely *that* must be the bug? Not really, since the current semantics of instance search allows instance candidates to be filtered out by type errors. In particular, a type error in the **body** of the function may rule out an instance candidate in the **type signature** of that function. Observe: if we omit the body of `✓` as follows:
```agda
  ✓ : Semigroup A ⊗ (λ {{s'}} → Semigroup-Laws A)
  ✓ = {!!}
```
then we suddenly get an unsolved instance in the type:
```
———— Errors ————————————————————————————————————————————————
Failed to solve the following constraints:
  Resolve instance argument _67 : Semigroup A
  Candidates
    s' : Semigroup A
    s : Semigroup A
    (stuck)
```
The only reason why Agda manages to filter out the first candidate is because the solution found by instance search for the *body* of the function only typechecks with the second candidate but not with the first.

Similarly, if we leave out the body of the equality proof:
```agda
  _ : Lawful-Semigroup A ≡ Semigroup A ⊗ (λ {{s'}} → Semigroup-Laws A)
  _ = {!!}
```
then Agda again complains about not being able to choose an instance in the type:
```
Failed to solve the following constraints:
  Resolve instance argument _87 : Semigroup A
  Candidates
    s' : Semigroup A
    s : Semigroup A
    (stuck)
```
but the body `refl` only type-checks with the *first* candidate `s'` so that is the one we pick.

So is there a bug according to the current semantics of instance search? No, technically speaking not. But do I consider this good language design? Well, hell no.

I suppose I should thank you, since I've found the filtering of ill-typed instances semantics of instance search always quite insane, so this gives me a good reason to finally cut it down to size.

**Comment by jespercockx** [comment]
The most gentle way to solve this would be to freeze all instance metas after we finish typechecking a signature (and before we check the body). That would be sufficient to avoid "leaking" information from the body into the signature. More generally, I think I would prefer if **all** metas were frozen after typechecking a signature since a similar problem might pop up for regular metas. But I seem to remember proposing this before and losing the argument. Perhaps @andreasabel or @nad has changed their opinion since then.

**Comment by jespercockx** [comment]
Another way to fix this would to restrict instance search to only filter out instances based on their type and not on whether they produce a type error when unified with the hole. This would prevent some of the current use cases of instance search, but (1) this would make instance search much more predictable, (2) this would open up more opportunities for optimization of instance search and (3) the current behaviour could still be replicated with a macro.

**Comment by plt-amy** [comment]
It'd also improve the error messages for when instance search fails _because_ of a type error — they'd no longer get buried deep in a list of rejected instances. This happens quite often to me since I use `do` notation a bunch.

**Comment by nad** [comment]
> More generally, I think I would prefer if **all** metas were frozen after typechecking a signature since a similar problem might pop up for regular metas.

Recently I've also been thinking along those lines. For instance, if we were to implement something like Haddock for Agda (#5541), then one might want to ensure that the meaning of the presented type signatures do not depend on details of the implementation.

However, in some cases one might want to elide parts or all of the type signature, especially for local definitions. Perhaps we could add a flag that turns on freezing for top-level definitions, and see how much code breaks when that flag is used.

One thing to consider is how mutually recursive definitions should be treated. Should we freeze after every single type signature?

**Comment by jespercockx** [comment]
> One thing to consider is how mutually recursive definitions should be treated. Should we freeze after every single type signature?

Yeah, this is also a question I had. I think we should look at what we are currently doing for `abstract` blocks, where we already have the restriction that the body of a function cannot solve any metas coming from its signature.

**Comment by anuyts** [comment]
What about highlighting theorems whose meaning depends on their proof? These are generally fine locally, but may mislead human readers (e.g. reviewers of a paper with formalization).

**Comment by jespercockx** [comment]
What are these "theorems" and "proofs" you are talking about? I use Agda to write types and programs :)

**Comment by nad** [comment]
> More generally, I think I would prefer if **all** metas were frozen after typechecking a signature since a similar problem might pop up for regular metas.

I think it makes sense to open a new issue for this.
