### ISSUE TITLE
Refine does not work for overloaded record constructors

### ISSUE THREAD

**Issue by szumixie** [agda/agda#6374]
In Emacs mode for Agda 2.6.2 and 2.6.3, the refine command does not work for named record constructors in an empty hole when another constructor with the same name is in scope:
```agda
record A : Set where
  constructor c

record B : Set where
  constructor c

a : A
a = {!!} -- C-c C-r does not work
```
It throws the following error:
```
Not in scope:
  Issue6374.c
    (did you mean 'c'?)
when scope checking Issue6374.c
```

**Comment by plt-amy** [comment]
Alright, so this is _really_ funny. The way `refine` works is by first calling `introTactic` to generate a `String` candidate for the new contents of the hole; If the hole's type is a record with a name constructor, this will end up in `introData`.

Now, `introData` knows that **data** constructor names may be ambiguous, so it tries to generate a string with unambiguous constructor names. This is because the returned `String` will later get parsed and elaborated, so we want to make sure that it will actually be a constructor of the right data type. But there's no way to unambiguously refer to a **record** constructor name (this is #4189, #4219, etc)! So this step fails: that's your bug.

This bit is mostly just to sate my curiosity (and it's where the funny lies, to me): if `introData` generates an unambiguous constructor name, why does calling refine in the following hole:

```agda
data C : Set where
  c : C

data D : Set where
  c : D

a : C
a = ?
```

generate `a = c`? That's because the generated string goes through a round-trip of parsing → scope-checking → pretty-printing --- but the way abstract expressions are printed (for interaction results, at least) is to first turn them into a concrete expression, which goes through the same "look up concrete name" procedure, except this time allowing ambiguity.

Anyway, fix incoming: since elaboration will happen against the expected type of the goal there isn't really any reason to use an _unambiguous_ name.
