### ISSUE TITLE
Subject reduction problem related to projections with non-erased parameter arguments

### ISSUE THREAD

**Issue by nad** [agda/agda#6406]
The following code is not accepted by Agda 2.6.2.2:
```agda
record R (A : Set) : Set where
  field
    x : A

works : (@0 A : Set) → R A → A
works _ record{ x = x } = x

-- The normal form of works is λ (@0 A) → R.x.

fails : (@0 A : Set) → R A → A
fails = λ (@0 A) → R.x
```
Agda refuses to instantiate the `A` argument of `R.x` with the erased variable `A`.

The code above is accepted by the current Agda 2.6.3 release candidate. However, it is not accepted by the variant of Agda that you get from (the current state of) PR #6405.

**Comment by nad** [comment]
How can this be fixed without making the parameter erased in the type of the projection? Perhaps one can reject the definition of `works`. However, then the definition of [`to`](https://github.com/agda/agda/pull/6399#issuecomment-1346368638) that I posted before would presumably also be rejected.

**Comment by nad** [comment]
The following code is accepted by Agda 2.6.2.2:
```agda
data D (A : Set) : Set where
  c : A → D A

works : (@0 A : Set) → A → D A
works _ x = c x
```
However, the following code is rejected:
```agda
fails : (@0 A : Set) → A → D A
fails A x = c {A = A} x
```
Above `works` is accepted because the argument `A` of `c` is not present in the internal syntax. I thought that projections were treated in the same way as constructors, but apparently that is not the case. Note that the following code fails:
```agda
record R (A : Set) : Set where
  field
    x : A

open R

fails : (@0 A : Set) → R A → A
fails = λ (@0 A) r → x r
```
Perhaps the problem can be fixed by treating projections in the same way as constructors.

**Comment by jespercockx** [comment]
This seems like some weird interaction between eta equality and pattern matching on records: the normal form of `works` (in the OP) should be `λ (@0 A) y → R.x y`, not `λ (@0 A) → R.x`. It seems that Agda performs an eta contraction here that is ill-typed in the absence of subtyping for `@0`.

**Comment by jespercockx** [comment]
See https://github.com/agda/agda/issues/2464 for the analogous problem for irrelevance, and https://github.com/agda/agda/issues/2732 for more general reasons to get rid of eta contraction.

**Comment by nad** [comment]
> This seems like some weird interaction between eta equality and pattern matching on records: the normal form of `works` (in the OP) should be `λ (@0 A) y → R.x y`, not `λ (@0 A) → R.x`.

As I noted above the expanded variant is also rejected.

**Comment by jespercockx** [comment]
Ah sorry, I missed that. Currently projection have a dual status in the internal syntax: their canonical representation is as an elimination, which does not mention the parameters and is hence treated in the same way as constructors. However, each projection also has a representation as a *definition* which does take the parameters as arguments, but reduces to the elimination form (these definitions are also used for representing unapplied projections). What I suspect is going on here is that the syntax still contains the unreduced definition form which mentions the parameter, and is hence rejected when the parameter is not erased.

Perhaps one way to solve this would be to do more eager inlining of these definitions to their canonical form which does not mention the parameters.

**Comment by nad** [comment]
OK. There seems to be (at least) two problems:
* The main problem with subject reduction can perhaps be fixed by turning off η-reduction for projections. (Will this break anything?)
* If η-reduction is turned off we might still have the problem that Agda prints "projection definition fully applied to explicit argument" and "argument with projection eliminator" in the same way. For the example above this might mean that something that is well-typed is no longer well-typed after the round-trip via concrete syntax. I think this problem is less serious than the other one, because it is easy to get Agda to print something that does not type-check. However, perhaps one can fix the problem by ensuring that "projection definition fully applied to explicit argument" and "argument with projection eliminator" are treated in the same way internally, so that it does not matter how the code is parsed.

**Comment by jespercockx** [comment]
Looking at the code in `TypeChecking.Rules.Application`, it seems that while ambiguous projections are treated specially, *unambiguous* projections are using the general `checkHeadApplication` logic. And indeed, making the projection `x` ambiguous makes the example type check:
```agda
record R (A : Set) : Set where
  field
    x : A

open R

record R' (A : Set) : Set where
  field
    x : A

open R'

-- this works now!
works : (@0 A : Set) → R A → A
works = λ (@0 A) r → x r
```
(this works using the version of Agda from https://github.com/agda/agda/pull/6405). So perhaps we should change the implementation of `checkUnambiguousProjectionApplication` to rely on `checkProjApp` rather than `checkHeadApplication`.

**Comment by nad** [comment]
I tried to turn off η-contraction entirely, and the normal form of `works` from the OP is still `λ (@0 A) → R.x`.

**Comment by jespercockx** [comment]
I'm looking deeper into the code for how projections are handled and you may consider me HORRIFIED that there is in fact 0% code or even logic in common with how constructors are handled. I think a big refactoring here is in order, but for now I'll see what I can do to fix the concrete issue with unambiguous projections above.

**Comment by jespercockx** [comment]
Unfortunately it's not easy to fix the issue without introducing major changes to the code. The problem is that while there is a special handling of ambiguous projections in `inferOrCheckProjApp` that extracts the parameters directly from the type of the principal argument (and thus does not create any metas), this is not done in the code for *unambiguous* projections in `checkUnambiguousProjectionApplication`, which simply relies on the generic `checkHeadApplication` function. This means that the typechecker will create metavariables for the parameters of unambiguous projections, and these metavariables will use the modality from the type of the projection. So if we change Agda back like how it was in 2.6.2 and do not mark these parameters as erased, these metas will not have an erasure modality and hence will not be solvable with erased solutions, even though they *do not even appear in the final elaborated term*.

At first, I thought this would be easy to solve by making `checkUnambiguousProjectionApplication` call `checkProjApp` instead of `checkHeadApplication`, but this turns out to cause a lot of problems since Agda is (necessarily) much more conservative in dealing with overloaded projections than non-overloaded ones. In particular, it causes errors of the kind "could not resolve overloaded projection" even though there is only a single disambiguation possible. So this is not a viable solution.

I then tried to instead copy the logic from `inferOrCheckProjApp` and `inferOrCheckProjAppToKnownPrincipalArg` and cut out all the parts that deal with disambiguation, putting the result into `checkUnambiguousProjectionApplication`. Due to the complexity of these two functions (over 200 lines of code), this ended up being quite involved and I must have made some mistakes in the process, as the result ended up with some incomprehensible errors when checking the builtin Agda modules. I could try to put more time into this but it does not feel terribly promising.

The option that I finally managed to get to work is to instead add special handling of (unambiguous) projections to `checkHeadApplication` and `inferApplication` to insert the implicit parameters in erased mode (even when the type of the projection does not have erasure annotations on them). I'll add my fix to the PR in https://github.com/agda/agda/pull/6405.

What I now think would be the *proper* solution is to change the code for dealing with overloaded projections completely to be more in line with the code for overloaded constructors: instead of having two totally separate code paths for ambiguous and non-ambiguous projections, there really should be two separate functions `disambiguateProjection` (analogous to `disambiguateConstructor`) and `checkProjectionApplication` (analogous to `checkConstructorApplication`), where the second one is called directly for non-ambiguous projections. However, this would involve a major refactoring which I currently do not have the time for (and would also not be desirable to do just before the release).

**Comment by jespercockx** [comment]
> I tried to turn off η-contraction entirely, and the normal form of works from the OP is still `λ (@0 A) → R.x`.

The remaining problem (the ill-typed eta-contraction from `λ (@0 A) r → R.x r` to `λ (@0 A) → R.x`) is caused by the following piece of code:

https://github.com/agda/agda/blob/3da43a3e34ecd2256f5bde7d7d4ec74342f06cef/src/full/Agda/Syntax/Internal.hs#L1050-L1052

**Comment by nad** [comment]
Agda 2.6.2.2 has the problem documented in the OP. Perhaps it makes sense to release Agda 2.6.3 without a fix for this problem, and instead focus on a proper fix after the release. What do you think?

**Comment by jespercockx** [comment]
I tried to look further into the problem with the heap exhaustion in the cubical library, but unfortunately I did not make any real progress. So I agree with your proposal to leave this issue unfixed for the release, and merge your original version of PR #6405. We could consider still including the second part of my fix for this issue (https://github.com/agda/agda/commit/8a0346be3af017187f90d8024b2c0e2a51a57148), which didn't cause any problems when I tried it out in isolation. I'll update the PR.

**Comment by nad** [comment]
> > I tried to turn off η-contraction entirely, and the normal form of works from the OP is still `λ (@0 A) → R.x`.
> 
> The remaining problem (the ill-typed eta-contraction from `λ (@0 A) r → R.x r` to `λ (@0 A) → R.x`) is caused by the following piece of code:
> 
> https://github.com/agda/agda/blob/3da43a3e34ecd2256f5bde7d7d4ec74342f06cef/src/full/Agda/Syntax/Internal.hs#L1050-L1052

I only edited `Agda.TypeChecking.EtaContract`. Perhaps it would make sense to document that the implementation of η-contraction is spread out over several files.

**Comment by nad** [comment]
> I only edited `Agda.TypeChecking.EtaContract`. Perhaps it would make sense to document that the implementation of η-contraction is spread out over several files.

Now I saw that you removed the η-contraction in `hasElims`.

**Comment by jespercockx** [comment]
I don't have time to look into this before the release, so bumping to 2.6.5 (unless someone else wants to pick it up).
