### ISSUE TITLE
Miscompilation of nested patterns in erased fields

### ISSUE THREAD

**Issue by Lysxia** [agda/agda#6413]
The following program compiles to Haskell code that tries to pattern-match on `erased`. Reproducible on 2.6.2.2 and on master.

```agda
module Main where

data T : Set where
  tt : T
  ff : T

record _×_ (A B : Set) : Set where
  constructor _,_
  field
    fst : A
    snd : B

infixr 4 _×_
infixr 4 _,_

record E : Set where
  constructor e
  field
    @0 une : T × T × T

g : E → T
g (e (c , a , b)) = tt
```

```
-- Main.g
d_g_36 :: T_E_28 -> T_T_2
d_g_36 ~v0 = du_g_36
du_g_36 :: T_T_2
du_g_36
  = let v0 = erased in
    case coe v0 of
      C__'44'__26 v1 v2 -> coe seq (coe v2) (coe C_tt_4)
      _ -> MAlonzo.RTE.mazUnreachableError
```

**Comment by nad** [comment]
Here is a variant of the code:
```agda
module Main where

open import Agda.Builtin.IO
open import Agda.Builtin.Unit

postulate
  print : ⊤ → IO ⊤

{-# COMPILE GHC print = print #-}

data D (A : Set) : Set where
  c : ⊤ → A → D A

f : @0 D (D ⊤) → ⊤
f (c _ (c _ _)) = tt

main : IO ⊤
main = print (f (c tt (c tt tt)))
```
This code triggers a segfault for me (using `--compile` and GHC 9.4.3, but not if I also include `--ghc-strict` or `--ghc-strict-data`).

**Comment by nad** [comment]
I did not find any code that is intended to remove all matches on erased arguments. Consider the following variant of the code above:
```agda
module Main where

open import Agda.Builtin.IO
open import Agda.Builtin.Unit

postulate
  print : ⊤ → IO ⊤

{-# COMPILE GHC print = print #-}

data D (A : Set) : Set where
  c : ⊤ → A → D A

f : @0 (D ⊤) → ⊤
f (c _ _) = tt

main : IO ⊤
main = print (f (c tt tt))
```
If I compile this program using the GHC backend and run it I get the following output:
```
()
```
However, the code is compiled in the following way:
```haskell
-- Main.print
d_print_2 ::
  MAlonzo.Code.Agda.Builtin.Unit.T_'8868'_6 ->
  MAlonzo.Code.Agda.Builtin.IO.T_IO_8
    () MAlonzo.Code.Agda.Builtin.Unit.T_'8868'_6
d_print_2 = print
-- Main.D
d_D_6 a0 = ()
data T_D_6
  = C_c_10 MAlonzo.Code.Agda.Builtin.Unit.T_'8868'_6 AgdaAny
-- Main.f
d_f_12 :: T_D_6 -> MAlonzo.Code.Agda.Builtin.Unit.T_'8868'_6
d_f_12 v0
  = coe seq (coe v0) (coe MAlonzo.Code.Agda.Builtin.Unit.C_tt_8)
main = coe d_main_14
-- Main.main
d_main_14 ::
  MAlonzo.Code.Agda.Builtin.IO.T_IO_8
    AgdaAny MAlonzo.Code.Agda.Builtin.Unit.T_'8868'_6
d_main_14 = coe d_print_2 (d_f_12 erased)
```
It appears as if `d_f_12` should be strict in its argument, but the program does not crash. I tried to remove every occurrence of `coe` from the body of `d_f_12`, and the program still did not crash (even when I used the GHC option `-fpedantic-bottoms`). However, when I replaced `erased` with `undefined` in `d_main_14` (and left everything else unchanged), then the program did crash. So, why does the code work when `erased` is used? Note that the match in `f` is replaced with a use of `seq` in `d_f_12`. Furthermore `erased` is defined in the following way:

https://github.com/agda/agda/blob/39cc3079c6b4ef46f64868c7146fd7bc3aa4ef23/src/data/MAlonzo/src/MAlonzo/RTE.hs#L32-L33

I guess that GHC's implementation of the polymorphic `seq` primitive treats `erased` as non-bottom. (This makes sense, because a lambda abstraction is not equal to bottom.)

This makes me believe that compilation of functions with erased arguments has only worked by accident.

**Comment by nad** [comment]
The treeless syntax contains information about matches on erased arguments:

https://github.com/agda/agda/blob/39cc3079c6b4ef46f64868c7146fd7bc3aa4ef23/src/full/Agda/Syntax/Treeless.hs#L196-L205

As can be seen that information is only present for data types, not literals. Is it possible to have an erased match on a literal? How is the following code compiled?
```agda
open import Agda.Builtin.Equality
open import Agda.Builtin.Nat

f : (@0 m : Nat) (n : Nat) → m ≡ n → Nat
f 0 .0 refl = 0
f _ _  _    = 0
```
With the flag `-vtreeless:100` I obtained the following output:
```agda
  λ a _ _ →
    let b = 0 in
    case a of
      0 → 0
      _ → b
```
It thus appears as if treeless code can contain erased matches on literals. Perhaps it makes sense to include this information in the treeless syntax.

The following code in `Agda.Compiler.Treeless.Erase` sometimes removes case expressions entirely, and sometimes replaces a case expression with its body:

https://github.com/agda/agda/blob/39cc3079c6b4ef46f64868c7146fd7bc3aa4ef23/src/full/Agda/Compiler/Treeless/Erase.hs#L112-L116

https://github.com/agda/agda/blob/39cc3079c6b4ef46f64868c7146fd7bc3aa4ef23/src/full/Agda/Compiler/Treeless/Erase.hs#L137-L149

One could perhaps modify this code so that if a case expression cannot be removed entirely, but the match is on an erased argument, then the match is removed but the body retained.

The function `eraseTerms` also uses `usedArguments`:

https://github.com/agda/agda/blob/39cc3079c6b4ef46f64868c7146fd7bc3aa4ef23/src/full/Agda/Compiler/Treeless/Erase.hs#L70-L71

I noticed that the first argument of `TCase` is unconditionally treated as used:

https://github.com/agda/agda/blob/39cc3079c6b4ef46f64868c7146fd7bc3aa4ef23/src/full/Agda/Compiler/Treeless/Unused.hs#L69

Perhaps it would make sense to not do this for matches on erased arguments.
