### ISSUE TITLE
"with _ in eq" does not work for cubical

### ISSUE THREAD

**Issue by xekoukou** [agda/agda#6426]
```agda
{-# OPTIONS --cubical #-}

module test where

open import Cubical.Foundations.Prelude

postulate
  g : ∀{A : Type} → A → A

f : ∀{A : Type} → A → A
f a with (g a) in eq1
... | r = ?

```

returns 

```
No binding for builtin thing REFL, use {-# BUILTIN REFL name #-} to
bind it to 'name'
when checking that the clause
f a with eq1 : g a
... | r = ?
has type {A : Type} → A → A

```

**Comment by gallais** [comment]
Is it just a matter of importing `Agda.Builtin.Equality`?

**Comment by xekoukou** [comment]
Shouldn't it work with Path equality? The builtin equality is not used in cubical.

**Comment by andreasabel** [comment]
@xekoukou wrote:
> Shouldn't it work with Path equality? The builtin equality is not used in cubical.

Isn't path equality very different, in the sense that you cannot match against `refl` there?  (Not very sure, so I am asking.)

How would you translate this piece of code into something that does not use `with` nor matching against `refl`?
```agda
f a with (g a) in eq1
... | r = ?
```
Looking for a translation might help clarifying your question whether it should work with path equality.

**Comment by xekoukou** [comment]
Here is an example :

```agda

{-# OPTIONS --cubical #-}

module test where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Bool


postulate
  g : Bool → Bool


e : Bool → Bool
e a = l1 (g a) module e` where
  l1 : Bool → Bool
  l1 false = l2 (g a) module e`` where
    l2 : Bool → Bool
    l2 false = g a
    l2 true = g a
  l1 true = g a


f : (a : Bool) → e a ≡ g a
f a = l1 (g a) refl where
  l1 : ∀ w → (w ≡ g a) → e`.l1 a w ≡ w
  l1 false eq = J (λ y x → e`.e``.l2 a y ≡ false) (sym eq) eq
  l1 true eq = sym eq
```

**Comment by andreasabel** [comment]
Thanks, @xekoukou!  So to make this work with cubical, a new translation would have to be developed that uses `J` rather than matching on `refl`.  Or, to make it work uniformly for cubical and non-cubical, the current translation has to be changed.

All this is implementing a _new component_, not just a minor bugfix.  There needs to be a proposal with arguments that it will work in the general case.

**Comment by xekoukou** [comment]
Not a problem, the inspect idiom still works.

**Comment by plt-amy** [comment]
> Isn't path equality very different, in the sense that you cannot match against refl there? (Not very sure, so I am asking.)

As an aside, it'd be totally possible to invent a case tree for matching on `refl : Path A x y` (like we do for e.g. `conid` or `transpX`) --- most of the code for inductive families that currently exists could be reused. I'm not too fond of the idea, though, because it'd be _impossible_ to make this into an exact split (unlike the clauses we invent now).

Since you can (≥2.6.3) use the builtin equality type with Cubical Agda, I'd tend towards keeping paths (computes by type; can use J if desired; **no pattern matching**) and identities (computes on refl; hard to use with hcomp/transp; **can be matched on**) very clearly delineated.

**Comment by xekoukou** [comment]
Let me point out that those are two different issues. We do not have to case split on Path for this feature.

This is just sugar for the inspect idiom. After that, we can simply use J.

On the secondary issue, though, it would be really nice if we had an automated way of using J, having agda smart enough to deduce the "P"  of J , and hide it from view. (Maybe with a tactic?)

**Comment by gallais** [comment]
The inspect idiom (unlike `rewrite`) does not match on `refl`, it only passes `refl` as an
argument to the auxiliary function declared using `with`. So using path equality rather
than propositional equality should be doable by changing:

https://github.com/agda/agda/blob/bd27ae8c1acd9c0f2e41135a550edb9537c43ed2/src/full/Agda/TypeChecking/Abstract.hs#L62

to, in a cubical context, lookup the name of path equality rather than prop equality, and

https://github.com/agda/agda/blob/bd27ae8c1acd9c0f2e41135a550edb9537c43ed2/src/full/Agda/TypeChecking/With.hs#L188

to lookup the name of the path refl proof rather than the prop refl constructor.

**Comment by nad** [comment]
Are you suggesting that the discussed feature should use different equality types depending on whether (Erased) Cubical Agda is used or not? I can imagine that this could lead to problems: Someone might implement a function using the feature in a module that uses `--cubical-compatible`, and then someone else might try to prove something about the function in a module that uses `--cubical`. If the feature behaves differently it might be hard to express the proof.

**Comment by gallais** [comment]
Isn't this exactly what the OP was asking for?

**Comment by nad** [comment]
I'm not convinced that this is a good idea.

**Comment by plt-amy** [comment]
Ah, now I understand that my first comment was more tangential than I first assumed; apologies, I mistakenly assumed `with _ in _` relied on matching against the identity somehow.

I'm with @nad in this one.. but for slightly different reasons: Cubical Agda has more than one "identity type", and each is applicable in different situations, including [BUILTIN EQUALITY](https://github.com/agda/cubical/blob/master/Cubical/Data/Equality.agda#L44)!

This isn't just a theoretical point: I do actually make use of paths _and_ the inductive identity type both in the 1Lab. Rather than falling back to (or only allowing paths in `--cubical-agda`), I think a better implementation would allow `with ... in ...` to be used with an arbitrary reflexive relation, specified at each use site, keeping `BUILTIN EQUALITY`'s refl as the default to avoid a bikeshed.

**Comment by nad** [comment]
> This isn't just a theoretical point: I do actually make use of paths _and_ the inductive identity type both in the 1Lab.

I use these types as well as `Agda.Builtin.Cubical.Id.Id` in one library.

**Comment by UlfNorell** [comment]
I'm reading the discussion as concluding that we should not change anything here, so closing the issue. Reopen with a concrete action plan if that's not the case.
