### ISSUE TITLE
Remove user manuals for release candidates

### ISSUE THREAD

**Issue by nad** [agda/agda#6445]
Currently Read the Docs lists user manuals for "v2.6.2.2.20230105", "v2.6.2.2.20221128" and "v2.6.2.2.20221106". I think we should remove these manuals.

**Comment by asr** [comment]
I remove the user manuals of the release candidates after the final release.

**Comment by nad** [comment]
I thought that these user manuals were related to Agda 2.6.2.2. (I could have paid more attention to the dates.) Why do the release candidates for Agda 2.6.3 don't use version "numbers" like, say, 2.6.3-rc1?

**Comment by asr** [comment]
> Why do the release candidates for Agda 2.6.3 don't use version "numbers" like, say, 2.6.3-rc1?

Just because I use the same approach used for the release candidates of GHC (I don't know if `2.6.3-rc1` is a valid version number).

**Comment by andreasabel** [comment]
> I don't know if `2.6.3-rc1` is a valid version number

I used to be in ancient times, but now it is not valid.

However, I also thought our RC versioning is slightly confusing.  E.g. `2.6.2.2.20230105` could also mean this is a RC for `2.6.2.3`.

If version numbers were lists of integers rather than naturals, there would be no ambiguity as one could have `x.y.z.-1.date` as a RC  for `x.y.z`.

I think we have discussed this problem on and off in the past without satisfactory solution.  The only systematic approach was to only use odd version numbers (`2.any.odd[.odd]`) so that the even ones can be used for RCs.  We did this in `2.5.1.1` but then immediately dropped this solution in the next release `2.5.2`.

I think `stack` uses the odd-only versioning scheme.

Switching to odd-only would mean that now
- `2.6.4` is a dev version
- `2.6.4.date` could be release candidates for next major version `2.6.5`
- `2.6.5.0.date` could be release candidates for `2.6.5.1`
- subsequent minor releases would be `2.6.5.1`, `2.6.5.3` etc
- next dev version would be `2.6.6` etc.

**Comment by asr** [comment]
> I think we have discussed this problem on and off in the past without satisfactory solution. The only systematic approach was to only use odd version numbers (`2.any.odd[.odd]`) so that the even ones can be used for RCs. We did this in `2.5.1.1` but then immediately dropped this solution in the next release `2.5.2`.
> 
> Switching to odd-only would mean that now
> 
>     * `2.6.4` is a dev version
> 
>     * `2.6.4.date` could be release candidates for next major version `2.6.5`
> 
>     * `2.6.5.0.date` could be release candidates for `2.6.5.1`
> 
>     * subsequent minor releases would be `2.6.5.1`, `2.6.5.3` etc
> 
>     * next dev version would be `2.6.6` etc.

LGTM. I'll follow this approach for next releases.
