### ISSUE TITLE
Definition is suddenly in Setω when redefining Set and using levelOfType

### ISSUE THREAD

**Issue by EDT4** [agda/agda#6446]
I tried a recent commit of Agda:

```
Agda version 2.6.4-71a6396
```

and the following file does not type check:

```agda
open import Agda.Primitive

Seti : (ℓ : Level) → Set(lsuc ℓ)
Seti ℓ = Set ℓ

lvl : ∀{ℓ} → Seti ℓ → Level
lvl{ℓ} _ = ℓ

-- type : {T : Set} → T → Set(lzero) -- Works
-- type : {T : Set} → T → Seti(lzero) -- Works
-- type : {T : Set} → T → Set(lvl T) -- Works
type : {T : Set} → T → Seti(lvl T) -- Does not work (Setω is not less or equal than Set when checking the definition of R)
type{T} _ = T

R : {T : Set} → (P : T → Set) → (∀ x → P x) → Set
R P p = ∀ x → type(p x)
```

It works on a previous version I have on my system: `Agda version 2.6.2-caeadac`.

**Comment by andreasabel** [comment]
Fails also with 2.6.3-RC3, so we need to investigate...

**Comment by andreasabel** [comment]
Bisect says: 931edcc11e0d1bfb8bc48678993ed4cc9df4cf44 is the first bad commit
> Date:   Wed Oct 12 18:58:47 2022 +0200
> [ fix #5894 ] Compute proper blocking information when reducing a sort

@jespercockx Do you have time to investigate this?  We should hold 2.6.3 until we get a clear picture of our options here.

**Comment by jespercockx** [comment]
Here is a minimized example:
```agda
open import Agda.Primitive

Seti : (ℓ : Level) → Set (lsuc ℓ)
Seti ℓ = Set ℓ

lvl : Set → Level
lvl _ = lzero

type : (T : Set) → Seti (lvl T)
type T = T

R : Set₁
R = (X : Set) → type X
```
This gives the error:
```
Setω != Set₁
when checking that the expression (X : Set) → type X has type Set₁
```
but changing the return type of `type` to `Set (level T)` makes the file succeed.

I wonder whether this has something to do with https://github.com/agda/agda/issues/5810

**Comment by jespercockx** [comment]
Slightly further reduced example:
```agda
open import Agda.Primitive

Seti : (ℓ : Level) → Set (lsuc ℓ)
Seti ℓ = Set ℓ

lvl : Set → Level
lvl _ = lzero

ty : Set₁
ty = (X : Set) → Seti (lvl X)
```
It seems that normally Agda is smart enough to reduce the level argument `lvl X` when computing the sort of the pi type `(X : Set) -> Set (lvl X)`, but replacing `Set` by `Seti` is enough to confuse Agda.

**Comment by jespercockx** [comment]
Ok, so this *is* just #5810: the type `(X : Set) → Seti (lvl X)` is given sort `Setω` since the level of the codomain is `Set (lsuc (lvl X))`, which depends on the variable `X`. However, it reduces to  `(X : Set) → Set`, which has sort `Set1`. We can see the connection to #5810 even more clearly when we make `lvl` into an argument to `ty`:
```agda
open import Agda.Primitive

Seti : (ℓ : Level) → Set (lsuc ℓ)
Seti ℓ = Set ℓ

lvl0 : Set → Level
lvl0 _ = lzero

ty : (lvl : Set → Level) → Setω
ty lvl = (X : Set) → Seti (lvl X)

ty0 : Setω
ty0 = ty lvl0
```
In this version it is clear that the return type of `ty` *must* be `Setω`, since the sort of the codomain depends on its input in an unknown way. Hence also `ty0` is in `Setω`. But `ty0` normalizes to `(X : Set) → Set`, which definitely does not have type `Setω`!

The remaining question is whether there is anything that we can do to fix this particular issue without requiring a full fix of #5810. One thing that we could do is to *normalise* the codomain of a `piSort` in order to get rid of as many spurious dependencies as possible. I don't think doing more normalisation is very desirable, but in the case of sorts they (hopefully) do not get too large, and it would only be a stopgap measure until there is a proper fix of #5810. So I'll see if I can implement it and if it fixes the issue.

**Comment by jespercockx** [comment]
I have made a PR with a fix. However, I am feeling uncertain about the possible negative performance implications of this extra normalization step, so I'm not sure if we should include it for 2.6.3.

**Comment by nad** [comment]
> However, I am feeling uncertain about the possible negative performance implications of this extra normalization step

Me too.

**Comment by jespercockx** [comment]
Looking closer at my commit that broke this test case, I think I found which change exactly caused this regression: the `reduce` case for `Set l` used to reduce the level argument, but this was no longer needed after my refactoring (or so I thought). This was technically correct, however I didn't take into account #5810, and by removing the (seemingly unneeded) reduction I accidentally made it trigger in more circumstances. If I add back in the removed `reduce`, both the example in the OP and my minimized version pass. So I'll make another PR with this less invasive fix.

**Comment by jespercockx** [comment]
I'll cherry-pick the fix onto the release branch.

EDIT: done.

**Comment by nad** [comment]
Does this change affect the standard library benchmark? In that case we should perhaps revise the 2.6.3 release notes.

**Comment by jespercockx** [comment]
It shouldn't, but perhaps it is not a bad idea to check to make sure.
