### ISSUE TITLE
Ignore Unicode byte order mark

### ISSUE THREAD

**Issue by selinger** [agda/agda#6524]
Issue: When viewing an Agda file in a web browser, many browsers consider the Agda file to be a text file and display characters with the wrong text encoding (e.g.: Latin1 instead of UTF-8). 

Since the file has no metadata (unlike, say, HTML), the usual way to indicate that a plain text file is UTF-8 is to include the byte order mark (https://en.wikipedia.org/wiki/Byte_order_mark) as the first character in the file. In UTF-8, the byte order mark takes the form EF BB BF. However, while this makes the browser happy, it causes a syntax error in Agda: Agda will say that a non-printable character was encountered.

Proposed solutions: enhance the Agda lexer to (1) ignore the byte order mark when it is the first character in a file, or alternatively, (2) ignore byte order marks anywhere in the file, or alternatively, (3) treat them as white space.

This would enable the creation of files that can be both understood by Agda and correctly displayed by software that is not Agda-aware, such as web browers.

**Comment by andreasabel** [comment]
@selinger: Is this common procedure in handling of text files?  I.e., do editors (like emacs) write the BOM in new files?

**Comment by selinger** [comment]
@andreasabel: Emacs does not write the BOM by default, but it correctly handles the BOM on files that it opens, and it preserves it when writing these files. More precisely, Emacs has two different coding systems called utf-8-unix and utf-8-with-signature-unix. (You can see the coding system of the current buffer with M-x describe-current-coding-system, and you can change the coding system with  M-x set-buffer-file-coding-system). The "with-signature" version of the coding system includes the BOM.

The use case I was more immediately concerned with is something like this URL: https://www.mathstat.dal.ca/~selinger/papers/downloads/Wollic.agda. It is a raw Agda file that is incorrectly displayed by most browsers (see the comment near the start of the file). If I include the BOM, the browser will correctly identify it as UTF, but Agda will reject the file.

The use of a BOM is not required by the Unicode standard, but it is a useful feature. Also, according to the above Wiki page, "... many pieces of software on Microsoft Windows such as Notepad (prior to Windows 10 Build 1903) treat the BOM as a required magic number rather than use heuristics. These tools add a BOM when saving text as UTF-8, and cannot interpret UTF-8 unless the BOM is present or the file contains only ASCII."

**Comment by nad** [comment]
> The use case I was more immediately concerned with is something like this URL: https://www.mathstat.dal.ca/~selinger/papers/downloads/Wollic.agda. It is a raw Agda file that is incorrectly displayed by most browsers (see the comment near the start of the file). If I include the BOM, the browser will correctly identify it as UTF, but Agda will reject the file.

Can't you instruct the web server to generate a suitable `Content-type` header for the file (perhaps `Content-Type: text/plain; charset=utf-8`)? Another option is to use `agda --html`.

**Comment by nad** [comment]
It [seems as](https://gitlab.haskell.org/ghc/ghc/-/issues/1744) if GHC ignores the BOM at the beginning of a file.

**Comment by andreasabel** [comment]
Patching Agda to ignore the BOM at the beginning of a file should not be hard, so I think this feature request should be accepted.

**Comment by nad** [comment]
> not be hard

Should this only happen for `.agda` files, or also for `.lagda` files? What about `.agda-lib` files, and files like `.agda/libraries`?

If the BOM is ignored at the beginning of a file, then a token that starts in the n-th column of line 2 is treated as being aligned with a token that starts in the (1+n)-th column of line 1. Should the BOM be displayed or not? If it is displayed, then layout can be messed up. If it is not displayed, then potentially important information is not displayed to the user (but perhaps that is fine, the information can be found in other ways).

It seems as if Emacs by default uses the coding system `utf-8-with-signature` if a `.agda` file with an initial BOM is opened (see `auto-coding-regexp-alist`). This means that the BOM is not displayed, and that the character after the BOM is treated as being the first one. Thus, if we accept the BOM at the beginning of the file, then it may make sense for the Agda backend to treat the following character as the first one. Other frontends may need to be updated to support `.agda` files with initial BOMs.

Should the HTML backend include initial BOMs in the generated HTML files? Presumably not, and one should ensure that this is the case. Perhaps it makes sense to not include initial BOMs in the `iSource` and `iSourceHash` fields of `Interface`s.

I wonder if the easiest way to implement this is to change `Agda.Utils.IO.UTF8.readTextFile` so that an initial BOM is thrown away immediately. Then initial BOMs are ignored for all text files, and hopefully no frontend needs to be modified.

Perhaps some users want to ensure that Emacs always writes an initial BOM when a file is saved. I think this can be done without any changes from our side, because the following setting can be overridden:

https://github.com/agda/agda/blob/8717a7189996410213efb1ef45342a2c77ad5657/src/data/emacs-mode/agda2-mode.el#L373

**Comment by andreasabel** [comment]
> I wonder if the easiest way to implement this is to change `Agda.Utils.IO.UTF8.readTextFile` so that an initial BOM is thrown away immediately. Then initial BOMs are ignored for all text files, and hopefully no frontend needs to be modified.

This sound like a principled approach!

**Comment by selinger** [comment]
I believe a BOM at the beginning of a file should be regarded as part of the file encoding, and not as part of the file content, so it certainly should not affect things like indentation. (Unicode technically defines this character to be a zero-width space). I believe throwing it away is the correct way to handle it. 

You all are in a better position to decide whether this should be done by the lexer or by the file-handling code prior to lexing. If `Agda.Utils.IO.UTF8.readTextFile` is only used by Agda internally, this probably makes no difference. If `Agda.Utils.IO.UTF8.readTextFile` is also useable by user code to read (non-Agda) utf, it might be better to keep the BOM, which is actually a unicode character, or it could give unexpected results in some cases (say, if someone wants to write a utf8-to-utf16 converter)

**Comment by nad** [comment]
> I believe a BOM at the beginning of a file should be regarded as part of the file encoding

I agree.

> (Unicode technically defines this character to be a zero-width space).

Agda's layout mechanism treats each code point as a single character. (The LaTeX backend can be compiled with support for extended grapheme clusters.)

**Comment by andreasabel** [comment]
In #6614 I added `stripUtf8BOM` to `Agda.Utils.Utf8.readFile`.  So Agda now ignores the BOM in text files.
However, I didn't change `writeFile`, so Agda does not write any BOMs.

**Comment by nad** [comment]
> In #6614 I added `stripUtf8BOM` to `Agda.Utils.Utf8.readFile`. So Agda now ignores the BOM in text files. However, I didn't change `writeFile`, so Agda does not write any BOMs.

Would it make sense to preserve BOMs for, say, `.lagda.md`?

**Comment by andreasabel** [comment]
> Would it make sense to preserve BOMs for, say, `.lagda.md`?

Possibly, let's wait for the demand.
