### ISSUE TITLE
Instance fields are not considered for concrete instances

### ISSUE THREAD

**Issue by plt-amy** [agda/agda#6589]
Minimal reproducer:

```agda
module Test11 where

open import Agda.Builtin.Nat
open import Agda.Builtin.Equality

record T1 : Set where field val : Nat
record T2 : Set where field ⦃ t1 ⦄ : T1

open T1 ⦃ ... ⦄
open T2 ⦃ ... ⦄

instance
  it : T2
  T1.val (T2.t1 it) = 0

test′ : Nat
test′ = val
```

The use of copatterns in defining `it` does not matter.

**Comment by andreasabel** [comment]
The simple workaround for this MWE would be to add the instance explicitly.
```agda
instance
  it1 : T1
  T1.val it1 = 0
```
What you seem to expect is that the following instance is added automatically:
```agda
instance
  it1 : T1
  it1 = T2.t1 it
```
Is it natural to assume this?

To make this feature work efficiently, we would have to saturate the collection of instances by transitively adding all instances that are fields of a newly added instance.

**Comment by jespercockx** [comment]
You can already get the behaviour you want by marking the field as `instance` instead of using curly braces:
```agda
record T2 : Set where field instance t1 : T1
```
I don't think it makes sense to change the current behaviour: you can either use instance search to *build* new instances from their fields by marking the fields as instance arguments to the constructor, **or** you can use instance search to *destruct* instances by marking the projections as instances. But if you do both then instance search will start looping, so we do need to have separate syntax for the two cases.
