### ISSUE TITLE
Forcing analysis is inconsistent for large indices

### ISSUE THREAD

**Issue by jespercockx** [agda/agda#6654]
Example given by @plt-amy in #6653:

> It looks like this _is_ inconsistent:

```agda
{-# OPTIONS --with-K --safe #-}
module Test where

data ⊥ : Set where

data Bad : ((P : Set) → P → P) → Set where
  b : (f : (P : Set) → P → P) → Bad f

bad : Bad _
bad = b λ P p → p

no-bad : ∀ {x} → Bad x → ⊥
no-bad (b x) = no-bad (x _ bad)

very-bad : ⊥
very-bad = no-bad bad
```

_Originally posted by @plt-amy in https://github.com/agda/agda/issues/6653#issuecomment-1556224307_

**Comment by jespercockx** [comment]
Presumably this was introduced 9 years ago in https://github.com/agda/agda/commit/9a4ebdd372dc0510e2d77e726fb0f4e6f56781e8

**Comment by jespercockx** [comment]
Two possible avenues for fixing this:
1. Remove the forcing analysis as proposed in #6653 
2. Restrict the termination checker to only allow recursion on proper recursive arguments as discussed at the latest Agda meeting (cfr https://github.com/agda/agda/issues/3883)

**Comment by jespercockx** [comment]
A third option would be to disallow recursion on forced arguments, which is probably less invasive and easier to implement than the other two suggestions. It also makes sense since the forced argument is "not really there".

**Comment by plt-amy** [comment]
Excluding forced arguments from the termination order ([patch here](https://gist.github.com/plt-amy/b826dfda052667ed7486d131993a6e91)) breaks #4775, #5953, and the `TerminationInductionInduction` test case.

In this last test case (the only one checked --with-K/default flags), the call `g Γ (Π Γ A B) → f Γ` is no longer considered to be decreasing, since the relevant comparison, `Γ < Π Γ A B`, is instead turned into `Γ < Π A B`, which fails --- the `Γ` argument to Π, being forced, got dropped.

**Comment by andreasabel** [comment]
> A third option would be to disallow recursion on forced arguments, which is probably less invasive and easier to implement than the other two suggestions. It also makes sense since the forced argument is "not really there".

Agree.  I think when we introduced the forcing analysis, we did not look at the termination checker.  

Great example, @plt-amy, showing how impredicativity sneaks in through the back door here.

> In this last test case (the only one checked --with-K/default flags), the call `g Γ (Π Γ A B) → f Γ` is no longer considered to be decreasing, since the relevant comparison, `Γ < Π Γ A B`, is instead turned into `Γ < Π A B`, which fails --- the `Γ` argument to Π, being forced, got dropped.

Yes, I remember that termination checking fails if you make some indices into parameters in this example.

Frankly, the termination checker was developed against rather simple concepts of data types.  That it works for induction-recursion or induction-induction (or rather does not work for the latter) is mere coincidence, imho.
- The underlying publication (Abel, Altenkirch, JFP 2000) only has simple types.
- David Wahlstedt's thesis has only "first order datatypes" (https://research.chalmers.se/publication/45188).

In general, I think sized types are a more robust concept when it comes to termination checking, however, I also have not looked at advanced data types when it comes to dependent types.  And the implementation is too permissive, so inconsistencies have surfaced.  However, sized types require the user to have a clear idea about the recursive positions in data types (as they have to put the size annotations there).
What this example concerns, it cannot be done with sized types---there are no recursive positions in the type.

I would be fine to not support induction-induction by default in Agda, until someone comes along with a practical and provably correct termination checker for them.

The short-term fix is definitely to disable large indices for dot-pattern termination---it looks like this can readily be done because we have a clear idea how to do this.

**Comment by jespercockx** [comment]
>  However, sized types require the user to have a clear idea about the recursive positions in data types (as they have to put the size annotations there).

As a compromise, would it be possible to let users mark the recursive positions somehow *without* changing the types? This would make it much less invasive and costly for the user to convey their intent.

**Comment by andreasabel** [comment]
```agda
T : Set₁
T = (X : Set) → X → X

id : T
id X x = x

data Bad : T → Set where
  b : (f : T) → Bad f

bad : Bad id
bad = b id

no-bad : (f : T) → Bad f → ⊥
no-bad f (b .f) = no-bad id (f (Bad id) bad)
```
Today Jonas Höfer, @plt-amy, and I discussed how to get the termination checker discount bad constructor fields (such as the argument to `b`) for the sake of certifying termination.  Maybe we can instrument the positivity checker to mark bad constructor fields as such.  (Positivity checking runs before termination checking.)  I think folks (@flupe) at AIM XXXVI also worked on something like that.

The example shows that `X` of `T` can be instantiated by `Bad` because its size as a large index allows this, and also because quantification over `X` appears in a positive position in the type of the constructor field (in this case, at the root of the type).  Thus, `X` should be considered as mutual with `Bad`, so that the negative occurrence of `X` in `T` becomes visible to the positivity checker and can lead to the constructor field to be rejected as source for structural descent.
However, as the example shows, this would require also tracking some positivity information in closed types like `T`, which is very unlike to what we are doing atm.

While I am writing this, I am thinking, maybe there is a simpler solution: __just mark any large constructor arguments as unusable for structural descent?__  We should have the sort of each constructor argument, so we could check it against the sort of the data type to determine whether it is large(r).  This is actually almost what the forcing analysis is doing.  In our discussion @plt-amy was worried that this check is not postponable, so what if the sort isn't known yet?  We already have a systematic issue with that (#118). E.g.
```agda
{-# OPTIONS --allow-unsolved-metas #-}

mutual
  X : Set 
  X = ?

  data D : Set where
    lam : (X → ⊥) → D

app : D → D → ⊥
app (lam f) = f

omega : D
omega = lam λ x → app x x

Omega : ⊥
Omega = app omega omega
```
Here we do not get a complaint from the positivity checker, since `X = D` is only revealed (by its uses) after meta `X` has been frozen.  The current contract is that checks run at the end of the mutual block, and if we have unsolved metas still then, checks might not be too optimistic (and thus allow inconsistency).  
So, I guess having a check on large constructor arguments just before termination checking should be consistent with Agda's overall behavior in such issues.

**Comment by andreasabel** [comment]
Afterthought:  Rejecting large constructor fields will reject this example for induction-induction where we arbitrarily place `Cxt` in a "too large" universe `Set1` instead of `Set`:
```agda
mutual
  data Cxt : Set₁ where
    ε    :  Cxt
    _,_  :  (Γ : Cxt) (A : Ty Γ) → Cxt

  data Ty : (Γ : Cxt) → Set where
    u  :  ∀ Γ → Ty Γ
    Π  :  ∀ Γ (A : Ty Γ) (B : Ty (Γ , A)) → Ty Γ

mutual
  f : Cxt → Cxt
  f ε        =  ε
  f (Γ , T)  =  (f Γ , g Γ T)

  g : ∀ Γ → Ty Γ → Ty (f Γ)
  g Γ (u .Γ)      =  u (f Γ)
  g Γ (Π .Γ A B)  =  Π (f Γ) (g Γ A) (g (Γ , A) B)
```
CC: @jonashoefer

**Comment by wenkokke** [comment]
@andreasabel The text of PLFA currently suggests that the following definitions are equivalent:

```agda
data List (A : Set) : Set where
    []  : List A
    _∷_ : A →   List A → List A

data List′ : Set → Set where
    []′  : ∀ {A : Set} → List′ A
    _∷′_ : ∀ {A : Set} → A → List′ A → List′ A
```
I'm assuming this is no longer the case.

Does anyone have a suggested change in the language used by PLFA?
https://plfa.github.io/Lists/#lists
