### ISSUE TITLE
Cannot put `where` token on new line for `private module`

### ISSUE THREAD

**Issue by jpoiret** [agda/agda#6685]
The following code doesn't parse in 2.6.3
```agda
private module Test
  where
  test = Set
```

as opposed to
```agda
module Test
  where
  test = Set
```

This means that if I want to write a long telescope for a private module, I need to open a `private` block inside which I put the `module` declaration, leading to a lot of indentation. This is related to #1145, the corresponding example code in the original post doesn't parse either.

**Comment by andreasabel** [comment]
Since `private` is a layout keyword, a new layout block is started at the column where `module` starts.  Only if you have `where` (which is another layout keyword) _on the same line_ as `private`, it cancels the effect of the former (namely starting a new layout block).

With @plt-amy I discussed (in the `opaque...unfolding...where` situation), "anti-layout" keywords.  So, if we make `module` an anti-layout keyword, canceling previous layout keywords on the same line, your example would pass.  However, this would change its semantics
```agda
private module A
          where
        module B
          where
``` 
Currently these are two parallel modules, with `module` being anti-layout this would mean that `B` is a submodule of `A`.

**Comment by jpoiret** [comment]
I didn't know this was the behavior of layout keywords! This seems counter-intuitive, but I guess the change would break backwards-compatibility, which is unfortunate. This is more of a papercut issue, although the parser error doesn't help understanding what is going wrong.

**Comment by jespercockx** [comment]
It's not clear what should be done here, so I'm closing it. Please re-open or create a new issue if you have a concrete suggestion for improvement.
