### ISSUE TITLE
Building with `make install` requires too much time/memory

### ISSUE THREAD

**Issue by nad** [agda/agda#6801]
Building Agda 2.6.3 using `make install` (which uses `-foptimise-heavily`) and GHC 9.4.7 works fine for me:
```
real    10m15,225s
user    17m9,364s
sys     0m11,464s
```
However, building Agda 2.6.4-67ea08d268c217f85e9a4230b0de086b3a5ad1ef works less well:
```
[410 of 430] Compiling Agda.Compiler.MAlonzo.Compiler ( src/full/Agda/Compiler/MAlonzo/Compiler.hs, dist-2.6.4-ghc-9.4.7/build/Agda/Compiler/MAlonzo/Compiler.o, dist-2.6.4-ghc-9.4.7/build/Agda/Compiler/MAlonzo/Compiler.dyn_o )
panic! (the 'impossible' happened)
  GHC version 9.4.7:
        heap overflow

Please report this as a GHC bug:  https://www.haskell.org/ghc/reportabug

Failed to install Agda-2.6.4
Error: cabal: Some packages failed to install:
Agda-2.6.4-BXGmUJ9X0PgLoxjYggcJR0 failed during the building phase. The
exception was:
ExitFailure 1


real    27m10,679s
user    35m21,248s
sys     0m9,863s
make: *** [Makefile:177: install-bin] Error 1
```
I think this should be investigated before the release.

**Comment by nad** [comment]
Without `-foptimise-heavily`, for 2.6.3 (the numbers are the ones reported for `install-bin`):
```
real    3m56,873s
user    7m43,924s
sys     0m7,625s
```
For 2.6.4-67ea08d268c217f85e9a4230b0de086b3a5ad1ef:
```
real    4m29,653s
user    9m33,169s
sys     0m8,964s
```

**Comment by andreasabel** [comment]
Can't be blamed on the code size which increased only by 5%:
- 2.6.3 150 kloc 5800 kB
- 2.6.4 156 kloc 6040 kB

I observed an increased hunger in compilation memory with GHC 9.6 in 20779d20c68eada6bf22847370e53f39ef113f18, raised it from 4GB to 6GB.
https://github.com/agda/agda/actions/runs/5380606090/jobs/9763559735#step:10:425

**Comment by andreasabel** [comment]
@nad: Since building with `-foptimize-heavily` actually fails on your machine, @nad, you could try a `git bisect`.

**Comment by andreasabel** [comment]
On my Mac (OS Monterey) with 16GB main memory:
Using GHC 9.4.7 and one core, I get this for 2.6.3 with `cabal build -f optimise-aggressively` and dependencies already built (and frozen with `cabal freeze`):
```
real	12m30.646s
user	11m21.488s
sys	0m38.601s
```
This is for 2.6.4 (1ec1b8c79d9fa2b86936a80f96a0782bc805fe98), under the same conditions
```
real	13m10.451s
user	12m4.972s
sys	0m40.368s
```
Not a significant difference, expected with the growth of the code base.

So, I cannot reproduce.  Are you short of main memory, @nad?

**Comment by andreasabel** [comment]
This is today:
```
time cabal v1-install --disable-documentation --enable-tests -foptimise-heavily --builddir=./dist-2.6.4-ghc-9.6.2 -j1 --disable-library-profiling -fenable-cluster-counting --ghc-options="+RTS -A128M -M10G -RTS"  --program-suffix=-2.6.4
...
real	24m29.378s
user	21m39.938s
sys	1m24.019s
```
Oops, above I misspelled the cabal flag `optimise-heavily` and `optimise-aggressively` (confused it with `unfold-aggressively`).  `cabal` is such a bummer, no checking of flag spelling (no flag scoping)...

**Comment by andreasabel** [comment]
Agda 2.6.3 compilation with heavy optimization: GHC 9.4.7 allocated 8GB real memory max.
```
time cabal build -f optimise-heavily -f enable-cluster-counting -w ghc-9.4.7 
...
real	24m4.647s
user	22m29.014s
sys	1m0.044s
```
In comparison, compiling 2.6.4 took 2 min longer and 2 GB more memory (peaked at 10.3GB with 8.5GB real memory).
```
gtime --verbose cabal build -f optimise-heavily -f enable-cluster-counting -w ghc-9.4.7 
...
	Command being timed: "cabal build -f optimise-heavily -f enable-cluster-counting -w ghc-9.4.7"
	User time (seconds): 1477.90
	System time (seconds): 78.27
	Percent of CPU this job got: 97%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 26:34.20
...
	Maximum resident set size (kbytes): 9899260
	Major (requiring I/O) page faults: 250270
	Minor (reclaiming a frame) page faults: 16566921
	Voluntary context switches: 13492
	Involuntary context switches: 1508504.
	Page size (bytes): 4096
```
Maybe one has to go back to interrupting GHC in the middle and restart compilation, as it used to be...

**Comment by AndrasKovacs** [comment]
FWIW, here's a tool with which module build times can be displayed decently: https://github.com/codedownio/time-ghc-modules. We add `-ddump-timings -ddump-to-file` ghc options, then run the above tool in the agda dir. 

Here are the displayed times for building on my laptop:

- With `optimise-heavily`: https://andraskovacs.github.io/misc/agda-build-timings/optimise/report.html
- Without: https://andraskovacs.github.io/misc/agda-build-timings/no-optimise/report.html
- `quicker-install` while we're at it: https://andraskovacs.github.io/misc/agda-build-timings/quicker-install/report.html

**Comment by andreasabel** [comment]
> * With `optimise-heavily`: https://andraskovacs.github.io/misc/agda-build-timings/optimise/report.html

Surprisingly, the 20-line (sans imports) module `EtaExpand` is among the top 5.  Maybe this could be investigated.
https://github.com/agda/agda/blob/b38093ef713158fb01aac1880f035ee183602372/src/full/Agda/TypeChecking/EtaExpand.hs#L1-L35

**Comment by nad** [comment]
Some examples of modules that seem to become much slower to compile when `-foptimise-heavily` is turned on:
* `Agda.TypeChecking.Coverage`.
* `Agda.TypeChecking.Rules.LHS`.
* `Agda.TypeChecking.Rewriting.Confluence`.

**Comment by AndrasKovacs** [comment]
After digging into the Core output for the `EtaExpand` module, I learned some things and I can make some educated guesses.

It seems there's a way that code specialization is intended to work in GHC, which is already very inefficient, and the actual behavior is a lot worse than that.

The "ideal" intended scenario: when a module uses a polymorphic symbol at some concrete type, we generate specialized code and put it in the module code output. Every module which imports this module can refer back to the existing specializations instead of generating the same code again. This approach is already very bad, because if we have a large amount of polymorphic code in module `A`, if `B` and `C` separately import `A`, using code at concrete instantiations, they separately specialize everything. As far as I see, this is unavoidable in current GHC, because compilation is fundamentally per-module and knows nothing about sibling modules.

The actual behavior: lots of code is duplicated even in a single linear chain of imports. I'm not sure about the reasons, but to speculate:
- GHC only creates SPEC rules for symbols that are externally visible, even if `-fexpose-all-unfoldings` is on. This seems to imply that un-exported or locally let-bound definitions must be always duplicated on specialization. Eyeballing the Core seems to support this.
- SPEC rules might just simply not fire for some reason, or GHC might just miss generating SPEC rules for every specialization.

The following happens in `EtaExpand`, more concretely:
- The call to `checkInternal'` triggers the specialization to TCM for everything it depends on, and we get 50k lines of Core.   None of the other imported modules trigger the same specialization, so at this point the specialized code doesn't exist in imports.
- If I create an identical copy of `EtaExpand`, named `EtaExpand2`, exactly the same code is generated again, as expected from the "ideal" setup.
- I did the following experiment. I put the following in `EtaExpand`:
```haskell
deepEtaExpand :: Term -> Type -> TCM Term
deepEtaExpand = deepEtaExpand'

deepEtaExpand' :: MonadCheckInternal m => Term -> Type -> m Term
deepEtaExpand' v a = checkInternal' etaExpandAction v CmpLeq a
```
And the following in a dummy module which imports `EtaExpand`:
```haskell
foo :: Term -> Type -> TCM Term
foo = deepEtaExpand'
```
Although exactly the same specialization happens in two modules, the dummy module generates another copy of the 50k lines. 

The most realistic fix for now is the following: look through modules that blow up with `-foptimise-heavily` and skim the Core to see what should be manually specialized at definition sites. This shouldn't be a huge amount of work and should yield robust speedups. But of course it's fragile and it'd need to become a regular chore. 

On the longer term, I'd personally welcome phasing out polymorphic effects and `MonadX`. Or less ambitiously, we could write effect-monomorphic code by default and only generalize it if the actual need arises. My rule of thumb for decent scaling and performance has been the following:
- Only use class polymorphism in class methods or always-inlined code, not in large chunks of program logic. 
- Instead of effect polymorphism, use several concrete monads that cover what's needed, and perhaps overload the embedding of actions of one monad in actions of another. 

As far as I see, effect polymorphism is only worth it if we do substantial mocking and sandboxing, or other radical reinterpretation of effectful operations.

**Comment by gallais** [comment]
^ This may be of interest to @adamgundry (who IIRC told me at an SPLS meeting
that Agda is considered an interesting test case for GHC's performance)

**Comment by AndreasPK** [comment]
[https://gitlab.haskell.org/ghc/ghc/-/issues/18532 seems relevant to this.](https://gitlab.haskell.org/ghc/ghc/-/issues/18532) It has some discussion about when GHC does prune spec rules (and if it should do so).

> GHC only creates SPEC rules for symbols that are externally visible, even if -fexpose-all-unfoldings is on.

This sounds like a potential bug. GHC is pretty aggressive about pruning adhoc rules resulting from non-user specializations. (See the linked ticket). But I'm not sure if that's the case here.

--------

> I did the following experiment.
> ... Although exactly the same specialization happens in two modules, the dummy module generates another copy of the 50k lines.

Without having looked too deep that sounds like a bug to me. If the polymorphic definition that get's specialized is exported then the spec rule shouldn't be trimmed iirc and therefore get used in the second module instead of being reinvented.

It's possible I remember something wrong here but I believe that's worth a ticket.

**Comment by AndrasKovacs** [comment]
@AndreasPK thanks! The dropping of workers seems very plausible as culprit. Is it correct that `IO` unwrapping can produce workers and thus prevent code sharing the same way as unboxed workers? I've seen a lot of `fun = cast fun1` in core where `fun1` is an unwrapping of `IO` or a newtype.

**Comment by jespercockx** [comment]
> On the longer term, I'd personally welcome phasing out polymorphic effects and MonadX. Or less ambitiously, we could write effect-monomorphic code by default and only generalize it if the actual need arises. My rule of thumb for decent scaling and performance has been the following:
>
>    Only use class polymorphism in class methods or always-inlined code, not in large chunks of program logic.
>    Instead of effect polymorphism, use several concrete monads that cover what's needed, and perhaps overload the embedding of actions of one monad in actions of another.
>
> As far as I see, effect polymorphism is only worth it if we do substantial mocking and sandboxing, or other radical reinterpretation of effectful operations.

Note that we do "serious mocking and sandboxing" of large parts of the Agda typechecking code. In particular:
- We have the `ReduceM` monad which is a pure version of the `TCM` monad used for reduction.
- Pretty-printing code is effect-polymorphic in order to make sure it does not modify the state by accident.
- Conversion checking is effect-polymorphic so we can call it in a way that statically rules out any state changes (see `Agda.TypeChecking.Conversion.Pure`).

I have put in significant effort to make more parts of the Agda codebase effect-polymorphic for these reasons, and I don't see how we can retain these benefits if we give up on pervasive effect polymorphism.

**Comment by AndrasKovacs** [comment]
Here's another batch of potentially useful data:
- Statistics for failed specializations: https://andraskovacs.github.io/misc/agda-build-timings/spec_warnings_stats.txt
- The same thing as raw GHC output: https://andraskovacs.github.io/misc/agda-build-timings/spec_warnings.txt

This was obtained with [`-fwall-missed-specializations`](https://downloads.haskell.org/ghc/latest/docs/users_guide/using-warnings.html#ghc-flag--Wall-missed-specialisations).

@jespercockx I don't think the mtl-style is necessary to guarantee that some code doesn't modify some state. A concrete monad can be defined to not access some data and effects, and then it can be embedded in some other monad by a `run` function. For reshuffling and restricting Reader and State data, there's no essential need to generate any specialized code, and the most efficient code should explicitly avoid that, to avoid passing unused Reader and State. 

This is unlike the kind of mocking that I meant, where e.g. we want to run programs in real IO, instrumented IO or fake pure IO. There, if we have basic operations that should be inlined, we really need to generate new code for each specialization. I haven't looked at much of the Agda code yet, so I don't know how much such usage of specialization there is.

**Comment by AndreasPK** [comment]
> @AndreasPK thanks! The dropping of workers seems very plausible as culprit. Is it correct that `IO` unwrapping can produce workers and thus prevent code sharing the same way as unboxed workers? I've seen a lot of `fun = cast fun1` in core where `fun1` is an unwrapping of `IO` or a newtype.

That seems plausible. I believe the reason for the wrappers in the IO case is document in this ghc note https://github.com/ghc/ghc/blob/fa4e5913251786f2b535b31abd3fad39da8b3602/compiler/GHC/Core/Opt/Simplify/Iteration.hs#L451C16-L451C16

Here is a small reproducer:

```
{-# INLINABLE foo #-}
foo :: (Monad m, Integral a) => a -> a -> a -> IO (a,a,a,a,a, m a)
foo x y z = do
  let !x1 = x+1
  let !x2 = x+2
  let !x3 = x+3
  let !x4 = x+4
  let !x5 = x+5
  pure (x1, x2, x3, x4, x5, pure (x1+x2))

bar :: Int -> IO (Int,Int,Int,Int,Int, IO Int)
bar = foo 1 2
```

In the meantime one workaround is using custom specialise pragmas on large specializations known to happen. For the reproducer if we add `{-# SPECIALISE foo :: Int -> Int -> Int -> IO (Int,Int,Int,Int,Int, IO Int) #-}
` then the spec rule is retained as desired.

If anyone feels compelled to open a GHC ticket it would be very welcome.

**Comment by AndreasPK** [comment]
I reopened https://gitlab.haskell.org/ghc/ghc/-/issues/21917 as it seems to pretty much describe the specialization issue.

**Comment by jespercockx** [comment]
> I don't think the mtl-style is necessary to guarantee that some code doesn't modify some state. A concrete monad can be defined to not access some data and effects, and then it can be embedded in some other monad by a run function. For reshuffling and restricting Reader and State data, there's no essential need to generate any specialized code, and the most efficient code should explicitly avoid that, to avoid passing unused Reader and State.

What I meant is that we have a rather large number of utility functions that are not stateful but they are used in different contexts with different monads, in particular `TCM` and `ReduceM`. It is extremely noisy and annoying to have to insert `run` or `lift` functions by hand. The current approach also gives us a relatively fine-grained way to control side-effects beyond state, e.g. which parts of code can throw or catch exceptions and/or pattern violations, which parts can raise constraints, which parts require read-only access to the state, ... This is all extremely useful documentation to me as a developer, and having it be checked by the type-checker is crucial because comments are too easily ignored.

So I am not at all arguing from an efficiency perspective here, but purely from a developer ergonomic perspective. In a codebase as large and complex as Agda, ergonomics are important.

**Comment by simonpj** [comment]
Dear Agda folk 

I have added a flag, `-fkeep-auto-rules`, that tells GHC to keep the specialisations of functions, thereby avoiding the code duplication described above (e.g. https://github.com/agda/agda/issues/6801#issuecomment-1721346776).

The patch has landed in HEAD.  Would you like to try it?  (It's off by default at the moment.)

For completeness, here is the commit:
```
commit e96c51cbd137113ec953d8b7b0817d2d268f3c96
Author: Andreas Klebinger <klebinger.andreas@gmx.at>
Date:   Thu Aug 4 21:27:57 2022 +0200

    Add a flag -fkeep-auto-rules to optionally keep auto-generated rules around.
    
    The motivation for the flag is given in #21917.

 compiler/GHC/Driver/Config/Tidy.hs                     |  1 +
 compiler/GHC/Driver/Flags.hs                           |  1 +
 compiler/GHC/Driver/Session.hs                         |  1 +
 compiler/GHC/Iface/Tidy.hs                             | 30 ++++++++++++++++++++----------
 docs/users_guide/using-optimisation.rst                | 18 ++++++++++++++++++
 testsuite/tests/simplCore/should_compile/T21917.hs     | 21 +++++++++++++++++++++
 testsuite/tests/simplCore/should_compile/T21917.stderr |  8 ++++++++
 testsuite/tests/simplCore/should_compile/all.T         |  2 ++
 8 files changed, 72 insertions(+), 10 deletions(-)
```

**Comment by andreasabel** [comment]
Install times have gone down considerably thanks to @AndrasKovacs ' efforts.  Should we close this?  (Otherwise, please bump the milestone.)

**Comment by AndrasKovacs** [comment]
I vote for closing. The most obvious cases of code duplication are already addressed. We'll get more build time reductions if we de-MTL-ify parts of the codebase, but more like as a side effect.
