### ISSUE TITLE
`DuplicateExecutable` test randomly breaks other `Fail/` tests

### ISSUE THREAD

**Issue by lawcho** [agda/agda#6832]
On latest `master` (283730b), running `make test` fails non-deterministically.

The console pauses several times and displays diffs such as
```diff
1.actual
index e83670021..a3a9e853d 100644
--- a/tmp/nix-shell.qnWrHw/AbstractModuleMacro524397-0.golden
+++ b/tmp/nix-shell.qnWrHw/AbstractModuleMacro524397-1.actual
@@ -1,5 +1,3 @@
-AbstractModuleMacro.agda:7,1-8,19
-warning: -W[no]UselessAbstract
-Using abstract here has no effect. Abstract applies to only
-definitions like data definitions, record type definitions and
-function clauses.
+Duplicate entries for executable 'echo' in DuplicateExecutable/executables:
+  2: /bin/echo
+  3: /bin/echo
```
or
```diff
diff --git a/tmp/nix-shell.qnWrHw/BadForcedIrrelevance524397-2.golden b/tmp/nix-shell.qnWrHw/BadForcedIrrelevance524397-3.actual
index dc1787cd6..a3a9e853d 100644
--- a/tmp/nix-shell.qnWrHw/BadForcedIrrelevance524397-2.golden
+++ b/tmp/nix-shell.qnWrHw/BadForcedIrrelevance524397-3.actual
@@ -1,3 +1,3 @@
-BadForcedIrrelevance.agda:11,16-17
-Variable n is declared erased, so it cannot be used here
-when checking that the expression n has type Nat
+Duplicate entries for executable 'echo' in DuplicateExecutable/executables:
+  2: /bin/echo
+  3: /bin/echo
(END)
```
the incoming fragment is always for the `DuplicateExecutable` test. The other test varies, but is always from the `Fail/` suite.

When running `make test -j1`, exactly 1 other test is affected, but without the `-j1` flag the number of affected tests varies.

I am using GNU Make 4.4.1, cabal 3.8.1.0, and ghc 9.2.7, all provided by `nix develop` in this repo's root.
OS is Ubuntu 22.04.3 LTS x86_64

**Comment by andreasabel** [comment]
@lawcho: I am having a deja vu here, this sounds similar to:
- https://github.com/agda/agda/issues/4940

There, I also saw the error from the `executables` test reproduced in other cases, because the parsing of the `executables` file continued to fail after it had been directed to a faulty one by setting the `AGDA_DIR`.

In your case, this would be here:
https://github.com/agda/agda/blob/88be4c97d53edb2ca272e3bf5ad5122c6979979c/test/Fail/DuplicateExecutable.vars#L1
https://github.com/agda/agda/blob/88be4c97d53edb2ca272e3bf5ad5122c6979979c/test/Fail/DuplicateExecutable/executables#L1-L3

I could fix the problem there by properly setting back the environment variables to their original value, see d7455a69e1e6e3b89fdd36ea623300fedb98b9ed.

It could be that this does not work correctly in your case due to concurrency, maybe?

**Comment by lawcho** [comment]
It does seem to be a concurrency bug.
On an 8 core machine:
* `PARALLEL_TESTS=1 make fail` succeeds
* `PARALLEL_TESTS=6 make fail` succeeds
* `PARALLEL_TESTS=8 make fail` fails on 1 or 2 cases
* `PARALLEL_TESTS=16 make fail` fails on 5 cases
* `PARALLEL_TESTS=32 make fail` fails on 9 cases
* `PARALLEL_TESTS=128 make fail` fails on 55 cases
All the failing cases come in a bunch after the `DuplicateExecutable` test.

**Comment by gallais** [comment]
I have been experiencing the same problem for a while now.
