### ISSUE TITLE
Uncaught pattern violation when using `with...in...` instead of old-school inspect

### ISSUE THREAD

**Issue by omelkonian** [agda/agda#6841]
# Agda version: 2.6.3
---

The following code typechecks with `inspect`, but panics when using `with...in...`:
```agda
open import Data.Maybe
open import Relation.Binary.PropositionalEquality

postulate A : Set; x : A

withIn-bug : A
withIn-bug
--   with just x | inspect just x
-- ... | just y | [ eq ]
  with just x in eq
... | just y
  = y
```
```
Panic: uncaught pattern violation
```

---
(Andreas:)
Related:
- #5805

**Comment by andreasabel** [comment]
Shrunk to:
```agda

open import Agda.Builtin.Equality

postulate A : Set; a : A

data MaybeA : Set where
  just : A → MaybeA
  nothing : MaybeA

withIn-bug : A
withIn-bug with just a in eq
... | just y = _
```
Accepted by Agda 2.6.2.2 (with errors), crashing Agda 2.6.3 and `master` with uncaught pattern violation.

**Comment by jamesmckinna** [comment]
:man_facepalming:

**Comment by andreasabel** [comment]
Actually, the situation is more complex, which I found out by trying bisection:
- 2.6.2: Panic
- 2.6.2.1: Panic
- 2.6.2.2: Fails regularly with errors
- 2.6.3: Panic
- 2.6.4 (master): Panic

Bisecting 2.6.2.2 (good) vs. 2.6.3 (bad) failed because the merge base is bad.
One can try bisection to see what _fixed_ the problem between 2.6.2.1 and 2.6.2.2.

**Comment by andreasabel** [comment]
So e1a38942a00c1ee2303125abddc6ca30419acfe0 by @jespercockx _fixed_ the problem until it reappeared later again.
> Date:   Mon Mar 14 18:41:30 2022 +0100
> [ fix #5805 ] Catch pattern violations in `checkType`

So let's take this as good commit vs. 2.6.3.

Bugger, this again leads to the bad merge base 16faf8a529f83a1e62f1865cd10291f4d485f1b (@asr committed on Jun 19, 2021).  Why is such an old commit the merge base?  Well, likely because I used it to cherry-pick for 2.6.2.1 and 2.6.2.2...

Ok, I can start at the original (not cherry-picked) version  6bd89db69cf36a202464f0de71d79e28e0b5fb24.  But it is in a different context will it still be good?

Yes, this one is good, so let's roll bisection again!

**Comment by andreasabel** [comment]
Bisection says e39eeab75287e4b70d798aa15545a731130c49d3 is the first bad commit @jespercockx
> Date:   Thu Mar 17 10:24:58 2022 +0100
> [ re #5805 ] Create constraint instead of hard error in checkType
>    
>   This fixes the issue when I load Issue5805.agda in Emacs, but
>   when I run `make test` it somehow throws a pattern violation again.

Ah, we are still inside #5832 in the second [commit](https://github.com/agda/agda/pull/5832/commits).
So, the problem got unfixed in the very next commit.

**Comment by jespercockx** [comment]
The pattern violation is thrown by the call to `isFibrant` at https://github.com/agda/agda/blob/f25a71a1c1d22c8702514df22e4f206982c15f40/src/full/Agda/TypeChecking/Coverage.hs#L1260, and is not caught anywhere in the coverage checker. Adding some debug prints, it seems like `isFibrant` is called with the type `just a ≡ nothing`, however the sort of this type is set to `_10 (w = nothing)`, where `_10` is an unsolved meta. So the question is: why do we get a known type for which the sort is unknown?

**Comment by jespercockx** [comment]
Aha, the meta is created by https://github.com/agda/agda/blob/f25a71a1c1d22c8702514df22e4f206982c15f40/src/full/Agda/TypeChecking/Abstract.hs#L78 and is supposed to be solved by the call to `checkType` two lines later (https://github.com/agda/agda/blob/f25a71a1c1d22c8702514df22e4f206982c15f40/src/full/Agda/TypeChecking/Abstract.hs#L80). However, in this case the call fails (for *some* reason) which generates a constraint and leaves the meta unsolved (thanks to https://github.com/agda/agda/commit/e39eeab75287e4b70d798aa15545a731130c49d3).

Instead of relying on `checkType` to solve the sort, we could instead use the `sortOf` function directly. However, this only works when we already know that the type is well-formed, which I guess is not the case for with-abstraction. Another option is to simply add a call to `noConstraints` around `checkType` here, which would make it raise a proper error rather than continue with a potentially ill-formed type.

**Comment by jespercockx** [comment]
After investigating a bit more, I discovered why the call to `checkType` is failing in the first place. The `with`-abstraction machinery is generating the type of the equality proof rather lazily, i.e. it provides the two term arguments but not their type or level. Instead, it just fills them in to be metavariables and leaves it up to the call to `checkType` to solve them. (Probably the reason for this is that we support many different shapes for the parameter telescope of the identity type, as long as it is polymorphic and homogeneous.) However, in case where the term we are `with`-abstracting over is not inferable (e.g. a constructor form, such as `just a` in this example) the type inference will give up and throw a pattern violation.

Since we check that the type of the builtin equality type is of the form `... -> (A : Set ...) -> A -> A -> Set ...`, we can fix the root problem causing this issue by instead of providing the final *two* arguments to the equality type, instead providing the final *three* ones.

**Comment by jespercockx** [comment]
On a related note, I am not sure whether we even need the call to `checkType` at https://github.com/agda/agda/blob/f25a71a1c1d22c8702514df22e4f206982c15f40/src/full/Agda/TypeChecking/Abstract.hs#L80

The only place where this function is used is in `withFunctionType`, which does its own call to `checkType` anyway.

**Comment by gallais** [comment]
> Since we check that the type of the builtin equality type is of the form `... -> (A : Set ...) -> A -> A -> Set ...`, we can fix the root problem causing this issue by instead of providing the final _two_ arguments to the equality type, instead providing the final _three_ ones.

Nice find!
