### ISSUE TITLE
CI: size-solver-test rebuilds Agda

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#6933]
See e.g. this CI run: https://github.com/agda/agda/actions/runs/6577500740/job/17869278492
1. 15m 40s  Build Agda
2. 13m 46s  Run tests for the size solver

Compare this with pre #6863 run https://github.com/agda/agda/actions/runs/6510947029/job/17685706260
1. 14m 10s
2. 26s

Post #6863 run https://github.com/agda/agda/actions/runs/6534521998/job/17741904793
1. 13m 31s
2. 11m 51s

So this is likely a regression introduced by
- #6863 

This PR changed the default flags for building Agda (adding `-f debug` to preserve debug printing facility) which have not been likewise changed in  https://github.com/agda/agda/blob/326f95c9d41cc04d7f016efb07b45a0bad4a7b04/src/size-solver/Makefile#L11-L18
ATTN: @AndrasKovacs 

The question is whether we need the `size-solver-test` at all in CI.  
In #6932 I added commit be28b6e2edc3961292eb9e56f80080289d90c61f to switch it off (hot fix to recover CI times).

**Comment by jespercockx** [comment]
@AndrasKovacs can you please take a look?

**Comment by AndrasKovacs** [comment]
OK

**Comment by jespercockx** [comment]
This concerns the development workflow of Agda so it does not really make sense to have it on a specific milestone.

**Comment by AndrasKovacs** [comment]
Why is size-solver an executable in a separate cabal project, instead of an executable in Agda.cabal?

Also, currently in the CI, I get the Agda rebuild from size-solver, and this is the message:

```
Agda-2.6.5: unregistering (flags changed from
["-fdebug","-f-debug-parsing","-f-debug-serialisation","-fenable-cluster-counting","-foptimise-heavily"]
to
["-f-debug","-f-debug-parsing","-f-debug-serialisation","-f-enable-cluster-counting","-f-optimise-heavily"])
```

Apparently there are extra dashes in the flags. But I don't know where any of these flags come from. The cabal file in the size-solver directory does not specify any flags. Also can't find the extra-dash flags anywhere in the Agda repo, so probably something mangles them.

EDIT: nevermind, I was told that the extra dash is actually "minus" which means that the flag has false value...
