### ISSUE TITLE
Making `--exact-split` and `--postfix-projections` default?

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#6943]
I wonder when is a good time to change some defaults?
- [ ] 2.6.5?
- [x] or do we have to bump to 2.7 then?

Candidates for defaults:
- [x] `--exact-split`
- [x] `--postfix-projections`
- [ ] `--prop`

Anything else?

- [x] `--keep-pattern-variables`
- [ ] `--erasure`

I think it would be good to bundle such changes so migration (like adding `flags` to `.agda-lib` files) can be done in one go.

**Comment by UlfNorell** [comment]
`--postfix-projection` I think would be good: copattern definitions are much more readable with postfix projections and I think we should encourage that style. Another candidate is `--keep-pattern-variables`. At least personally I never find dot patterns helpful.

`--prop` I think makes sense as default too. It doesn't harm casual users and for users that really don't want prop they should be using `--no-prop` already to make that clear.

`--exact-split` I'm against. This is pretty standard code that a new user might write
```agda
_==_ : Bool → Bool → Bool
false == false = true
true  == true  = true
_     == _     = false
```
Being forced to turn on `--no-exact-split`, write an ugly `CATCHALL` pragma, or expand the remaining cases would put a lot of people off I think. I don't think the first-match semantics is very hard to explain to people either.

I don't think changing default flags require a major version bump.

**Comment by jespercockx** [comment]
Agreed with Ulf. Some other candidates:
- I would also like `--erasure` for the same reason as `--prop`
- Another candidate would be `--keep-pattern-variables`, which I believe is much nicer from an interaction point of view. Nowadays we show the values of let-bound variables in the context, so there is still an easy way to see which variables have been refined.

**Comment by andreasabel** [comment]
Let's get some more opinions, e.g. from @nad @oskeri @plt-amy @gallais @L-TChen @martinescardo @JacquesCarette @MatthewDaggitt @felixwellen @jamesmckinna @AndrasKovacs ...

**Comment by gallais** [comment]
I agree on yes to everything except for `--exact-split`.

**Comment by martinescardo** [comment]
I use exact split, but I disable postfix projections, the reason being that I prefer to match mathematical notional practice rather than programming language notation.

However, I don't mind what you choose, because we can tweak `typetopology.agda-lib`.

One minor detail is that, unfortunately, for reasons unknown to me, I don't manage one or two files to type-check with `--exact-split`. So as long as `--no-exact-split` is available (is it?), I am happy for you to choose whatever you please.

The important thing is that these two options, if made default, have a negative version.

I pretty much disable anything that leads to a departure from standard (even minimal) Martin-Loef Type Theories.

**Comment by martinescardo** [comment]
If coinduction could be disabled, I would disable it.

It would be great if Agda allowed one to control (more or less) precisely which type theory one (doesn't) want.

We had this discussion last Friday with Thierry Coquand, Peter Dybjer and Marc Bezem, where we felt that this would be a highly desirable feature of Agda.

**Comment by martinescardo** [comment]
Maybe @tomdjong would like to have say, given that he is a major contributor of TypeTopology.

**Comment by martinescardo** [comment]
Oh, and let's remember why `--exact-split` was originally added. Once Achim Jung tried to learn Agda, and he gave up when his definitions didn't hold as definitional equalities. Remember that? This is the origin of `--exact-split`. So I would say that for beginners, not having `--exact-split` can be a real barrier.

**Comment by tomdjong** [comment]
While I like `--exact-split` for the reason Martin explained above, I find Ulf's example convincing. So, since there are arguments for both proposals, I think it's probably best to leave things as they are right now when it comes to `--exact-split`. 

Since Andreas wanted more opinions, maybe @egbertrijke has anything to say?

**Comment by L-TChen** [comment]
> I agree on yes to everything except for `--exact-split`.

Same here. I feel that Agda is more like a programming language, than a proof assistant, so having `--postfix-projections` enabled by default makes more sense. On the other hand, it might be great to have an introduction for mathematicians and a list of suggestions to overcome the (potential) barrier.

**Comment by andreasabel** [comment]
@martinescardo wrote:
> If coinduction could be disabled, I would disable it.

I think it is disabled by default, you need to turn on either `--guardedness` or `--sized-types` to get a corecursive function through the termination checker.

**Comment by martinescardo** [comment]
Right. But we can still define coinductive records, even if we can't do anything with them.

**Comment by andreasabel** [comment]
@martinescardo wrote:
> Right. But we can still define coinductive records, even if we can't do anything with them.

I think a `--[no-]coinduction` flag pair would be easy to add, a no-brainer except for clarifying its (co)infectivity status (which always makes my head hurt).  Would you have an opinion/wish for the latter?  
And in principle, do you have a student that could implement such a flag, given some help/supervision from us?
(Welcome to discuss this in a new issue, we are side-tracking here...)

**Comment by JacquesCarette** [comment]
Personally, I use `--exact-split` in almost all my code (but not all). I agree that `--postfix-projections` are often stylistically pleasant. I would likely end up using `--no-prop` in my global settings.

But that is largely irrelevant: the "target market" for defaults should not be expert users, as they are exactly the ones who can figure out how to set them to what they want. The target should be *beginners*. What should be 'default face' of Agda be, when you first crack open the box? Is Agda meant to be for-experts-only research software, or is it meant to attempt to attract a wider audience? That should be, IMHO, the principal criteria for choosing defaults.

I would prefer if the Agda devs were ambitious and wanted a wide audience. For a broad audience, some "training wheels" features (including `--safe`) should likely be the default. I'd argue `--exact-split` belongs to that as well.

If the defaults are mainly meant to make as many experts as happy as possible "out of the box", then I actually don't care what the defaults are, because I am expert enough to set them for myself just the way I want!

**Comment by gallais** [comment]
I don't think we should make `--safe` the default precisely because it'll immediately force us
to tell users how to turn it off to compile "hello world" which a lot of beginners insist on doing
to check their install.

**Comment by JacquesCarette** [comment]
That is a very solid argument @gallais . Consider my suggestion for `--safe` retracted. It is unfortunate, but it is important to be pragmatic in such cases.

**Comment by martinescardo** [comment]
> I don't think we should make `--safe` the default precisely because it'll immediately force us to tell users how to turn it off to compile "hello world" which a lot of beginners insist on doing to check their install.

The Hello World program could simply include `--unsafe`. After all, it is a sample program (which does not illustrate typical Agda code that people write). In any case, it doesn't matter to me, because I write `--safe` for emphasis in my files (as well as `--without-K`).

**Comment by martinescardo** [comment]
> And in principle, do you have a student that could implement such a flag, given some help/supervision from us?

Unfortunately I don't at the moment.

**Comment by martinescardo** [comment]
(I am curious about this: Is it true that most people use Agda as a programming language? I don't think I have seen any example of a serious application written in Agda.)

**Comment by nad** [comment]
I'm fine with changing the defaults for things that do not affect what is accepted by Agda, like `--postfix-projections`. However, I don't think we should break existing code by changing the defaults for `--prop` or `--erasure` unless we decide on a clear strategy for defaults and change all defaults at the same time.

**Comment by jwaldmann** [comment]
> ... serious application written in Agda

that's in a very early stage of a prototype of a proof-of-concept, but ... https://gitlab.imn.htwk-leipzig.de/waldmann/cetera

**Comment by L-TChen** [comment]
> (I am curious about this: Is it true that most people use Agda as a programming language? I don't think I have seen any example of a serious application written in Agda.)

[Cedille](https://cedille.github.io) is a programming language written in Agda. I also have a joint [project](https://github.com/josh-hs-ko/NDGP) experimenting datatype-generic programming for inductive families in Agda. (By programming language, I didn’t mean a production-ready language but a language used to experiment dependently typed programming and other features that are not supported by mainstream languages.)
