### ISSUE TITLE
Don't replace builtins by `TPrim`. Only replace the function body.

### ISSUE THREAD

**Issue by fredins** [agda/agda#6950]
During the `toTreeless` transformation we replace all calls to builtins by `TPrim`. E.g. `Agda.Builtin.Nat._+_` is replaced by `PAdd`. Then, the Ghc backend emits `PAdd` as `intAdd`. `intAdd` is defined as the builtin/primitive `(+)`  in `RTE.hs` .  
 
 ```haskell 
module MAlonzo.RTE where
addInt :: Integer -> Integer -> Integer
addInt = (+)
```
But `Agda.Builtin.Nat._+_` is compiled to the same thing... 
```haskell
module MAlonzo.Code.Agda.Builtin.Nat where
-- Agda.Builtin.Nat._+_
d__'43'__14 = ((+) :: Integer -> Integer -> Integer)
```

I think it would better to replace the function body of `Agda.Builtin.Nat._+_` with `PAdd` and leave all other call sites unchanged. Then, the GHC backend can map `PAdd` to `(+) :: Integer -> Integer -> Integer`. 

I am building a backend and the current implementation forces me to rewrap all `TPrim` which is annoying and prohibit separate compilation. Due to my compilation strategy, the function body of `Agda.Builitin.Nat_+_` is specialized for each program so I cannot load a RTE file like MAlonzo.

Am I missing something? I can send a draft PR if the maintainers like the idea. 
## Example
```agda
module TestGhc where

open import Agda.Builtin.IO using (IO)
open import Agda.Builtin.Unit using (⊤)
open import Agda.Builtin.String using (String)
open import Data.Nat.Show using (show)
open import Agda.Builtin.Nat using (suc; zero; _+_) renaming (Nat to ℕ) 

postulate putStrLn : String → IO ⊤
{-# FOREIGN GHC import qualified Data.Text as T #-}
{-# COMPILE GHC putStrLn = putStrLn . T.unpack #-}

plusTwo : ℕ → ℕ
plusTwo = _+_ 2

main : IO ⊤
main = putStrLn (show (plusTwo 6))
```
```haskell
module MAlonzo.Code.TestGhc where
d_plusTwo_4 :: Integer -> Integer
d_plusTwo_4 = coe addInt (coe (2 :: Integer))
```

**Comment by UlfNorell** [comment]
Currently there's a lot of custom optimisation for the primitives (see [Agda.Compiler.Treeless.Simplify](https://github.com/agda/agda/blob/master/src/full/Agda/Compiler/Treeless/Simplify.hs)) and it sounds like your suggestion would lose that.

Also I'm not entirely sure what the problem is. The GHC backend could already compile `PAdd` to `(+)`, I think it's only using `addInt` because it's shorter and we anyway need the RTE module. Maybe `PAdd` is a bad example?

Something I think you could do in your backend is when you see `PAdd`, look up what `primNatPlus` is bound to and compile it to that identifier.
