### ISSUE TITLE
Document instance projections

### ISSUE THREAD

**Issue by plt-amy** [agda/agda#7017]
If you mark a record field as `instance`, it gets added to the instance table with a visible function type, and instance search will happily use _the projection function_ to solve an instance headed by its codomain:

```agda
module Test111 where

postulate
  P : Set

record Q : Set where
  field instance p : P

postulate
  q : Q

get-p : ⦃ x : P ⦄ → P
get-p ⦃ x ⦄ = x

it : P
it = get-p
```

This fails with unsolved constraint

```
Failed to solve the following constraints:
  Q → P =< P (stuck)
```

because instance search solved `x := λ r → Q.p r`; though since the type is wrong, you can't get Agda to admit that it's done this without using underhanded methods (interactive normalisation, reflection, checking the debug buffer, etc.) If you normalise `it`, you get `λ r → Q.p r`.

**Comment by UlfNorell** [comment]
Maybe we should just disallow marking fields as `instance`? Are there any use cases where this makes sense?

**Comment by plt-amy** [comment]
I'm not sure I've _ever_ seen this feature used; it's not documented under record types _or_ instance arguments, either. I only became aware of it after @jespercockx pointed it out to me in #6589. So I don't think anyone would mind if we got rid of it.

**Comment by andreasabel** [comment]
> Maybe we should just disallow marking fields as `instance`? 

Shouldn't we try to understand where this faulty behavior comes from?  Without taking a closer look, we cannot exclude that there is a fundamental bug in instance search that causes this behavior...

**Comment by jespercockx** [comment]
I don't think there's any faulty behavior here, marking a field as an instance just turns the projection function into an instance, which is consistent with how any other function can be marked as an instance. Though this is not a thing that has many use cases, I think forbidding it or (imho worse) changing its semantics would just make the language less consistent and harder to learn.

What you usually want to do is not to mark a field as an instance, but make it into an *instance argument* to the constructor, which can be done with the usual double curlies:
```agda
record Q : Set where
  field {{p}} : P
```
This will trigger instance search when using the record constructor, and will bring the instance into play when you have an argument of the record type in scope.

If you do insist on having the field `p` as an instance rather than as an instance argument, here is how you can make your code typecheck:
```agda
postulate
  P : Set

record Q : Set where
  field instance p : P

open Q {{...}}

postulate instance
  q : Q

get-p : ⦃ x : P ⦄ → P
get-p ⦃ x ⦄ = x

it : P
it = get-p
```
You need to do `open Q {{...}}` (since otherwise the instance will take an explicit argument of the record type and will never fire as a result) and also make `q` into an instance (since it needs to be found by the recursive instance search).

**Comment by jespercockx** [comment]
For completeness, here is how I would write the code with an instance field (rather than an instance projection):
```agda
postulate
  P : Set

record Q : Set where
  field {{p}} : P

postulate instance
  q : Q

get-p : ⦃ x : Q ⦄ → P
get-p ⦃ x ⦄ = Q.p x

it : P
it = get-p
```
EDIT: the above doesn't actually use the fact that `p` is an instance argument. Here's an example that does:
```agda
postulate
  P : Set

record Q : Set where
  field {{p}} : P

it : {{P}} → P
it {{x}} = x

get-p : ⦃ x : Q ⦄ → P
get-p = it
```

**Comment by plt-amy** [comment]
> I don't think there's any faulty behavior here, marking a field as an instance just turns the projection function into an instance, which is consistent with how _any other function_ can be marked as an instance.

Well, I mean,

```agda
instance
  q→p : Q → P
  q→p = Q.p
-- warning: -W[no]InstanceWithExplicitArg
-- Instance declarations with explicit arguments are never considered
-- by instance search, so making q→p into an instance has no effect.
```

but yea, fair enough - the behaviour I was pointing out (actually *selecting* the instance *with the visible argument*) doesn't happen on `master`. Even though I had just _built_ a clean `master`, my editor was still pointed at a stale build based off f6dc8b8, hence the confusion; but it doesn't happen there, either, and I can't figure out what screwed-up branch I was in that would consider `Q → P ≤ P` something wroth blocking on from my `git reflog`, either. I guess we can say it was a ghost in my dist-newstyle, and move on (sorry for the noise).

**Comment by andreasabel** [comment]
Thanks, @jespercockx for clarifying this!

**Comment by andreasabel** [comment]
Since even the developers are confused about instance fields, this should be covered to the documentation.
@plt-amy Would you volunteer?
