### ISSUE TITLE
Internal error on confluence check when rewriting a defined symbol with a hole

### ISSUE THREAD

**Issue by ionathanch** [agda/agda#7029]
_Agda version: 2.6.4.1 (installed via `cabal get Agda 2.6.4.1`)_

Type checking the following produces an internal error:

```agda
{-# OPTIONS --rewriting --confluence-check --with-K #-}

open import Agda.Builtin.Equality

{-# BUILTIN REWRITE _≡_ #-}

myrefl : ∀ {ℓ} {A : Set ℓ} {x : A} → x ≡ x
myrefl = ?

UIP : ∀ {ℓ} {A : Set ℓ} {x : A} → myrefl {ℓ} {A} {x} ≡ refl
UIP with refl ← myrefl = refl

{-# REWRITE UIP #-}
```

> An internal error has occurred. Please report this as a bug.
Location of the error: \_\_IMPOSSIBLE\_\_, called at src/full/Agda/TypeChecking/Rewriting/Confluence.hs:606:19

Removing confluence checking yields the following expected (I assume) error:

> UIP  is not a legal rewrite rule, since the left-hand side 
myrefl  reduces to  ?0
when checking the pragma REWRITE UIP

**Comment by jespercockx** [comment]
Thank you for reporting. The problem here is that the confluence checker assumes there are no metavariables in any of the rewrite rules it gets. This is true for normal rewrite rules, since the `REWRITE` pragma makes sure that the rule is fully instantiated before adding it to the signature. However, the confluence checker also takes into account the clauses of regular pattern-matching definitions, and THOSE might contain unsolved metas, as is the case for `myrefl`. Possible solutions:

- Refuse to add any rewrite rules to a function if there are still unsolved metas in the definition of that symbol and the confluence checker is on (the simplest but crudest solution).
- Postpone the confluence check by adding it as a new constraint (@liesnikov is gonna love this) and retrying the check once all the metas have been resolved.
- Actually do something smart with metavariables in the confluence checker, which would likely adding a constraint for *syntactic* equality of terms (up to instantiation of metavariables). 
- Or we could even make the confluence checker instantiate the metavariables to the correct solution that makes the rewriting system confluent. In the example here that would mean the `?` would be instantiated to `refl` (at least when you would put the whole thing in a mutual block).

I think the first option is what I'll implement for now, but the others are certainly interesting to think about.
