### ISSUE TITLE
transpX clauses can be beat out by user-written _ clauses, leading to proof of ⊥ 

### ISSUE THREAD

**Issue by howtonotwin** [agda/agda#7033]
I have two proofs of falsity, both based on seemingly the same principle. My Agda is compiled from commit `ee876ee` with GHC 9.6.3. Here's one

```agda
{-# OPTIONS --cubical --safe #-}
open import Agda.Primitive.Cubical renaming (primTransp to transp; primINeg to ~_; primHComp to hcomp)

data ⊥ : Set where
data ⊤ : Set where tt : ⊤
data D : Set where
    base  : D
    loop  : PathP (λ _ → D) base base
    other : D

onS¹ : D → Set
onS¹ base     = ⊤
onS¹ (loop i) = ⊤
onS¹ _        = ⊥

JEEPERS! : ⊥
JEEPERS! = transp (λ i → onS¹ (hcomp {φ = ~ i} (λ { j (i = i0) → base }) base)) i0 tt
```

The essential problem is that `onS¹ (hcomp {φ = i0} (λ _ ()) base)` computes to `⊥` instead of `⊤` as it should. I believe this happens because the generated clauses for the hidden `hcomp`/`transpX` constructors of HITs/indexed inductives are considered to come after the user clauses. This is broken when the user supplies a `_` pattern (or even just a variable pattern, like `x`) for that clause. I get a proof of `⊥` by proving that `onS¹ (hcomp {φ = i0} (λ _ ()) base)` *should* be `⊤` and transporting along that proof.

As hinted above, I can pull the same trick with a stuck `transp` for an indexed inductive.

```agda
{-# OPTIONS --cubical --safe #-}
open import Agda.Primitive.Cubical renaming (primTransp to transp; primINeg to ~_)

data ⊥ : Set where
data ⊤ : Set where tt : ⊤

data D : ⊤ → Set where
    c1 : D tt
    c2 : D tt

isC1 : {A : ⊤} → D A → Set
isC1 c1 = ⊤
isC1 _  = ⊥

JEEPERS! : ⊥
JEEPERS! = transp (λ i → isC1 (transp (λ j → D tt) (~ i) c1)) i0 tt
```

**Comment by howtonotwin** [comment]
Minimized even more!

```agda
{-# OPTIONS --cubical --safe #-}
module BigOops where

open import Agda.Primitive.Cubical renaming (primTransp to transp; primINeg to ~_)

data ⊥ : Set where
data ⊤ : Set where tt : ⊤

data D : ⊤ → Set where
    c1 : D tt
    c2 : D tt

isC1 : {A : ⊤} → D A → Set
isC1 c1 = ⊤
isC1 _  = ⊥

JEEPERS! : ⊥
JEEPERS! = transp (λ i → isC1 (transp (λ j → D tt) (~ i) c1)) i0 tt
```

**Comment by andreasabel** [comment]
This can be reproduced immediately with Agda 2.6.3, but older versions of Agda 2.6 do not export `PathP` from `Agda.Primitive.Cubical`.

**Comment by andreasabel** [comment]
`{-# OPTIONS -v tc.cc:15 #-}` reveals this: 
```
clauses before compilation
  onS¹ base = ⊤ 
  onS¹ (loop i) = ⊤ 
  onS¹ _ = ⊥
```
The constructed clauses are then generated (but not debug printed).
The case tree looks like this:
```
compiled clauses of  onS¹
  case 0 of
    Issue7033.D.base -> done[] Issue7033.⊤
    Issue7033.D.loop -> done[i] Issue7033.⊤
    Agda.Primitive.Cubical.primHComp -> done[{_}, {_}, {_}, _, _] Issue7033.⊥
    _ -> done[_] Issue7033.⊥
```
It seems that `hcomp` should maybe not be mapped to the empty type here.  What should it be mapped to?

**Comment by howtonotwin** [comment]
Well, I'm not familiar with the Agda internals, but the generated clause looks fine to me (`-v tc.def.fun.clauses:15`):

```agda
onS¹ base = ⊤
onS¹ (loop i) = ⊤
onS¹ _ = ⊥
onS¹ (hcomp {.Agda.Primitive.lzero} {.D} {φ = φ} u a)
  = primComp (λ i .o → onS¹ (u i _)) (onS¹ a)
```

It's just that, when the case tree is made, the `hcomp` case is caught by the `_` clause. The non-problematic definition

```agda
onS¹ : D → Set
onS¹ base     = ⊤
onS¹ (loop i) = ⊤
onS¹ other    = ⊥
```

produces the case tree

```agda
case 0 of
  Issue7033-1-none.D.base -> done[] Issue7033-1-none.⊤
  Issue7033-1-none.D.loop -> done[i] Issue7033-1-none.⊤
  Issue7033-1-none.D.other -> done[] Issue7033-1-none.⊥
  Agda.Primitive.Cubical.primHComp ->
    done[{_}, {_}, {_}, _, _]
      Agda.Primitive.Cubical.primComp
        {λ i -> lsuc lzero} {λ i -> Set}
        {Agda.Primitive.Cubical.primIMax @2 Agda.Primitive.Cubical.i0}
        (λ i -> λ o -> Issue7033-1-none.onS¹ (@3 @1 @0))
        (Issue7033-1-none.onS¹ @0)
```

I would think that last term is the correct one that should also appear in the case tree for the problematic version of `onS¹`.

**Comment by jespercockx** [comment]
Would it make sense to consider the generated `hcomp` clauses as coming *first* instead of last for the purpose of constructing the case tree?

**Comment by andreasabel** [comment]
> Would it make sense to consider the generated `hcomp` clauses as coming _first_ instead of last for the purpose of constructing the case tree?

This would probably fix the issue and we could go for this now.  
Might have some negative impact on performance if the hcomp case is always tried first...

**Comment by jespercockx** [comment]
For the case tree it doesn't matter since it is just a switch on the constructor name, no? Or do we still go through all of the constructors linearly? In that case we could still force the hcomp constructor to come last, but before any catchall branches.

**Comment by jespercockx** [comment]
It's a map so the order really doesn't matter: https://github.com/agda/agda/blob/ea16c4cf0833afa2b2386260928b804d7f471112/src/full/Agda/TypeChecking/CompiledClause.hs#L41

**Comment by andreasabel** [comment]
There is a statement in the code asking for adding hcomp clauses at the end: https://github.com/agda/agda/blob/ea16c4cf0833afa2b2386260928b804d7f471112/src/full/Agda/TypeChecking/Coverage/Cubical.hs#L1361
Unfortunately, direct blame history is truncated at 145dc625df78fe05ae48747cdd8c291923c8fa58 due to code movement. 
Tracing it manually, https://github.com/agda/agda/blame/d845567b76c0c5d963c7e19801acc63c3c85516a/src/full/Agda/TypeChecking/Coverage.hs#L1903 , gets us to the initial commit, fbc50e5a06ab10212f67fae43a18657c9f6b29e9, which already had the "Important: add at the end" comment.

**Comment by plt-amy** [comment]
The reason behind `hcomp` clauses having to come last, I assume, is a question of strictness. Since `hcomp` always looks like a `Def`, regardless of whether or not it's _actually_ something you can match on (e.g. in higher inductive types), it's infeasible for an arbitrary function to tell, if they're splitting on a `Def hcomp ...`, whether that's actually an "hcomp-constructor", or whether it's just something unevaluated.

Placing the hcomp clauses after the constructor cases makes it so that the ordinary pattern-matching behaviour will force the split argument to head-normal form, so that if you actually did end up with a `Def`, you can be sure it's actually of the hcomp-constructor variety.

> In that case we could still force the hcomp constructor to come last, but before any catchall branches.

This would work, but I'm not yet familiar enough with the coverage code to figure out how to do it. (This should also happen for `transpX` clauses.)
