### ISSUE TITLE
Test suite needs to be run with debug printing enabled

### ISSUE THREAD

**Issue by ncfavier** [agda/agda#7114]
Since debug printing was made optional in https://github.com/agda/agda/pull/6863, the test suite needs to be run with `make install-bin-debug test`. This should either be clarified in the documentation, or `test` should automatically use a debug-enabled build.

**Comment by andreasabel** [comment]
@AndrasKovacs suggested that the `-f debug` flag should be default in the `Makefile`, since this is a developer-targeted tool.  Users are supposed to use `cabal v2-install` or `stack install` directly. (Or maybe we keep a single dedicated batteries-included goal `install` in the Makefile for the users, but then all other goals are for the developers.)

**Comment by lawcho** [comment]
The Agda option controlling debug printing is `-v`

If non-debug Agda issued a warning when parsing `-v`, it would be easier to diagnose this problem.

**Comment by jespercockx** [comment]
Fixed by @UlfNorell in https://github.com/agda/agda/pull/7308
