### ISSUE TITLE
Regression when giving instances with visible arguments

### ISSUE THREAD

**Issue by ncfavier** [agda/agda#7196]
```agda
module Bug where

postulate
  T : Set
  I : T → Set

record Foo : Set where
  field
    t : T
    instance
      I-t : I t

auto : ∀ {ℓ} {A : Set ℓ} → ⦃ A ⦄ → A
auto ⦃ a ⦄ = a

module _ (f : Foo) where -- f needs to be visible
  open Foo f
  bug : I t
  bug = {! auto !}
```

Trying to give `auto` fails with

```
No instance of type I t was found in scope.
when checking that the expression auto has type I t
```

yet `auto` is accepted if the hole is removed. This regression appeared *somewhere* between a445e3b555bd978200f7d7ca93e9ba445ed639c0 and aa5d8bbe723ea095d2af92ccaa2cfd2fbd89570a.

**Comment by plt-amy** [comment]
[womp womp](https://github.com/agda/agda/commit/aa5d8bbe723ea095d2af92ccaa2cfd2fbd89570a#diff-96cb3651fdf54b1ce31ba7354c805fd6de454db32c96a9e88b52794fe9afb568R1063). The issue is that I remove instances that have visible arguments in their telescope after the top-level module is checked, but this happens before any interaction. I should do that when serializing it instead
