### ISSUE TITLE
Instance search needs to know whether a meta must be a function type

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#723]
What's the problem? Cut-and-pasted program examples are preferred over
attachments (if reasonably short).

Hello team,
I was trying to mimic type classes and got a problem. Here is a code snippet.
```agda
record Default {ℓ} (A : Set ℓ) : Set ℓ where
  constructor create
  field value : A

default : ∀ {ℓ} {A : Set ℓ} {{def : Default A}} → A
default {{def}} = Default.value def

defBool : Default Bool
defBool = create false

defNat : Default ℕ
defNat = create zero

defFunc : ∀ {ℓ} {A : Set ℓ} → Default (A → A)
defFunc = create (λ x → x)

-- these three lines are compiled successfully
n₁ = default ∶ ℕ
b₁ = default ∶ Bool
f₁ = default ∶ (ℕ → ℕ)

-- but this one hangs on "Checking"
n₂ = default (5 ∶ ℕ) ∶ ℕ
```
What version of Agda are you using? On what operating system (if relevant)?
I am using latest (Oct 20) darcs developer version.

Thank you,
Dmytro

Original issue reported on code.google.com by `d.staro...@gmail.com` on 20 Oct 2012 at 5:22

**Comment by andreasabel** [comment]
We would need a constraint `isFunctionType X` and use it during instance search to exclude the instance for Nat.

**Comment by UlfNorell** [comment]
I believe the reason we aren't simply solving the meta with a function type with unknown domain and codomain is that we're worried it might get solved to an implicit function type.

Related: #525

**Comment by jespercockx** [comment]
We could still have a constraint that ensures a type has at least a given number of visible function arrows (aside from an arbitrary number of hidden/instance ones).

**Comment by jespercockx** [comment]
Thinking about this, we actually already have a more refined version of the `isFunctionType X` constraint: the `CheckArgs` case of `PostponedTypecheckingProblem` enforces that a type accepts the arguments it is given.

The actual problem here seems to be the same as #2760 : instance search doesn't even try to filter out the candidates because there's an unconstrained meta in the type.

However, even when I temporarily disable the check on unconstrained metas, I still get yellow. The reason is that `CheckArgs` is part of an `Unblock m` constraint, but `Unblock` constraints are not considered during instance search since the patch https://github.com/agda/agda/commit/c495bdb4d632be07b5a905f6fdabf377fe804a80 by @andreasabel (this took quite some time to debug, I didn't expect the `isIFSConstraint` function to be so tricky). I will try to revert this change as we currently have a much more general mechanism to prevent looping in presence of unsolved metas (actually too general, this is exactly #2760).
