### ISSUE TITLE
Proof of ⊥ using HIT-indexed type

### ISSUE THREAD

**Issue by mkm** [agda/agda#7346]
The following code derives a contradiction in Agda 2.6.4.

```agda
{-# OPTIONS --cubical --safe #-}
module Bad where

open import Cubical.Core.Everything

data ⊥ : Type where

data T : Type where
  c : T
  pair : T → T → T
  c-unit : ∀ x → pair c x ≡ x

data IsPair : T → Type where
  is-pair : ∀ x y → IsPair (pair x y)

all-pairs : ∀ x → IsPair x
all-pairs x = transp (λ i → IsPair (c-unit x i)) i0 (is-pair c x)

f : T → ⊥
g : (x : T) → IsPair x → ⊥

f x = g x (all-pairs x)
g .(pair x y) (is-pair x y) = f x

nope : ⊥
nope = f c
```

**Comment by szumixie** [comment]
Agda correctly throws a termination error with `--no-forcing`. #4606 is related, but forcing removes the dot from the dot pattern.

Slightly simplified code:
```agda
{-# OPTIONS --cubical --safe #-}

open import Agda.Primitive.Cubical
open import Agda.Builtin.Cubical.Path

data ⊥ : Set where

data T : Set where
  zero : T
  suc : T → T
  eq : (x : T) → suc x ≡ x

data IsSuc : T → Set where
  is-suc : (x : T) → IsSuc (suc x)

all-sucs : (x : T) → IsSuc x
all-sucs x = primTransp (λ i → IsSuc (eq x i)) i0 (is-suc x)

not-suc : (x : T) → IsSuc x → ⊥
not-suc .(suc x) (is-suc x) = not-suc x (all-sucs x)

nope : ⊥
nope = not-suc zero (all-sucs zero)
```

**Comment by andreasabel** [comment]
@szumixie wrote:
> but forcing removes the dot from the dot pattern.

Thanks for the analysis!

Should we disable `--forcing` for `--cubical` and make it unsafe to enable it?

**Comment by jespercockx** [comment]
> Should we disable --forcing for --cubical and make it unsafe to enable it?

That seems like quite a drastic solution to me. Couldn't we rather make it so that forcing does not apply to HITs, but still apply it to regular datatypes?

**Comment by jespercockx** [comment]
Oh, it's not that easy, since the type that forcing is applied to is not a HIT itself, it only is *indexed* by a HIT. Rather, what we could do is to change the forcing analysis so it does not detect an argument as being forced if it appears as an argument to a constructor of a HIT.

Basically, we should check here https://github.com/agda/agda/blob/35b565990f0b8ffb72e2c7c5590ebe1332cb6af1/src/full/Agda/TypeChecking/Forcing.hs#L167 that the constructor is not a HIT constructor, and if it is return `mempty`.

**Comment by andreasabel** [comment]
> that the constructor is not a HIT constructor, and if it is return `mempty`.

I could easily implement this.

However, it is not clear to me what is the right thing to do.  
Because we have no compiler for cubical, the forcing analysis is a bit hanging in the air, it is not clear what it should achieve.
With K (and `T` not being a HIT), `IsSuc` would be a proposition and erased during compilation.
In Cubical (and `T` as defined),  both `T` and `IsSuc` are contractible (as witnessed by `all-sucs`), so, have no content and could be erased (!?).
Maybe nothing is wrong with the forcing analysis, but instead the termination checker should work on the compiled clauses and without K not look into lazy matches for termination witnesses?

**Comment by jespercockx** [comment]
> Because we have no compiler for cubical, the forcing analysis is a bit hanging in the air, it is not clear what it should achieve.

Semantically speaking, the forcing analysis tries to detect constructor arguments that are uniquely determined by the constructor indices. Here, the index `suc x` does *not* uniquely determine the argument `x` because `suc` is not injective. Hence, in this case the forcing analysis is clearly making a wrong assumption, and my proposed change would fix that.

You seem to be making a more general claim that forcing is something that should not be done at all in case of cubical. However, I'd like to see more evidence for that claim beyond just this single issue.

**Comment by szumixie** [comment]
It's still the case that forcing can change whether a function passes termination check:
```agda
{-# OPTIONS --cubical #-}
-- {-# OPTIONS --no-forcing #-} -- termination error if uncommented
open import Agda.Builtin.Nat

data Fin : Nat → Set where
  fzero : ∀ {n} → Fin (suc n)
  fsuc : ∀ {n} → Fin n → Fin (suc n)

postulate
  f : ∀ {n} → Fin n → Fin n

g : ∀ {n} → Fin n → Fin n
g .{suc n} (fzero {n}) = fzero
g .{suc n} (fsuc {n} x) = fsuc (g {n} (f x))
```

**Comment by andreasabel** [comment]
Continued in
- https://github.com/agda/agda/issues/7616
