### ISSUE TITLE
Mimer options `-l` and `-s` not covered by testsuite 

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#7371]
The `interaction` suite lacks function checks for the Mimer options `-l` and `-s` documented here:
https://github.com/agda/agda/blob/bdcbe480c704d6c5e12f08c62cb01ab05b3199f1/doc/user-manual/tools/auto.rst?plain=1#L41-L43

**Comment by andreasabel** [comment]
Let's not require this for 2.7.0, these options are not the most mainstream.  
Also, the result of these options will likely be very implementation dependent.

**Comment by UlfNorell** [comment]
Looking at this I noticed that #7265 (fixing #7212) broke the argument passing to Mimer. We don't notice this in the test suite because we don't go through the elisp code.

Fixing it properly is beyond my elisp skills. The problem is that `agda2-goal-cmd` doesn't have (as far as I can tell) an option where you get the argument string from the hole even when the input is empty. You either get the empty string regardless of the hole contents, or you get the hole contents when it's non-empty and a prompt if it's empty.

For the 2.7.0 release I think we should reverse #7265. @andreasabel
