### ISSUE TITLE
Agda 2.7.0-rc1 crashes when run twice, probably serialization issue

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#7382]
With the test case from #7380:
```agda
open import Agda.Builtin.IO
open import Agda.Builtin.Unit
open import Agda.Builtin.Nat
open import Agda.Builtin.Sigma

record R : Set where
  field x : Nat

variable r : R

data D : R → Nat → Set where
  c : let open R r in D r x

f : R → Nat
f x = fst g
  where
    g : Σ Nat (D x)
    g = (_ , c)

postulate print : Nat → IO ⊤
{-# COMPILE GHC print = print #-}

main = print (f (record { x = 3 }))
```
I get a crash if I run 2.7.0-rc1 twice on this file:
```
$ agda-2.7.0-rc1 Issue7380.agda && agda-2.7.0-rc1 -c Issue7380.agda
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE_VERBOSE__, called at src/full/Agda/TypeChecking/Reduce.hs:224:18
```
https://github.com/agda/agda/blob/ea00db09917de741fb5cb491639391f7af121369/src/full/Agda/TypeChecking/Reduce.hs#L224-L225
The internal error goes away with `--no-save-metas`.
Also, it cannot be triggered in 2.6.4.3 with `--save-metas`, so it must be a fresh regression in the `--save-metas` feature.

**Comment by andreasabel** [comment]
@AndrasKovacs Could you have a look?

**Comment by AndrasKovacs** [comment]
Yep.

**Comment by AndrasKovacs** [comment]
Minimized example:

```
foo : _ → Set
foo x = bar
  module _ where
    bar : Set
    bar = x
```
This fails compiling while already having the interface file, but succeeds if I give a name to the `module`. 

The problem is apparently that the metavariable for the type of `x` appears in the anonymous module section, but it's not live in DeadCode. If the module is named, it becomes a public module that's alive.

Currently *all* sections go into the interface, so the proper DeadCode behavior would be to consider all sections as alive. 

I don't know though why we need all sections. Can we eliminate dead sections? Btw, how hard is it to get the enclosing sections of a QName? That would be necessary for computing live sections.
