### ISSUE TITLE
Unexpected hidden argument in nested records/modules

### ISSUE THREAD

**Issue by WhatisRT** [agda/agda#7440]
Here's a minimal reproducer:

```agda
module Test where

open import Agda.Builtin.Nat

record R : Set where
  record S : Set where
    field s : Nat

module X (r : R) (open R r) where

  module A (Z : Set) where
    open S public

  module B (Z : Set) where
    open A Z

    t : S → Nat
    t = s {_}
```

In the last line, note that `s` should not accept a hidden argument. However, this file type checks. If we put a hole there, we can see that `s` has the type `{r = r₁ : R} → R.S _ → Nat` instead of the expected `S → Nat`. Also, if the opening of `R r` is moved inside the module, `s` has the expected type in `B`. I tested this with with Agda versions `2.6.4` and `2.7.0`.

**Comment by andreasabel** [comment]
When I see `open public` in a parametrised module, I see red.
It has a weird semantics I do not agree with.

**Comment by andreasabel** [comment]
Regression in 2.5.2 smells like a _parameter refinement_ issue.

Bisecting with:
- GHC 7.10.3
- Cabal 2.4.1
- Happy 1.19.5
```
agda-bisect-v1 -w ghc-7.10.3 --with-cabal=cabal-2.4.1 --good v2.5.1.1 --bad v2.5.2 --must-fail Issue7440.agda 
```
Starts feeling like software archeology.  I had already deleted GHC 7.

**Comment by andreasabel** [comment]
Actually bisection was just a wild goose chase.  The only difference from 2.5.1 to 2.5.2 is that the `R` argument to `s` changed from visible to hidden, making the OP succeed.  However, the real problem is that such an argument even exists.
This has already been like this in 2.4.2 and possibly before (can't check).
  
So here is the (probably uninteresting) bisection result:
>  /Users/abel/tmp/agda/Issue7440.agda:18,9-10
>  Found an implicit application where an explicit application was
>  expected
>  when checking that {_} is a valid argument to a function of type
>  (r₁ : R) → R.S _ → Nat
> Verdict: Good
> 1432ff46aa53fd3981c2acbfb83a04d411450ce8 is the first bad commit
> Author: Andreas Abel 
> Date:   Wed May 4 20:13:36 2016 +0200
>
>    Fixed #1954.  Projection parameters now remain hidden in module copies.

**Comment by UlfNorell** [comment]
Here's a version without records
```agda
open import Agda.Builtin.Nat

postulate
  X Γ Δ : Set
  x : X

module R (x : X) where
  module S where
    postulate s : Nat

module X (_ : Γ) (open R x) (_ : Δ) where

  _ : Nat
  _ = S.s

  module A (Z : Set) where
    open S public
    _ : Nat
    _ = s

  -- This is the slightly weird semantics:
  -- A.s doesn't take a Z parameter
  _ : Nat
  _ = A.s

  module B where
    open A Nat
    _ : Γ → Nat   -- Note: no Δ
    _ = s
```

**Comment by WhatisRT** [comment]
>  ```
>  -- This is the slightly weird semantics:
>  -- A.s doesn't take a Z parameter
>  _ : Nat
>  _ = A.s
> ```

Ohh, I didn't expect that! I always fully apply the modules where I do this so it doesn't matter, but I'd have expected it to have the extra argument. Also nice work removing the records, I tried that for a minute but gave up when the first thing I tried didn't work. Where does the `Δ` come from?

**Comment by UlfNorell** [comment]
I added the Δ to show that only the parameters *before* the `open` gets added to the type.

**Comment by UlfNorell** [comment]
The problem is the wrapper module that gets introduced here when the module telescope contains opens or module applications:

https://github.com/agda/agda/blob/819993172d05f5e9769f4c7f35cbabb3080b18e9/src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs#L1185-L1194

(added by @andreasabel in d07e6f81764, and extended to module applications here f739b3d7)

The wrapper module is added at the top-level, taking no parameters, but it should really take the parameters introduced before the module application.

Here's an even simpler example:

```agda
postulate
  X Y Γ : Set
  x : X
  γ : Γ

module R (x : X) where
  postulate s : Y

module A (γ : Γ) (let module M = R x) where
  -- Here, M lives in the wrapper module created around A, which doesn't have a Γ parameter
  open M public

-- so when we apply A, we don't pass γ to the stuff from M
module B = A γ

wrong : Γ → Y
wrong = B.s
```

I think the correct solution is to distribute the parameters over the wrapper module and the original module and add multiple wrappers in case there are multiple module applications with parameters in between.
