### ISSUE TITLE
Regression: emptiness check fails when erased constructors are involved

### ISSUE THREAD

**Issue by nad** [agda/agda#7442]
Agda rejects some code that didn't use to be rejected:
```
$ cat M.agda
```
```agda
{-# OPTIONS --erasure --cubical #-}

module M where

data ⊥ : Set where

record R : Set where
  field
    f : ⊥
```
```
$ cat Bug.agda
```
```agda
{-# OPTIONS --erasure --erased-cubical #-}

open import M

f : R → ⊥
f ()
```
```
$ agda --no-libraries Bug.agda
Checking Bug ([…]/Bug.agda).
 Checking M ([…]/M.agda).
[…]/Bug.agda:6,1-5: error: [ShouldBeEmpty]
R should be empty, but that's not obvious to me
when checking the clause left hand side
f ()
```
Bisection points towards 27ec4778bff0f59b3b34aa302582da1fff157da9 ("[ refactor ] Add two helper functions \`isEtaRecordDef\` and \`isEtaRecordConstructor\` to clean up code dealing with eta-equality"). @jespercockx, can you take a look at this?

**Comment by andreasabel** [comment]
A relevant question is also why one has to go through serialization to produce this bug.

**Comment by nad** [comment]
Note that one module uses `--cubical`, while the other uses `--erased-cubical`.

**Comment by jespercockx** [comment]
I could restore the old behavior by moving the check for erasure of the record constructor from `isEtaRecordDef` back to `isEtaRecord` where it was before. But to be honest, I don't really understand why we need the erasure check in the first place. Does it really make sense to allow erasing the constructor of an eta-record type?

Apparently the check was introduced in the fix of https://github.com/agda/agda/issues/6287, which does not even have an explicit erasure annotation on the constructor (but it is inferred somehow)?

My preferred solution here would be to remove the erasure check completely, but that would mean we need a different fix for #6287.

**Comment by nad** [comment]
If a module that uses `--erased-cubical` imports a module that uses `--cubical`, then definitions from that module are treated as erased ([more or less](https://agda.readthedocs.io/en/latest/language/cubical.html#cubical-agda-with-erased-glue)):

https://github.com/agda/agda/blob/84b0c60b418476d63d5287a5751da43ceab33735/src/full/Agda/TypeChecking/Monad/Signature.hs#L998-L1011

**Comment by andreasabel** [comment]
@jespercockx wrote:
> I could restore the old behavior by moving the check for erasure of the record constructor from `isEtaRecordDef` back to `isEtaRecord` where it was before.

In the interest of releasing 2.7.0.1 soon, could you do this as short-term solution?
Or should I give it a go, since you are at ICFP atm?

**Comment by andreasabel** [comment]
I looked a bit into this, and there are quite a few loose ends here.

The original feature 1c0363945dd4b495bf773bb3ab106c3d8bba6ea4 by @jespercockx, adding absurd patterns for (hereditary) records with empty fields did so only for eta records, and it remained like this.  
The commit does not include negative tests, e.g. failure if the record does not have eta, and the changelog does not mention eta either.  (The documentation https://agda.readthedocs.io/en/v2.7.0/language/function-definitions.html#absurd-patterns also does not mention the feature.) 
It anyway seems plausible to assume that the requirement of eta was intended.  I can speculate about the rationale for this:

(i) One rationale might be that the feature should not do more than one could do by manual expansion.  And non-eta record variables cannot be expanded into constructor/record patterns.  Except when they are declared `pattern`.  The latter is not taken into account by Agda:
```agda
data ⊥ : Set where

record D : Set where
  no-eta-equality; pattern; constructor c
  field f : ⊥

ok : D → ⊥
ok (c ())

rejected : D → ⊥
rejected ()
```

(ii) Another rationale might be that the feature should not change the strictness of the function.  Matching on a non-eta constructor makes the function more strict.  However, strictness cannot really play a role since absurd clauses are anyway removed by the compiler.  E.g. above `ok` is compiled to this Haskell program:
```hs
-- ⊥
data T_'8869'_2
-- D
data T_D_4 = C_c_10
-- ok
d_ok_12 :: T_D_4 -> T_'8869'_2
d_ok_12 = erased
```
So there is no trace of matching against `c` left.
That begs the question to @jespercockx:  Can the eta requirement be lifted from the emptiness check?  
At least for `pattern` constructors?
Coinductive constructors  are at the moment implicitly excluded by the eta requirement.  I _think_ we want to keep excluding them.

I create a new issue for continuing this discussion:
- #7467 


Concerning the feature of erased constructors, I have some questions to @nad.  I am not sure I understand the feature correctly.
So when you make a constructor erased by change of the flavor of cubical, then the record loses eta equality in non-erased contexts, right?  Because eta-expansion could make an erased constructor appear where the type checker would not allow it.
However, is eta-contraction also harmful?  It seems to use the same test for eta records.
So, should there maybe be a split of concepts, of eta that ignores erasure and eta that takes it into account?

Also, the compiler seems to erase clauses that use erased constructors.  And the type checker does not seem to require an argument to be erased for erased constructor matches to be legal.  E.g., these modules are accepted:
```agda
{-# OPTIONS --erasure --cubical #-}

module Issue7442Import where

data ⊥ : Set where

record R : Set where
  constructor c
  field f : ⊥
```
```agda
{-# OPTIONS --erasure --erased-cubical #-}

module Main where

open import Issue7442Import
open import Common.Prelude

test : R → Nat
test (c _) = zero

{-# NON_TERMINATING #-}
foo : R
foo = foo

main : IO _
main = printNat (test foo)
```
Compilation succeeds and the compiled program prints (on my machine) a non-deterministic value, e.g. I have been seeing `4391505640`
`4318289640`
`4368461544` ...

This feels broken, so I do not know whether we are really speaking of a regression in this issue or whether @jespercockx just shifted a pole in some unchartered territory.

If you change the type of `test` to `@0 R -> Nat` then the compiled program correctly prints `0`.
That seems to indicate that pattern matching still misses some checks with erased constructors.
 
I raised a variant of the above counterexample in
- #7466

My conclusion from the investigation is that the issue does not have a clear path of action yet and is also not pressing for 2.7.0.1, so I bump the milestone.

**Comment by nad** [comment]
> So when you make a constructor erased by change of the flavor of cubical, then the record loses eta equality in non-erased contexts, right?

A meta-variable in a non-erased position should not be instantiated with `c args` if `c` is an erased constructor, but `x` should still be definitionally equal to its η-expansion `c …`.

In my attempted [fix](https://github.com/agda/agda/commit/5c4ab96071a7118a8e0b379ecd7eafeee2f2dcfb) of issue #6287 I changed the implementation of `isEtaRecord`, but now it seems to me as if that was a bit of a hack.

> Also, the compiler seems to erase clauses that use erased constructors. And the type checker does not seem to require an argument to be erased for erased constructor matches to be legal.

This is by design. From the user manual:

https://github.com/agda/agda/blob/26ef5bcba940898ca861ea7a46304e3a30dea77b/doc/user-manual/language/runtime-irrelevance.lagda.rst?plain=1#L108-L129

> ```agda
> {-# NON_TERMINATING #-}
> foo : R
> foo = foo
> ```

> This feels broken, […].

You could use the same technique to implement `unsafeCoerce`.

**Comment by jespercockx** [comment]
> In the interest of releasing 2.7.0.1 soon, could you do this as short-term solution?
> Or should I give it a go, since you are at ICFP atm?

I'm sorry, I haven't had time to look into this further yet. I might have time next week.
