### ISSUE TITLE
Strange problem with --level-universe and --cubical

### ISSUE THREAD

**Issue by mortberg** [agda/agda#7529]
The following code does not work:

```agda
{-# OPTIONS --cubical --level-universe #-}

open import Agda.Primitive

data _≡_ {l : Level} {X : Set l} : X → X → Set l where
  refl : {x : X} → x ≡ x

Jbased : {l : Level} {X : Set l} (x : X) (A : (y : X) → x ≡ y → Set l)
       → A x refl → (y : X) (r : x ≡ y) → A y r
Jbased x A b _ refl = b
```

and the error message is:
```
Panic: Pattern match failure in 'do' block at
src/full/Agda/TypeChecking/Rules/LHS/Unify/LeftInverse.hs:203:3-15
when checking that the pattern refl has type x ≡ y
```

If I remove either `--level-universe` or `--cubical` it works. Interestingly, changing the equality type to the builtin equality type makes it work:

```agda
{-# OPTIONS --cubical --level-universe #-}

open import Agda.Primitive
open import Agda.Builtin.Equality

Jbased : {l : Level} {X : Set l} (x : X) (A : (y : X) → x ≡ y → Set l)
       → A x refl → (y : X) (r : x ≡ y) → A y r
Jbased x A b _ refl = b
```

Me and @martinescardo came across this when trying to combine the TypeTopology and agda/cubical libraries.

**Comment by andreasabel** [comment]
The current match failure is the `__IMPOSSIBLE__` in the first line of: https://github.com/agda/agda/blob/1e9725ee8a334de816fff39ce1bd32f91b6714e4/src/full/Agda/TypeChecking/Rules/LHS/Unify/LeftInverse.hs#L202-L215
This used to be a failed pattern bind, but it is the same problem: https://github.com/agda/agda/blob/727fc869e39d54c4d6ed5def47bec23d0767d94b/src/full/Agda/TypeChecking/Rules/LHS/Unify/LeftInverse.hs#L201

**Comment by andreasabel** [comment]
If we inspect the content on `Left` before going `__IMPOSSIBLE__`, it is `Level`.
Without `--level-universe`, we have `Level : Type 0` so `Level` is fibrant.
With `--level-universe`, we have `Level : LevelUniv` which makes `Level` non-fibrant since only types in `Type l` are considered fibrant by the current implementation of Cubical Agda.

So, what should the story be for `LevelUniv`?  Are its inhabitants fibrant?

As @arthur-adjedj writes in https://github.com/agda/agda/pull/7534#issuecomment-2393789255 there might be more issues when combining `--cubical` and `--level-universe`.  
We need to either resolve them or make the combination of these two flags an error.

**Comment by sattlerc** [comment]
> So, what should the story be for LevelUniv? Are its inhabitants fibrant?

No, they shouldn't be.
