### ISSUE TITLE
`Bad CPU type in executable` when running MacOS release build

### ISSUE THREAD

**Issue by haohanyang** [agda/agda#7599]
I downloaded agda build for macos from https://github.com/agda/agda/releases/download/v2.7.0.1/Agda-v2.7.0.1-macOS.tar.xz. Running `bin/agda` gave the error 

```
zsh: bad CPU type in executable: ./agda
```

OS: macOS 13.4.1 Intel CPU

**Comment by andreasabel** [comment]
Ha!  Good catch!
The explanation would be that the macOS deploy job for v2.7.01 ran on ARM, so the build product was an ARM binary: https://github.com/agda/agda/actions/runs/10835841110/job/30070141257#step:1:8

To address this, we need to diversify our deploy action so that it produces both Intel and ARM binaries for macOS.

**Comment by haohanyang** [comment]
Thank you for your prompt response.

Are you open to a PR to fix this?
