### ISSUE TITLE
Suggestion: Optimize tail-recursive definitions when evaluating

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#912]
A couple of examples:

```agda
module TailRec where

open import Data.Nat

-- Good old exponentiation
_**_ : ℕ  → ℕ → ℕ
m ** n = pow' 1 m n
          where
            pow' : ℕ → ℕ → ℕ → ℕ
            pow' acc _ zero = acc
            pow' acc m (suc n) = pow' (m * acc) m n

-- A sophisticated identity function
dummy : ℕ → ℕ
dummy n = dummy' zero n
            where
              dummy' : ℕ → ℕ → ℕ
              dummy' acc zero = acc
              dummy' acc (suc m) = dummy' (suc acc) m
```

With the default stack size, both (2 ** 100000) and (dummy 1000000) throw a stack-overflow error; it seems they are pushing up to 100_000 or 1_000_000 frames into the stack, respectively.

Most functional languages optimize tail-recursive functions so that they only use O(1) stack space. Could Agda do something similar?

Original issue reported on code.google.com by `victor@lopezjuan.com` on 25 Sep 2013 at 10:14

**Comment by UlfNorell** [comment]
The problem here isn't with tail-recursion; you have a memory leak in the accumulator argument. Agda uses a factor 3-4 more memory and runs 60% slower than `ghci` for `dummy` but has the same asymptotic behaviour. Fixing the memory leak by changing the last clause to
```agda
dummy' acc (suc m) = primForce acc λ acc → dummy' (suc acc) m
```
makes it run in constant space.
