### ISSUE TITLE
Module application display forms in parameterised modules

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#958]
```
git clone git@github.com:andreasabel/cubical.git -b 0.0.0.2
```

Load `cubical/src/Control/Decoration.agda`

Look at the goals.
Try to make sense of them...

Original issue reported on code.google.com by `andreas....@gmail.com` on 13 Nov 2013 at 11:28

**Comment by UlfNorell** [comment]
We generate display forms to solve the `map` issue, but the problem here is that the display form is generated inside a parameterised module (the record module), and thus does not apply outside. Here's a variant that makes the modules explicit:

```agda
postulate FunctorOps : Set
module FunctorOps (ops : FunctorOps) where
  postulate map : Set

postulate IsFunctor : Set
module IsFunctor (fun : IsFunctor) where
  postulate ops : FunctorOps
  open FunctorOps ops public
  -- inside here `FunctorOps.map ops` gets printed as `map`

open IsFunctor

-- but out here we lose the display form
test : IsFunctor → Set
test F = {!map F!}
-- C-c C-n map F  prints  FunctorOps.map (ops F)
```
It might be possible to lift the display forms out of the parameterised module, turning matches on module parameters into wildcard matches in the display pattern.

**Comment by UlfNorell** [comment]
Another test case in #2806.
